package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * ActivitiesLog generated by hbm2java
 */
@Entity
@Table(name = "ACTIVITIES_LOG")
public class ActivitiesLog extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	public static final String FieldName_ParentTransactionID = "parenttransactionid";
	public static final String FieldName_TransferID = "transferid";
	public static final String FieldName_MsgType = null;
	public static final String FieldName_Commodity = "commodity";
	public static final String FieldName_Company = "company";
	public static final String FieldName_ISO8583_AcquiringInstIdCode = "iso8583Acquiringinstidcode";
	public static final String FieldName_SourceSubscriberID = "sourcesubscriberid";
	
	private Company company;
	private BigDecimal parenttransactionid;
	private BigDecimal transferid;
	private Short issuccessful;
	private Long errorcode;
	private BigDecimal lopid;
	private BigDecimal bulkuploadentryid;
	private Long notificationcode;
	private Long msgtype;
	private BigDecimal sourcesubscriberid;
	private String sourcesubscribername;
	private BigDecimal sourcemdnid;
	private String sourcemdn;
	private String destmdn;
	private BigDecimal sourcepocketid;
	private Long sourcepockettype;
	private Long sourceapplication;
	private String servletpath;
	private String iso8583Processingcode;
	private String iso8583Primaryaccountnumber;
	private String iso8583Systemtraceauditnumber;
	private String iso8583Retrievalreferencenum;
	private String iso8583Merchanttype;
	private Long iso8583Acquiringinstidcode;
	private String iso8583Cardacceptoridcode;
	private String iso8583Variant;
	private String iso8583Responsecode;
	private String webclientip;
	private Long commodity;
	private Long activitycategory;

	public ActivitiesLog() {
	}

	public ActivitiesLog(BigDecimal id, Company company,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby,
			BigDecimal parenttransactionid) {
		this.id = id;
		this.company = company;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.parenttransactionid = parenttransactionid;
	}

	public ActivitiesLog(BigDecimal id, Company company,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby,
			BigDecimal parenttransactionid, BigDecimal transferid,
			Short issuccessful, Long errorcode, BigDecimal lopid,
			BigDecimal bulkuploadentryid, Long notificationcode, Long msgtype,
			BigDecimal sourcesubscriberid, String sourcesubscribername,
			BigDecimal sourcemdnid, String sourcemdn, String destmdn,
			BigDecimal sourcepocketid, Long sourcepockettype,
			Long sourceapplication, String servletpath,
			String iso8583Processingcode, String iso8583Primaryaccountnumber,
			String iso8583Systemtraceauditnumber,
			String iso8583Retrievalreferencenum, String iso8583Merchanttype,
			Long iso8583Acquiringinstidcode, String iso8583Cardacceptoridcode,
			String iso8583Variant, String iso8583Responsecode,
			String webclientip, Long commodity, Long activitycategory) {
		this.id = id;
		this.company = company;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.parenttransactionid = parenttransactionid;
		this.transferid = transferid;
		this.issuccessful = issuccessful;
		this.errorcode = errorcode;
		this.lopid = lopid;
		this.bulkuploadentryid = bulkuploadentryid;
		this.notificationcode = notificationcode;
		this.msgtype = msgtype;
		this.sourcesubscriberid = sourcesubscriberid;
		this.sourcesubscribername = sourcesubscribername;
		this.sourcemdnid = sourcemdnid;
		this.sourcemdn = sourcemdn;
		this.destmdn = destmdn;
		this.sourcepocketid = sourcepocketid;
		this.sourcepockettype = sourcepockettype;
		this.sourceapplication = sourceapplication;
		this.servletpath = servletpath;
		this.iso8583Processingcode = iso8583Processingcode;
		this.iso8583Primaryaccountnumber = iso8583Primaryaccountnumber;
		this.iso8583Systemtraceauditnumber = iso8583Systemtraceauditnumber;
		this.iso8583Retrievalreferencenum = iso8583Retrievalreferencenum;
		this.iso8583Merchanttype = iso8583Merchanttype;
		this.iso8583Acquiringinstidcode = iso8583Acquiringinstidcode;
		this.iso8583Cardacceptoridcode = iso8583Cardacceptoridcode;
		this.iso8583Variant = iso8583Variant;
		this.iso8583Responsecode = iso8583Responsecode;
		this.webclientip = webclientip;
		this.commodity = commodity;
		this.activitycategory = activitycategory;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	

	@Column(name = "PARENTTRANSACTIONID", nullable = false, scale = 0)
	public BigDecimal getParenttransactionid() {
		return this.parenttransactionid;
	}

	public void setParenttransactionid(BigDecimal parenttransactionid) {
		this.parenttransactionid = parenttransactionid;
	}

	@Column(name = "TRANSFERID", scale = 0)
	public BigDecimal getTransferid() {
		return this.transferid;
	}

	public void setTransferid(BigDecimal transferid) {
		this.transferid = transferid;
	}

	@Column(name = "ISSUCCESSFUL", precision = 3, scale = 0)
	public Short getIssuccessful() {
		return this.issuccessful;
	}

	public void setIssuccessful(Short issuccessful) {
		this.issuccessful = issuccessful;
	}

	@Column(name = "ERRORCODE", precision = 10, scale = 0)
	public Long getErrorcode() {
		return this.errorcode;
	}

	public void setErrorcode(Long errorcode) {
		this.errorcode = errorcode;
	}

	@Column(name = "LOPID", scale = 0)
	public BigDecimal getLopid() {
		return this.lopid;
	}

	public void setLopid(BigDecimal lopid) {
		this.lopid = lopid;
	}

	@Column(name = "BULKUPLOADENTRYID", scale = 0)
	public BigDecimal getBulkuploadentryid() {
		return this.bulkuploadentryid;
	}

	public void setBulkuploadentryid(BigDecimal bulkuploadentryid) {
		this.bulkuploadentryid = bulkuploadentryid;
	}

	@Column(name = "NOTIFICATIONCODE", precision = 10, scale = 0)
	public Long getNotificationcode() {
		return this.notificationcode;
	}

	public void setNotificationcode(Long notificationcode) {
		this.notificationcode = notificationcode;
	}

	@Column(name = "MSGTYPE", precision = 10, scale = 0)
	public Long getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(Long msgtype) {
		this.msgtype = msgtype;
	}

	@Column(name = "SOURCESUBSCRIBERID", scale = 0)
	public BigDecimal getSourcesubscriberid() {
		return this.sourcesubscriberid;
	}

	public void setSourcesubscriberid(BigDecimal sourcesubscriberid) {
		this.sourcesubscriberid = sourcesubscriberid;
	}

	@Column(name = "SOURCESUBSCRIBERNAME", length = 1020)
	public String getSourcesubscribername() {
		return this.sourcesubscribername;
	}

	public void setSourcesubscribername(String sourcesubscribername) {
		this.sourcesubscribername = sourcesubscribername;
	}

	@Column(name = "SOURCEMDNID", scale = 0)
	public BigDecimal getSourcemdnid() {
		return this.sourcemdnid;
	}

	public void setSourcemdnid(BigDecimal sourcemdnid) {
		this.sourcemdnid = sourcemdnid;
	}

	@Column(name = "SOURCEMDN", length = 1020)
	public String getSourcemdn() {
		return this.sourcemdn;
	}

	public void setSourcemdn(String sourcemdn) {
		this.sourcemdn = sourcemdn;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

	@Column(name = "SOURCEPOCKETID", scale = 0)
	public BigDecimal getSourcepocketid() {
		return this.sourcepocketid;
	}

	public void setSourcepocketid(BigDecimal sourcepocketid) {
		this.sourcepocketid = sourcepocketid;
	}

	@Column(name = "SOURCEPOCKETTYPE", precision = 10, scale = 0)
	public Long getSourcepockettype() {
		return this.sourcepockettype;
	}

	public void setSourcepockettype(Long sourcepockettype) {
		this.sourcepockettype = sourcepockettype;
	}

	@Column(name = "SOURCEAPPLICATION", precision = 10, scale = 0)
	public Long getSourceapplication() {
		return this.sourceapplication;
	}

	public void setSourceapplication(Long sourceapplication) {
		this.sourceapplication = sourceapplication;
	}

	@Column(name = "SERVLETPATH", length = 1020)
	public String getServletpath() {
		return this.servletpath;
	}

	public void setServletpath(String servletpath) {
		this.servletpath = servletpath;
	}

	@Column(name = "ISO8583_PROCESSINGCODE", length = 1020)
	public String getIso8583Processingcode() {
		return this.iso8583Processingcode;
	}

	public void setIso8583Processingcode(String iso8583Processingcode) {
		this.iso8583Processingcode = iso8583Processingcode;
	}

	@Column(name = "ISO8583_PRIMARYACCOUNTNUMBER", length = 1020)
	public String getIso8583Primaryaccountnumber() {
		return this.iso8583Primaryaccountnumber;
	}

	public void setIso8583Primaryaccountnumber(
			String iso8583Primaryaccountnumber) {
		this.iso8583Primaryaccountnumber = iso8583Primaryaccountnumber;
	}

	@Column(name = "ISO8583_SYSTEMTRACEAUDITNUMBER", length = 1020)
	public String getIso8583Systemtraceauditnumber() {
		return this.iso8583Systemtraceauditnumber;
	}

	public void setIso8583Systemtraceauditnumber(
			String iso8583Systemtraceauditnumber) {
		this.iso8583Systemtraceauditnumber = iso8583Systemtraceauditnumber;
	}

	@Column(name = "ISO8583_RETRIEVALREFERENCENUM", length = 1020)
	public String getIso8583Retrievalreferencenum() {
		return this.iso8583Retrievalreferencenum;
	}

	public void setIso8583Retrievalreferencenum(
			String iso8583Retrievalreferencenum) {
		this.iso8583Retrievalreferencenum = iso8583Retrievalreferencenum;
	}

	@Column(name = "ISO8583_MERCHANTTYPE", length = 1020)
	public String getIso8583Merchanttype() {
		return this.iso8583Merchanttype;
	}

	public void setIso8583Merchanttype(String iso8583Merchanttype) {
		this.iso8583Merchanttype = iso8583Merchanttype;
	}

	@Column(name = "ISO8583_ACQUIRINGINSTIDCODE", precision = 10, scale = 0)
	public Long getIso8583Acquiringinstidcode() {
		return this.iso8583Acquiringinstidcode;
	}

	public void setIso8583Acquiringinstidcode(Long iso8583Acquiringinstidcode) {
		this.iso8583Acquiringinstidcode = iso8583Acquiringinstidcode;
	}

	@Column(name = "ISO8583_CARDACCEPTORIDCODE", length = 1020)
	public String getIso8583Cardacceptoridcode() {
		return this.iso8583Cardacceptoridcode;
	}

	public void setIso8583Cardacceptoridcode(String iso8583Cardacceptoridcode) {
		this.iso8583Cardacceptoridcode = iso8583Cardacceptoridcode;
	}

	@Column(name = "ISO8583_VARIANT", length = 1020)
	public String getIso8583Variant() {
		return this.iso8583Variant;
	}

	public void setIso8583Variant(String iso8583Variant) {
		this.iso8583Variant = iso8583Variant;
	}

	@Column(name = "ISO8583_RESPONSECODE", length = 1020)
	public String getIso8583Responsecode() {
		return this.iso8583Responsecode;
	}

	public void setIso8583Responsecode(String iso8583Responsecode) {
		this.iso8583Responsecode = iso8583Responsecode;
	}

	@Column(name = "WEBCLIENTIP", length = 1020)
	public String getWebclientip() {
		return this.webclientip;
	}

	public void setWebclientip(String webclientip) {
		this.webclientip = webclientip;
	}

	@Column(name = "COMMODITY", precision = 10, scale = 0)
	public Long getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Long commodity) {
		this.commodity = commodity;
	}

	@Column(name = "ACTIVITYCATEGORY", precision = 10, scale = 0)
	public Long getActivitycategory() {
		return this.activitycategory;
	}

	public void setActivitycategory(Long activitycategory) {
		this.activitycategory = activitycategory;
	}

}
