package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActorChannelMapping generated by hbm2java
 */
@Entity
@Table(name = "ACTOR_CHANNEL_MAPPING", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "BUSINESSPARTNERTYPE", "SERVICEID",
				"TRANSACTIONTYPEID", "CHANNELCODEID", "GROUPID" }),
		@UniqueConstraint(columnNames = { "SUBSCRIBERTYPE", "KYCLEVEL",
				"SERVICEID", "TRANSACTIONTYPEID", "CHANNELCODEID", "GROUPID" }) })
public class ActorChannelMapping extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String FieldName_SubscriberType = "subscribertype";
	public static final String FieldName_BusinessPartnerType = "businesspartnertype";
	public static final String FieldName_Service = "service";

	public static final String FieldName_TransactionType = "transactionType";

	public static final String FieldName_ChannelCode = "channelCode";

	public static final String FieldName_KYCLevelByKYCLevel = "kycLevel";

	public static final String FieldName_Group = "groups";
	
	private ChannelCode channelCode;
	private Service service;
	private KycLevel kycLevel;
	private Groups groups;
	private TransactionType transactionType;
	private short isallowed;
	private long subscribertype;
	private Long businesspartnertype;
	private Long id;

	public ActorChannelMapping() {
	}
	
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "actor_channel_mapping_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHANNELCODEID", nullable = false)
	public ChannelCode getChannelCode() {
		return this.channelCode;
	}

	public void setChannelCode(ChannelCode channelCode) {
		this.channelCode = channelCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KYCLEVEL")
	public KycLevel getKycLevel() {
		return this.kycLevel;
	}

	public void setKycLevel(KycLevel kycLevel) {
		this.kycLevel = kycLevel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUPID")
	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONTYPEID", nullable = false)
	public TransactionType getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	
	@Column(name = "ISALLOWED", nullable = false, precision = 3, scale = 0)
	public short getIsallowed() {
		return this.isallowed;
	}

	public void setIsallowed(short isallowed) {
		this.isallowed = isallowed;
	}

	@Column(name = "SUBSCRIBERTYPE", nullable = false, precision = 10, scale = 0)
	public long getSubscribertype() {
		return this.subscribertype;
	}

	public void setSubscribertype(long subscribertype) {
		this.subscribertype = subscribertype;
	}

	@Column(name = "BUSINESSPARTNERTYPE", precision = 10, scale = 0)
	public Long getBusinesspartnertype() {
		return this.businesspartnertype;
	}

	public void setBusinesspartnertype(Long businesspartnertype) {
		this.businesspartnertype = businesspartnertype;
	}

}
