package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AgentCashinTxnLog generated by hbm2java
 */
@Entity
@Table(name = "AGENT_CASHIN_TXN_LOG")
public class AgentCashinTxnLog implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal destpartnerid;
	private String sourcemdn;
	private String destmdn;
	private BigDecimal sourcepocketid;
	private BigDecimal destpocketid;
	private BigDecimal amount;
	private Long agentcashintrxnstatus;
	private String agentcashintrxnstatusreason;
	private BigDecimal sctlid;

	public AgentCashinTxnLog() {
	}

	public AgentCashinTxnLog(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public AgentCashinTxnLog(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal destpartnerid, String sourcemdn, String destmdn,
			BigDecimal sourcepocketid, BigDecimal destpocketid,
			BigDecimal amount, Long agentcashintrxnstatus,
			String agentcashintrxnstatusreason, BigDecimal sctlid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.destpartnerid = destpartnerid;
		this.sourcemdn = sourcemdn;
		this.destmdn = destmdn;
		this.sourcepocketid = sourcepocketid;
		this.destpocketid = destpocketid;
		this.amount = amount;
		this.agentcashintrxnstatus = agentcashintrxnstatus;
		this.agentcashintrxnstatusreason = agentcashintrxnstatusreason;
		this.sctlid = sctlid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "DESTPARTNERID", scale = 0)
	public BigDecimal getDestpartnerid() {
		return this.destpartnerid;
	}

	public void setDestpartnerid(BigDecimal destpartnerid) {
		this.destpartnerid = destpartnerid;
	}

	@Column(name = "SOURCEMDN", length = 1020)
	public String getSourcemdn() {
		return this.sourcemdn;
	}

	public void setSourcemdn(String sourcemdn) {
		this.sourcemdn = sourcemdn;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

	@Column(name = "SOURCEPOCKETID", scale = 0)
	public BigDecimal getSourcepocketid() {
		return this.sourcepocketid;
	}

	public void setSourcepocketid(BigDecimal sourcepocketid) {
		this.sourcepocketid = sourcepocketid;
	}

	@Column(name = "DESTPOCKETID", scale = 0)
	public BigDecimal getDestpocketid() {
		return this.destpocketid;
	}

	public void setDestpocketid(BigDecimal destpocketid) {
		this.destpocketid = destpocketid;
	}

	@Column(name = "AMOUNT", precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "AGENTCASHINTRXNSTATUS", precision = 10, scale = 0)
	public Long getAgentcashintrxnstatus() {
		return this.agentcashintrxnstatus;
	}

	public void setAgentcashintrxnstatus(Long agentcashintrxnstatus) {
		this.agentcashintrxnstatus = agentcashintrxnstatus;
	}

	@Column(name = "AGENTCASHINTRXNSTATUSREASON")
	public String getAgentcashintrxnstatusreason() {
		return this.agentcashintrxnstatusreason;
	}

	public void setAgentcashintrxnstatusreason(
			String agentcashintrxnstatusreason) {
		this.agentcashintrxnstatusreason = agentcashintrxnstatusreason;
	}

	@Column(name = "SCTLID", scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

}
