package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AirtimePurchase generated by hbm2java
 */
@Entity
@Table(name = "AIRTIME_PURCHASE")
public class AirtimePurchase implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal sctlid;
	private String partnercode;
	private String incode;
	private String rechargemdn;
	private String sourcemdn;
	private BigDecimal amount;
	private BigDecimal charges;
	private Long responsecode;
	private String intxnid;
	private String inaccounttype;
	private Long airtimepurchasestatus;

	public AirtimePurchase() {
	}

	public AirtimePurchase(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
	}

	public AirtimePurchase(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid, String partnercode, String incode,
			String rechargemdn, String sourcemdn, BigDecimal amount,
			BigDecimal charges, Long responsecode, String intxnid,
			String inaccounttype, Long airtimepurchasestatus) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.partnercode = partnercode;
		this.incode = incode;
		this.rechargemdn = rechargemdn;
		this.sourcemdn = sourcemdn;
		this.amount = amount;
		this.charges = charges;
		this.responsecode = responsecode;
		this.intxnid = intxnid;
		this.inaccounttype = inaccounttype;
		this.airtimepurchasestatus = airtimepurchasestatus;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SCTLID", nullable = false, scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "PARTNERCODE", length = 1020)
	public String getPartnercode() {
		return this.partnercode;
	}

	public void setPartnercode(String partnercode) {
		this.partnercode = partnercode;
	}

	@Column(name = "INCODE", length = 1020)
	public String getIncode() {
		return this.incode;
	}

	public void setIncode(String incode) {
		this.incode = incode;
	}

	@Column(name = "RECHARGEMDN", length = 1020)
	public String getRechargemdn() {
		return this.rechargemdn;
	}

	public void setRechargemdn(String rechargemdn) {
		this.rechargemdn = rechargemdn;
	}

	@Column(name = "SOURCEMDN", length = 1020)
	public String getSourcemdn() {
		return this.sourcemdn;
	}

	public void setSourcemdn(String sourcemdn) {
		this.sourcemdn = sourcemdn;
	}

	@Column(name = "AMOUNT", precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "CHARGES", precision = 25, scale = 4)
	public BigDecimal getCharges() {
		return this.charges;
	}

	public void setCharges(BigDecimal charges) {
		this.charges = charges;
	}

	@Column(name = "RESPONSECODE", precision = 10, scale = 0)
	public Long getResponsecode() {
		return this.responsecode;
	}

	public void setResponsecode(Long responsecode) {
		this.responsecode = responsecode;
	}

	@Column(name = "INTXNID", length = 1020)
	public String getIntxnid() {
		return this.intxnid;
	}

	public void setIntxnid(String intxnid) {
		this.intxnid = intxnid;
	}

	@Column(name = "INACCOUNTTYPE", length = 1020)
	public String getInaccounttype() {
		return this.inaccounttype;
	}

	public void setInaccounttype(String inaccounttype) {
		this.inaccounttype = inaccounttype;
	}

	@Column(name = "AIRTIMEPURCHASESTATUS", precision = 10, scale = 0)
	public Long getAirtimepurchasestatus() {
		return this.airtimepurchasestatus;
	}

	public void setAirtimepurchasestatus(Long airtimepurchasestatus) {
		this.airtimepurchasestatus = airtimepurchasestatus;
	}

}
