package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ArchiveMdns generated by hbm2java
 */
@Entity
@Table(name = "ARCHIVE_MDNS")
public class ArchiveMdns implements java.io.Serializable {

	private ArchiveMdnsId id;

	public ArchiveMdns() {
	}

	public ArchiveMdns(ArchiveMdnsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "subscriberid", column = @Column(name = "SUBSCRIBERID", scale = 0)),
			@AttributeOverride(name = "mdn", column = @Column(name = "MDN")),
			@AttributeOverride(name = "archiveDate", column = @Column(name = "ARCHIVE_DATE")) })
	public ArchiveMdnsId getId() {
		return this.id;
	}

	public void setId(ArchiveMdnsId id) {
		this.id = id;
	}

}
