package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;
/**
 * AuditLog generated by hbm2java
 */
@Entity
@Table(name = "AUDIT_LOG")
public class AuditLog extends Base implements java.io.Serializable {

	
	private String messagename;
	private Clob fixmessage;
	private String jsaction;

	public AuditLog() {
	}

	

	@Column(name = "MESSAGENAME", nullable = false)
	public String getMessagename() {
		return this.messagename;
	}

	public void setMessagename(String messagename) {
		this.messagename = messagename;
	}

	@Column(name = "FIXMESSAGE", nullable = false)
	public Clob getFixmessage() {
		return this.fixmessage;
	}

	public void setFixmessage(Clob fixmessage) {
		this.fixmessage = fixmessage;
	}

	@Column(name = "JSACTION", nullable = false)
	public String getJsaction() {
		return this.jsaction;
	}

	public void setJsaction(String jsaction) {
		this.jsaction = jsaction;
	}

}
