package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AuditLog generated by hbm2java
 */
@Entity
@Table(name = "AUDIT_LOG")
public class AuditLog implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String messagename;
	private Clob fixmessage;
	private String jsaction;

	public AuditLog() {
	}

	public AuditLog(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			String messagename, Clob fixmessage, String jsaction) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.messagename = messagename;
		this.fixmessage = fixmessage;
		this.jsaction = jsaction;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MESSAGENAME", nullable = false)
	public String getMessagename() {
		return this.messagename;
	}

	public void setMessagename(String messagename) {
		this.messagename = messagename;
	}

	@Column(name = "FIXMESSAGE", nullable = false)
	public Clob getFixmessage() {
		return this.fixmessage;
	}

	public void setFixmessage(Clob fixmessage) {
		this.fixmessage = fixmessage;
	}

	@Column(name = "JSACTION", nullable = false)
	public String getJsaction() {
		return this.jsaction;
	}

	public void setJsaction(String jsaction) {
		this.jsaction = jsaction;
	}

}
