package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AuthPersonDetails generated by hbm2java
 */
@Entity
@Table(name = "AUTH_PERSON_DETAILS")
public class AuthPersonDetails implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Address address;
	private MfinoServiceProvider mfinoServiceProvider;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String firstname;
	private String lastname;
	private String iddesc;
	private String idnumber;
	private Serializable dateofbirth;
	private Set<Subscriber> subscribers = new HashSet<Subscriber>(0);

	public AuthPersonDetails() {
	}

	public AuthPersonDetails(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public AuthPersonDetails(BigDecimal id, Address address,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String firstname,
			String lastname, String iddesc, String idnumber,
			Serializable dateofbirth, Set<Subscriber> subscribers) {
		this.id = id;
		this.address = address;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.firstname = firstname;
		this.lastname = lastname;
		this.iddesc = iddesc;
		this.idnumber = idnumber;
		this.dateofbirth = dateofbirth;
		this.subscribers = subscribers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESSID")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "FIRSTNAME", length = 1020)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", length = 1020)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "IDDESC", length = 1020)
	public String getIddesc() {
		return this.iddesc;
	}

	public void setIddesc(String iddesc) {
		this.iddesc = iddesc;
	}

	@Column(name = "IDNUMBER", length = 1020)
	public String getIdnumber() {
		return this.idnumber;
	}

	public void setIdnumber(String idnumber) {
		this.idnumber = idnumber;
	}

	@Column(name = "DATEOFBIRTH")
	public Serializable getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Serializable dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authPersonDetails")
	public Set<Subscriber> getSubscribers() {
		return this.subscribers;
	}

	public void setSubscribers(Set<Subscriber> subscribers) {
		this.subscribers = subscribers;
	}

}
