package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * AutoReversals generated by hbm2java
 */
@Entity
@Table(name = "AUTO_REVERSALS")
public class AutoReversals implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal sctlid;
	private BigDecimal sourcepocketid;
	private BigDecimal destpocketid;
	private long autorevstatus;
	private BigDecimal amount;
	private BigDecimal charges;

	public AutoReversals() {
	}

	public AutoReversals(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid, BigDecimal sourcepocketid,
			BigDecimal destpocketid, long autorevstatus) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.sourcepocketid = sourcepocketid;
		this.destpocketid = destpocketid;
		this.autorevstatus = autorevstatus;
	}

	public AutoReversals(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid, BigDecimal sourcepocketid,
			BigDecimal destpocketid, long autorevstatus, BigDecimal amount,
			BigDecimal charges) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.sourcepocketid = sourcepocketid;
		this.destpocketid = destpocketid;
		this.autorevstatus = autorevstatus;
		this.amount = amount;
		this.charges = charges;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 20, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 11, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SCTLID", nullable = false, precision = 20, scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "SOURCEPOCKETID", nullable = false, precision = 20, scale = 0)
	public BigDecimal getSourcepocketid() {
		return this.sourcepocketid;
	}

	public void setSourcepocketid(BigDecimal sourcepocketid) {
		this.sourcepocketid = sourcepocketid;
	}

	@Column(name = "DESTPOCKETID", nullable = false, precision = 20, scale = 0)
	public BigDecimal getDestpocketid() {
		return this.destpocketid;
	}

	public void setDestpocketid(BigDecimal destpocketid) {
		this.destpocketid = destpocketid;
	}

	@Column(name = "AUTOREVSTATUS", nullable = false, precision = 11, scale = 0)
	public long getAutorevstatus() {
		return this.autorevstatus;
	}

	public void setAutorevstatus(long autorevstatus) {
		this.autorevstatus = autorevstatus;
	}

	@Column(name = "AMOUNT", precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "CHARGES", precision = 25, scale = 4)
	public BigDecimal getCharges() {
		return this.charges;
	}

	public void setCharges(BigDecimal charges) {
		this.charges = charges;
	}

}
