package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;

/**
 * AutoReversals generated by hbm2java
 */
@Entity
@Table(name = "AUTO_REVERSALS")
public class AutoReversals  extends Base implements java.io.Serializable {

	private BigDecimal sctlid;
	private BigDecimal sourcepocketid;
	private BigDecimal destpocketid;
	private long autorevstatus;
	private BigDecimal amount;
	private BigDecimal charges;

	public AutoReversals() {
	}

	public AutoReversals(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal sctlid, BigDecimal sourcepocketid,
			BigDecimal destpocketid, long autorevstatus) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.sourcepocketid = sourcepocketid;
		this.destpocketid = destpocketid;
		this.autorevstatus = autorevstatus;
	}

	public AutoReversals(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal sctlid, BigDecimal sourcepocketid,
			BigDecimal destpocketid, long autorevstatus, BigDecimal amount,
			BigDecimal charges) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.sourcepocketid = sourcepocketid;
		this.destpocketid = destpocketid;
		this.autorevstatus = autorevstatus;
		this.amount = amount;
		this.charges = charges;
	}

	

	@Column(name = "SCTLID", nullable = false, precision = 20, scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "SOURCEPOCKETID", nullable = false, precision = 20, scale = 0)
	public BigDecimal getSourcepocketid() {
		return this.sourcepocketid;
	}

	public void setSourcepocketid(BigDecimal sourcepocketid) {
		this.sourcepocketid = sourcepocketid;
	}

	@Column(name = "DESTPOCKETID", nullable = false, precision = 20, scale = 0)
	public BigDecimal getDestpocketid() {
		return this.destpocketid;
	}

	public void setDestpocketid(BigDecimal destpocketid) {
		this.destpocketid = destpocketid;
	}

	@Column(name = "AUTOREVSTATUS", nullable = false, precision = 11, scale = 0)
	public long getAutorevstatus() {
		return this.autorevstatus;
	}

	public void setAutorevstatus(long autorevstatus) {
		this.autorevstatus = autorevstatus;
	}

	@Column(name = "AMOUNT", precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "CHARGES", precision = 25, scale = 4)
	public BigDecimal getCharges() {
		return this.charges;
	}

	public void setCharges(BigDecimal charges) {
		this.charges = charges;
	}

}
