package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BankAdmin generated by hbm2java
 */
@Entity
@Table(name = "BANK_ADMIN")
public class BankAdmin extends Base implements java.io.Serializable {

	
	private MfinoUser mfinoUser;
	private Bank bank;
	private Long id;

	public BankAdmin() {
	}
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "bank_admin_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
		

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID", nullable = false)
	public MfinoUser getMfinoUser() {
		return this.mfinoUser;
	}

	public void setMfinoUser(MfinoUser mfinoUser) {
		this.mfinoUser = mfinoUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BANKID", nullable = false)
	public Bank getBank() {
		return this.bank;
	}

	public void setBank(Bank bank) {
		this.bank = bank;
	}

	

}
