package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name = "BANK", uniqueConstraints = @UniqueConstraint(columnNames = "BANKCODE"))
public class Bank implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String name;
	private Long bankcode;
	private String header;
	private String contactnumber;
	private String description;
	private Long status;
	private Serializable statustime;
	private Set<BankAdmin> bankAdmins = new HashSet<BankAdmin>(0);

	public Bank() {
	}

	public Bank(BigDecimal id, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public Bank(BigDecimal id, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String name,
			Long bankcode, String header, String contactnumber,
			String description, Long status, Serializable statustime,
			Set<BankAdmin> bankAdmins) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.name = name;
		this.bankcode = bankcode;
		this.header = header;
		this.contactnumber = contactnumber;
		this.description = description;
		this.status = status;
		this.statustime = statustime;
		this.bankAdmins = bankAdmins;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "NAME", length = 1020)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "BANKCODE", unique = true, precision = 10, scale = 0)
	public Long getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(Long bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "HEADER", length = 1020)
	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	@Column(name = "CONTACTNUMBER", length = 1020)
	public String getContactnumber() {
		return this.contactnumber;
	}

	public void setContactnumber(String contactnumber) {
		this.contactnumber = contactnumber;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "STATUS", precision = 10, scale = 0)
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Column(name = "STATUSTIME")
	public Serializable getStatustime() {
		return this.statustime;
	}

	public void setStatustime(Serializable statustime) {
		this.statustime = statustime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bank")
	public Set<BankAdmin> getBankAdmins() {
		return this.bankAdmins;
	}

	public void setBankAdmins(Set<BankAdmin> bankAdmins) {
		this.bankAdmins = bankAdmins;
	}

}
