package com.mfino.domain;

// Generated Jul 27, 2009 3:18:44 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

import com.mfino.fix.CmFinoFIX;

/**
 * BillPayments generated by hbm2java
 */
public class BillPayments extends CmFinoFIX.CRBillPayments {

	public BigDecimal getOperatorAmount() {
		BigDecimal amount;

		if ((getChargesIncluded() != null) && getChargesIncluded().equals(true)) {
			amount = getCharges().add(getAmount());
			return amount;
		} else {
			amount = getAmount();
			return amount;
		}

	}
}
