package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * BookingDatedBalance generated by hbm2java
 */
@Entity
@Table(name = "BOOKING_DATED_BALANCE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"POCKETID", "BOOKINGDATE" }))
public class BookingDatedBalance implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal pocketid;
	private Serializable bookingdate;
	private String openingbalance;
	private String closingbalance;
	private BigDecimal totalcredit;
	private BigDecimal totaldebit;
	private BigDecimal netturnover;

	public BookingDatedBalance() {
	}

	public BookingDatedBalance(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal pocketid, Serializable bookingdate,
			String openingbalance, String closingbalance,
			BigDecimal totalcredit, BigDecimal totaldebit,
			BigDecimal netturnover) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.pocketid = pocketid;
		this.bookingdate = bookingdate;
		this.openingbalance = openingbalance;
		this.closingbalance = closingbalance;
		this.totalcredit = totalcredit;
		this.totaldebit = totaldebit;
		this.netturnover = netturnover;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "POCKETID", nullable = false, scale = 0)
	public BigDecimal getPocketid() {
		return this.pocketid;
	}

	public void setPocketid(BigDecimal pocketid) {
		this.pocketid = pocketid;
	}

	@Column(name = "BOOKINGDATE", nullable = false)
	public Serializable getBookingdate() {
		return this.bookingdate;
	}

	public void setBookingdate(Serializable bookingdate) {
		this.bookingdate = bookingdate;
	}

	@Column(name = "OPENINGBALANCE", nullable = false)
	public String getOpeningbalance() {
		return this.openingbalance;
	}

	public void setOpeningbalance(String openingbalance) {
		this.openingbalance = openingbalance;
	}

	@Column(name = "CLOSINGBALANCE", nullable = false)
	public String getClosingbalance() {
		return this.closingbalance;
	}

	public void setClosingbalance(String closingbalance) {
		this.closingbalance = closingbalance;
	}

	@Column(name = "TOTALCREDIT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getTotalcredit() {
		return this.totalcredit;
	}

	public void setTotalcredit(BigDecimal totalcredit) {
		this.totalcredit = totalcredit;
	}

	@Column(name = "TOTALDEBIT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getTotaldebit() {
		return this.totaldebit;
	}

	public void setTotaldebit(BigDecimal totaldebit) {
		this.totaldebit = totaldebit;
	}

	@Column(name = "NETTURNOVER", nullable = false, precision = 25, scale = 4)
	public BigDecimal getNetturnover() {
		return this.netturnover;
	}

	public void setNetturnover(BigDecimal netturnover) {
		this.netturnover = netturnover;
	}

}
