package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;

/**
 * BookingDatedBalance generated by hbm2java
 */
@Entity
@Table(name = "BOOKING_DATED_BALANCE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"POCKETID", "BOOKINGDATE" }))
public class BookingDatedBalance extends Base implements java.io.Serializable {

	
	private BigDecimal pocketid;
	private Timestamp bookingdate;
	private String openingbalance;
	private String closingbalance;
	private BigDecimal totalcredit;
	private BigDecimal totaldebit;
	private BigDecimal netturnover;

	public BookingDatedBalance() {
	}

	public BookingDatedBalance(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal pocketid, Timestamp bookingdate,
			String openingbalance, String closingbalance,
			BigDecimal totalcredit, BigDecimal totaldebit,
			BigDecimal netturnover) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.pocketid = pocketid;
		this.bookingdate = bookingdate;
		this.openingbalance = openingbalance;
		this.closingbalance = closingbalance;
		this.totalcredit = totalcredit;
		this.totaldebit = totaldebit;
		this.netturnover = netturnover;
	}

	
	@Column(name = "POCKETID", nullable = false, scale = 0)
	public BigDecimal getPocketid() {
		return this.pocketid;
	}

	public void setPocketid(BigDecimal pocketid) {
		this.pocketid = pocketid;
	}

	@Column(name = "BOOKINGDATE", nullable = false)
	public Timestamp getBookingdate() {
		return this.bookingdate;
	}

	public void setBookingdate(Timestamp bookingdate) {
		this.bookingdate = bookingdate;
	}

	@Column(name = "OPENINGBALANCE", nullable = false)
	public String getOpeningbalance() {
		return this.openingbalance;
	}

	public void setOpeningbalance(String openingbalance) {
		this.openingbalance = openingbalance;
	}

	@Column(name = "CLOSINGBALANCE", nullable = false)
	public String getClosingbalance() {
		return this.closingbalance;
	}

	public void setClosingbalance(String closingbalance) {
		this.closingbalance = closingbalance;
	}

	@Column(name = "TOTALCREDIT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getTotalcredit() {
		return this.totalcredit;
	}

	public void setTotalcredit(BigDecimal totalcredit) {
		this.totalcredit = totalcredit;
	}

	@Column(name = "TOTALDEBIT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getTotaldebit() {
		return this.totaldebit;
	}

	public void setTotaldebit(BigDecimal totaldebit) {
		this.totaldebit = totaldebit;
	}

	@Column(name = "NETTURNOVER", nullable = false, precision = 25, scale = 4)
	public BigDecimal getNetturnover() {
		return this.netturnover;
	}

	public void setNetturnover(BigDecimal netturnover) {
		this.netturnover = netturnover;
	}

}
