package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "BRAND", uniqueConstraints = @UniqueConstraint(columnNames = "BRANDNAME"))
public class Brand implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private MfinoServiceProvider mfinoServiceProvider;
	private Company company;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String internationalcountrycode;
	private String prefixcode;
	private String brandname;
	private Set<SmsCode> smsCodes = new HashSet<SmsCode>(0);
	private Set<MdnRange> mdnRanges = new HashSet<MdnRange>(0);

	public Brand() {
	}

	public Brand(BigDecimal id, MfinoServiceProvider mfinoServiceProvider,
			Company company, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby,
			String internationalcountrycode, String prefixcode, String brandname) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.company = company;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.internationalcountrycode = internationalcountrycode;
		this.prefixcode = prefixcode;
		this.brandname = brandname;
	}

	public Brand(BigDecimal id, MfinoServiceProvider mfinoServiceProvider,
			Company company, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby,
			String internationalcountrycode, String prefixcode,
			String brandname, Set<SmsCode> smsCodes, Set<MdnRange> mdnRanges) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.company = company;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.internationalcountrycode = internationalcountrycode;
		this.prefixcode = prefixcode;
		this.brandname = brandname;
		this.smsCodes = smsCodes;
		this.mdnRanges = mdnRanges;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "INTERNATIONALCOUNTRYCODE", nullable = false, length = 1020)
	public String getInternationalcountrycode() {
		return this.internationalcountrycode;
	}

	public void setInternationalcountrycode(String internationalcountrycode) {
		this.internationalcountrycode = internationalcountrycode;
	}

	@Column(name = "PREFIXCODE", nullable = false, length = 1020)
	public String getPrefixcode() {
		return this.prefixcode;
	}

	public void setPrefixcode(String prefixcode) {
		this.prefixcode = prefixcode;
	}

	@Column(name = "BRANDNAME", unique = true, nullable = false, length = 1020)
	public String getBrandname() {
		return this.brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set<SmsCode> getSmsCodes() {
		return this.smsCodes;
	}

	public void setSmsCodes(Set<SmsCode> smsCodes) {
		this.smsCodes = smsCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set<MdnRange> getMdnRanges() {
		return this.mdnRanges;
	}

	public void setMdnRanges(Set<MdnRange> mdnRanges) {
		this.mdnRanges = mdnRanges;
	}

}
