package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;

/**
 * Branchcodes generated by hbm2java
 */
@Entity
@Table(name = "BRANCHCODES")
public class BranchCodes extends Base implements java.io.Serializable {

	
	private String branchcode;
	private String branchname;
	private String officecategory;

	public BranchCodes() {
	}

	public BranchCodes(BigDecimal id, Timestamp createtime,
			String createdby, String branchcode, String branchname) {
		this.id = id;
		this.createtime = createtime;
		this.createdby = createdby;
		this.branchcode = branchcode;
		this.branchname = branchname;
	}

	public BranchCodes(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			String branchcode, String branchname, String officecategory) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.branchcode = branchcode;
		this.branchname = branchname;
		this.officecategory = officecategory;
	}

	

	@Column(name = "BRANCHCODE", nullable = false, length = 10)
	public String getBranchcode() {
		return this.branchcode;
	}

	public void setBranchcode(String branchcode) {
		this.branchcode = branchcode;
	}

	@Column(name = "BRANCHNAME", nullable = false, length = 200)
	public String getBranchname() {
		return this.branchname;
	}

	public void setBranchname(String branchname) {
		this.branchname = branchname;
	}

	@Column(name = "OFFICECATEGORY", length = 100)
	public String getOfficecategory() {
		return this.officecategory;
	}

	public void setOfficecategory(String officecategory) {
		this.officecategory = officecategory;
	}

}
