package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * BulkUploadFileEntry generated by hbm2java
 */
@Entity
@Table(name = "BULK_UPLOAD_FILE_ENTRY")
public class BulkUploadFileEntry implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private BulkUploadFile bulkUploadFile;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private Clob linedata;
	private long linenumber;
	private long bulkuploadfileentrystatus;
	private String failurereason;

	public BulkUploadFileEntry() {
	}

	public BulkUploadFileEntry(BigDecimal id, BulkUploadFile bulkUploadFile,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, Clob linedata,
			long linenumber, long bulkuploadfileentrystatus) {
		this.id = id;
		this.bulkUploadFile = bulkUploadFile;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.linedata = linedata;
		this.linenumber = linenumber;
		this.bulkuploadfileentrystatus = bulkuploadfileentrystatus;
	}

	public BulkUploadFileEntry(BigDecimal id, BulkUploadFile bulkUploadFile,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, Clob linedata,
			long linenumber, long bulkuploadfileentrystatus,
			String failurereason) {
		this.id = id;
		this.bulkUploadFile = bulkUploadFile;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.linedata = linedata;
		this.linenumber = linenumber;
		this.bulkuploadfileentrystatus = bulkuploadfileentrystatus;
		this.failurereason = failurereason;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BULKUPLOADFILEID", nullable = false)
	public BulkUploadFile getBulkUploadFile() {
		return this.bulkUploadFile;
	}

	public void setBulkUploadFile(BulkUploadFile bulkUploadFile) {
		this.bulkUploadFile = bulkUploadFile;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "LINEDATA", nullable = false)
	public Clob getLinedata() {
		return this.linedata;
	}

	public void setLinedata(Clob linedata) {
		this.linedata = linedata;
	}

	@Column(name = "LINENUMBER", nullable = false, precision = 10, scale = 0)
	public long getLinenumber() {
		return this.linenumber;
	}

	public void setLinenumber(long linenumber) {
		this.linenumber = linenumber;
	}

	@Column(name = "BULKUPLOADFILEENTRYSTATUS", nullable = false, precision = 10, scale = 0)
	public long getBulkuploadfileentrystatus() {
		return this.bulkuploadfileentrystatus;
	}

	public void setBulkuploadfileentrystatus(long bulkuploadfileentrystatus) {
		this.bulkuploadfileentrystatus = bulkuploadfileentrystatus;
	}

	@Column(name = "FAILUREREASON")
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

}
