package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BulkUploadFileEntry generated by hbm2java
 */
@Entity
@Table(name = "BULK_UPLOAD_FILE_ENTRY")
public class BulkUploadFileEntry extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	public static final String FieldName_BulkUploadFile = "bulkUploadFile";
	
	private BulkUploadFile bulkUploadFile;
	private Clob linedata;
	private long linenumber;
	private long bulkuploadfileentrystatus;
	private String failurereason;
	private Long id;

	public BulkUploadFileEntry() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "bulk_upload_file_entry_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BULKUPLOADFILEID", nullable = false)
	public BulkUploadFile getBulkUploadFile() {
		return this.bulkUploadFile;
	}

	public void setBulkUploadFile(BulkUploadFile bulkUploadFile) {
		this.bulkUploadFile = bulkUploadFile;
	}

	

	@Column(name = "LINEDATA", nullable = false)
	public Clob getLinedata() {
		return this.linedata;
	}

	public void setLinedata(Clob linedata) {
		this.linedata = linedata;
	}

	@Column(name = "LINENUMBER", nullable = false, precision = 10, scale = 0)
	public long getLinenumber() {
		return this.linenumber;
	}

	public void setLinenumber(long linenumber) {
		this.linenumber = linenumber;
	}

	@Column(name = "BULKUPLOADFILEENTRYSTATUS", nullable = false, precision = 10, scale = 0)
	public long getBulkuploadfileentrystatus() {
		return this.bulkuploadfileentrystatus;
	}

	public void setBulkuploadfileentrystatus(long bulkuploadfileentrystatus) {
		this.bulkuploadfileentrystatus = bulkuploadfileentrystatus;
	}

	@Column(name = "FAILUREREASON")
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

}
