package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.mfino.hibernate.Timestamp;

/**
 * BulkUploadEntry generated by hbm2java
 */
@Entity
@Table(name = "BULK_UPLOAD_ENTRY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"UPLOADID", "LINENUMBER" }))
public class BulkUploadEntry extends Base implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	public static final String FieldName_BulkUploadID = "uploadid";
	public static final String FieldName_BulkUploadLineNumber = "linenumber";
	public static final String FieldName_TransferStatus = "status";
	public static final String FieldName_IsUnRegistered = "isunregistered";
	public static final String FieldName_ServiceChargeTransactionLogID = "servicechargetransactionlogid";
	
	private Long uploadid;
	private long linenumber;
	private long status;
	private Long transferfailurereason;
	private Long notificationcode;
	private BigDecimal transferid;
	private BigDecimal amount;
	private String destmdn;
	private String failurereason;
	private BigDecimal servicechargetransactionlogid;
	private String firstname;
	private String lastname;
	private Short isunregistered;
	private Short istrftosuspense;

	public BulkUploadEntry() {
	}

	
	

	@Column(name = "UPLOADID", nullable = false, scale = 0)
	public Long getUploadid() {
		return this.uploadid;
	}

	public void setUploadid(Long uploadid) {
		this.uploadid = uploadid;
	}

	@Column(name = "LINENUMBER", nullable = false, precision = 10, scale = 0)
	public long getLinenumber() {
		return this.linenumber;
	}

	public void setLinenumber(long linenumber) {
		this.linenumber = linenumber;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "TRANSFERFAILUREREASON", precision = 10, scale = 0)
	public Long getTransferfailurereason() {
		return this.transferfailurereason;
	}

	public void setTransferfailurereason(Long transferfailurereason) {
		this.transferfailurereason = transferfailurereason;
	}

	@Column(name = "NOTIFICATIONCODE", precision = 10, scale = 0)
	public Long getNotificationcode() {
		return this.notificationcode;
	}

	public void setNotificationcode(Long notificationcode) {
		this.notificationcode = notificationcode;
	}

	@Column(name = "TRANSFERID", scale = 0)
	public BigDecimal getTransferid() {
		return this.transferid;
	}

	public void setTransferid(BigDecimal transferid) {
		this.transferid = transferid;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

	@Column(name = "FAILUREREASON", length = 1020)
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

	@Column(name = "SERVICECHARGETRANSACTIONLOGID", scale = 0)
	public BigDecimal getServicechargetransactionlogid() {
		return this.servicechargetransactionlogid;
	}

	public void setServicechargetransactionlogid(
			BigDecimal servicechargetransactionlogid) {
		this.servicechargetransactionlogid = servicechargetransactionlogid;
	}

	@Column(name = "FIRSTNAME", length = 1020)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", length = 1020)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "ISUNREGISTERED", precision = 3, scale = 0)
	public Short getIsunregistered() {
		return this.isunregistered;
	}

	public void setIsunregistered(Short isunregistered) {
		this.isunregistered = isunregistered;
	}

	@Column(name = "ISTRFTOSUSPENSE", precision = 3, scale = 0)
	public Short getIstrftosuspense() {
		return this.istrftosuspense;
	}

	public void setIstrftosuspense(Short istrftosuspense) {
		this.istrftosuspense = istrftosuspense;
	}

}
