package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * BulkUploadFileEntry generated by hbm2java
 */
@Entity
@Table(name = "BULK_UPLOAD_FILE_ENTRY")
public class BulkUploadFileEntry extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	public static final String FieldName_BulkUploadFile = "bulkUploadFile";
	
	private BulkUploadFile bulkUploadFile;
	private Clob linedata;
	private long linenumber;
	private long bulkuploadfileentrystatus;
	private String failurereason;

	public BulkUploadFileEntry() {
	}

	public BulkUploadFileEntry(BigDecimal id, BulkUploadFile bulkUploadFile,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, Clob linedata,
			long linenumber, long bulkuploadfileentrystatus) {
		this.id = id;
		this.bulkUploadFile = bulkUploadFile;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.linedata = linedata;
		this.linenumber = linenumber;
		this.bulkuploadfileentrystatus = bulkuploadfileentrystatus;
	}

	public BulkUploadFileEntry(BigDecimal id, BulkUploadFile bulkUploadFile,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, Clob linedata,
			long linenumber, long bulkuploadfileentrystatus,
			String failurereason) {
		this.id = id;
		this.bulkUploadFile = bulkUploadFile;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.linedata = linedata;
		this.linenumber = linenumber;
		this.bulkuploadfileentrystatus = bulkuploadfileentrystatus;
		this.failurereason = failurereason;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BULKUPLOADFILEID", nullable = false)
	public BulkUploadFile getBulkUploadFile() {
		return this.bulkUploadFile;
	}

	public void setBulkUploadFile(BulkUploadFile bulkUploadFile) {
		this.bulkUploadFile = bulkUploadFile;
	}

	

	@Column(name = "LINEDATA", nullable = false)
	public Clob getLinedata() {
		return this.linedata;
	}

	public void setLinedata(Clob linedata) {
		this.linedata = linedata;
	}

	@Column(name = "LINENUMBER", nullable = false, precision = 10, scale = 0)
	public long getLinenumber() {
		return this.linenumber;
	}

	public void setLinenumber(long linenumber) {
		this.linenumber = linenumber;
	}

	@Column(name = "BULKUPLOADFILEENTRYSTATUS", nullable = false, precision = 10, scale = 0)
	public long getBulkuploadfileentrystatus() {
		return this.bulkuploadfileentrystatus;
	}

	public void setBulkuploadfileentrystatus(long bulkuploadfileentrystatus) {
		this.bulkuploadfileentrystatus = bulkuploadfileentrystatus;
	}

	@Column(name = "FAILUREREASON")
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

}
