package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * BulkUploadEntry generated by hbm2java
 */
@Entity
@Table(name = "BULK_UPLOAD_ENTRY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"UPLOADID", "LINENUMBER" }))
public class BulkUploadEntry implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal uploadid;
	private long linenumber;
	private long status;
	private Long transferfailurereason;
	private Long notificationcode;
	private BigDecimal transferid;
	private BigDecimal amount;
	private String destmdn;
	private String failurereason;
	private BigDecimal servicechargetransactionlogid;
	private String firstname;
	private String lastname;
	private Short isunregistered;
	private Short istrftosuspense;

	public BulkUploadEntry() {
	}

	public BulkUploadEntry(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal uploadid, long linenumber, long status, BigDecimal amount) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.uploadid = uploadid;
		this.linenumber = linenumber;
		this.status = status;
		this.amount = amount;
	}

	public BulkUploadEntry(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal uploadid, long linenumber, long status,
			Long transferfailurereason, Long notificationcode,
			BigDecimal transferid, BigDecimal amount, String destmdn,
			String failurereason, BigDecimal servicechargetransactionlogid,
			String firstname, String lastname, Short isunregistered,
			Short istrftosuspense) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.uploadid = uploadid;
		this.linenumber = linenumber;
		this.status = status;
		this.transferfailurereason = transferfailurereason;
		this.notificationcode = notificationcode;
		this.transferid = transferid;
		this.amount = amount;
		this.destmdn = destmdn;
		this.failurereason = failurereason;
		this.servicechargetransactionlogid = servicechargetransactionlogid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.isunregistered = isunregistered;
		this.istrftosuspense = istrftosuspense;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "UPLOADID", nullable = false, scale = 0)
	public BigDecimal getUploadid() {
		return this.uploadid;
	}

	public void setUploadid(BigDecimal uploadid) {
		this.uploadid = uploadid;
	}

	@Column(name = "LINENUMBER", nullable = false, precision = 10, scale = 0)
	public long getLinenumber() {
		return this.linenumber;
	}

	public void setLinenumber(long linenumber) {
		this.linenumber = linenumber;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "TRANSFERFAILUREREASON", precision = 10, scale = 0)
	public Long getTransferfailurereason() {
		return this.transferfailurereason;
	}

	public void setTransferfailurereason(Long transferfailurereason) {
		this.transferfailurereason = transferfailurereason;
	}

	@Column(name = "NOTIFICATIONCODE", precision = 10, scale = 0)
	public Long getNotificationcode() {
		return this.notificationcode;
	}

	public void setNotificationcode(Long notificationcode) {
		this.notificationcode = notificationcode;
	}

	@Column(name = "TRANSFERID", scale = 0)
	public BigDecimal getTransferid() {
		return this.transferid;
	}

	public void setTransferid(BigDecimal transferid) {
		this.transferid = transferid;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

	@Column(name = "FAILUREREASON", length = 1020)
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

	@Column(name = "SERVICECHARGETRANSACTIONLOGID", scale = 0)
	public BigDecimal getServicechargetransactionlogid() {
		return this.servicechargetransactionlogid;
	}

	public void setServicechargetransactionlogid(
			BigDecimal servicechargetransactionlogid) {
		this.servicechargetransactionlogid = servicechargetransactionlogid;
	}

	@Column(name = "FIRSTNAME", length = 1020)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", length = 1020)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "ISUNREGISTERED", precision = 3, scale = 0)
	public Short getIsunregistered() {
		return this.isunregistered;
	}

	public void setIsunregistered(Short isunregistered) {
		this.isunregistered = isunregistered;
	}

	@Column(name = "ISTRFTOSUSPENSE", precision = 3, scale = 0)
	public Short getIstrftosuspense() {
		return this.istrftosuspense;
	}

	public void setIstrftosuspense(Short istrftosuspense) {
		this.istrftosuspense = istrftosuspense;
	}

}
