package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
/**
 * CardInfo generated by hbm2java
 */
@Entity
@Table(name = "CARD_INFO")
public class CardInfo extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	public static final String FieldName_CardStatus = "cardstatus";
	public static final String FieldName_isConformationRequired = "isconformationrequired";
	
	private Pocket pocket;
	private Address addressByBillingaddressid;
	private Address addressByOldaddressid;
	private Address addressByOldbillingaddressid;
	private Subscriber subscriber;
	private Address addressByAddressid;
	private String cardf6;
	private String cardl4;
	private String issuername;
	private String nameoncard;
	private String oldcardf6;
	private String oldcardl4;
	private String oldissuername;
	private String oldnameoncard;
	private long cardstatus;
	private Boolean isconformationrequired;
	private Long id;

	public CardInfo() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "card_info_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETID")
	public Pocket getPocket() {
		return this.pocket;
	}

	public void setPocket(Pocket pocket) {
		this.pocket = pocket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILLINGADDRESSID")
	public Address getAddressByBillingaddressid() {
		return this.addressByBillingaddressid;
	}

	public void setAddressByBillingaddressid(Address addressByBillingaddressid) {
		this.addressByBillingaddressid = addressByBillingaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OLDADDRESSID")
	public Address getAddressByOldaddressid() {
		return this.addressByOldaddressid;
	}

	public void setAddressByOldaddressid(Address addressByOldaddressid) {
		this.addressByOldaddressid = addressByOldaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OLDBILLINGADDRESSID")
	public Address getAddressByOldbillingaddressid() {
		return this.addressByOldbillingaddressid;
	}

	public void setAddressByOldbillingaddressid(
			Address addressByOldbillingaddressid) {
		this.addressByOldbillingaddressid = addressByOldbillingaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERID", nullable = false)
	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESSID")
	public Address getAddressByAddressid() {
		return this.addressByAddressid;
	}

	public void setAddressByAddressid(Address addressByAddressid) {
		this.addressByAddressid = addressByAddressid;
	}

	
	@Column(name = "CARDF6", length = 1020)
	public String getCardf6() {
		return this.cardf6;
	}

	public void setCardf6(String cardf6) {
		this.cardf6 = cardf6;
	}

	@Column(name = "CARDL4", length = 1020)
	public String getCardl4() {
		return this.cardl4;
	}

	public void setCardl4(String cardl4) {
		this.cardl4 = cardl4;
	}

	@Column(name = "ISSUERNAME", length = 1020)
	public String getIssuername() {
		return this.issuername;
	}

	public void setIssuername(String issuername) {
		this.issuername = issuername;
	}

	@Column(name = "NAMEONCARD", length = 1020)
	public String getNameoncard() {
		return this.nameoncard;
	}

	public void setNameoncard(String nameoncard) {
		this.nameoncard = nameoncard;
	}

	@Column(name = "OLDCARDF6", length = 1020)
	public String getOldcardf6() {
		return this.oldcardf6;
	}

	public void setOldcardf6(String oldcardf6) {
		this.oldcardf6 = oldcardf6;
	}

	@Column(name = "OLDCARDL4", length = 1020)
	public String getOldcardl4() {
		return this.oldcardl4;
	}

	public void setOldcardl4(String oldcardl4) {
		this.oldcardl4 = oldcardl4;
	}

	@Column(name = "OLDISSUERNAME", length = 1020)
	public String getOldissuername() {
		return this.oldissuername;
	}

	public void setOldissuername(String oldissuername) {
		this.oldissuername = oldissuername;
	}

	@Column(name = "OLDNAMEONCARD", length = 1020)
	public String getOldnameoncard() {
		return this.oldnameoncard;
	}

	public void setOldnameoncard(String oldnameoncard) {
		this.oldnameoncard = oldnameoncard;
	}

	@Column(name = "CARDSTATUS", nullable = false, precision = 10, scale = 0)
	public long getCardstatus() {
		return this.cardstatus;
	}

	public void setCardstatus(long cardstatus) {
		this.cardstatus = cardstatus;
	}

	@Column(name = "ISCONFORMATIONREQUIRED", precision = 3, scale = 0)
	public Boolean getIsconformationrequired() {
		return this.isconformationrequired;
	}

	public void setIsconformationrequired(Boolean isconformationrequired) {
		this.isconformationrequired = isconformationrequired;
	}

}
