package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * CardInfo generated by hbm2java
 */
@Entity
@Table(name = "CARD_INFO")
public class CardInfo implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Pocket pocket;
	private Address addressByBillingaddressid;
	private Address addressByOldaddressid;
	private Address addressByOldbillingaddressid;
	private Subscriber subscriber;
	private Address addressByAddressid;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String cardf6;
	private String cardl4;
	private String issuername;
	private String nameoncard;
	private String oldcardf6;
	private String oldcardl4;
	private String oldissuername;
	private String oldnameoncard;
	private long cardstatus;
	private Short isconformationrequired;

	public CardInfo() {
	}

	public CardInfo(BigDecimal id, Subscriber subscriber,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, long cardstatus) {
		this.id = id;
		this.subscriber = subscriber;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.cardstatus = cardstatus;
	}

	public CardInfo(BigDecimal id, Pocket pocket,
			Address addressByBillingaddressid, Address addressByOldaddressid,
			Address addressByOldbillingaddressid, Subscriber subscriber,
			Address addressByAddressid, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			String cardf6, String cardl4, String issuername, String nameoncard,
			String oldcardf6, String oldcardl4, String oldissuername,
			String oldnameoncard, long cardstatus, Short isconformationrequired) {
		this.id = id;
		this.pocket = pocket;
		this.addressByBillingaddressid = addressByBillingaddressid;
		this.addressByOldaddressid = addressByOldaddressid;
		this.addressByOldbillingaddressid = addressByOldbillingaddressid;
		this.subscriber = subscriber;
		this.addressByAddressid = addressByAddressid;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.cardf6 = cardf6;
		this.cardl4 = cardl4;
		this.issuername = issuername;
		this.nameoncard = nameoncard;
		this.oldcardf6 = oldcardf6;
		this.oldcardl4 = oldcardl4;
		this.oldissuername = oldissuername;
		this.oldnameoncard = oldnameoncard;
		this.cardstatus = cardstatus;
		this.isconformationrequired = isconformationrequired;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETID")
	public Pocket getPocket() {
		return this.pocket;
	}

	public void setPocket(Pocket pocket) {
		this.pocket = pocket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILLINGADDRESSID")
	public Address getAddressByBillingaddressid() {
		return this.addressByBillingaddressid;
	}

	public void setAddressByBillingaddressid(Address addressByBillingaddressid) {
		this.addressByBillingaddressid = addressByBillingaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OLDADDRESSID")
	public Address getAddressByOldaddressid() {
		return this.addressByOldaddressid;
	}

	public void setAddressByOldaddressid(Address addressByOldaddressid) {
		this.addressByOldaddressid = addressByOldaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OLDBILLINGADDRESSID")
	public Address getAddressByOldbillingaddressid() {
		return this.addressByOldbillingaddressid;
	}

	public void setAddressByOldbillingaddressid(
			Address addressByOldbillingaddressid) {
		this.addressByOldbillingaddressid = addressByOldbillingaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERID", nullable = false)
	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESSID")
	public Address getAddressByAddressid() {
		return this.addressByAddressid;
	}

	public void setAddressByAddressid(Address addressByAddressid) {
		this.addressByAddressid = addressByAddressid;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "CARDF6", length = 1020)
	public String getCardf6() {
		return this.cardf6;
	}

	public void setCardf6(String cardf6) {
		this.cardf6 = cardf6;
	}

	@Column(name = "CARDL4", length = 1020)
	public String getCardl4() {
		return this.cardl4;
	}

	public void setCardl4(String cardl4) {
		this.cardl4 = cardl4;
	}

	@Column(name = "ISSUERNAME", length = 1020)
	public String getIssuername() {
		return this.issuername;
	}

	public void setIssuername(String issuername) {
		this.issuername = issuername;
	}

	@Column(name = "NAMEONCARD", length = 1020)
	public String getNameoncard() {
		return this.nameoncard;
	}

	public void setNameoncard(String nameoncard) {
		this.nameoncard = nameoncard;
	}

	@Column(name = "OLDCARDF6", length = 1020)
	public String getOldcardf6() {
		return this.oldcardf6;
	}

	public void setOldcardf6(String oldcardf6) {
		this.oldcardf6 = oldcardf6;
	}

	@Column(name = "OLDCARDL4", length = 1020)
	public String getOldcardl4() {
		return this.oldcardl4;
	}

	public void setOldcardl4(String oldcardl4) {
		this.oldcardl4 = oldcardl4;
	}

	@Column(name = "OLDISSUERNAME", length = 1020)
	public String getOldissuername() {
		return this.oldissuername;
	}

	public void setOldissuername(String oldissuername) {
		this.oldissuername = oldissuername;
	}

	@Column(name = "OLDNAMEONCARD", length = 1020)
	public String getOldnameoncard() {
		return this.oldnameoncard;
	}

	public void setOldnameoncard(String oldnameoncard) {
		this.oldnameoncard = oldnameoncard;
	}

	@Column(name = "CARDSTATUS", nullable = false, precision = 10, scale = 0)
	public long getCardstatus() {
		return this.cardstatus;
	}

	public void setCardstatus(long cardstatus) {
		this.cardstatus = cardstatus;
	}

	@Column(name = "ISCONFORMATIONREQUIRED", precision = 3, scale = 0)
	public Short getIsconformationrequired() {
		return this.isconformationrequired;
	}

	public void setIsconformationrequired(Short isconformationrequired) {
		this.isconformationrequired = isconformationrequired;
	}

}
