package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CashinFirstTime generated by hbm2java
 */
@Entity
@Table(name = "CASHIN_FIRST_TIME")
public class CashinFirstTime extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String FieldName_MDN = "mdn";
	
	private BigDecimal mdnid;
	private String mdn;
	private BigDecimal sctlid;
	private BigDecimal transactionamount;
	private  Long id;

	public CashinFirstTime() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "cashin_first_time_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "MDNID", scale = 0)
	public BigDecimal getMdnid() {
		return this.mdnid;
	}

	public void setMdnid(BigDecimal mdnid) {
		this.mdnid = mdnid;
	}

	@Column(name = "MDN")
	public String getMdn() {
		return this.mdn;
	}

	public void setMdn(String mdn) {
		this.mdn = mdn;
	}

	@Column(name = "SCTLID", scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "TRANSACTIONAMOUNT", precision = 25, scale = 4)
	public BigDecimal getTransactionamount() {
		return this.transactionamount;
	}

	public void setTransactionamount(BigDecimal transactionamount) {
		this.transactionamount = transactionamount;
	}

}
