package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * ChannelSessionMgmt generated by hbm2java
 */
@Entity
@Table(name = "CHANNEL_SESSION_MGMT")
public class ChannelSessionMgmt extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_SubscriberMDNByMDNID = "subscriberMdn";
	private SubscriberMdn subscriberMdn;
	private String sessionkey;
	private Long requestcountafterlogin;
	private Timestamp lastrequesttime;
	private Timestamp lastlogintime;

	public ChannelSessionMgmt() {
	}

	public ChannelSessionMgmt(BigDecimal id, SubscriberMdn subscriberMdn,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby) {
		this.id = id;
		this.subscriberMdn = subscriberMdn;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public ChannelSessionMgmt(BigDecimal id, SubscriberMdn subscriberMdn,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String sessionkey,
			Long requestcountafterlogin, Timestamp lastrequesttime,
			Timestamp lastlogintime) {
		this.id = id;
		this.subscriberMdn = subscriberMdn;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sessionkey = sessionkey;
		this.requestcountafterlogin = requestcountafterlogin;
		this.lastrequesttime = lastrequesttime;
		this.lastlogintime = lastlogintime;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDNID", nullable = false)
	public SubscriberMdn getSubscriberMdn() {
		return this.subscriberMdn;
	}

	public void setSubscriberMdn(SubscriberMdn subscriberMdn) {
		this.subscriberMdn = subscriberMdn;
	}

	

	@Column(name = "SESSIONKEY", length = 1020)
	public String getSessionkey() {
		return this.sessionkey;
	}

	public void setSessionkey(String sessionkey) {
		this.sessionkey = sessionkey;
	}

	@Column(name = "REQUESTCOUNTAFTERLOGIN", precision = 10, scale = 0)
	public Long getRequestcountafterlogin() {
		return this.requestcountafterlogin;
	}

	public void setRequestcountafterlogin(Long requestcountafterlogin) {
		this.requestcountafterlogin = requestcountafterlogin;
	}

	@Column(name = "LASTREQUESTTIME")
	public Timestamp getLastrequesttime() {
		return this.lastrequesttime;
	}

	public void setLastrequesttime(Timestamp lastrequesttime) {
		this.lastrequesttime = lastrequesttime;
	}

	@Column(name = "LASTLOGINTIME")
	public Timestamp getLastlogintime() {
		return this.lastlogintime;
	}

	public void setLastlogintime(Timestamp lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

}
