package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * ChargeDefinition generated by hbm2java
 */
@Entity
@Table(name = "CHARGE_DEFINITION", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class ChargeDefinition implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Pocket pocket;
	private ChargeType chargeTypeByChargetypeid;
	private Partner partner;
	private MfinoServiceProvider mfinoServiceProvider;
	private ChargeType chargeTypeByDependantchargetypeid;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String name;
	private String description;
	private short ischargefromcustomer;
	private short istaxable;
	private Set<TransactionCharge> transactionCharges = new HashSet<TransactionCharge>(
			0);
	private Set<ChargePricing> chargePricings = new HashSet<ChargePricing>(0);

	public ChargeDefinition() {
	}

	public ChargeDefinition(BigDecimal id, ChargeType chargeTypeByChargetypeid,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String name,
			short ischargefromcustomer, short istaxable) {
		this.id = id;
		this.chargeTypeByChargetypeid = chargeTypeByChargetypeid;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.name = name;
		this.ischargefromcustomer = ischargefromcustomer;
		this.istaxable = istaxable;
	}

	public ChargeDefinition(BigDecimal id, Pocket pocket,
			ChargeType chargeTypeByChargetypeid, Partner partner,
			MfinoServiceProvider mfinoServiceProvider,
			ChargeType chargeTypeByDependantchargetypeid,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String name,
			String description, short ischargefromcustomer, short istaxable,
			Set<TransactionCharge> transactionCharges,
			Set<ChargePricing> chargePricings) {
		this.id = id;
		this.pocket = pocket;
		this.chargeTypeByChargetypeid = chargeTypeByChargetypeid;
		this.partner = partner;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.chargeTypeByDependantchargetypeid = chargeTypeByDependantchargetypeid;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.name = name;
		this.description = description;
		this.ischargefromcustomer = ischargefromcustomer;
		this.istaxable = istaxable;
		this.transactionCharges = transactionCharges;
		this.chargePricings = chargePricings;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETID")
	public Pocket getPocket() {
		return this.pocket;
	}

	public void setPocket(Pocket pocket) {
		this.pocket = pocket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGETYPEID", nullable = false)
	public ChargeType getChargeTypeByChargetypeid() {
		return this.chargeTypeByChargetypeid;
	}

	public void setChargeTypeByChargetypeid(ChargeType chargeTypeByChargetypeid) {
		this.chargeTypeByChargetypeid = chargeTypeByChargetypeid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUNDINGPARTNERID")
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPENDANTCHARGETYPEID")
	public ChargeType getChargeTypeByDependantchargetypeid() {
		return this.chargeTypeByDependantchargetypeid;
	}

	public void setChargeTypeByDependantchargetypeid(
			ChargeType chargeTypeByDependantchargetypeid) {
		this.chargeTypeByDependantchargetypeid = chargeTypeByDependantchargetypeid;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 1020)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ISCHARGEFROMCUSTOMER", nullable = false, precision = 3, scale = 0)
	public short getIschargefromcustomer() {
		return this.ischargefromcustomer;
	}

	public void setIschargefromcustomer(short ischargefromcustomer) {
		this.ischargefromcustomer = ischargefromcustomer;
	}

	@Column(name = "ISTAXABLE", nullable = false, precision = 3, scale = 0)
	public short getIstaxable() {
		return this.istaxable;
	}

	public void setIstaxable(short istaxable) {
		this.istaxable = istaxable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargeDefinition")
	public Set<TransactionCharge> getTransactionCharges() {
		return this.transactionCharges;
	}

	public void setTransactionCharges(Set<TransactionCharge> transactionCharges) {
		this.transactionCharges = transactionCharges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargeDefinition")
	public Set<ChargePricing> getChargePricings() {
		return this.chargePricings;
	}

	public void setChargePricings(Set<ChargePricing> chargePricings) {
		this.chargePricings = chargePricings;
	}

}
