package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChargePricing generated by hbm2java
 */
@Entity
@Table(name = "CHARGE_PRICING")
public class ChargePricing extends Base implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static final String FieldName_ChargeDefinition = "chargeDefinition";
	public static final String FieldName_MinAmount = "minamount";
	
	private MfinoServiceProvider mfinoServiceProvider;
	private ChargeDefinition chargeDefinition;
	private BigDecimal minamount;
	private BigDecimal maxamount;
	private BigDecimal chargeinfixed;
	private BigDecimal chargeinpercentage;
	private Short isdefault;
	private String charge;
	private String mincharge;
	private String maxcharge;

	public ChargePricing() {
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGEDEFINITIONID", nullable = false)
	public ChargeDefinition getChargeDefinition() {
		return this.chargeDefinition;
	}

	public void setChargeDefinition(ChargeDefinition chargeDefinition) {
		this.chargeDefinition = chargeDefinition;
	}

	

	@Column(name = "MINAMOUNT", precision = 25, scale = 4)
	public BigDecimal getMinamount() {
		return this.minamount;
	}

	public void setMinamount(BigDecimal minamount) {
		this.minamount = minamount;
	}

	@Column(name = "MAXAMOUNT", precision = 25, scale = 4)
	public BigDecimal getMaxamount() {
		return this.maxamount;
	}

	public void setMaxamount(BigDecimal maxamount) {
		this.maxamount = maxamount;
	}

	@Column(name = "CHARGEINFIXED", precision = 25, scale = 4)
	public BigDecimal getChargeinfixed() {
		return this.chargeinfixed;
	}

	public void setChargeinfixed(BigDecimal chargeinfixed) {
		this.chargeinfixed = chargeinfixed;
	}

	@Column(name = "CHARGEINPERCENTAGE", precision = 25, scale = 4)
	public BigDecimal getChargeinpercentage() {
		return this.chargeinpercentage;
	}

	public void setChargeinpercentage(BigDecimal chargeinpercentage) {
		this.chargeinpercentage = chargeinpercentage;
	}

	@Column(name = "ISDEFAULT", precision = 3, scale = 0)
	public Short getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Short isdefault) {
		this.isdefault = isdefault;
	}

	@Column(name = "CHARGE")
	public String getCharge() {
		return this.charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

	@Column(name = "MINCHARGE")
	public String getMincharge() {
		return this.mincharge;
	}

	public void setMincharge(String mincharge) {
		this.mincharge = mincharge;
	}

	@Column(name = "MAXCHARGE")
	public String getMaxcharge() {
		return this.maxcharge;
	}

	public void setMaxcharge(String maxcharge) {
		this.maxcharge = maxcharge;
	}

}
