package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ChargePricing generated by hbm2java
 */
@Entity
@Table(name = "CHARGE_PRICING")
public class ChargePricing implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private MfinoServiceProvider mfinoServiceProvider;
	private ChargeDefinition chargeDefinition;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal minamount;
	private BigDecimal maxamount;
	private BigDecimal chargeinfixed;
	private BigDecimal chargeinpercentage;
	private Short isdefault;
	private String charge;
	private String mincharge;
	private String maxcharge;

	public ChargePricing() {
	}

	public ChargePricing(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			ChargeDefinition chargeDefinition, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.chargeDefinition = chargeDefinition;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public ChargePricing(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			ChargeDefinition chargeDefinition, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal minamount, BigDecimal maxamount,
			BigDecimal chargeinfixed, BigDecimal chargeinpercentage,
			Short isdefault, String charge, String mincharge, String maxcharge) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.chargeDefinition = chargeDefinition;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.minamount = minamount;
		this.maxamount = maxamount;
		this.chargeinfixed = chargeinfixed;
		this.chargeinpercentage = chargeinpercentage;
		this.isdefault = isdefault;
		this.charge = charge;
		this.mincharge = mincharge;
		this.maxcharge = maxcharge;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGEDEFINITIONID", nullable = false)
	public ChargeDefinition getChargeDefinition() {
		return this.chargeDefinition;
	}

	public void setChargeDefinition(ChargeDefinition chargeDefinition) {
		this.chargeDefinition = chargeDefinition;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MINAMOUNT", precision = 25, scale = 4)
	public BigDecimal getMinamount() {
		return this.minamount;
	}

	public void setMinamount(BigDecimal minamount) {
		this.minamount = minamount;
	}

	@Column(name = "MAXAMOUNT", precision = 25, scale = 4)
	public BigDecimal getMaxamount() {
		return this.maxamount;
	}

	public void setMaxamount(BigDecimal maxamount) {
		this.maxamount = maxamount;
	}

	@Column(name = "CHARGEINFIXED", precision = 25, scale = 4)
	public BigDecimal getChargeinfixed() {
		return this.chargeinfixed;
	}

	public void setChargeinfixed(BigDecimal chargeinfixed) {
		this.chargeinfixed = chargeinfixed;
	}

	@Column(name = "CHARGEINPERCENTAGE", precision = 25, scale = 4)
	public BigDecimal getChargeinpercentage() {
		return this.chargeinpercentage;
	}

	public void setChargeinpercentage(BigDecimal chargeinpercentage) {
		this.chargeinpercentage = chargeinpercentage;
	}

	@Column(name = "ISDEFAULT", precision = 3, scale = 0)
	public Short getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Short isdefault) {
		this.isdefault = isdefault;
	}

	@Column(name = "CHARGE")
	public String getCharge() {
		return this.charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

	@Column(name = "MINCHARGE")
	public String getMincharge() {
		return this.mincharge;
	}

	public void setMincharge(String mincharge) {
		this.mincharge = mincharge;
	}

	@Column(name = "MAXCHARGE")
	public String getMaxcharge() {
		return this.maxcharge;
	}

	public void setMaxcharge(String maxcharge) {
		this.maxcharge = maxcharge;
	}

}
