package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;

/**
 * CommodityTransferNextId generated by hbm2java
 */
@Entity
@Table(name = "COMMODITY_TRANSFER_NEXT_ID")
public class CommodityTransferNextID extends Base  implements java.io.Serializable {


	private BigDecimal nextrecordid;

	public CommodityTransferNextID() {
	}

	public CommodityTransferNextID(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal nextrecordid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.nextrecordid = nextrecordid;
	}

	

	@Column(name = "NEXTRECORDID", nullable = false, scale = 0)
	public BigDecimal getNextrecordid() {
		return this.nextrecordid;
	}

	public void setNextrecordid(BigDecimal nextrecordid) {
		this.nextrecordid = nextrecordid;
	}

}
