package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CommodityTransferNextId generated by hbm2java
 */
@Entity
@Table(name = "COMMODITY_TRANSFER_NEXT_ID")
public class CommodityTransferNextId extends Base  implements java.io.Serializable {


	private Long nextrecordid;
	private Long id;

	public CommodityTransferNextId() {
	}

	
	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "NEXTRECORDID", nullable = false, scale = 0)
	public Long getNextrecordid() {
		return this.nextrecordid;
	}

	public void setNextrecordid(Long nextrecordid) {
		this.nextrecordid = nextrecordid;
	}

}
