package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * CreditcardDestinations generated by hbm2java
 */
@Entity
@Table(name = "CREDITCARD_DESTINATIONS")
public class CreditcardDestinations implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Subscriber subscriber;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String destmdn;
	private String olddestmdn;
	private Long ccmdnstatus;

	public CreditcardDestinations() {
	}

	public CreditcardDestinations(BigDecimal id, Subscriber subscriber,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby) {
		this.id = id;
		this.subscriber = subscriber;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public CreditcardDestinations(BigDecimal id, Subscriber subscriber,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String destmdn,
			String olddestmdn, Long ccmdnstatus) {
		this.id = id;
		this.subscriber = subscriber;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.destmdn = destmdn;
		this.olddestmdn = olddestmdn;
		this.ccmdnstatus = ccmdnstatus;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERID", nullable = false)
	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

	@Column(name = "OLDDESTMDN", length = 1020)
	public String getOlddestmdn() {
		return this.olddestmdn;
	}

	public void setOlddestmdn(String olddestmdn) {
		this.olddestmdn = olddestmdn;
	}

	@Column(name = "CCMDNSTATUS", precision = 10, scale = 0)
	public Long getCcmdnstatus() {
		return this.ccmdnstatus;
	}

	public void setCcmdnstatus(Long ccmdnstatus) {
		this.ccmdnstatus = ccmdnstatus;
	}

}
