package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CurrentBalanceInfo generated by hbm2java
 */
@Entity
@Table(name = "CURRENT_BALANCE_INFO")
public class CurrentBalanceInfo  extends Base implements java.io.Serializable {


	private String currentbalance;
	private BigDecimal subscriberid;
	private BigDecimal kyclevel;
	private Long id;
	

	public CurrentBalanceInfo() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "current_balance_info_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "CURRENTBALANCE")
	public String getCurrentbalance() {
		return this.currentbalance;
	}

	public void setCurrentbalance(String currentbalance) {
		this.currentbalance = currentbalance;
	}

	@Column(name = "SUBSCRIBERID", precision = 20, scale = 0)
	public BigDecimal getSubscriberid() {
		return this.subscriberid;
	}

	public void setSubscriberid(BigDecimal subscriberid) {
		this.subscriberid = subscriberid;
	}

	@Column(name = "KYCLEVEL", precision = 20, scale = 0)
	public BigDecimal getKyclevel() {
		return this.kyclevel;
	}

	public void setKyclevel(BigDecimal kyclevel) {
		this.kyclevel = kyclevel;
	}

}
