package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * DctRestrictions generated by hbm2java
 */
@Entity
@Table(name = "DCT_RESTRICTIONS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DCTID", "TRANSACTIONTYPEID", "RELATIONSHIPTYPE", "DISTRIBUTIONLEVEL" }))
public class DctRestrictions implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private long dctid;
	private Long transactiontypeid;
	private Long relationshiptype;
	private Long distributionlevel;
	private Short isallowed;

	public DctRestrictions() {
	}

	public DctRestrictions(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			long dctid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.dctid = dctid;
	}

	public DctRestrictions(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			long dctid, Long transactiontypeid, Long relationshiptype,
			Long distributionlevel, Short isallowed) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.dctid = dctid;
		this.transactiontypeid = transactiontypeid;
		this.relationshiptype = relationshiptype;
		this.distributionlevel = distributionlevel;
		this.isallowed = isallowed;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "DCTID", nullable = false, precision = 10, scale = 0)
	public long getDctid() {
		return this.dctid;
	}

	public void setDctid(long dctid) {
		this.dctid = dctid;
	}

	@Column(name = "TRANSACTIONTYPEID", precision = 10, scale = 0)
	public Long getTransactiontypeid() {
		return this.transactiontypeid;
	}

	public void setTransactiontypeid(Long transactiontypeid) {
		this.transactiontypeid = transactiontypeid;
	}

	@Column(name = "RELATIONSHIPTYPE", precision = 10, scale = 0)
	public Long getRelationshiptype() {
		return this.relationshiptype;
	}

	public void setRelationshiptype(Long relationshiptype) {
		this.relationshiptype = relationshiptype;
	}

	@Column(name = "DISTRIBUTIONLEVEL", precision = 10, scale = 0)
	public Long getDistributionlevel() {
		return this.distributionlevel;
	}

	public void setDistributionlevel(Long distributionlevel) {
		this.distributionlevel = distributionlevel;
	}

	@Column(name = "ISALLOWED", precision = 3, scale = 0)
	public Short getIsallowed() {
		return this.isallowed;
	}

	public void setIsallowed(Short isallowed) {
		this.isallowed = isallowed;
	}

}
