package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import com.mfino.hibernate.Timestamp;

/**
 * DctRestrictions generated by hbm2java
 */
@Entity
@Table(name = "DCT_RESTRICTIONS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DCTID", "TRANSACTIONTYPEID", "RELATIONSHIPTYPE", "DISTRIBUTIONLEVEL" }))
public class DCTRestrictions extends Base implements java.io.Serializable {

	
	private long dctid;
	private Long transactiontypeid;
	private Long relationshiptype;
	private Long distributionlevel;
	private Short isallowed;

	public DCTRestrictions() {
	}

	public DCTRestrictions(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long dctid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.dctid = dctid;
	}

	public DCTRestrictions(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long dctid, Long transactiontypeid, Long relationshiptype,
			Long distributionlevel, Short isallowed) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.dctid = dctid;
		this.transactiontypeid = transactiontypeid;
		this.relationshiptype = relationshiptype;
		this.distributionlevel = distributionlevel;
		this.isallowed = isallowed;
	}

	

	@Column(name = "DCTID", nullable = false, precision = 10, scale = 0)
	public long getDctid() {
		return this.dctid;
	}

	public void setDctid(long dctid) {
		this.dctid = dctid;
	}

	@Column(name = "TRANSACTIONTYPEID", precision = 10, scale = 0)
	public Long getTransactiontypeid() {
		return this.transactiontypeid;
	}

	public void setTransactiontypeid(Long transactiontypeid) {
		this.transactiontypeid = transactiontypeid;
	}

	@Column(name = "RELATIONSHIPTYPE", precision = 10, scale = 0)
	public Long getRelationshiptype() {
		return this.relationshiptype;
	}

	public void setRelationshiptype(Long relationshiptype) {
		this.relationshiptype = relationshiptype;
	}

	@Column(name = "DISTRIBUTIONLEVEL", precision = 10, scale = 0)
	public Long getDistributionlevel() {
		return this.distributionlevel;
	}

	public void setDistributionlevel(Long distributionlevel) {
		this.distributionlevel = distributionlevel;
	}

	@Column(name = "ISALLOWED", precision = 3, scale = 0)
	public Short getIsallowed() {
		return this.isallowed;
	}

	public void setIsallowed(Short isallowed) {
		this.isallowed = isallowed;
	}

}
