package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Denomination generated by hbm2java
 */
@Entity
@Table(name = "DENOMINATION")
public class Denomination extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_DenominationAmount = "denominationamount";
	Biller biller;
	 BigDecimal denominationamount;

	public Denomination() {
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BILLERID", nullable = false)
	public Biller getBiller() {
		return this.biller;
	}

	public void setBiller(Biller biller) {
		this.biller = biller;
	}

	
	@Column(name = "DENOMINATIONAMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getDenominationamount() {
		return this.denominationamount;
	}

	public void setDenominationamount(BigDecimal denominationamount) {
		this.denominationamount = denominationamount;
	}

}
