package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DistributionChainTemp generated by hbm2java
 */
@Entity
@Table(name = "DISTRIBUTION_CHAIN_TEMP")
public class DistributionChainTemp extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	public static final String FieldName_DistributionChainName = "name";

	public static final String FieldName_ServiceID = "serviceid";

	public static final String FieldName_PartnerServicesFromDistributionChainTemplateID = null;
	
	private MfinoServiceProvider mfinoServiceProvider;
	private String name;
	private String description;
	private long serviceid;
	private Long id;
	private Set<LetterOfPurchase> letterOfPurchases = new HashSet<LetterOfPurchase>(
			0);
	private Set<BulkLop> bulkLops = new HashSet<BulkLop>(0);
	private Set<DistributionChainLvl> distributionChainLvls = new HashSet<DistributionChainLvl>(
			0);
	private Set<PartnerServices> partnerServiceses = new HashSet<PartnerServices>(
			0);

	public DistributionChainTemp() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "distribution_chain_temp_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	

	@Column(name = "NAME", nullable = false, length = 1020)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SERVICEID", nullable = false, precision = 10, scale = 0)
	public long getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(long serviceid) {
		this.serviceid = serviceid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distributionChainTemp")
	public Set<LetterOfPurchase> getLetterOfPurchases() {
		return this.letterOfPurchases;
	}

	public void setLetterOfPurchases(Set<LetterOfPurchase> letterOfPurchases) {
		this.letterOfPurchases = letterOfPurchases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distributionChainTemp")
	public Set<BulkLop> getBulkLops() {
		return this.bulkLops;
	}

	public void setBulkLops(Set<BulkLop> bulkLops) {
		this.bulkLops = bulkLops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distributionChainTemp")
	public Set<DistributionChainLvl> getDistributionChainLvls() {
		return this.distributionChainLvls;
	}

	public void setDistributionChainLvls(
			Set<DistributionChainLvl> distributionChainLvls) {
		this.distributionChainLvls = distributionChainLvls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distributionChainTemp")
	public Set<PartnerServices> getPartnerServiceses() {
		return this.partnerServiceses;
	}

	public void setPartnerServiceses(Set<PartnerServices> partnerServiceses) {
		this.partnerServiceses = partnerServiceses;
	}
	@Override
	public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        } else if(obj == null) {
            return false;
        } else {
            if(getId() != null){
            	return (getId().equals(((DistributionChainTemp)obj).getId()));
            }
            
            return false;
        }
	}
	
	@Override
	public int hashCode() {
		if(null != this.getId()){
			return this.getId().intValue();
		}
		
		return -1;
	}
	
	@Override
	public String toString() {
		return "DCTID:"+getId() + ",DctName:"+getName();
	}
}
