package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import com.mfino.hibernate.Timestamp;
/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "DISTRICT")
public class District extends Base implements java.io.Serializable {

	
	public static final String FieldName_IdRegion = "provinceRegion";
	public static final String FieldName_DistrictId = "districtid";
	private ProvinceRegion provinceRegion;
	private String districtid;
	private String displaytext;
	private Set<Village> villages = new HashSet<Village>(0);

	public District() {
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGION", nullable = false)
	public ProvinceRegion getProvinceRegion() {
		return this.provinceRegion;
	}

	public void setProvinceRegion(ProvinceRegion provinceRegion) {
		this.provinceRegion = provinceRegion;
	}

	

	@Column(name = "DISTRICTID", nullable = false, length = 80)
	public String getDistrictid() {
		return this.districtid;
	}

	public void setDistrictid(String districtid) {
		this.districtid = districtid;
	}

	@Column(name = "DISPLAYTEXT", length = 800)
	public String getDisplaytext() {
		return this.displaytext;
	}

	public void setDisplaytext(String displaytext) {
		this.displaytext = displaytext;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Village> getVillages() {
		return this.villages;
	}

	public void setVillages(Set<Village> villages) {
		this.villages = villages;
	}

}
