package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "DISTRICT")
public class District implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private ProvinceRegion provinceRegion;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String districtid;
	private String displaytext;
	private Set<Village> villages = new HashSet<Village>(0);

	public District() {
	}

	public District(BigDecimal id, ProvinceRegion provinceRegion,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String districtid) {
		this.id = id;
		this.provinceRegion = provinceRegion;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.districtid = districtid;
	}

	public District(BigDecimal id, ProvinceRegion provinceRegion,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String districtid,
			String displaytext, Set<Village> villages) {
		this.id = id;
		this.provinceRegion = provinceRegion;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.districtid = districtid;
		this.displaytext = displaytext;
		this.villages = villages;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDREGION", nullable = false)
	public ProvinceRegion getProvinceRegion() {
		return this.provinceRegion;
	}

	public void setProvinceRegion(ProvinceRegion provinceRegion) {
		this.provinceRegion = provinceRegion;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "DISTRICTID", nullable = false, length = 80)
	public String getDistrictid() {
		return this.districtid;
	}

	public void setDistrictid(String districtid) {
		this.districtid = districtid;
	}

	@Column(name = "DISPLAYTEXT", length = 800)
	public String getDisplaytext() {
		return this.displaytext;
	}

	public void setDisplaytext(String displaytext) {
		this.displaytext = displaytext;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Village> getVillages() {
		return this.villages;
	}

	public void setVillages(Set<Village> villages) {
		this.villages = villages;
	}

}
