package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * DistributionChainTemp generated by hbm2java
 */
@Entity
@Table(name = "DISTRIBUTION_CHAIN_TEMP")
public class DistributionChainTemp implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private MfinoServiceProvider mfinoServiceProvider;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String name;
	private String description;
	private long serviceid;
	private Set<LetterOfPurchase> letterOfPurchases = new HashSet<LetterOfPurchase>(
			0);
	private Set<BulkLop> bulkLops = new HashSet<BulkLop>(0);
	private Set<DistributionChainLvl> distributionChainLvls = new HashSet<DistributionChainLvl>(
			0);
	private Set<PartnerServices> partnerServiceses = new HashSet<PartnerServices>(
			0);

	public DistributionChainTemp() {
	}

	public DistributionChainTemp(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String name,
			long serviceid) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.name = name;
		this.serviceid = serviceid;
	}

	public DistributionChainTemp(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String name,
			String description, long serviceid,
			Set<LetterOfPurchase> letterOfPurchases, Set<BulkLop> bulkLops,
			Set<DistributionChainLvl> distributionChainLvls,
			Set<PartnerServices> partnerServiceses) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.name = name;
		this.description = description;
		this.serviceid = serviceid;
		this.letterOfPurchases = letterOfPurchases;
		this.bulkLops = bulkLops;
		this.distributionChainLvls = distributionChainLvls;
		this.partnerServiceses = partnerServiceses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "NAME", nullable = false, length = 1020)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SERVICEID", nullable = false, precision = 10, scale = 0)
	public long getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(long serviceid) {
		this.serviceid = serviceid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distributionChainTemp")
	public Set<LetterOfPurchase> getLetterOfPurchases() {
		return this.letterOfPurchases;
	}

	public void setLetterOfPurchases(Set<LetterOfPurchase> letterOfPurchases) {
		this.letterOfPurchases = letterOfPurchases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distributionChainTemp")
	public Set<BulkLop> getBulkLops() {
		return this.bulkLops;
	}

	public void setBulkLops(Set<BulkLop> bulkLops) {
		this.bulkLops = bulkLops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distributionChainTemp")
	public Set<DistributionChainLvl> getDistributionChainLvls() {
		return this.distributionChainLvls;
	}

	public void setDistributionChainLvls(
			Set<DistributionChainLvl> distributionChainLvls) {
		this.distributionChainLvls = distributionChainLvls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "distributionChainTemp")
	public Set<PartnerServices> getPartnerServiceses() {
		return this.partnerServiceses;
	}

	public void setPartnerServiceses(Set<PartnerServices> partnerServiceses) {
		this.partnerServiceses = partnerServiceses;
	}

}
