package com.mfino.domain;
// Generated Jul 27, 2009 3:18:44 PM by Hibernate Tools 3.2.1.GA


import com.mfino.fix.CmFinoFIX;

/**
 * EnumText generated by hbm2java
 */
public class EnumText   extends CmFinoFIX.CREnumText {



}


