package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;

/**
 * EnumText generated by hbm2java
 */
@Entity
@Table(name = "ENUM_TEXT", uniqueConstraints = @UniqueConstraint(columnNames = {
		"LANGUAGE", "TAGID", "ENUMCODE" }))
public class EnumText extends Base implements java.io.Serializable {

	
	private long language;
	private String tagname;
	private long tagid;
	private String enumcode;
	private String enumvalue;
	private String displaytext;

	public EnumText() {
	}

	public EnumText(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long language, String tagname, long tagid, String enumcode,
			String enumvalue) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.language = language;
		this.tagname = tagname;
		this.tagid = tagid;
		this.enumcode = enumcode;
		this.enumvalue = enumvalue;
	}

	public EnumText(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long language, String tagname, long tagid, String enumcode,
			String enumvalue, String displaytext) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.language = language;
		this.tagname = tagname;
		this.tagid = tagid;
		this.enumcode = enumcode;
		this.enumvalue = enumvalue;
		this.displaytext = displaytext;
	}

	

	@Column(name = "LANGUAGE", nullable = false, precision = 10, scale = 0)
	public long getLanguage() {
		return this.language;
	}

	public void setLanguage(long language) {
		this.language = language;
	}

	@Column(name = "TAGNAME", nullable = false, length = 1020)
	public String getTagname() {
		return this.tagname;
	}

	public void setTagname(String tagname) {
		this.tagname = tagname;
	}

	@Column(name = "TAGID", nullable = false, precision = 10, scale = 0)
	public long getTagid() {
		return this.tagid;
	}

	public void setTagid(long tagid) {
		this.tagid = tagid;
	}

	@Column(name = "ENUMCODE", nullable = false, length = 1020)
	public String getEnumcode() {
		return this.enumcode;
	}

	public void setEnumcode(String enumcode) {
		this.enumcode = enumcode;
	}

	@Column(name = "ENUMVALUE", nullable = false, length = 1020)
	public String getEnumvalue() {
		return this.enumvalue;
	}

	public void setEnumvalue(String enumvalue) {
		this.enumvalue = enumvalue;
	}

	@Column(name = "DISPLAYTEXT", length = 1020)
	public String getDisplaytext() {
		return this.displaytext;
	}

	public void setDisplaytext(String displaytext) {
		this.displaytext = displaytext;
	}

}
