package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;
/**
 * ExcludeSubscriberLc generated by hbm2java
 */
@Entity
@Table(name = "EXCLUDE_SUBSCRIBER_LC")
public class ExcludeSubscriberLc extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_MDN = "subscriberMdn";
	public static final String FieldName_SubscriberMDNByMDNID = "subscriberMdn";
	private SubscriberMdn subscriberMdn;
	

	public ExcludeSubscriberLc() {
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDNID", nullable = false)
	public SubscriberMdn getSubscriberMdn() {
		return this.subscriberMdn;
	}

	public void setSubscriberMdn(SubscriberMdn subscriberMdn) {
		this.subscriberMdn = subscriberMdn;
	}

	
}
