package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;

/**
 * FavoriteCategory generated by hbm2java
 */
@Entity
@Table(name = "FAVORITE_CATEGORY")
public class FavoriteCategory extends Base implements java.io.Serializable {

	
	private String categoryname;
	private String displayname;
	private Set<SubscriberFavorite> subscriberFavorites = new HashSet<SubscriberFavorite>(
			0);

	public FavoriteCategory() {
	}

	public FavoriteCategory(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			String categoryname, String displayname) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.categoryname = categoryname;
		this.displayname = displayname;
	}

	public FavoriteCategory(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			String categoryname, String displayname,
			Set<SubscriberFavorite> subscriberFavorites) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.categoryname = categoryname;
		this.displayname = displayname;
		this.subscriberFavorites = subscriberFavorites;
	}

	

	@Column(name = "CATEGORYNAME", nullable = false)
	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	@Column(name = "DISPLAYNAME", nullable = false)
	public String getDisplayname() {
		return this.displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "favoriteCategory")
	public Set<SubscriberFavorite> getSubscriberFavorites() {
		return this.subscriberFavorites;
	}

	public void setSubscriberFavorites(
			Set<SubscriberFavorite> subscriberFavorites) {
		this.subscriberFavorites = subscriberFavorites;
	}

}
