package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * FundDistributionInfo generated by hbm2java
 */
@Entity
@Table(name = "FUND_DISTRIBUTION_INFO")
public class FundDistributionInfo implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private UnregisteredTxnInfo unregisteredTxnInfo;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal mspid;
	private BigDecimal distributedamount;
	private Long distributionstatus;
	private String failurereason;
	private Long failurereasoncode;
	private BigDecimal transfersctlid;
	private BigDecimal transferctid;
	private Long distributiontype;

	public FundDistributionInfo() {
	}

	public FundDistributionInfo(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal mspid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mspid = mspid;
	}

	public FundDistributionInfo(BigDecimal id,
			UnregisteredTxnInfo unregisteredTxnInfo,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal mspid,
			BigDecimal distributedamount, Long distributionstatus,
			String failurereason, Long failurereasoncode,
			BigDecimal transfersctlid, BigDecimal transferctid,
			Long distributiontype) {
		this.id = id;
		this.unregisteredTxnInfo = unregisteredTxnInfo;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mspid = mspid;
		this.distributedamount = distributedamount;
		this.distributionstatus = distributionstatus;
		this.failurereason = failurereason;
		this.failurereasoncode = failurereasoncode;
		this.transfersctlid = transfersctlid;
		this.transferctid = transferctid;
		this.distributiontype = distributiontype;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUNDALLOCATIONID")
	public UnregisteredTxnInfo getUnregisteredTxnInfo() {
		return this.unregisteredTxnInfo;
	}

	public void setUnregisteredTxnInfo(UnregisteredTxnInfo unregisteredTxnInfo) {
		this.unregisteredTxnInfo = unregisteredTxnInfo;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MSPID", nullable = false, scale = 0)
	public BigDecimal getMspid() {
		return this.mspid;
	}

	public void setMspid(BigDecimal mspid) {
		this.mspid = mspid;
	}

	@Column(name = "DISTRIBUTEDAMOUNT", precision = 25, scale = 4)
	public BigDecimal getDistributedamount() {
		return this.distributedamount;
	}

	public void setDistributedamount(BigDecimal distributedamount) {
		this.distributedamount = distributedamount;
	}

	@Column(name = "DISTRIBUTIONSTATUS", precision = 10, scale = 0)
	public Long getDistributionstatus() {
		return this.distributionstatus;
	}

	public void setDistributionstatus(Long distributionstatus) {
		this.distributionstatus = distributionstatus;
	}

	@Column(name = "FAILUREREASON")
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

	@Column(name = "FAILUREREASONCODE", precision = 10, scale = 0)
	public Long getFailurereasoncode() {
		return this.failurereasoncode;
	}

	public void setFailurereasoncode(Long failurereasoncode) {
		this.failurereasoncode = failurereasoncode;
	}

	@Column(name = "TRANSFERSCTLID", scale = 0)
	public BigDecimal getTransfersctlid() {
		return this.transfersctlid;
	}

	public void setTransfersctlid(BigDecimal transfersctlid) {
		this.transfersctlid = transfersctlid;
	}

	@Column(name = "TRANSFERCTID", scale = 0)
	public BigDecimal getTransferctid() {
		return this.transferctid;
	}

	public void setTransferctid(BigDecimal transferctid) {
		this.transferctid = transferctid;
	}

	@Column(name = "DISTRIBUTIONTYPE", precision = 10, scale = 0)
	public Long getDistributiontype() {
		return this.distributiontype;
	}

	public void setDistributiontype(Long distributiontype) {
		this.distributiontype = distributiontype;
	}

}
