package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * FundEvents generated by hbm2java
 */
@Entity
@Table(name = "FUND_EVENTS")
public class FundEvents implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal mspid;
	private Long fundeventtype;
	private String fundeventdescription;
	private Set<FundDefinition> fundDefinitionsForOnfundallocationtimeexpiry = new HashSet<FundDefinition>(
			0);
	private Set<FundDefinition> fundDefinitionsForGenerationofotponfailure = new HashSet<FundDefinition>(
			0);
	private Set<FundDefinition> fundDefinitionsForOnfailedattemptsexceeded = new HashSet<FundDefinition>(
			0);

	public FundEvents() {
	}

	public FundEvents(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal mspid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mspid = mspid;
	}

	public FundEvents(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal mspid, Long fundeventtype, String fundeventdescription,
			Set<FundDefinition> fundDefinitionsForOnfundallocationtimeexpiry,
			Set<FundDefinition> fundDefinitionsForGenerationofotponfailure,
			Set<FundDefinition> fundDefinitionsForOnfailedattemptsexceeded) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mspid = mspid;
		this.fundeventtype = fundeventtype;
		this.fundeventdescription = fundeventdescription;
		this.fundDefinitionsForOnfundallocationtimeexpiry = fundDefinitionsForOnfundallocationtimeexpiry;
		this.fundDefinitionsForGenerationofotponfailure = fundDefinitionsForGenerationofotponfailure;
		this.fundDefinitionsForOnfailedattemptsexceeded = fundDefinitionsForOnfailedattemptsexceeded;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MSPID", nullable = false, scale = 0)
	public BigDecimal getMspid() {
		return this.mspid;
	}

	public void setMspid(BigDecimal mspid) {
		this.mspid = mspid;
	}

	@Column(name = "FUNDEVENTTYPE", precision = 10, scale = 0)
	public Long getFundeventtype() {
		return this.fundeventtype;
	}

	public void setFundeventtype(Long fundeventtype) {
		this.fundeventtype = fundeventtype;
	}

	@Column(name = "FUNDEVENTDESCRIPTION")
	public String getFundeventdescription() {
		return this.fundeventdescription;
	}

	public void setFundeventdescription(String fundeventdescription) {
		this.fundeventdescription = fundeventdescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fundEventsByOnfundallocationtimeexpiry")
	public Set<FundDefinition> getFundDefinitionsForOnfundallocationtimeexpiry() {
		return this.fundDefinitionsForOnfundallocationtimeexpiry;
	}

	public void setFundDefinitionsForOnfundallocationtimeexpiry(
			Set<FundDefinition> fundDefinitionsForOnfundallocationtimeexpiry) {
		this.fundDefinitionsForOnfundallocationtimeexpiry = fundDefinitionsForOnfundallocationtimeexpiry;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fundEventsByGenerationofotponfailure")
	public Set<FundDefinition> getFundDefinitionsForGenerationofotponfailure() {
		return this.fundDefinitionsForGenerationofotponfailure;
	}

	public void setFundDefinitionsForGenerationofotponfailure(
			Set<FundDefinition> fundDefinitionsForGenerationofotponfailure) {
		this.fundDefinitionsForGenerationofotponfailure = fundDefinitionsForGenerationofotponfailure;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fundEventsByOnfailedattemptsexceeded")
	public Set<FundDefinition> getFundDefinitionsForOnfailedattemptsexceeded() {
		return this.fundDefinitionsForOnfailedattemptsexceeded;
	}

	public void setFundDefinitionsForOnfailedattemptsexceeded(
			Set<FundDefinition> fundDefinitionsForOnfailedattemptsexceeded) {
		this.fundDefinitionsForOnfailedattemptsexceeded = fundDefinitionsForOnfailedattemptsexceeded;
	}

}
