package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FundDistributionInfo generated by hbm2java
 */
@Entity
@Table(name = "FUND_DISTRIBUTION_INFO")
public class FundDistributionInfo extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	public static final String FieldName_TransferSCTLId = "transfersctlid";
	public static final String FieldName_TransferCTId = "transferctid";
	public static final String FieldName_DistributionStatus = "distributionstatus";
	public static final String FieldName_DistributionType = "distributiontype";
	
	private UnregisteredTxnInfo unregisteredTxnInfo;
	private BigDecimal mspid;
	private BigDecimal distributedamount;
	private Long distributionstatus;
	private String failurereason;
	private Long failurereasoncode;
	private BigDecimal transfersctlid;
	private BigDecimal transferctid;
	private Long distributiontype;

	public FundDistributionInfo() {
	}

	

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUNDALLOCATIONID")
	public UnregisteredTxnInfo getUnregisteredTxnInfo() {
		return this.unregisteredTxnInfo;
	}

	public void setUnregisteredTxnInfo(UnregisteredTxnInfo unregisteredTxnInfo) {
		this.unregisteredTxnInfo = unregisteredTxnInfo;
	}

	

	@Column(name = "MSPID", nullable = false, scale = 0)
	public BigDecimal getMspid() {
		return this.mspid;
	}

	public void setMspid(BigDecimal mspid) {
		this.mspid = mspid;
	}

	@Column(name = "DISTRIBUTEDAMOUNT", precision = 25, scale = 4)
	public BigDecimal getDistributedamount() {
		return this.distributedamount;
	}

	public void setDistributedamount(BigDecimal distributedamount) {
		this.distributedamount = distributedamount;
	}

	@Column(name = "DISTRIBUTIONSTATUS", precision = 10, scale = 0)
	public Long getDistributionstatus() {
		return this.distributionstatus;
	}

	public void setDistributionstatus(Long distributionstatus) {
		this.distributionstatus = distributionstatus;
	}

	@Column(name = "FAILUREREASON")
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

	@Column(name = "FAILUREREASONCODE", precision = 10, scale = 0)
	public Long getFailurereasoncode() {
		return this.failurereasoncode;
	}

	public void setFailurereasoncode(Long failurereasoncode) {
		this.failurereasoncode = failurereasoncode;
	}

	@Column(name = "TRANSFERSCTLID", scale = 0)
	public BigDecimal getTransfersctlid() {
		return this.transfersctlid;
	}

	public void setTransfersctlid(BigDecimal transfersctlid) {
		this.transfersctlid = transfersctlid;
	}

	@Column(name = "TRANSFERCTID", scale = 0)
	public BigDecimal getTransferctid() {
		return this.transferctid;
	}

	public void setTransferctid(BigDecimal transferctid) {
		this.transferctid = transferctid;
	}

	@Column(name = "DISTRIBUTIONTYPE", precision = 10, scale = 0)
	public Long getDistributiontype() {
		return this.distributiontype;
	}

	public void setDistributiontype(Long distributiontype) {
		this.distributiontype = distributiontype;
	}

}
