package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "GROUPS")
public class Groups extends Base implements java.io.Serializable {

	public static final String FieldName_GroupName = "groupname";
	public static final String FieldName_SystemGroup = "systemgroup";
	
	private long id;
	private long version;
	private String groupname;
	private String description;
	private Short systemgroup;
	private Set<ActorChannelMapping> actorChannelMappings = new HashSet<ActorChannelMapping>(
			0);
	private Set<PtcGroupMapping> ptcGroupMappings = new HashSet<PtcGroupMapping>(
			0);

	public Groups() {
	}

	public Groups(long id, Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String groupname) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.groupname = groupname;
	}

	public Groups(long id, Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String groupname,
			String description, Short systemgroup,
			Set<ActorChannelMapping> actorChannelMappings,
			Set<PtcGroupMapping> ptcGroupMappings) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.groupname = groupname;
		this.description = description;
		this.systemgroup = systemgroup;
		this.actorChannelMappings = actorChannelMappings;
		this.ptcGroupMappings = ptcGroupMappings;
	}

	

	@Column(name = "GROUPNAME", nullable = false, length = 1020)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "SYSTEMGROUP", precision = 3, scale = 0)
	public Short getSystemgroup() {
		return this.systemgroup;
	}

	public void setSystemgroup(Short systemgroup) {
		this.systemgroup = systemgroup;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<ActorChannelMapping> getActorChannelMappings() {
		return this.actorChannelMappings;
	}

	public void setActorChannelMappings(
			Set<ActorChannelMapping> actorChannelMappings) {
		this.actorChannelMappings = actorChannelMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groups")
	public Set<PtcGroupMapping> getPtcGroupMappings() {
		return this.ptcGroupMappings;
	}

	public void setPtcGroupMappings(Set<PtcGroupMapping> ptcGroupMappings) {
		this.ptcGroupMappings = ptcGroupMappings;
	}

}
