package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * InterbankTransfers generated by hbm2java
 */
@Entity
@Table(name = "INTERBANK_TRANSFERS")
public class InterbankTransfers extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_SctlId = "sctlid";
	public static final String FieldName_TransferID = "transferid";
	
	private String terminalid;
	private String destbankcode;
	private String sourceaccountname;
	private String destaccountname;
	private String sourceaccountnumber;
	private String destaccountnumber;
	private BigDecimal amount;
	private BigDecimal charges;
	private BigDecimal transferid;
	private BigDecimal sctlid;
	private String sessionid;
	private String narration;
	private String paymentreference;
	private String nibresponsecode;
	private Long ibtstatus;
	private String destbankname;

	public InterbankTransfers() {
	}

	
	
	@Column(name = "TERMINALID", length = 1020)
	public String getTerminalid() {
		return this.terminalid;
	}

	public void setTerminalid(String terminalid) {
		this.terminalid = terminalid;
	}

	@Column(name = "DESTBANKCODE", nullable = false, length = 1020)
	public String getDestbankcode() {
		return this.destbankcode;
	}

	public void setDestbankcode(String destbankcode) {
		this.destbankcode = destbankcode;
	}

	@Column(name = "SOURCEACCOUNTNAME", length = 1020)
	public String getSourceaccountname() {
		return this.sourceaccountname;
	}

	public void setSourceaccountname(String sourceaccountname) {
		this.sourceaccountname = sourceaccountname;
	}

	@Column(name = "DESTACCOUNTNAME", length = 1020)
	public String getDestaccountname() {
		return this.destaccountname;
	}

	public void setDestaccountname(String destaccountname) {
		this.destaccountname = destaccountname;
	}

	@Column(name = "SOURCEACCOUNTNUMBER", length = 1020)
	public String getSourceaccountnumber() {
		return this.sourceaccountnumber;
	}

	public void setSourceaccountnumber(String sourceaccountnumber) {
		this.sourceaccountnumber = sourceaccountnumber;
	}

	@Column(name = "DESTACCOUNTNUMBER", length = 1020)
	public String getDestaccountnumber() {
		return this.destaccountnumber;
	}

	public void setDestaccountnumber(String destaccountnumber) {
		this.destaccountnumber = destaccountnumber;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "CHARGES", nullable = false, precision = 25, scale = 4)
	public BigDecimal getCharges() {
		return this.charges;
	}

	public void setCharges(BigDecimal charges) {
		this.charges = charges;
	}

	@Column(name = "TRANSFERID", scale = 0)
	public BigDecimal getTransferid() {
		return this.transferid;
	}

	public void setTransferid(BigDecimal transferid) {
		this.transferid = transferid;
	}

	@Column(name = "SCTLID", scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "SESSIONID", length = 1020)
	public String getSessionid() {
		return this.sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	@Column(name = "NARRATION", length = 1020)
	public String getNarration() {
		return this.narration;
	}

	public void setNarration(String narration) {
		this.narration = narration;
	}

	@Column(name = "PAYMENTREFERENCE", length = 1020)
	public String getPaymentreference() {
		return this.paymentreference;
	}

	public void setPaymentreference(String paymentreference) {
		this.paymentreference = paymentreference;
	}

	@Column(name = "NIBRESPONSECODE", length = 1020)
	public String getNibresponsecode() {
		return this.nibresponsecode;
	}

	public void setNibresponsecode(String nibresponsecode) {
		this.nibresponsecode = nibresponsecode;
	}

	@Column(name = "IBTSTATUS", precision = 10, scale = 0)
	public Long getIbtstatus() {
		return this.ibtstatus;
	}

	public void setIbtstatus(Long ibtstatus) {
		this.ibtstatus = ibtstatus;
	}

	@Column(name = "DESTBANKNAME")
	public String getDestbankname() {
		return this.destbankname;
	}

	public void setDestbankname(String destbankname) {
		this.destbankname = destbankname;
	}

}
