package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * IntegrationPartnerMap generated by hbm2java
 */
@Entity
@Table(name = "INTEGRATION_PARTNER_MAP")
public class IntegrationPartnerMap implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Partner partner;
	private MfsBiller mfsBiller;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String institutionid;
	private String integrationname;
	private String authenticationkey;
	private Short isauthenticationkeyenabled;
	private Short isloginenabled;
	private Short isapptypecheckenabled;
	private Set<IpMapping> ipMappings = new HashSet<IpMapping>(0);

	public IntegrationPartnerMap() {
	}

	public IntegrationPartnerMap(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			String institutionid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.institutionid = institutionid;
	}

	public IntegrationPartnerMap(BigDecimal id, Partner partner,
			MfsBiller mfsBiller, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String institutionid,
			String integrationname, String authenticationkey,
			Short isauthenticationkeyenabled, Short isloginenabled,
			Short isapptypecheckenabled, Set<IpMapping> ipMappings) {
		this.id = id;
		this.partner = partner;
		this.mfsBiller = mfsBiller;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.institutionid = institutionid;
		this.integrationname = integrationname;
		this.authenticationkey = authenticationkey;
		this.isauthenticationkeyenabled = isauthenticationkeyenabled;
		this.isloginenabled = isloginenabled;
		this.isapptypecheckenabled = isapptypecheckenabled;
		this.ipMappings = ipMappings;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARTNERID")
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MFSBILLERID")
	public MfsBiller getMfsBiller() {
		return this.mfsBiller;
	}

	public void setMfsBiller(MfsBiller mfsBiller) {
		this.mfsBiller = mfsBiller;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "INSTITUTIONID", nullable = false)
	public String getInstitutionid() {
		return this.institutionid;
	}

	public void setInstitutionid(String institutionid) {
		this.institutionid = institutionid;
	}

	@Column(name = "INTEGRATIONNAME", length = 1020)
	public String getIntegrationname() {
		return this.integrationname;
	}

	public void setIntegrationname(String integrationname) {
		this.integrationname = integrationname;
	}

	@Column(name = "AUTHENTICATIONKEY", length = 1020)
	public String getAuthenticationkey() {
		return this.authenticationkey;
	}

	public void setAuthenticationkey(String authenticationkey) {
		this.authenticationkey = authenticationkey;
	}

	@Column(name = "ISAUTHENTICATIONKEYENABLED", precision = 3, scale = 0)
	public Short getIsauthenticationkeyenabled() {
		return this.isauthenticationkeyenabled;
	}

	public void setIsauthenticationkeyenabled(Short isauthenticationkeyenabled) {
		this.isauthenticationkeyenabled = isauthenticationkeyenabled;
	}

	@Column(name = "ISLOGINENABLED", precision = 3, scale = 0)
	public Short getIsloginenabled() {
		return this.isloginenabled;
	}

	public void setIsloginenabled(Short isloginenabled) {
		this.isloginenabled = isloginenabled;
	}

	@Column(name = "ISAPPTYPECHECKENABLED", precision = 3, scale = 0)
	public Short getIsapptypecheckenabled() {
		return this.isapptypecheckenabled;
	}

	public void setIsapptypecheckenabled(Short isapptypecheckenabled) {
		this.isapptypecheckenabled = isapptypecheckenabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "integrationPartnerMap")
	public Set<IpMapping> getIpMappings() {
		return this.ipMappings;
	}

	public void setIpMappings(Set<IpMapping> ipMappings) {
		this.ipMappings = ipMappings;
	}

}
