package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * IntegrationSummary generated by hbm2java
 */
@Entity
@Table(name = "INTEGRATION_SUMMARY")
public class IntegrationSummary implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal sctlid;
	private String integrationtype;
	private String reconcilationid1;
	private String reconcilationid2;
	private String reconcilationid3;
	private String reconcilationid4;
	private BigDecimal pctid;
	private String institutionid;

	public IntegrationSummary() {
	}

	public IntegrationSummary(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
	}

	public IntegrationSummary(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid, String integrationtype, String reconcilationid1,
			String reconcilationid2, String reconcilationid3,
			String reconcilationid4, BigDecimal pctid, String institutionid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.integrationtype = integrationtype;
		this.reconcilationid1 = reconcilationid1;
		this.reconcilationid2 = reconcilationid2;
		this.reconcilationid3 = reconcilationid3;
		this.reconcilationid4 = reconcilationid4;
		this.pctid = pctid;
		this.institutionid = institutionid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SCTLID", nullable = false, scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "INTEGRATIONTYPE")
	public String getIntegrationtype() {
		return this.integrationtype;
	}

	public void setIntegrationtype(String integrationtype) {
		this.integrationtype = integrationtype;
	}

	@Column(name = "RECONCILATIONID1")
	public String getReconcilationid1() {
		return this.reconcilationid1;
	}

	public void setReconcilationid1(String reconcilationid1) {
		this.reconcilationid1 = reconcilationid1;
	}

	@Column(name = "RECONCILATIONID2", length = 1024)
	public String getReconcilationid2() {
		return this.reconcilationid2;
	}

	public void setReconcilationid2(String reconcilationid2) {
		this.reconcilationid2 = reconcilationid2;
	}

	@Column(name = "RECONCILATIONID3")
	public String getReconcilationid3() {
		return this.reconcilationid3;
	}

	public void setReconcilationid3(String reconcilationid3) {
		this.reconcilationid3 = reconcilationid3;
	}

	@Column(name = "RECONCILATIONID4", length = 225)
	public String getReconcilationid4() {
		return this.reconcilationid4;
	}

	public void setReconcilationid4(String reconcilationid4) {
		this.reconcilationid4 = reconcilationid4;
	}

	@Column(name = "PCTID", scale = 0)
	public BigDecimal getPctid() {
		return this.pctid;
	}

	public void setPctid(BigDecimal pctid) {
		this.pctid = pctid;
	}

	@Column(name = "INSTITUTIONID", length = 900)
	public String getInstitutionid() {
		return this.institutionid;
	}

	public void setInstitutionid(String institutionid) {
		this.institutionid = institutionid;
	}

}
