package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * IpMapping generated by hbm2java
 */
@Entity
@Table(name = "IP_MAPPING")
public class IPMapping extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_IntegrationPartnerMappingByIntegrationID = "integrationPartnerMap";
	public static final String FieldName_IPAddress = "ipaddress";
	
	private IntegrationPartnerMapping integrationPartnerMap;
	private String ipaddress;

	public IPMapping() {
	}

	public IPMapping(BigDecimal id,
			IntegrationPartnerMapping integrationPartnerMap,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String ipaddress) {
		this.id = id;
		this.integrationPartnerMap = integrationPartnerMap;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.ipaddress = ipaddress;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INTEGRATIONID", nullable = false)
	public IntegrationPartnerMapping getIntegrationPartnerMap() {
		return this.integrationPartnerMap;
	}

	public void setIntegrationPartnerMap(
			IntegrationPartnerMapping integrationPartnerMap) {
		this.integrationPartnerMap = integrationPartnerMap;
	}

	

	@Column(name = "IPADDRESS", nullable = false, length = 1020)
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

}
