package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * KtpDetails generated by hbm2java
 */
@Entity
@Table(name = "KTP_DETAILS")
public class KtpDetails extends Base implements java.io.Serializable {

	
	public static final String FieldName_MDN = "mdn";
	private String mdn;
	private String ktpid;
	private String fullname;
	private Timestamp dateofbirth;
	private String agentmdn;
	private String bankresponsestatus;
	private String bankresponse;

	public KtpDetails() {
	}

	
	
	@Column(name = "MDN", nullable = false, length = 1020)
	public String getMdn() {
		return this.mdn;
	}

	public void setMdn(String mdn) {
		this.mdn = mdn;
	}

	@Column(name = "KTPID", length = 1020)
	public String getKtpid() {
		return this.ktpid;
	}

	public void setKtpid(String ktpid) {
		this.ktpid = ktpid;
	}

	@Column(name = "FULLNAME", length = 1020)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "DATEOFBIRTH")
	public Timestamp getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Timestamp dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "AGENTMDN", length = 1020)
	public String getAgentmdn() {
		return this.agentmdn;
	}

	public void setAgentmdn(String agentmdn) {
		this.agentmdn = agentmdn;
	}

	@Column(name = "BANKRESPONSESTATUS")
	public String getBankresponsestatus() {
		return this.bankresponsestatus;
	}

	public void setBankresponsestatus(String bankresponsestatus) {
		this.bankresponsestatus = bankresponsestatus;
	}

	@Column(name = "BANKRESPONSE", length = 4000)
	public String getBankresponse() {
		return this.bankresponse;
	}

	public void setBankresponse(String bankresponse) {
		this.bankresponse = bankresponse;
	}

}
