package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * KtpDetails generated by hbm2java
 */
@Entity
@Table(name = "KTP_DETAILS")
public class KtpDetails implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String mdn;
	private String ktpid;
	private String fullname;
	private Serializable dateofbirth;
	private String agentmdn;
	private String bankresponsestatus;
	private String bankresponse;

	public KtpDetails() {
	}

	public KtpDetails(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			String mdn) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mdn = mdn;
	}

	public KtpDetails(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			String mdn, String ktpid, String fullname,
			Serializable dateofbirth, String agentmdn,
			String bankresponsestatus, String bankresponse) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mdn = mdn;
		this.ktpid = ktpid;
		this.fullname = fullname;
		this.dateofbirth = dateofbirth;
		this.agentmdn = agentmdn;
		this.bankresponsestatus = bankresponsestatus;
		this.bankresponse = bankresponse;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MDN", nullable = false, length = 1020)
	public String getMdn() {
		return this.mdn;
	}

	public void setMdn(String mdn) {
		this.mdn = mdn;
	}

	@Column(name = "KTPID", length = 1020)
	public String getKtpid() {
		return this.ktpid;
	}

	public void setKtpid(String ktpid) {
		this.ktpid = ktpid;
	}

	@Column(name = "FULLNAME", length = 1020)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "DATEOFBIRTH")
	public Serializable getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Serializable dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "AGENTMDN", length = 1020)
	public String getAgentmdn() {
		return this.agentmdn;
	}

	public void setAgentmdn(String agentmdn) {
		this.agentmdn = agentmdn;
	}

	@Column(name = "BANKRESPONSESTATUS")
	public String getBankresponsestatus() {
		return this.bankresponsestatus;
	}

	public void setBankresponsestatus(String bankresponsestatus) {
		this.bankresponsestatus = bankresponsestatus;
	}

	@Column(name = "BANKRESPONSE", length = 4000)
	public String getBankresponse() {
		return this.bankresponse;
	}

	public void setBankresponse(String bankresponse) {
		this.bankresponse = bankresponse;
	}

}
