package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * KycFields generated by hbm2java
 */
@Entity
@Table(name = "KYC_FIELDS")
public class KycFields implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private KycLevel kycLevel;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String kycfieldsname;
	private String kycfieldsdescription;

	public KycFields() {
	}

	public KycFields(BigDecimal id, KycLevel kycLevel,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String kycfieldsname) {
		this.id = id;
		this.kycLevel = kycLevel;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.kycfieldsname = kycfieldsname;
	}

	public KycFields(BigDecimal id, KycLevel kycLevel,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String kycfieldsname,
			String kycfieldsdescription) {
		this.id = id;
		this.kycLevel = kycLevel;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.kycfieldsname = kycfieldsname;
		this.kycfieldsdescription = kycfieldsdescription;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KYCFIELDSLEVELID", nullable = false)
	public KycLevel getKycLevel() {
		return this.kycLevel;
	}

	public void setKycLevel(KycLevel kycLevel) {
		this.kycLevel = kycLevel;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "KYCFIELDSNAME", nullable = false, length = 1020)
	public String getKycfieldsname() {
		return this.kycfieldsname;
	}

	public void setKycfieldsname(String kycfieldsname) {
		this.kycfieldsname = kycfieldsname;
	}

	@Column(name = "KYCFIELDSDESCRIPTION", length = 1020)
	public String getKycfieldsdescription() {
		return this.kycfieldsdescription;
	}

	public void setKycfieldsdescription(String kycfieldsdescription) {
		this.kycfieldsdescription = kycfieldsdescription;
	}

}
