package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KycFields generated by hbm2java
 */
@Entity
@Table(name = "KYC_FIELDS")
public class KycFields extends Base implements java.io.Serializable {

	
	public static final String FieldName_KYCLevelByKYCFieldsLevelID = "kycLevel";
	private KycLevel kycLevel;
	private String kycfieldsname;
	private String kycfieldsdescription;

	public KycFields() {
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KYCFIELDSLEVELID", nullable = false)
	public KycLevel getKycLevel() {
		return this.kycLevel;
	}

	public void setKycLevel(KycLevel kycLevel) {
		this.kycLevel = kycLevel;
	}

	

	@Column(name = "KYCFIELDSNAME", nullable = false, length = 1020)
	public String getKycfieldsname() {
		return this.kycfieldsname;
	}

	public void setKycfieldsname(String kycfieldsname) {
		this.kycfieldsname = kycfieldsname;
	}

	@Column(name = "KYCFIELDSDESCRIPTION", length = 1020)
	public String getKycfieldsdescription() {
		return this.kycfieldsdescription;
	}

	public void setKycfieldsdescription(String kycfieldsdescription) {
		this.kycfieldsdescription = kycfieldsdescription;
	}

}
