package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;
/**
 * KycLevel generated by hbm2java
 */
@Entity
@Table(name = "KYC_LEVEL", uniqueConstraints = @UniqueConstraint(columnNames = "KYCLEVEL"))
public class KYCLevel extends Base implements java.io.Serializable {

	
	private PocketTemplate pocketTemplate;
	private BigDecimal kyclevel;
	private String kyclevelname;
	private String kycleveldescription;
	private Set<TransactionRule> transactionRulesForDestkyc = new HashSet<TransactionRule>(
			0);
	private Set<TransactionRule> transactionRulesForSourcekyc = new HashSet<TransactionRule>(
			0);
	private Set<KYCFields> kycFieldses = new HashSet<KYCFields>(0);
	private Set<Subscriber> subscribers = new HashSet<Subscriber>(0);
	private Set<PocketTemplateConfig> pocketTemplateConfigs = new HashSet<PocketTemplateConfig>(
			0);
	private Set<ActorChannelMapping> actorChannelMappings = new HashSet<ActorChannelMapping>(
			0);

	public KYCLevel() {
	}

	public KYCLevel(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal kyclevel, String kyclevelname) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.kyclevel = kyclevel;
		this.kyclevelname = kyclevelname;
	}

	public KYCLevel(BigDecimal id, PocketTemplate pocketTemplate,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, BigDecimal kyclevel,
			String kyclevelname, String kycleveldescription,
			Set<TransactionRule> transactionRulesForDestkyc,
			Set<TransactionRule> transactionRulesForSourcekyc,
			Set<KYCFields> kycFieldses, Set<Subscriber> subscribers,
			Set<PocketTemplateConfig> pocketTemplateConfigs,
			Set<ActorChannelMapping> actorChannelMappings) {
		this.id = id;
		this.pocketTemplate = pocketTemplate;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.kyclevel = kyclevel;
		this.kyclevelname = kyclevelname;
		this.kycleveldescription = kycleveldescription;
		this.transactionRulesForDestkyc = transactionRulesForDestkyc;
		this.transactionRulesForSourcekyc = transactionRulesForSourcekyc;
		this.kycFieldses = kycFieldses;
		this.subscribers = subscribers;
		this.pocketTemplateConfigs = pocketTemplateConfigs;
		this.actorChannelMappings = actorChannelMappings;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETTEMPLATEID")
	public PocketTemplate getPocketTemplate() {
		return this.pocketTemplate;
	}

	public void setPocketTemplate(PocketTemplate pocketTemplate) {
		this.pocketTemplate = pocketTemplate;
	}

	
	@Column(name = "KYCLEVEL", unique = true, nullable = false, scale = 0)
	public BigDecimal getKyclevel() {
		return this.kyclevel;
	}

	public void setKyclevel(BigDecimal kyclevel) {
		this.kyclevel = kyclevel;
	}

	@Column(name = "KYCLEVELNAME", nullable = false, length = 1020)
	public String getKyclevelname() {
		return this.kyclevelname;
	}

	public void setKyclevelname(String kyclevelname) {
		this.kyclevelname = kyclevelname;
	}

	@Column(name = "KYCLEVELDESCRIPTION", length = 1020)
	public String getKycleveldescription() {
		return this.kycleveldescription;
	}

	public void setKycleveldescription(String kycleveldescription) {
		this.kycleveldescription = kycleveldescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevelByDestkyc")
	public Set<TransactionRule> getTransactionRulesForDestkyc() {
		return this.transactionRulesForDestkyc;
	}

	public void setTransactionRulesForDestkyc(
			Set<TransactionRule> transactionRulesForDestkyc) {
		this.transactionRulesForDestkyc = transactionRulesForDestkyc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevelBySourcekyc")
	public Set<TransactionRule> getTransactionRulesForSourcekyc() {
		return this.transactionRulesForSourcekyc;
	}

	public void setTransactionRulesForSourcekyc(
			Set<TransactionRule> transactionRulesForSourcekyc) {
		this.transactionRulesForSourcekyc = transactionRulesForSourcekyc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevel")
	public Set<KYCFields> getKycFieldses() {
		return this.kycFieldses;
	}

	public void setKycFieldses(Set<KYCFields> kycFieldses) {
		this.kycFieldses = kycFieldses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevel")
	public Set<Subscriber> getSubscribers() {
		return this.subscribers;
	}

	public void setSubscribers(Set<Subscriber> subscribers) {
		this.subscribers = subscribers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevel")
	public Set<PocketTemplateConfig> getPocketTemplateConfigs() {
		return this.pocketTemplateConfigs;
	}

	public void setPocketTemplateConfigs(
			Set<PocketTemplateConfig> pocketTemplateConfigs) {
		this.pocketTemplateConfigs = pocketTemplateConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevel")
	public Set<ActorChannelMapping> getActorChannelMappings() {
		return this.actorChannelMappings;
	}

	public void setActorChannelMappings(
			Set<ActorChannelMapping> actorChannelMappings) {
		this.actorChannelMappings = actorChannelMappings;
	}

}
