package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * KycLevel generated by hbm2java
 */
@Entity
@Table(name = "KYC_LEVEL", uniqueConstraints = @UniqueConstraint(columnNames = "KYCLEVEL"))
public class KycLevel implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private PocketTemplate pocketTemplate;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal kyclevel;
	private String kyclevelname;
	private String kycleveldescription;
	private Set<TransactionRule> transactionRulesForDestkyc = new HashSet<TransactionRule>(
			0);
	private Set<TransactionRule> transactionRulesForSourcekyc = new HashSet<TransactionRule>(
			0);
	private Set<KycFields> kycFieldses = new HashSet<KycFields>(0);
	private Set<Subscriber> subscribers = new HashSet<Subscriber>(0);
	private Set<PocketTemplateConfig> pocketTemplateConfigs = new HashSet<PocketTemplateConfig>(
			0);
	private Set<ActorChannelMapping> actorChannelMappings = new HashSet<ActorChannelMapping>(
			0);

	public KycLevel() {
	}

	public KycLevel(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal kyclevel, String kyclevelname) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.kyclevel = kyclevel;
		this.kyclevelname = kyclevelname;
	}

	public KycLevel(BigDecimal id, PocketTemplate pocketTemplate,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal kyclevel,
			String kyclevelname, String kycleveldescription,
			Set<TransactionRule> transactionRulesForDestkyc,
			Set<TransactionRule> transactionRulesForSourcekyc,
			Set<KycFields> kycFieldses, Set<Subscriber> subscribers,
			Set<PocketTemplateConfig> pocketTemplateConfigs,
			Set<ActorChannelMapping> actorChannelMappings) {
		this.id = id;
		this.pocketTemplate = pocketTemplate;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.kyclevel = kyclevel;
		this.kyclevelname = kyclevelname;
		this.kycleveldescription = kycleveldescription;
		this.transactionRulesForDestkyc = transactionRulesForDestkyc;
		this.transactionRulesForSourcekyc = transactionRulesForSourcekyc;
		this.kycFieldses = kycFieldses;
		this.subscribers = subscribers;
		this.pocketTemplateConfigs = pocketTemplateConfigs;
		this.actorChannelMappings = actorChannelMappings;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETTEMPLATEID")
	public PocketTemplate getPocketTemplate() {
		return this.pocketTemplate;
	}

	public void setPocketTemplate(PocketTemplate pocketTemplate) {
		this.pocketTemplate = pocketTemplate;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "KYCLEVEL", unique = true, nullable = false, scale = 0)
	public BigDecimal getKyclevel() {
		return this.kyclevel;
	}

	public void setKyclevel(BigDecimal kyclevel) {
		this.kyclevel = kyclevel;
	}

	@Column(name = "KYCLEVELNAME", nullable = false, length = 1020)
	public String getKyclevelname() {
		return this.kyclevelname;
	}

	public void setKyclevelname(String kyclevelname) {
		this.kyclevelname = kyclevelname;
	}

	@Column(name = "KYCLEVELDESCRIPTION", length = 1020)
	public String getKycleveldescription() {
		return this.kycleveldescription;
	}

	public void setKycleveldescription(String kycleveldescription) {
		this.kycleveldescription = kycleveldescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevelByDestkyc")
	public Set<TransactionRule> getTransactionRulesForDestkyc() {
		return this.transactionRulesForDestkyc;
	}

	public void setTransactionRulesForDestkyc(
			Set<TransactionRule> transactionRulesForDestkyc) {
		this.transactionRulesForDestkyc = transactionRulesForDestkyc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevelBySourcekyc")
	public Set<TransactionRule> getTransactionRulesForSourcekyc() {
		return this.transactionRulesForSourcekyc;
	}

	public void setTransactionRulesForSourcekyc(
			Set<TransactionRule> transactionRulesForSourcekyc) {
		this.transactionRulesForSourcekyc = transactionRulesForSourcekyc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevel")
	public Set<KycFields> getKycFieldses() {
		return this.kycFieldses;
	}

	public void setKycFieldses(Set<KycFields> kycFieldses) {
		this.kycFieldses = kycFieldses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevel")
	public Set<Subscriber> getSubscribers() {
		return this.subscribers;
	}

	public void setSubscribers(Set<Subscriber> subscribers) {
		this.subscribers = subscribers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevel")
	public Set<PocketTemplateConfig> getPocketTemplateConfigs() {
		return this.pocketTemplateConfigs;
	}

	public void setPocketTemplateConfigs(
			Set<PocketTemplateConfig> pocketTemplateConfigs) {
		this.pocketTemplateConfigs = pocketTemplateConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kycLevel")
	public Set<ActorChannelMapping> getActorChannelMappings() {
		return this.actorChannelMappings;
	}

	public void setActorChannelMappings(
			Set<ActorChannelMapping> actorChannelMappings) {
		this.actorChannelMappings = actorChannelMappings;
	}

}
