package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import com.mfino.hibernate.Timestamp;

/**
 * Ledger generated by hbm2java
 */
@Entity
@Table(name = "LEDGER")
public class Ledger extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	public static final String FieldName_SourcePocketID = "sourcepocketid";
	public static final String FieldName_SourceMDN = "sourcemdn";
	public static final String FieldName_CommodityTransferID = "commoditytransferid";
	public static final String FieldName_DestPocketID = "destpocketid";
	public static final String FieldName_DestMDN = "destmdn";
	
	private BigDecimal commoditytransferid;
	private String sourcemdn;
	private BigDecimal sourcepocketid;
	private String sourcepocketbalance;
	private String destmdn;
	private BigDecimal destpocketid;
	private String destpocketbalance;
	private BigDecimal amount;

	public Ledger() {
	}

	public Ledger(BigDecimal id, Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby,
			BigDecimal commoditytransferid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.commoditytransferid = commoditytransferid;
	}

	public Ledger(BigDecimal id, Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby,
			BigDecimal commoditytransferid, String sourcemdn,
			BigDecimal sourcepocketid, String sourcepocketbalance,
			String destmdn, BigDecimal destpocketid, String destpocketbalance,
			BigDecimal amount) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.commoditytransferid = commoditytransferid;
		this.sourcemdn = sourcemdn;
		this.sourcepocketid = sourcepocketid;
		this.sourcepocketbalance = sourcepocketbalance;
		this.destmdn = destmdn;
		this.destpocketid = destpocketid;
		this.destpocketbalance = destpocketbalance;
		this.amount = amount;
	}

	
	@Column(name = "COMMODITYTRANSFERID", nullable = false, scale = 0)
	public BigDecimal getCommoditytransferid() {
		return this.commoditytransferid;
	}

	public void setCommoditytransferid(BigDecimal commoditytransferid) {
		this.commoditytransferid = commoditytransferid;
	}

	@Column(name = "SOURCEMDN", length = 1020)
	public String getSourcemdn() {
		return this.sourcemdn;
	}

	public void setSourcemdn(String sourcemdn) {
		this.sourcemdn = sourcemdn;
	}

	@Column(name = "SOURCEPOCKETID", scale = 0)
	public BigDecimal getSourcepocketid() {
		return this.sourcepocketid;
	}

	public void setSourcepocketid(BigDecimal sourcepocketid) {
		this.sourcepocketid = sourcepocketid;
	}

	@Column(name = "SOURCEPOCKETBALANCE", length = 1020)
	public String getSourcepocketbalance() {
		return this.sourcepocketbalance;
	}

	public void setSourcepocketbalance(String sourcepocketbalance) {
		this.sourcepocketbalance = sourcepocketbalance;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

	@Column(name = "DESTPOCKETID", scale = 0)
	public BigDecimal getDestpocketid() {
		return this.destpocketid;
	}

	public void setDestpocketid(BigDecimal destpocketid) {
		this.destpocketid = destpocketid;
	}

	@Column(name = "DESTPOCKETBALANCE", length = 1020)
	public String getDestpocketbalance() {
		return this.destpocketbalance;
	}

	public void setDestpocketbalance(String destpocketbalance) {
		this.destpocketbalance = destpocketbalance;
	}

	@Column(name = "AMOUNT", precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

}
