package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * LopHistory generated by hbm2java
 */
@Entity
@Table(name = "LOP_HISTORY")
public class LopHistory implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private LetterOfPurchase letterOfPurchase;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal olddiscount;
	private BigDecimal newdiscount;
	private String discountchangedby;
	private Serializable discountchangetime;
	private String comments;

	public LopHistory() {
	}

	public LopHistory(BigDecimal id, LetterOfPurchase letterOfPurchase,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby) {
		this.id = id;
		this.letterOfPurchase = letterOfPurchase;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public LopHistory(BigDecimal id, LetterOfPurchase letterOfPurchase,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal olddiscount,
			BigDecimal newdiscount, String discountchangedby,
			Serializable discountchangetime, String comments) {
		this.id = id;
		this.letterOfPurchase = letterOfPurchase;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.olddiscount = olddiscount;
		this.newdiscount = newdiscount;
		this.discountchangedby = discountchangedby;
		this.discountchangetime = discountchangetime;
		this.comments = comments;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOPID", nullable = false)
	public LetterOfPurchase getLetterOfPurchase() {
		return this.letterOfPurchase;
	}

	public void setLetterOfPurchase(LetterOfPurchase letterOfPurchase) {
		this.letterOfPurchase = letterOfPurchase;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "OLDDISCOUNT", precision = 25, scale = 4)
	public BigDecimal getOlddiscount() {
		return this.olddiscount;
	}

	public void setOlddiscount(BigDecimal olddiscount) {
		this.olddiscount = olddiscount;
	}

	@Column(name = "NEWDISCOUNT", precision = 25, scale = 4)
	public BigDecimal getNewdiscount() {
		return this.newdiscount;
	}

	public void setNewdiscount(BigDecimal newdiscount) {
		this.newdiscount = newdiscount;
	}

	@Column(name = "DISCOUNTCHANGEDBY", length = 1020)
	public String getDiscountchangedby() {
		return this.discountchangedby;
	}

	public void setDiscountchangedby(String discountchangedby) {
		this.discountchangedby = discountchangedby;
	}

	@Column(name = "DISCOUNTCHANGETIME")
	public Serializable getDiscountchangetime() {
		return this.discountchangetime;
	}

	public void setDiscountchangetime(Serializable discountchangetime) {
		this.discountchangetime = discountchangetime;
	}

	@Column(name = "COMMENTS", length = 1020)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
