package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import com.mfino.hibernate.Timestamp;
/**
 * MdnOtp generated by hbm2java
 */
@Entity
@Table(name = "MDN_OTP")
public class MdnOtp extends Base implements java.io.Serializable {

	
	public static final String FieldName_MDN = "mdn";
	public static final String FieldName_OTPStatus = "status";
	private String mdn;
	private String otp;
	private Timestamp otpexpirationtime;
	private long status;
	private Long otpretrycount;

	public MdnOtp() {
	}

	
	
	@Column(name = "MDN", nullable = false, length = 1020)
	public String getMdn() {
		return this.mdn;
	}

	public void setMdn(String mdn) {
		this.mdn = mdn;
	}

	@Column(name = "OTP", nullable = false, length = 1020)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@Column(name = "OTPEXPIRATIONTIME", nullable = false)
	public Timestamp getOtpexpirationtime() {
		return this.otpexpirationtime;
	}

	public void setOtpexpirationtime(Timestamp otpexpirationtime) {
		this.otpexpirationtime = otpexpirationtime;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "OTPRETRYCOUNT", precision = 10, scale = 0)
	public Long getOtpretrycount() {
		return this.otpretrycount;
	}

	public void setOtpretrycount(Long otpretrycount) {
		this.otpretrycount = otpretrycount;
	}

}
