package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MdnOtp generated by hbm2java
 */
@Entity
@Table(name = "MDN_OTP")
public class MdnOtp implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String mdn;
	private String otp;
	private Serializable otpexpirationtime;
	private long status;
	private Long otpretrycount;

	public MdnOtp() {
	}

	public MdnOtp(BigDecimal id, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String mdn, String otp,
			Serializable otpexpirationtime, long status) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mdn = mdn;
		this.otp = otp;
		this.otpexpirationtime = otpexpirationtime;
		this.status = status;
	}

	public MdnOtp(BigDecimal id, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String mdn, String otp,
			Serializable otpexpirationtime, long status, Long otpretrycount) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mdn = mdn;
		this.otp = otp;
		this.otpexpirationtime = otpexpirationtime;
		this.status = status;
		this.otpretrycount = otpretrycount;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MDN", nullable = false, length = 1020)
	public String getMdn() {
		return this.mdn;
	}

	public void setMdn(String mdn) {
		this.mdn = mdn;
	}

	@Column(name = "OTP", nullable = false, length = 1020)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@Column(name = "OTPEXPIRATIONTIME", nullable = false)
	public Serializable getOtpexpirationtime() {
		return this.otpexpirationtime;
	}

	public void setOtpexpirationtime(Serializable otpexpirationtime) {
		this.otpexpirationtime = otpexpirationtime;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "OTPRETRYCOUNT", precision = 10, scale = 0)
	public Long getOtpretrycount() {
		return this.otpretrycount;
	}

	public void setOtpretrycount(Long otpretrycount) {
		this.otpretrycount = otpretrycount;
	}

}
