package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import com.mfino.hibernate.Timestamp;

/**
 * MerchantPrefixCode generated by hbm2java
 */
@Entity
@Table(name = "MERCHANT_PREFIX_CODE", uniqueConstraints = @UniqueConstraint(columnNames = "MERCHANTPREFIXCODE"))
public class MerchantPrefixCode extends Base implements java.io.Serializable {

	
	public static final String FieldName_MerchantPrefixCode = "merchantprefixcode";
	public static final String FieldName_BillerName = "billername";
	private long merchantprefixcode;
	private String billername;
	private BigDecimal companyid;
	private String vaservicename;

	public MerchantPrefixCode() {
	}

	public MerchantPrefixCode(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long merchantprefixcode, String billername, String vaservicename) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.merchantprefixcode = merchantprefixcode;
		this.billername = billername;
		this.vaservicename = vaservicename;
	}

	public MerchantPrefixCode(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long merchantprefixcode, String billername, BigDecimal companyid,
			String vaservicename) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.merchantprefixcode = merchantprefixcode;
		this.billername = billername;
		this.companyid = companyid;
		this.vaservicename = vaservicename;
	}

	@Column(name = "MERCHANTPREFIXCODE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getMerchantprefixcode() {
		return this.merchantprefixcode;
	}

	public void setMerchantprefixcode(long merchantprefixcode) {
		this.merchantprefixcode = merchantprefixcode;
	}

	@Column(name = "BILLERNAME", nullable = false, length = 1020)
	public String getBillername() {
		return this.billername;
	}

	public void setBillername(String billername) {
		this.billername = billername;
	}

	@Column(name = "COMPANYID", scale = 0)
	public BigDecimal getCompanyid() {
		return this.companyid;
	}

	public void setCompanyid(BigDecimal companyid) {
		this.companyid = companyid;
	}

	@Column(name = "VASERVICENAME", nullable = false, length = 1020)
	public String getVaservicename() {
		return this.vaservicename;
	}

	public void setVaservicename(String vaservicename) {
		this.vaservicename = vaservicename;
	}

}
