package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import com.mfino.hibernate.Timestamp;

/**
 * MfaAuthentication generated by hbm2java
 */
@Entity
@Table(name = "MFA_AUTHENTICATION")
public class MFAAuthentication extends Base implements java.io.Serializable {

	
	public static final String FieldName_SctlId = "sctlid";
	public static final String FieldName_MFAMode = "mfamode";
	public static final String FieldName_MFAValue = "mfavalue";
	private BigDecimal sctlid;
	private long mfamode;
	private String mfavalue;
	private BigDecimal retryattempt;

	public MFAAuthentication() {
	}

	public MFAAuthentication(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal sctlid, long mfamode, String mfavalue) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.mfamode = mfamode;
		this.mfavalue = mfavalue;
	}

	public MFAAuthentication(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal sctlid, long mfamode, String mfavalue,
			BigDecimal retryattempt) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.mfamode = mfamode;
		this.mfavalue = mfavalue;
		this.retryattempt = retryattempt;
	}

	
	@Column(name = "SCTLID", nullable = false, scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "MFAMODE", nullable = false, precision = 10, scale = 0)
	public long getMfamode() {
		return this.mfamode;
	}

	public void setMfamode(long mfamode) {
		this.mfamode = mfamode;
	}

	@Column(name = "MFAVALUE", nullable = false, length = 1020)
	public String getMfavalue() {
		return this.mfavalue;
	}

	public void setMfavalue(String mfavalue) {
		this.mfavalue = mfavalue;
	}

	@Column(name = "RETRYATTEMPT", precision = 22, scale = 0)
	public BigDecimal getRetryattempt() {
		return this.retryattempt;
	}

	public void setRetryattempt(BigDecimal retryattempt) {
		this.retryattempt = retryattempt;
	}

}
