package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MfaTransactionsInfo generated by hbm2java
 */
@Entity
@Table(name = "MFA_TRANSACTIONS_INFO")
public class MfaTransactionsInfo extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_Service = "service";
	public static final String FieldName_TransactionType = "transactionType";
	public static final String FieldName_ChannelCode = "channelCode";
	public static final String FieldName_MFAMode = "mfamode";
	private ChannelCode channelCode;
	private Service service;
	private TransactionType transactionType;
	private BigDecimal mspid;
	private Integer mfamode;
	private Long id;

	public MfaTransactionsInfo() {
	}
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "mfa_transactions_info_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
		
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHANNELCODEID", nullable = false)
	public ChannelCode getChannelCode() {
		return this.channelCode;
	}

	public void setChannelCode(ChannelCode channelCode) {
		this.channelCode = channelCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONTYPEID", nullable = false)
	public TransactionType getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	
	@Column(name = "MSPID", nullable = false, scale = 0)
	public BigDecimal getMspid() {
		return this.mspid;
	}

	public void setMspid(BigDecimal mspid) {
		this.mspid = mspid;
	}

	@Column(name = "MFAMODE", nullable = false, precision = 10, scale = 0)
	public Integer getMfamode() {
		return this.mfamode;
	}

	public void setMfamode(Integer mfamode) {
		this.mfamode = mfamode;
	}

}
