package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MfinoJobDetailsId generated by hbm2java
 */
@Embeddable
public class MfinoJobDetailsId implements java.io.Serializable {

	private String jobName;
	private String jobGroup;

	public MfinoJobDetailsId() {
	}

	public MfinoJobDetailsId(String jobName, String jobGroup) {
		this.jobName = jobName;
		this.jobGroup = jobGroup;
	}

	@Column(name = "JOB_NAME", nullable = false, length = 200)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "JOB_GROUP", nullable = false, length = 200)
	public String getJobGroup() {
		return this.jobGroup;
	}

	public void setJobGroup(String jobGroup) {
		this.jobGroup = jobGroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MfinoJobDetailsId))
			return false;
		MfinoJobDetailsId castOther = (MfinoJobDetailsId) other;

		return ((this.getJobName() == castOther.getJobName()) || (this
				.getJobName() != null && castOther.getJobName() != null && this
				.getJobName().equals(castOther.getJobName())))
				&& ((this.getJobGroup() == castOther.getJobGroup()) || (this
						.getJobGroup() != null
						&& castOther.getJobGroup() != null && this
						.getJobGroup().equals(castOther.getJobGroup())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getJobName() == null ? 0 : this.getJobName().hashCode());
		result = 37 * result
				+ (getJobGroup() == null ? 0 : this.getJobGroup().hashCode());
		return result;
	}

}
