package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MfinoJobListeners generated by hbm2java
 */
@Entity
@Table(name = "MFINO_JOB_LISTENERS")
public class MfinoJobListeners implements java.io.Serializable {

	private MfinoJobListenersId id;
	private MfinoJobDetails mfinoJobDetails;

	public MfinoJobListeners() {
	}

	public MfinoJobListeners(MfinoJobListenersId id,
			MfinoJobDetails mfinoJobDetails) {
		this.id = id;
		this.mfinoJobDetails = mfinoJobDetails;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "jobName", column = @Column(name = "JOB_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "jobGroup", column = @Column(name = "JOB_GROUP", nullable = false, length = 200)),
			@AttributeOverride(name = "jobListener", column = @Column(name = "JOB_LISTENER", nullable = false, length = 200)) })
	public MfinoJobListenersId getId() {
		return this.id;
	}

	public void setId(MfinoJobListenersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "JOB_NAME", referencedColumnName = "JOB_NAME", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "JOB_GROUP", referencedColumnName = "JOB_GROUP", nullable = false, insertable = false, updatable = false) })
	public MfinoJobDetails getMfinoJobDetails() {
		return this.mfinoJobDetails;
	}

	public void setMfinoJobDetails(MfinoJobDetails mfinoJobDetails) {
		this.mfinoJobDetails = mfinoJobDetails;
	}

}
