package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * MfinoSimpleTriggers generated by hbm2java
 */
@Entity
@Table(name = "MFINO_SIMPLE_TRIGGERS")
public class MfinoSimpleTriggers implements java.io.Serializable {

	private MfinoSimpleTriggersId id;
	private MfinoTriggers mfinoTriggers;
	private int repeatCount;
	private long repeatInterval;
	private long timesTriggered;

	public MfinoSimpleTriggers() {
	}

	public MfinoSimpleTriggers(MfinoTriggers mfinoTriggers, int repeatCount,
			long repeatInterval, long timesTriggered) {
		this.mfinoTriggers = mfinoTriggers;
		this.repeatCount = repeatCount;
		this.repeatInterval = repeatInterval;
		this.timesTriggered = timesTriggered;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "triggerName", column = @Column(name = "TRIGGER_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "TRIGGER_GROUP", nullable = false, length = 200)) })
	public MfinoSimpleTriggersId getId() {
		return this.id;
	}

	public void setId(MfinoSimpleTriggersId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public MfinoTriggers getMfinoTriggers() {
		return this.mfinoTriggers;
	}

	public void setMfinoTriggers(MfinoTriggers mfinoTriggers) {
		this.mfinoTriggers = mfinoTriggers;
	}

	@Column(name = "REPEAT_COUNT", nullable = false, precision = 7, scale = 0)
	public int getRepeatCount() {
		return this.repeatCount;
	}

	public void setRepeatCount(int repeatCount) {
		this.repeatCount = repeatCount;
	}

	@Column(name = "REPEAT_INTERVAL", nullable = false, precision = 12, scale = 0)
	public long getRepeatInterval() {
		return this.repeatInterval;
	}

	public void setRepeatInterval(long repeatInterval) {
		this.repeatInterval = repeatInterval;
	}

	@Column(name = "TIMES_TRIGGERED", nullable = false, precision = 10, scale = 0)
	public long getTimesTriggered() {
		return this.timesTriggered;
	}

	public void setTimesTriggered(long timesTriggered) {
		this.timesTriggered = timesTriggered;
	}

}
