package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * MfinoCronTriggers generated by hbm2java
 */
@Entity
@Table(name = "MFINO_CRON_TRIGGERS")
public class MfinoCronTriggers implements java.io.Serializable {

	private MfinoCronTriggersId id;
	private MfinoTriggers mfinoTriggers;
	private String cronExpression;
	private String timeZoneId;

	public MfinoCronTriggers() {
	}

	public MfinoCronTriggers(MfinoTriggers mfinoTriggers, String cronExpression) {
		this.mfinoTriggers = mfinoTriggers;
		this.cronExpression = cronExpression;
	}

	public MfinoCronTriggers(MfinoTriggers mfinoTriggers,
			String cronExpression, String timeZoneId) {
		this.mfinoTriggers = mfinoTriggers;
		this.cronExpression = cronExpression;
		this.timeZoneId = timeZoneId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "triggerName", column = @Column(name = "TRIGGER_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "TRIGGER_GROUP", nullable = false, length = 200)) })
	public MfinoCronTriggersId getId() {
		return this.id;
	}

	public void setId(MfinoCronTriggersId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public MfinoTriggers getMfinoTriggers() {
		return this.mfinoTriggers;
	}

	public void setMfinoTriggers(MfinoTriggers mfinoTriggers) {
		this.mfinoTriggers = mfinoTriggers;
	}

	@Column(name = "CRON_EXPRESSION", nullable = false, length = 120)
	public String getCronExpression() {
		return this.cronExpression;
	}

	public void setCronExpression(String cronExpression) {
		this.cronExpression = cronExpression;
	}

	@Column(name = "TIME_ZONE_ID", length = 80)
	public String getTimeZoneId() {
		return this.timeZoneId;
	}

	public void setTimeZoneId(String timeZoneId) {
		this.timeZoneId = timeZoneId;
	}

}
