package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * MfinoBlobTriggers generated by hbm2java
 */
@Entity
@Table(name = "MFINO_BLOB_TRIGGERS")
public class MfinoBlobTriggers implements java.io.Serializable {

	private MfinoBlobTriggersId id;
	private MfinoTriggers mfinoTriggers;
	private Blob blobData;

	public MfinoBlobTriggers() {
	}

	public MfinoBlobTriggers(MfinoTriggers mfinoTriggers) {
		this.mfinoTriggers = mfinoTriggers;
	}

	public MfinoBlobTriggers(MfinoTriggers mfinoTriggers, Blob blobData) {
		this.mfinoTriggers = mfinoTriggers;
		this.blobData = blobData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "triggerName", column = @Column(name = "TRIGGER_NAME", nullable = false, length = 200)),
			@AttributeOverride(name = "triggerGroup", column = @Column(name = "TRIGGER_GROUP", nullable = false, length = 200)) })
	public MfinoBlobTriggersId getId() {
		return this.id;
	}

	public void setId(MfinoBlobTriggersId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public MfinoTriggers getMfinoTriggers() {
		return this.mfinoTriggers;
	}

	public void setMfinoTriggers(MfinoTriggers mfinoTriggers) {
		this.mfinoTriggers = mfinoTriggers;
	}

	@Column(name = "BLOB_DATA")
	public Blob getBlobData() {
		return this.blobData;
	}

	public void setBlobData(Blob blobData) {
		this.blobData = blobData;
	}

}
