package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MfinoCalendars generated by hbm2java
 */
@Entity
@Table(name = "MFINO_CALENDARS")
public class MfinoCalendars implements java.io.Serializable {

	private String calendarName;
	private Blob calendar;
	private Long id;

	public MfinoCalendars() {
	}

	@Id
	@SequenceGenerator(name = "id_Sequence", sequenceName = "actor_channel_mapping_ID_SEQ")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	public MfinoCalendars(String calendarName, Blob calendar) {
		this.calendarName = calendarName;
		this.calendar = calendar;
	}

	@Id
	@Column(name = "CALENDAR_NAME", unique = true, nullable = false, length = 200)
	public String getCalendarName() {
		return this.calendarName;
	}

	public void setCalendarName(String calendarName) {
		this.calendarName = calendarName;
	}

	@Column(name = "CALENDAR", nullable = false)
	public Blob getCalendar() {
		return this.calendar;
	}

	public void setCalendar(Blob calendar) {
		this.calendar = calendar;
	}

}
