package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MfsBiller generated by hbm2java
 */
@Entity
@Table(name = "MFS_BILLER")
public class MfsBiller implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private MfinoServiceProvider mfinoServiceProvider;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String mfsbillername;
	private String mfsbillercode;
	private String mfsbillertype;
	private Set<MfsbillerPartnerMap> mfsbillerPartnerMaps = new HashSet<MfsbillerPartnerMap>(
			0);
	private Set<IntegrationPartnerMap> integrationPartnerMaps = new HashSet<IntegrationPartnerMap>(
			0);

	public MfsBiller() {
	}

	public MfsBiller(BigDecimal id, MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String mfsbillername,
			String mfsbillercode, String mfsbillertype) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mfsbillername = mfsbillername;
		this.mfsbillercode = mfsbillercode;
		this.mfsbillertype = mfsbillertype;
	}

	public MfsBiller(BigDecimal id, MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String mfsbillername,
			String mfsbillercode, String mfsbillertype,
			Set<MfsbillerPartnerMap> mfsbillerPartnerMaps,
			Set<IntegrationPartnerMap> integrationPartnerMaps) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mfsbillername = mfsbillername;
		this.mfsbillercode = mfsbillercode;
		this.mfsbillertype = mfsbillertype;
		this.mfsbillerPartnerMaps = mfsbillerPartnerMaps;
		this.integrationPartnerMaps = integrationPartnerMaps;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MFSBILLERNAME", nullable = false, length = 1020)
	public String getMfsbillername() {
		return this.mfsbillername;
	}

	public void setMfsbillername(String mfsbillername) {
		this.mfsbillername = mfsbillername;
	}

	@Column(name = "MFSBILLERCODE", nullable = false, length = 1020)
	public String getMfsbillercode() {
		return this.mfsbillercode;
	}

	public void setMfsbillercode(String mfsbillercode) {
		this.mfsbillercode = mfsbillercode;
	}

	@Column(name = "MFSBILLERTYPE", nullable = false, length = 1020)
	public String getMfsbillertype() {
		return this.mfsbillertype;
	}

	public void setMfsbillertype(String mfsbillertype) {
		this.mfsbillertype = mfsbillertype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mfsBiller")
	public Set<MfsbillerPartnerMap> getMfsbillerPartnerMaps() {
		return this.mfsbillerPartnerMaps;
	}

	public void setMfsbillerPartnerMaps(
			Set<MfsbillerPartnerMap> mfsbillerPartnerMaps) {
		this.mfsbillerPartnerMaps = mfsbillerPartnerMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mfsBiller")
	public Set<IntegrationPartnerMap> getIntegrationPartnerMaps() {
		return this.integrationPartnerMaps;
	}

	public void setIntegrationPartnerMaps(
			Set<IntegrationPartnerMap> integrationPartnerMaps) {
		this.integrationPartnerMaps = integrationPartnerMaps;
	}

}
