package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;

/**
 * MfsDenominations generated by hbm2java
 */
@Entity
@Table(name = "MFS_DENOMINATIONS")
public class MFSDenominations extends Base implements java.io.Serializable {

	
	private BigDecimal mfsid;
	private BigDecimal denominationamount;
	private String description;
	private String productcode;

	public MFSDenominations() {
	}

	public MFSDenominations(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal mfsid, BigDecimal denominationamount) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mfsid = mfsid;
		this.denominationamount = denominationamount;
	}

	public MFSDenominations(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal mfsid, BigDecimal denominationamount,
			String description, String productcode) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mfsid = mfsid;
		this.denominationamount = denominationamount;
		this.description = description;
		this.productcode = productcode;
	}

	
	@Column(name = "MFSID", nullable = false, scale = 0)
	public BigDecimal getMfsid() {
		return this.mfsid;
	}

	public void setMfsid(BigDecimal mfsid) {
		this.mfsid = mfsid;
	}

	@Column(name = "DENOMINATIONAMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getDenominationamount() {
		return this.denominationamount;
	}

	public void setDenominationamount(BigDecimal denominationamount) {
		this.denominationamount = denominationamount;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PRODUCTCODE")
	public String getProductcode() {
		return this.productcode;
	}

	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}

}
