package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * MfsLedger generated by hbm2java
 */
@Entity
@Table(name = "MFS_LEDGER")
public class MfsLedger implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal sctlid;
	private BigDecimal commoditytransferid;
	private BigDecimal pocketid;
	private BigDecimal amount;
	private String ledgertype;
	private String ledgerstatus;

	public MfsLedger() {
	}

	public MfsLedger(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid, BigDecimal commoditytransferid,
			BigDecimal pocketid, BigDecimal amount, String ledgertype,
			String ledgerstatus) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.commoditytransferid = commoditytransferid;
		this.pocketid = pocketid;
		this.amount = amount;
		this.ledgertype = ledgertype;
		this.ledgerstatus = ledgerstatus;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SCTLID", nullable = false, scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "COMMODITYTRANSFERID", nullable = false, scale = 0)
	public BigDecimal getCommoditytransferid() {
		return this.commoditytransferid;
	}

	public void setCommoditytransferid(BigDecimal commoditytransferid) {
		this.commoditytransferid = commoditytransferid;
	}

	@Column(name = "POCKETID", nullable = false, scale = 0)
	public BigDecimal getPocketid() {
		return this.pocketid;
	}

	public void setPocketid(BigDecimal pocketid) {
		this.pocketid = pocketid;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "LEDGERTYPE", nullable = false, length = 25)
	public String getLedgertype() {
		return this.ledgertype;
	}

	public void setLedgertype(String ledgertype) {
		this.ledgertype = ledgertype;
	}

	@Column(name = "LEDGERSTATUS", nullable = false, length = 25)
	public String getLedgerstatus() {
		return this.ledgerstatus;
	}

	public void setLedgerstatus(String ledgerstatus) {
		this.ledgerstatus = ledgerstatus;
	}

}
