package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MoneyClearanceGraved generated by hbm2java
 */
@Entity
@Table(name = "MONEY_CLEARANCE_GRAVED", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MDNID", "POCKETID" }))
public class MoneyClearanceGraved implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Pocket pocketByPocketid;
	private ServiceChargeTxnLog serviceChargeTxnLogByRefundsctlid;
	private SubscriberMdn subscriberMdnByRefundmdnid;
	private SubscriberMdn subscriberMdnByMdnid;
	private Pocket pocketByRefundpocketid;
	private ServiceChargeTxnLog serviceChargeTxnLogBySctlid;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal amount;
	private String refundaccountnumber;
	private long mcstatus;

	public MoneyClearanceGraved() {
	}

	public MoneyClearanceGraved(BigDecimal id, Pocket pocketByPocketid,
			SubscriberMdn subscriberMdnByMdnid,
			ServiceChargeTxnLog serviceChargeTxnLogBySctlid,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal amount,
			long mcstatus) {
		this.id = id;
		this.pocketByPocketid = pocketByPocketid;
		this.subscriberMdnByMdnid = subscriberMdnByMdnid;
		this.serviceChargeTxnLogBySctlid = serviceChargeTxnLogBySctlid;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.amount = amount;
		this.mcstatus = mcstatus;
	}

	public MoneyClearanceGraved(BigDecimal id, Pocket pocketByPocketid,
			ServiceChargeTxnLog serviceChargeTxnLogByRefundsctlid,
			SubscriberMdn subscriberMdnByRefundmdnid,
			SubscriberMdn subscriberMdnByMdnid, Pocket pocketByRefundpocketid,
			ServiceChargeTxnLog serviceChargeTxnLogBySctlid,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal amount,
			String refundaccountnumber, long mcstatus) {
		this.id = id;
		this.pocketByPocketid = pocketByPocketid;
		this.serviceChargeTxnLogByRefundsctlid = serviceChargeTxnLogByRefundsctlid;
		this.subscriberMdnByRefundmdnid = subscriberMdnByRefundmdnid;
		this.subscriberMdnByMdnid = subscriberMdnByMdnid;
		this.pocketByRefundpocketid = pocketByRefundpocketid;
		this.serviceChargeTxnLogBySctlid = serviceChargeTxnLogBySctlid;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.amount = amount;
		this.refundaccountnumber = refundaccountnumber;
		this.mcstatus = mcstatus;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETID", nullable = false)
	public Pocket getPocketByPocketid() {
		return this.pocketByPocketid;
	}

	public void setPocketByPocketid(Pocket pocketByPocketid) {
		this.pocketByPocketid = pocketByPocketid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REFUNDSCTLID")
	public ServiceChargeTxnLog getServiceChargeTxnLogByRefundsctlid() {
		return this.serviceChargeTxnLogByRefundsctlid;
	}

	public void setServiceChargeTxnLogByRefundsctlid(
			ServiceChargeTxnLog serviceChargeTxnLogByRefundsctlid) {
		this.serviceChargeTxnLogByRefundsctlid = serviceChargeTxnLogByRefundsctlid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REFUNDMDNID")
	public SubscriberMdn getSubscriberMdnByRefundmdnid() {
		return this.subscriberMdnByRefundmdnid;
	}

	public void setSubscriberMdnByRefundmdnid(
			SubscriberMdn subscriberMdnByRefundmdnid) {
		this.subscriberMdnByRefundmdnid = subscriberMdnByRefundmdnid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDNID", nullable = false)
	public SubscriberMdn getSubscriberMdnByMdnid() {
		return this.subscriberMdnByMdnid;
	}

	public void setSubscriberMdnByMdnid(SubscriberMdn subscriberMdnByMdnid) {
		this.subscriberMdnByMdnid = subscriberMdnByMdnid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REFUNDPOCKETID")
	public Pocket getPocketByRefundpocketid() {
		return this.pocketByRefundpocketid;
	}

	public void setPocketByRefundpocketid(Pocket pocketByRefundpocketid) {
		this.pocketByRefundpocketid = pocketByRefundpocketid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCTLID", nullable = false)
	public ServiceChargeTxnLog getServiceChargeTxnLogBySctlid() {
		return this.serviceChargeTxnLogBySctlid;
	}

	public void setServiceChargeTxnLogBySctlid(
			ServiceChargeTxnLog serviceChargeTxnLogBySctlid) {
		this.serviceChargeTxnLogBySctlid = serviceChargeTxnLogBySctlid;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "REFUNDACCOUNTNUMBER", length = 16)
	public String getRefundaccountnumber() {
		return this.refundaccountnumber;
	}

	public void setRefundaccountnumber(String refundaccountnumber) {
		this.refundaccountnumber = refundaccountnumber;
	}

	@Column(name = "MCSTATUS", nullable = false, precision = 11, scale = 0)
	public long getMcstatus() {
		return this.mcstatus;
	}

	public void setMcstatus(long mcstatus) {
		this.mcstatus = mcstatus;
	}

}
