package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MonthlyBalance generated by hbm2java
 */
@Entity
@Table(name = "MONTHLY_BALANCE", uniqueConstraints = @UniqueConstraint(columnNames = {
		"POCKETID", "MONTH", "YEAR" }))
public class MonthlyBalance extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	public static final String FieldName_Pocket = "pocket";
	public static final String FieldName_Month = "month";
	public static final String FieldName_Year = "year";
	
	private Pocket pocket;
	private String month;
	private long year;
	private BigDecimal averagemonthlybalance;
	private BigDecimal interestcalculated;
	private BigDecimal agentcommissioncalculated;

	public MonthlyBalance() {
	}

	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETID", nullable = false)
	public Pocket getPocket() {
		return this.pocket;
	}

	public void setPocket(Pocket pocket) {
		this.pocket = pocket;
	}

	
	@Column(name = "MONTH", nullable = false, length = 20)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "YEAR", nullable = false, precision = 10, scale = 0)
	public long getYear() {
		return this.year;
	}

	public void setYear(long year) {
		this.year = year;
	}

	@Column(name = "AVERAGEMONTHLYBALANCE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAveragemonthlybalance() {
		return this.averagemonthlybalance;
	}

	public void setAveragemonthlybalance(BigDecimal averagemonthlybalance) {
		this.averagemonthlybalance = averagemonthlybalance;
	}

	@Column(name = "INTERESTCALCULATED", nullable = false, precision = 25, scale = 4)
	public BigDecimal getInterestcalculated() {
		return this.interestcalculated;
	}

	public void setInterestcalculated(BigDecimal interestcalculated) {
		this.interestcalculated = interestcalculated;
	}

	@Column(name = "AGENTCOMMISSIONCALCULATED", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAgentcommissioncalculated() {
		return this.agentcommissioncalculated;
	}

	public void setAgentcommissioncalculated(
			BigDecimal agentcommissioncalculated) {
		this.agentcommissioncalculated = agentcommissioncalculated;
	}

}
