package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import com.mfino.hibernate.Timestamp;

/**
 * NotificationLog generated by hbm2java
 */
@Entity
@Table(name = "NOTIFICATION_LOG")
public class NotificationLog extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	public static final String FieldName_SctlId = "sctlid";
	public static final String FieldName_NotificationCode = "code";
	public static final String FieldName_NotificationMethod = "notificationmethod";
	public static final String FieldName_SourceAddress = "sourceaddress";
	public static final String FieldName_NotificationReceiverType = "notificationreceivertype";
	public static final String FieldName_IsSensitiveData = "issensitivedata";
	
	private BigDecimal sctlid;
	private long code;
	private String text;
	private long notificationmethod;
	private String sourceaddress;
	private long notificationreceivertype;
	private String emailsubject;
	private Short issensitivedata;
	private Set<NlogDetails> nlogDetailses = new HashSet<NlogDetails>(0);

	public NotificationLog() {
	}

	public NotificationLog(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal sctlid, long code, long notificationmethod,
			String sourceaddress, long notificationreceivertype) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.code = code;
		this.notificationmethod = notificationmethod;
		this.sourceaddress = sourceaddress;
		this.notificationreceivertype = notificationreceivertype;
	}

	public NotificationLog(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal sctlid, long code, String text, long notificationmethod,
			String sourceaddress, long notificationreceivertype,
			String emailsubject, Short issensitivedata,
			Set<NlogDetails> nlogDetailses) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.code = code;
		this.text = text;
		this.notificationmethod = notificationmethod;
		this.sourceaddress = sourceaddress;
		this.notificationreceivertype = notificationreceivertype;
		this.emailsubject = emailsubject;
		this.issensitivedata = issensitivedata;
		this.nlogDetailses = nlogDetailses;
	}

	
	@Column(name = "SCTLID", nullable = false, scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "CODE", nullable = false, precision = 11, scale = 0)
	public long getCode() {
		return this.code;
	}

	public void setCode(long code) {
		this.code = code;
	}

	@Column(name = "TEXT", length = 1000)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "NOTIFICATIONMETHOD", nullable = false, precision = 10, scale = 0)
	public long getNotificationmethod() {
		return this.notificationmethod;
	}

	public void setNotificationmethod(long notificationmethod) {
		this.notificationmethod = notificationmethod;
	}

	@Column(name = "SOURCEADDRESS", nullable = false, length = 1020)
	public String getSourceaddress() {
		return this.sourceaddress;
	}

	public void setSourceaddress(String sourceaddress) {
		this.sourceaddress = sourceaddress;
	}

	@Column(name = "NOTIFICATIONRECEIVERTYPE", nullable = false, precision = 10, scale = 0)
	public long getNotificationreceivertype() {
		return this.notificationreceivertype;
	}

	public void setNotificationreceivertype(long notificationreceivertype) {
		this.notificationreceivertype = notificationreceivertype;
	}

	@Column(name = "EMAILSUBJECT", length = 1020)
	public String getEmailsubject() {
		return this.emailsubject;
	}

	public void setEmailsubject(String emailsubject) {
		this.emailsubject = emailsubject;
	}

	@Column(name = "ISSENSITIVEDATA", precision = 3, scale = 0)
	public Short getIssensitivedata() {
		return this.issensitivedata;
	}

	public void setIssensitivedata(Short issensitivedata) {
		this.issensitivedata = issensitivedata;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationLog")
	public Set<NlogDetails> getNlogDetailses() {
		return this.nlogDetailses;
	}

	public void setNlogDetailses(Set<NlogDetails> nlogDetailses) {
		this.nlogDetailses = nlogDetailses;
	}

}
