package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NotificationLog generated by hbm2java
 */
@Entity
@Table(name = "NOTIFICATION_LOG")
public class NotificationLog extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	public static final String FieldName_SctlId = "sctlid";
	public static final String FieldName_NotificationCode = "code";
	public static final String FieldName_NotificationMethod = "notificationmethod";
	public static final String FieldName_SourceAddress = "sourceaddress";
	public static final String FieldName_NotificationReceiverType = "notificationreceivertype";
	public static final String FieldName_IsSensitiveData = "issensitivedata";
	
	private Long sctlid;
	private Integer code;
	private String text;
	private Integer notificationmethod;
	private String sourceaddress;
	private Integer notificationreceivertype;
	private String emailsubject;
	private Boolean issensitivedata;
	private Long id;
	private Set<NlogDetails> nlogDetailses = new HashSet<NlogDetails>(0);

	public NotificationLog() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "notification_log_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@Column(name = "SCTLID")
	public Long getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(Long sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "CODE")
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "TEXT")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "NOTIFICATIONMETHOD")
	public Integer getNotificationmethod() {
		return this.notificationmethod;
	}

	public void setNotificationmethod(Integer notificationmethod) {
		this.notificationmethod = notificationmethod;
	}

	@Column(name = "SOURCEADDRESS")
	public String getSourceaddress() {
		return this.sourceaddress;
	}

	public void setSourceaddress(String sourceaddress) {
		this.sourceaddress = sourceaddress;
	}

	@Column(name = "NOTIFICATIONRECEIVERTYPE")
	public Integer getNotificationreceivertype() {
		return this.notificationreceivertype;
	}

	public void setNotificationreceivertype(Integer notificationreceivertype) {
		this.notificationreceivertype = notificationreceivertype;
	}

	@Column(name = "EMAILSUBJECT")
	public String getEmailsubject() {
		return this.emailsubject;
	}

	public void setEmailsubject(String emailsubject) {
		this.emailsubject = emailsubject;
	}

	@Column(name = "ISSENSITIVEDATA")
	public Boolean getIssensitivedata() {
		return this.issensitivedata;
	}

	public void setIssensitivedata(Boolean issensitivedata) {
		this.issensitivedata = issensitivedata;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationLog")
	public Set<NlogDetails> getNlogDetailses() {
		return this.nlogDetailses;
	}

	public void setNlogDetailses(Set<NlogDetails> nlogDetailses) {
		this.nlogDetailses = nlogDetailses;
	}

}
