package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Type;

import com.mfino.hibernate.Timestamp;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "NOTIFICATION", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MSPID", "CODE", "NOTIFICATIONMETHOD", "LANGUAGE", "COMPANYID" }))
public class Notification extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String FieldName_Language = "language";
	public static final String FieldName_NotificationCode = "code";
	public static final String FieldName_NotificationMethod = "notificationmethod";
	public static final String FieldName_NotificationText = "text";
	public static final String FieldName_NotificationCodeName = "codename";
	public static final String FieldName_Company = "company";
	
	
	private MfinoServiceProvider mfinoServiceProvider;
	private Company company;
	private Integer code;
	private String codename;
	private Integer notificationmethod;
	private String text;
	private String stkml;
	private Integer language;
	private Integer status;
	private Timestamp statustime;
	private String accesscode;
	private String smsnotificationcode;
	private Short isactive;
	private Long id;

	public Notification() {
	}
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "notification_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "CODE", nullable = false, precision = 10, scale = 0)
	public Integer getCode() {
		return this.code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	@Column(name = "CODENAME", nullable = false, length = 1020)
	public String getCodename() {
		return this.codename;
	}

	public void setCodename(String codename) {
		this.codename = codename;
	}

	@Column(name = "NOTIFICATIONMETHOD", nullable = false, precision = 10, scale = 0)
	public Integer getNotificationmethod() {
		return this.notificationmethod;
	}

	public void setNotificationmethod(Integer notificationmethod) {
		this.notificationmethod = notificationmethod;
	}

	@Column(name = "TEXT", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "STKML")
	public String getStkml() {
		return this.stkml;
	}

	public void setStkml(String stkml) {
		this.stkml = stkml;
	}

	@Column(name = "LANGUAGE", nullable = false, precision = 10, scale = 0)
	public Integer getLanguage() {
		return this.language;
	}

	public void setLanguage(Integer language) {
		this.language = language;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Type(type = "userDefinedTimeStamp")
	@Column(name = "STATUSTIME", nullable = false)
	public Timestamp getStatustime() {
		return this.statustime;
	}

	public void setStatustime(Timestamp statustime) {
		this.statustime = statustime;
	}

	@Column(name = "ACCESSCODE", length = 1020)
	public String getAccesscode() {
		return this.accesscode;
	}

	public void setAccesscode(String accesscode) {
		this.accesscode = accesscode;
	}

	@Column(name = "SMSNOTIFICATIONCODE", length = 1020)
	public String getSmsnotificationcode() {
		return this.smsnotificationcode;
	}

	public void setSmsnotificationcode(String smsnotificationcode) {
		this.smsnotificationcode = smsnotificationcode;
	}

	@Column(name = "ISACTIVE", precision = 3, scale = 0)
	public Short getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Short isactive) {
		this.isactive = isactive;
	}

}
