package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * OfflineReportReceiver generated by hbm2java
 */
@Entity
@Table(name = "OFFLINE_REPORT_RECEIVER")
public class OfflineReportReceiver  extends Base implements java.io.Serializable {

	
	private OfflineReport offlineReport;
	private String email;
	private Long id;

	public OfflineReportReceiver() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "offline_report_receiver_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPORTID", nullable = false)
	public OfflineReport getOfflineReport() {
		return this.offlineReport;
	}

	public void setOfflineReport(OfflineReport offlineReport) {
		this.offlineReport = offlineReport;
	}

	

	@Column(name = "EMAIL", nullable = false, length = 1020)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
