package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.mfino.hibernate.Timestamp;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name = "PARTNER", uniqueConstraints = @UniqueConstraint(columnNames = "TRADENAME"))
public class Partner extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_User = "mfinoUser";
	public static final String FieldName_PartnerServicesFromPartnerID = "partnerServicesesForPartnerid";
	public static final String FieldName_BusinessPartnerType = "businesspartnertype";
	public static final String FieldName_TradeName = "tradename";
	public static final String FieldName_AuthorizedEmail = "authorizedemail";
	public static final String FieldName_Subscriber = "subscriber";
	public static final String FieldName_PartnerCode = "partnercode";
	public static final String FieldName_BranchCode = "branchcode";
	
	private Address addressByMerchantaddressid;
	private Address addressByFranchiseoutletaddressid;
	private MfinoUser mfinoUser;
	private Subscriber subscriber;
	private MfinoServiceProvider mfinoServiceProvider;
	private String partnercode;
	private long partnerstatus;
	private String tradename;
	private String typeoforganization;
	private String faxnumber;
	private String website;
	private String authorizedrepresentative;
	private String representativename;
	private String designation;
	private String franchisephonenumber;
	private String classification;
	private Long numberofoutlets;
	private String industryclassification;
	private Long yearestablished;
	private String authorizedfaxnumber;
	private String authorizedemail;
	private Long businesspartnertype;
	private String branchcode;
	private Long branchsequence;
	private String accountnumberofbanksinarmas;
	private String companyemailid;
	private String closecomments;
	private BigDecimal closeacctstatus;
	private String closeacctapprovedby;
	private Timestamp closeaccttime;
	private String closeapprovercomments;
	private Set<ChargeDefinition> chargeDefinitions = new HashSet<ChargeDefinition>(
			0);
	private Set<PartnerServices> partnerServicesesForParentid = new HashSet<PartnerServices>(
			0);
	private Set<SctlSettlementMap> sctlSettlementMaps = new HashSet<SctlSettlementMap>(
			0);
	private Set<PartnerServices> partnerServicesesForServiceproviderid = new HashSet<PartnerServices>(
			0);
	private Set<TransactionRule> transactionRules = new HashSet<TransactionRule>(
			0);
	private Set<SharePartner> sharePartners = new HashSet<SharePartner>(0);
	private Set<PartnerServices> partnerServicesesForPartnerid = new HashSet<PartnerServices>(
			0);
	private Set<SettlementTemplate> settlementTemplates = new HashSet<SettlementTemplate>(
			0);
	private Set<TxnAmountDstrbLog> txnAmountDstrbLogs = new HashSet<TxnAmountDstrbLog>(
			0);
	private Set<IntegrationPartnerMap> integrationPartnerMaps = new HashSet<IntegrationPartnerMap>(
			0);
	private Set<ServiceDefualtConfig> serviceDefualtConfigs = new HashSet<ServiceDefualtConfig>(
			0);
	private Set<MfsbillerPartnerMap> mfsbillerPartnerMaps = new HashSet<MfsbillerPartnerMap>(
			0);

	public Partner() {
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MERCHANTADDRESSID")
	public Address getAddressByMerchantaddressid() {
		return this.addressByMerchantaddressid;
	}

	public void setAddressByMerchantaddressid(Address addressByMerchantaddressid) {
		this.addressByMerchantaddressid = addressByMerchantaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FRANCHISEOUTLETADDRESSID")
	public Address getAddressByFranchiseoutletaddressid() {
		return this.addressByFranchiseoutletaddressid;
	}

	public void setAddressByFranchiseoutletaddressid(
			Address addressByFranchiseoutletaddressid) {
		this.addressByFranchiseoutletaddressid = addressByFranchiseoutletaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID", nullable = false)
	public MfinoUser getMfinoUser() {
		return this.mfinoUser;
	}

	public void setMfinoUser(MfinoUser mfinoUser) {
		this.mfinoUser = mfinoUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERID", nullable = false)
	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	
	@Column(name = "PARTNERCODE", length = 1020)
	public String getPartnercode() {
		return this.partnercode;
	}

	public void setPartnercode(String partnercode) {
		this.partnercode = partnercode;
	}

	@Column(name = "PARTNERSTATUS", nullable = false, precision = 10, scale = 0)
	public long getPartnerstatus() {
		return this.partnerstatus;
	}

	public void setPartnerstatus(long partnerstatus) {
		this.partnerstatus = partnerstatus;
	}

	@Column(name = "TRADENAME", unique = true, length = 1020)
	public String getTradename() {
		return this.tradename;
	}

	public void setTradename(String tradename) {
		this.tradename = tradename;
	}

	@Column(name = "TYPEOFORGANIZATION", length = 1020)
	public String getTypeoforganization() {
		return this.typeoforganization;
	}

	public void setTypeoforganization(String typeoforganization) {
		this.typeoforganization = typeoforganization;
	}

	@Column(name = "FAXNUMBER", length = 1020)
	public String getFaxnumber() {
		return this.faxnumber;
	}

	public void setFaxnumber(String faxnumber) {
		this.faxnumber = faxnumber;
	}

	@Column(name = "WEBSITE", length = 1020)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "AUTHORIZEDREPRESENTATIVE", length = 1020)
	public String getAuthorizedrepresentative() {
		return this.authorizedrepresentative;
	}

	public void setAuthorizedrepresentative(String authorizedrepresentative) {
		this.authorizedrepresentative = authorizedrepresentative;
	}

	@Column(name = "REPRESENTATIVENAME", length = 1020)
	public String getRepresentativename() {
		return this.representativename;
	}

	public void setRepresentativename(String representativename) {
		this.representativename = representativename;
	}

	@Column(name = "DESIGNATION", length = 1020)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "FRANCHISEPHONENUMBER", length = 1020)
	public String getFranchisephonenumber() {
		return this.franchisephonenumber;
	}

	public void setFranchisephonenumber(String franchisephonenumber) {
		this.franchisephonenumber = franchisephonenumber;
	}

	@Column(name = "CLASSIFICATION", length = 1020)
	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	@Column(name = "NUMBEROFOUTLETS", precision = 10, scale = 0)
	public Long getNumberofoutlets() {
		return this.numberofoutlets;
	}

	public void setNumberofoutlets(Long numberofoutlets) {
		this.numberofoutlets = numberofoutlets;
	}

	@Column(name = "INDUSTRYCLASSIFICATION", length = 1020)
	public String getIndustryclassification() {
		return this.industryclassification;
	}

	public void setIndustryclassification(String industryclassification) {
		this.industryclassification = industryclassification;
	}

	@Column(name = "YEARESTABLISHED", precision = 10, scale = 0)
	public Long getYearestablished() {
		return this.yearestablished;
	}

	public void setYearestablished(Long yearestablished) {
		this.yearestablished = yearestablished;
	}

	@Column(name = "AUTHORIZEDFAXNUMBER", length = 1020)
	public String getAuthorizedfaxnumber() {
		return this.authorizedfaxnumber;
	}

	public void setAuthorizedfaxnumber(String authorizedfaxnumber) {
		this.authorizedfaxnumber = authorizedfaxnumber;
	}

	@Column(name = "AUTHORIZEDEMAIL", length = 1020)
	public String getAuthorizedemail() {
		return this.authorizedemail;
	}

	public void setAuthorizedemail(String authorizedemail) {
		this.authorizedemail = authorizedemail;
	}

	@Column(name = "BUSINESSPARTNERTYPE", precision = 10, scale = 0)
	public Long getBusinesspartnertype() {
		return this.businesspartnertype;
	}

	public void setBusinesspartnertype(Long businesspartnertype) {
		this.businesspartnertype = businesspartnertype;
	}

	@Column(name = "BRANCHCODE")
	public String getBranchcode() {
		return this.branchcode;
	}

	public void setBranchcode(String branchcode) {
		this.branchcode = branchcode;
	}

	@Column(name = "BRANCHSEQUENCE", precision = 10, scale = 0)
	public Long getBranchsequence() {
		return this.branchsequence;
	}

	public void setBranchsequence(Long branchsequence) {
		this.branchsequence = branchsequence;
	}

	@Column(name = "ACCOUNTNUMBEROFBANKSINARMAS")
	public String getAccountnumberofbanksinarmas() {
		return this.accountnumberofbanksinarmas;
	}

	public void setAccountnumberofbanksinarmas(
			String accountnumberofbanksinarmas) {
		this.accountnumberofbanksinarmas = accountnumberofbanksinarmas;
	}

	@Column(name = "COMPANYEMAILID")
	public String getCompanyemailid() {
		return this.companyemailid;
	}

	public void setCompanyemailid(String companyemailid) {
		this.companyemailid = companyemailid;
	}

	@Column(name = "CLOSECOMMENTS", length = 512)
	public String getClosecomments() {
		return this.closecomments;
	}

	public void setClosecomments(String closecomments) {
		this.closecomments = closecomments;
	}

	@Column(name = "CLOSEACCTSTATUS", precision = 22, scale = 0)
	public BigDecimal getCloseacctstatus() {
		return this.closeacctstatus;
	}

	public void setCloseacctstatus(BigDecimal closeacctstatus) {
		this.closeacctstatus = closeacctstatus;
	}

	@Column(name = "CLOSEACCTAPPROVEDBY")
	public String getCloseacctapprovedby() {
		return this.closeacctapprovedby;
	}

	public void setCloseacctapprovedby(String closeacctapprovedby) {
		this.closeacctapprovedby = closeacctapprovedby;
	}

	@Column(name = "CLOSEACCTTIME")
	public Timestamp getCloseaccttime() {
		return this.closeaccttime;
	}

	public void setCloseaccttime(Timestamp closeaccttime) {
		this.closeaccttime = closeaccttime;
	}

	@Column(name = "CLOSEAPPROVERCOMMENTS")
	public String getCloseapprovercomments() {
		return this.closeapprovercomments;
	}

	public void setCloseapprovercomments(String closeapprovercomments) {
		this.closeapprovercomments = closeapprovercomments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<ChargeDefinition> getChargeDefinitions() {
		return this.chargeDefinitions;
	}

	public void setChargeDefinitions(Set<ChargeDefinition> chargeDefinitions) {
		this.chargeDefinitions = chargeDefinitions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partnerByParentid")
	public Set<PartnerServices> getPartnerServicesesForParentid() {
		return this.partnerServicesesForParentid;
	}

	public void setPartnerServicesesForParentid(
			Set<PartnerServices> partnerServicesesForParentid) {
		this.partnerServicesesForParentid = partnerServicesesForParentid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<SctlSettlementMap> getSctlSettlementMaps() {
		return this.sctlSettlementMaps;
	}

	public void setSctlSettlementMaps(Set<SctlSettlementMap> sctlSettlementMaps) {
		this.sctlSettlementMaps = sctlSettlementMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partnerByServiceproviderid")
	public Set<PartnerServices> getPartnerServicesesForServiceproviderid() {
		return this.partnerServicesesForServiceproviderid;
	}

	public void setPartnerServicesesForServiceproviderid(
			Set<PartnerServices> partnerServicesesForServiceproviderid) {
		this.partnerServicesesForServiceproviderid = partnerServicesesForServiceproviderid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<TransactionRule> getTransactionRules() {
		return this.transactionRules;
	}

	public void setTransactionRules(Set<TransactionRule> transactionRules) {
		this.transactionRules = transactionRules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<SharePartner> getSharePartners() {
		return this.sharePartners;
	}

	public void setSharePartners(Set<SharePartner> sharePartners) {
		this.sharePartners = sharePartners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partnerByPartnerid")
	public Set<PartnerServices> getPartnerServicesesForPartnerid() {
		return this.partnerServicesesForPartnerid;
	}

	public void setPartnerServicesesForPartnerid(
			Set<PartnerServices> partnerServicesesForPartnerid) {
		this.partnerServicesesForPartnerid = partnerServicesesForPartnerid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<SettlementTemplate> getSettlementTemplates() {
		return this.settlementTemplates;
	}

	public void setSettlementTemplates(
			Set<SettlementTemplate> settlementTemplates) {
		this.settlementTemplates = settlementTemplates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<TxnAmountDstrbLog> getTxnAmountDstrbLogs() {
		return this.txnAmountDstrbLogs;
	}

	public void setTxnAmountDstrbLogs(Set<TxnAmountDstrbLog> txnAmountDstrbLogs) {
		this.txnAmountDstrbLogs = txnAmountDstrbLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<IntegrationPartnerMap> getIntegrationPartnerMaps() {
		return this.integrationPartnerMaps;
	}

	public void setIntegrationPartnerMaps(
			Set<IntegrationPartnerMap> integrationPartnerMaps) {
		this.integrationPartnerMaps = integrationPartnerMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<ServiceDefualtConfig> getServiceDefualtConfigs() {
		return this.serviceDefualtConfigs;
	}

	public void setServiceDefualtConfigs(
			Set<ServiceDefualtConfig> serviceDefualtConfigs) {
		this.serviceDefualtConfigs = serviceDefualtConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partner")
	public Set<MfsbillerPartnerMap> getMfsbillerPartnerMaps() {
		return this.mfsbillerPartnerMaps;
	}

	public void setMfsbillerPartnerMaps(
			Set<MfsbillerPartnerMap> mfsbillerPartnerMaps) {
		this.mfsbillerPartnerMaps = mfsbillerPartnerMaps;
	}

}
