package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * PartnerServices generated by hbm2java
 */
@Entity
@Table(name = "PARTNER_SERVICES")
public class PartnerServices implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Partner partnerByPartnerid;
	private Service service;
	private Partner partnerByParentid;
	private Pocket pocketByDestpocketid;
	private DistributionChainTemp distributionChainTemp;
	private MfinoServiceProvider mfinoServiceProvider;
	private Partner partnerByServiceproviderid;
	private Pocket pocketBySourcepocket;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private Long pslevel;
	private long status;
	private BigDecimal collectorpocket;
	private Long isservicechargeshare;
	private Set<ServiceSettlementCfg> serviceSettlementCfgs = new HashSet<ServiceSettlementCfg>(
			0);

	public PartnerServices() {
	}

	public PartnerServices(BigDecimal id, Partner partnerByPartnerid,
			Service service, MfinoServiceProvider mfinoServiceProvider,
			Partner partnerByServiceproviderid, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			long status) {
		this.id = id;
		this.partnerByPartnerid = partnerByPartnerid;
		this.service = service;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.partnerByServiceproviderid = partnerByServiceproviderid;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.status = status;
	}

	public PartnerServices(BigDecimal id, Partner partnerByPartnerid,
			Service service, Partner partnerByParentid,
			Pocket pocketByDestpocketid,
			DistributionChainTemp distributionChainTemp,
			MfinoServiceProvider mfinoServiceProvider,
			Partner partnerByServiceproviderid, Pocket pocketBySourcepocket,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, Long pslevel,
			long status, BigDecimal collectorpocket, Long isservicechargeshare,
			Set<ServiceSettlementCfg> serviceSettlementCfgs) {
		this.id = id;
		this.partnerByPartnerid = partnerByPartnerid;
		this.service = service;
		this.partnerByParentid = partnerByParentid;
		this.pocketByDestpocketid = pocketByDestpocketid;
		this.distributionChainTemp = distributionChainTemp;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.partnerByServiceproviderid = partnerByServiceproviderid;
		this.pocketBySourcepocket = pocketBySourcepocket;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.pslevel = pslevel;
		this.status = status;
		this.collectorpocket = collectorpocket;
		this.isservicechargeshare = isservicechargeshare;
		this.serviceSettlementCfgs = serviceSettlementCfgs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARTNERID", nullable = false)
	public Partner getPartnerByPartnerid() {
		return this.partnerByPartnerid;
	}

	public void setPartnerByPartnerid(Partner partnerByPartnerid) {
		this.partnerByPartnerid = partnerByPartnerid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARENTID")
	public Partner getPartnerByParentid() {
		return this.partnerByParentid;
	}

	public void setPartnerByParentid(Partner partnerByParentid) {
		this.partnerByParentid = partnerByParentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DESTPOCKETID")
	public Pocket getPocketByDestpocketid() {
		return this.pocketByDestpocketid;
	}

	public void setPocketByDestpocketid(Pocket pocketByDestpocketid) {
		this.pocketByDestpocketid = pocketByDestpocketid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISTRIBUTIONCHAINTEMPLATEID")
	public DistributionChainTemp getDistributionChainTemp() {
		return this.distributionChainTemp;
	}

	public void setDistributionChainTemp(
			DistributionChainTemp distributionChainTemp) {
		this.distributionChainTemp = distributionChainTemp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEPROVIDERID", nullable = false)
	public Partner getPartnerByServiceproviderid() {
		return this.partnerByServiceproviderid;
	}

	public void setPartnerByServiceproviderid(Partner partnerByServiceproviderid) {
		this.partnerByServiceproviderid = partnerByServiceproviderid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOURCEPOCKET")
	public Pocket getPocketBySourcepocket() {
		return this.pocketBySourcepocket;
	}

	public void setPocketBySourcepocket(Pocket pocketBySourcepocket) {
		this.pocketBySourcepocket = pocketBySourcepocket;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "PSLEVEL", precision = 10, scale = 0)
	public Long getPslevel() {
		return this.pslevel;
	}

	public void setPslevel(Long pslevel) {
		this.pslevel = pslevel;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "COLLECTORPOCKET", scale = 0)
	public BigDecimal getCollectorpocket() {
		return this.collectorpocket;
	}

	public void setCollectorpocket(BigDecimal collectorpocket) {
		this.collectorpocket = collectorpocket;
	}

	@Column(name = "ISSERVICECHARGESHARE", precision = 10, scale = 0)
	public Long getIsservicechargeshare() {
		return this.isservicechargeshare;
	}

	public void setIsservicechargeshare(Long isservicechargeshare) {
		this.isservicechargeshare = isservicechargeshare;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partnerServices")
	public Set<ServiceSettlementCfg> getServiceSettlementCfgs() {
		return this.serviceSettlementCfgs;
	}

	public void setServiceSettlementCfgs(
			Set<ServiceSettlementCfg> serviceSettlementCfgs) {
		this.serviceSettlementCfgs = serviceSettlementCfgs;
	}

}
