package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.mfino.hibernate.Timestamp;

/**
 * PartnerRestrictions generated by hbm2java
 */
@Entity
@Table(name = "PARTNER_RESTRICTIONS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DCTID", "PARTNERID", "TRANSACTIONTYPEID", "RELATIONSHIPTYPE" }))
public class PartnerRestrictions extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	public static final String FieldName_DistributionChainTemplateByDCTID = "dctid";
	public static final String FieldName_Partner = "partnerid";
	public static final String FieldName_TransactionType = "transactiontypeid";
	public static final String FieldName_RelationShipType = "relationshiptype";
	public static final String FieldName_IsAllowed = "isallowed";
	
	private long dctid;
	private long partnerid;
	private Long transactiontypeid;
	private Long relationshiptype;
	private Short isallowed;
	private Short isvalid;

	public PartnerRestrictions() {
	}

	
	
	@Column(name = "DCTID", nullable = false, precision = 10, scale = 0)
	public long getDctid() {
		return this.dctid;
	}

	public void setDctid(long dctid) {
		this.dctid = dctid;
	}

	@Column(name = "PARTNERID", nullable = false, precision = 10, scale = 0)
	public long getPartnerid() {
		return this.partnerid;
	}

	public void setPartnerid(long partnerid) {
		this.partnerid = partnerid;
	}

	@Column(name = "TRANSACTIONTYPEID", precision = 10, scale = 0)
	public Long getTransactiontypeid() {
		return this.transactiontypeid;
	}

	public void setTransactiontypeid(Long transactiontypeid) {
		this.transactiontypeid = transactiontypeid;
	}

	@Column(name = "RELATIONSHIPTYPE", precision = 10, scale = 0)
	public Long getRelationshiptype() {
		return this.relationshiptype;
	}

	public void setRelationshiptype(Long relationshiptype) {
		this.relationshiptype = relationshiptype;
	}

	@Column(name = "ISALLOWED", precision = 3, scale = 0)
	public Short getIsallowed() {
		return this.isallowed;
	}

	public void setIsallowed(Short isallowed) {
		this.isallowed = isallowed;
	}

	@Column(name = "ISVALID", precision = 3, scale = 0)
	public Short getIsvalid() {
		return this.isvalid;
	}

	public void setIsvalid(Short isvalid) {
		this.isvalid = isvalid;
	}

}
