package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PartnerRestrictions generated by hbm2java
 */
@Entity
@Table(name = "PARTNER_RESTRICTIONS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DCTID", "PARTNERID", "TRANSACTIONTYPEID", "RELATIONSHIPTYPE" }))
public class PartnerRestrictions implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private long dctid;
	private long partnerid;
	private Long transactiontypeid;
	private Long relationshiptype;
	private Short isallowed;
	private Short isvalid;

	public PartnerRestrictions() {
	}

	public PartnerRestrictions(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			long dctid, long partnerid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.dctid = dctid;
		this.partnerid = partnerid;
	}

	public PartnerRestrictions(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			long dctid, long partnerid, Long transactiontypeid,
			Long relationshiptype, Short isallowed, Short isvalid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.dctid = dctid;
		this.partnerid = partnerid;
		this.transactiontypeid = transactiontypeid;
		this.relationshiptype = relationshiptype;
		this.isallowed = isallowed;
		this.isvalid = isvalid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "DCTID", nullable = false, precision = 10, scale = 0)
	public long getDctid() {
		return this.dctid;
	}

	public void setDctid(long dctid) {
		this.dctid = dctid;
	}

	@Column(name = "PARTNERID", nullable = false, precision = 10, scale = 0)
	public long getPartnerid() {
		return this.partnerid;
	}

	public void setPartnerid(long partnerid) {
		this.partnerid = partnerid;
	}

	@Column(name = "TRANSACTIONTYPEID", precision = 10, scale = 0)
	public Long getTransactiontypeid() {
		return this.transactiontypeid;
	}

	public void setTransactiontypeid(Long transactiontypeid) {
		this.transactiontypeid = transactiontypeid;
	}

	@Column(name = "RELATIONSHIPTYPE", precision = 10, scale = 0)
	public Long getRelationshiptype() {
		return this.relationshiptype;
	}

	public void setRelationshiptype(Long relationshiptype) {
		this.relationshiptype = relationshiptype;
	}

	@Column(name = "ISALLOWED", precision = 3, scale = 0)
	public Short getIsallowed() {
		return this.isallowed;
	}

	public void setIsallowed(Short isallowed) {
		this.isallowed = isallowed;
	}

	@Column(name = "ISVALID", precision = 3, scale = 0)
	public Short getIsvalid() {
		return this.isvalid;
	}

	public void setIsvalid(Short isvalid) {
		this.isvalid = isvalid;
	}

}
