package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;


/**
 * PendingCommodityTransfer generated by hbm2java
 */
@Entity
@Table(name = "PENDING_COMMODITY_TRANSFER", uniqueConstraints = @UniqueConstraint(columnNames = {
		"BULKUPLOADID", "BULKUPLOADLINENUMBER" }))
public class PendingCommodityTransfer extends Base implements java.io.Serializable {

	
	private SubscriberMdn subscriberMdn;
	private TransactionLog transactionLog;
	private CreditCardTransaction creditCardTransaction;
	private LetterOfPurchase letterOfPurchase;
	private Subscriber subscriber;
	private mFinoServiceProvider mfinoServiceProvider;
	private Company company;
	private DistributionChainLvl distributionChainLvl;
	private Pocket pocket;
	private long msgtype;
	private Long uicategory;
	private long transferstatus;
	private Long transferfailurereason;
	private Long notificationcode;
	private Timestamp starttime;
	private Timestamp endtime;
	private long expirationtimeout;
	private String sourceip;
	private String sourcereferenceid;
	private String sourceterminalid;
	private String sourcemdn;
	private Long levelpermissions;
	private String sourcesubscribername;
	private Long sourcepocketallowance;
	private long sourcepockettype;
	private String sourcepocketbalance;
	private String sourcecardpan;
	private String sourcemessage;
	private String destmdn;
	private BigDecimal destmdnid;
	private BigDecimal destsubscriberid;
	private String destsubscribername;
	private Long destpocketallowance;
	private Long destpockettype;
	private BigDecimal destpocketid;
	private String destpocketbalance;
	private String destbankaccountname;
	private String destcardpan;
	private Long billingtype;
	private BigDecimal amount;
	private BigDecimal charges;
	private BigDecimal taxamount;
	private long commodity;
	private String buckettype;
	private long sourceapplication;
	private String servletpath;
	private String currency;
	private Long bankcode;
	private Long operatorcode;
	private Timestamp operatorresponsetime;
	private Long operatorresponsecode;
	private String operatorrejectreason;
	private String operatorerrortext;
	private String operatorauthorizationcode;
	private Timestamp operatorreversalresponsetime;
	private Long operatorreversalresponsecode;
	private String operatorreversalrejectreason;
	private String operatorreversalerrortext;
	private Long operatorreversalcount;
	private Timestamp operatorlastreversaltime;
	private BigDecimal topupperiod;
	private String bankretrievalreferencenumber;
	private String banksystemtraceauditnumber;
	private Timestamp bankresponsetime;
	private Long bankresponsecode;
	private String bankrejectreason;
	private String bankerrortext;
	private String bankauthorizationcode;
	private Timestamp bankreversalresponsetime;
	private Long bankreversalresponsecode;
	private String bankreversalrejectreason;
	private String bankreversalerrortext;
	private String bankreversalauthorizationcode;
	private Long reversalcount;
	private Timestamp lastreversaltime;
	private Long csraction;
	private Timestamp csractiontime;
	private BigDecimal csruserid;
	private String csrusername;
	private String csrcomment;
	private String iso8583Processingcode;
	private String iso8583Primaryaccountnumber;
	private String iso8583Systemtraceauditnumber;
	private String iso8583Localtxntimehhmmss;
	private String iso8583Merchanttype;
	private Long iso8583Acquiringinstidcode;
	private String iso8583Retrievalreferencenum;
	private String iso8583Cardacceptoridcode;
	private String iso8583Variant;
	private String iso8583Responsecode;
	private BigDecimal bulkuploadid;
	private Long bulkuploadlinenumber;
	private String copytopermanenterror;
	private String webclientip;
	private String operatorrrn;
	private String operatorstan;
	private String productindicatorcode;
	private BigDecimal units;
	private BigDecimal denomination;
	private BigDecimal transactionchargeid;
	private Short ispartofsharedupchain;
	private Timestamp lastupdatetime;
	private String updatedby;
	private Timestamp createtime;
	private String createdby;
	private short localbalancerevertrequired;
	private short localrevertrequired;
	private short bankreversalrequired;
	private short operatoractionrequired;

	public PendingCommodityTransfer() {
	}

	public PendingCommodityTransfer(BigDecimal id, SubscriberMdn subscriberMdn,
			TransactionLog transactionLog, Subscriber subscriber,
			mFinoServiceProvider mfinoServiceProvider, Company company,
			Pocket pocket, long msgtype, long transferstatus,
			Timestamp starttime, long expirationtimeout, String sourcemdn,
			long sourcepockettype, BigDecimal amount, BigDecimal charges,
			long commodity, long sourceapplication, String currency,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby,
			short localbalancerevertrequired, short localrevertrequired,
			short bankreversalrequired, short operatoractionrequired) {
		this.id = id;
		this.subscriberMdn = subscriberMdn;
		this.transactionLog = transactionLog;
		this.subscriber = subscriber;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.company = company;
		this.pocket = pocket;
		this.msgtype = msgtype;
		this.transferstatus = transferstatus;
		this.starttime = starttime;
		this.expirationtimeout = expirationtimeout;
		this.sourcemdn = sourcemdn;
		this.sourcepockettype = sourcepockettype;
		this.amount = amount;
		this.charges = charges;
		this.commodity = commodity;
		this.sourceapplication = sourceapplication;
		this.currency = currency;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.localbalancerevertrequired = localbalancerevertrequired;
		this.localrevertrequired = localrevertrequired;
		this.bankreversalrequired = bankreversalrequired;
		this.operatoractionrequired = operatoractionrequired;
	}

	public PendingCommodityTransfer(BigDecimal id, SubscriberMdn subscriberMdn,
			TransactionLog transactionLog,
			CreditCardTransaction creditCardTransaction,
			LetterOfPurchase letterOfPurchase, Subscriber subscriber,
			mFinoServiceProvider mfinoServiceProvider, Company company,
			DistributionChainLvl distributionChainLvl, Pocket pocket,
			long msgtype, Long uicategory, long transferstatus,
			Long transferfailurereason, Long notificationcode,
			Timestamp starttime, Timestamp endtime,
			long expirationtimeout, String sourceip, String sourcereferenceid,
			String sourceterminalid, String sourcemdn, Long levelpermissions,
			String sourcesubscribername, Long sourcepocketallowance,
			long sourcepockettype, String sourcepocketbalance,
			String sourcecardpan, String sourcemessage, String destmdn,
			BigDecimal destmdnid, BigDecimal destsubscriberid,
			String destsubscribername, Long destpocketallowance,
			Long destpockettype, BigDecimal destpocketid,
			String destpocketbalance, String destbankaccountname,
			String destcardpan, Long billingtype, BigDecimal amount,
			BigDecimal charges, BigDecimal taxamount, long commodity,
			String buckettype, long sourceapplication, String servletpath,
			String currency, Long bankcode, Long operatorcode,
			Timestamp operatorresponsetime, Long operatorresponsecode,
			String operatorrejectreason, String operatorerrortext,
			String operatorauthorizationcode,
			Timestamp operatorreversalresponsetime,
			Long operatorreversalresponsecode,
			String operatorreversalrejectreason,
			String operatorreversalerrortext, Long operatorreversalcount,
			Timestamp operatorlastreversaltime, BigDecimal topupperiod,
			String bankretrievalreferencenumber,
			String banksystemtraceauditnumber, Timestamp bankresponsetime,
			Long bankresponsecode, String bankrejectreason,
			String bankerrortext, String bankauthorizationcode,
			Timestamp bankreversalresponsetime,
			Long bankreversalresponsecode, String bankreversalrejectreason,
			String bankreversalerrortext, String bankreversalauthorizationcode,
			Long reversalcount, Timestamp lastreversaltime, Long csraction,
			Timestamp csractiontime, BigDecimal csruserid,
			String csrusername, String csrcomment,
			String iso8583Processingcode, String iso8583Primaryaccountnumber,
			String iso8583Systemtraceauditnumber,
			String iso8583Localtxntimehhmmss, String iso8583Merchanttype,
			Long iso8583Acquiringinstidcode,
			String iso8583Retrievalreferencenum,
			String iso8583Cardacceptoridcode, String iso8583Variant,
			String iso8583Responsecode, BigDecimal bulkuploadid,
			Long bulkuploadlinenumber, String copytopermanenterror,
			String webclientip, String operatorrrn, String operatorstan,
			String productindicatorcode, BigDecimal units,
			BigDecimal denomination, BigDecimal transactionchargeid,
			Short ispartofsharedupchain, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			short localbalancerevertrequired, short localrevertrequired,
			short bankreversalrequired, short operatoractionrequired) {
		this.id = id;
		this.subscriberMdn = subscriberMdn;
		this.transactionLog = transactionLog;
		this.creditCardTransaction = creditCardTransaction;
		this.letterOfPurchase = letterOfPurchase;
		this.subscriber = subscriber;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.company = company;
		this.distributionChainLvl = distributionChainLvl;
		this.pocket = pocket;
		this.msgtype = msgtype;
		this.uicategory = uicategory;
		this.transferstatus = transferstatus;
		this.transferfailurereason = transferfailurereason;
		this.notificationcode = notificationcode;
		this.starttime = starttime;
		this.endtime = endtime;
		this.expirationtimeout = expirationtimeout;
		this.sourceip = sourceip;
		this.sourcereferenceid = sourcereferenceid;
		this.sourceterminalid = sourceterminalid;
		this.sourcemdn = sourcemdn;
		this.levelpermissions = levelpermissions;
		this.sourcesubscribername = sourcesubscribername;
		this.sourcepocketallowance = sourcepocketallowance;
		this.sourcepockettype = sourcepockettype;
		this.sourcepocketbalance = sourcepocketbalance;
		this.sourcecardpan = sourcecardpan;
		this.sourcemessage = sourcemessage;
		this.destmdn = destmdn;
		this.destmdnid = destmdnid;
		this.destsubscriberid = destsubscriberid;
		this.destsubscribername = destsubscribername;
		this.destpocketallowance = destpocketallowance;
		this.destpockettype = destpockettype;
		this.destpocketid = destpocketid;
		this.destpocketbalance = destpocketbalance;
		this.destbankaccountname = destbankaccountname;
		this.destcardpan = destcardpan;
		this.billingtype = billingtype;
		this.amount = amount;
		this.charges = charges;
		this.taxamount = taxamount;
		this.commodity = commodity;
		this.buckettype = buckettype;
		this.sourceapplication = sourceapplication;
		this.servletpath = servletpath;
		this.currency = currency;
		this.bankcode = bankcode;
		this.operatorcode = operatorcode;
		this.operatorresponsetime = operatorresponsetime;
		this.operatorresponsecode = operatorresponsecode;
		this.operatorrejectreason = operatorrejectreason;
		this.operatorerrortext = operatorerrortext;
		this.operatorauthorizationcode = operatorauthorizationcode;
		this.operatorreversalresponsetime = operatorreversalresponsetime;
		this.operatorreversalresponsecode = operatorreversalresponsecode;
		this.operatorreversalrejectreason = operatorreversalrejectreason;
		this.operatorreversalerrortext = operatorreversalerrortext;
		this.operatorreversalcount = operatorreversalcount;
		this.operatorlastreversaltime = operatorlastreversaltime;
		this.topupperiod = topupperiod;
		this.bankretrievalreferencenumber = bankretrievalreferencenumber;
		this.banksystemtraceauditnumber = banksystemtraceauditnumber;
		this.bankresponsetime = bankresponsetime;
		this.bankresponsecode = bankresponsecode;
		this.bankrejectreason = bankrejectreason;
		this.bankerrortext = bankerrortext;
		this.bankauthorizationcode = bankauthorizationcode;
		this.bankreversalresponsetime = bankreversalresponsetime;
		this.bankreversalresponsecode = bankreversalresponsecode;
		this.bankreversalrejectreason = bankreversalrejectreason;
		this.bankreversalerrortext = bankreversalerrortext;
		this.bankreversalauthorizationcode = bankreversalauthorizationcode;
		this.reversalcount = reversalcount;
		this.lastreversaltime = lastreversaltime;
		this.csraction = csraction;
		this.csractiontime = csractiontime;
		this.csruserid = csruserid;
		this.csrusername = csrusername;
		this.csrcomment = csrcomment;
		this.iso8583Processingcode = iso8583Processingcode;
		this.iso8583Primaryaccountnumber = iso8583Primaryaccountnumber;
		this.iso8583Systemtraceauditnumber = iso8583Systemtraceauditnumber;
		this.iso8583Localtxntimehhmmss = iso8583Localtxntimehhmmss;
		this.iso8583Merchanttype = iso8583Merchanttype;
		this.iso8583Acquiringinstidcode = iso8583Acquiringinstidcode;
		this.iso8583Retrievalreferencenum = iso8583Retrievalreferencenum;
		this.iso8583Cardacceptoridcode = iso8583Cardacceptoridcode;
		this.iso8583Variant = iso8583Variant;
		this.iso8583Responsecode = iso8583Responsecode;
		this.bulkuploadid = bulkuploadid;
		this.bulkuploadlinenumber = bulkuploadlinenumber;
		this.copytopermanenterror = copytopermanenterror;
		this.webclientip = webclientip;
		this.operatorrrn = operatorrrn;
		this.operatorstan = operatorstan;
		this.productindicatorcode = productindicatorcode;
		this.units = units;
		this.denomination = denomination;
		this.transactionchargeid = transactionchargeid;
		this.ispartofsharedupchain = ispartofsharedupchain;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.localbalancerevertrequired = localbalancerevertrequired;
		this.localrevertrequired = localrevertrequired;
		this.bankreversalrequired = bankreversalrequired;
		this.operatoractionrequired = operatoractionrequired;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOURCEMDNID", nullable = false)
	public SubscriberMdn getSubscriberMdn() {
		return this.subscriberMdn;
	}

	public void setSubscriberMdn(SubscriberMdn subscriberMdn) {
		this.subscriberMdn = subscriberMdn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONID", nullable = false)
	public TransactionLog getTransactionLog() {
		return this.transactionLog;
	}

	public void setTransactionLog(TransactionLog transactionLog) {
		this.transactionLog = transactionLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREDITCARDTRANSACTIONID")
	public CreditCardTransaction getCreditCardTransaction() {
		return this.creditCardTransaction;
	}

	public void setCreditCardTransaction(
			CreditCardTransaction creditCardTransaction) {
		this.creditCardTransaction = creditCardTransaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOPID")
	public LetterOfPurchase getLetterOfPurchase() {
		return this.letterOfPurchase;
	}

	public void setLetterOfPurchase(LetterOfPurchase letterOfPurchase) {
		this.letterOfPurchase = letterOfPurchase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOURCESUBSCRIBERID", nullable = false)
	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public mFinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			mFinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DCTLEVELID")
	public DistributionChainLvl getDistributionChainLvl() {
		return this.distributionChainLvl;
	}

	public void setDistributionChainLvl(
			DistributionChainLvl distributionChainLvl) {
		this.distributionChainLvl = distributionChainLvl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SOURCEPOCKETID", nullable = false)
	public Pocket getPocket() {
		return this.pocket;
	}

	public void setPocket(Pocket pocket) {
		this.pocket = pocket;
	}

	@Column(name = "MSGTYPE", nullable = false, precision = 10, scale = 0)
	public long getMsgtype() {
		return this.msgtype;
	}

	public void setMsgtype(long msgtype) {
		this.msgtype = msgtype;
	}

	@Column(name = "UICATEGORY", precision = 10, scale = 0)
	public Long getUicategory() {
		return this.uicategory;
	}

	public void setUicategory(Long uicategory) {
		this.uicategory = uicategory;
	}

	@Column(name = "TRANSFERSTATUS", nullable = false, precision = 10, scale = 0)
	public long getTransferstatus() {
		return this.transferstatus;
	}

	public void setTransferstatus(long transferstatus) {
		this.transferstatus = transferstatus;
	}

	@Column(name = "TRANSFERFAILUREREASON", precision = 10, scale = 0)
	public Long getTransferfailurereason() {
		return this.transferfailurereason;
	}

	public void setTransferfailurereason(Long transferfailurereason) {
		this.transferfailurereason = transferfailurereason;
	}

	@Column(name = "NOTIFICATIONCODE", precision = 10, scale = 0)
	public Long getNotificationcode() {
		return this.notificationcode;
	}

	public void setNotificationcode(Long notificationcode) {
		this.notificationcode = notificationcode;
	}

	@Column(name = "STARTTIME", nullable = false)
	public Timestamp getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Timestamp starttime) {
		this.starttime = starttime;
	}

	@Column(name = "ENDTIME")
	public Timestamp getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Timestamp endtime) {
		this.endtime = endtime;
	}

	@Column(name = "EXPIRATIONTIMEOUT", nullable = false, precision = 10, scale = 0)
	public long getExpirationtimeout() {
		return this.expirationtimeout;
	}

	public void setExpirationtimeout(long expirationtimeout) {
		this.expirationtimeout = expirationtimeout;
	}

	@Column(name = "SOURCEIP", length = 1020)
	public String getSourceip() {
		return this.sourceip;
	}

	public void setSourceip(String sourceip) {
		this.sourceip = sourceip;
	}

	@Column(name = "SOURCEREFERENCEID", length = 1020)
	public String getSourcereferenceid() {
		return this.sourcereferenceid;
	}

	public void setSourcereferenceid(String sourcereferenceid) {
		this.sourcereferenceid = sourcereferenceid;
	}

	@Column(name = "SOURCETERMINALID", length = 1020)
	public String getSourceterminalid() {
		return this.sourceterminalid;
	}

	public void setSourceterminalid(String sourceterminalid) {
		this.sourceterminalid = sourceterminalid;
	}

	@Column(name = "SOURCEMDN", nullable = false, length = 1020)
	public String getSourcemdn() {
		return this.sourcemdn;
	}

	public void setSourcemdn(String sourcemdn) {
		this.sourcemdn = sourcemdn;
	}

	@Column(name = "LEVELPERMISSIONS", precision = 10, scale = 0)
	public Long getLevelpermissions() {
		return this.levelpermissions;
	}

	public void setLevelpermissions(Long levelpermissions) {
		this.levelpermissions = levelpermissions;
	}

	@Column(name = "SOURCESUBSCRIBERNAME", length = 1020)
	public String getSourcesubscribername() {
		return this.sourcesubscribername;
	}

	public void setSourcesubscribername(String sourcesubscribername) {
		this.sourcesubscribername = sourcesubscribername;
	}

	@Column(name = "SOURCEPOCKETALLOWANCE", precision = 10, scale = 0)
	public Long getSourcepocketallowance() {
		return this.sourcepocketallowance;
	}

	public void setSourcepocketallowance(Long sourcepocketallowance) {
		this.sourcepocketallowance = sourcepocketallowance;
	}

	@Column(name = "SOURCEPOCKETTYPE", nullable = false, precision = 10, scale = 0)
	public long getSourcepockettype() {
		return this.sourcepockettype;
	}

	public void setSourcepockettype(long sourcepockettype) {
		this.sourcepockettype = sourcepockettype;
	}

	@Column(name = "SOURCEPOCKETBALANCE", length = 1020)
	public String getSourcepocketbalance() {
		return this.sourcepocketbalance;
	}

	public void setSourcepocketbalance(String sourcepocketbalance) {
		this.sourcepocketbalance = sourcepocketbalance;
	}

	@Column(name = "SOURCECARDPAN", length = 1020)
	public String getSourcecardpan() {
		return this.sourcecardpan;
	}

	public void setSourcecardpan(String sourcecardpan) {
		this.sourcecardpan = sourcecardpan;
	}

	@Column(name = "SOURCEMESSAGE", length = 1020)
	public String getSourcemessage() {
		return this.sourcemessage;
	}

	public void setSourcemessage(String sourcemessage) {
		this.sourcemessage = sourcemessage;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

	@Column(name = "DESTMDNID", scale = 0)
	public BigDecimal getDestmdnid() {
		return this.destmdnid;
	}

	public void setDestmdnid(BigDecimal destmdnid) {
		this.destmdnid = destmdnid;
	}

	@Column(name = "DESTSUBSCRIBERID", scale = 0)
	public BigDecimal getDestsubscriberid() {
		return this.destsubscriberid;
	}

	public void setDestsubscriberid(BigDecimal destsubscriberid) {
		this.destsubscriberid = destsubscriberid;
	}

	@Column(name = "DESTSUBSCRIBERNAME", length = 1020)
	public String getDestsubscribername() {
		return this.destsubscribername;
	}

	public void setDestsubscribername(String destsubscribername) {
		this.destsubscribername = destsubscribername;
	}

	@Column(name = "DESTPOCKETALLOWANCE", precision = 10, scale = 0)
	public Long getDestpocketallowance() {
		return this.destpocketallowance;
	}

	public void setDestpocketallowance(Long destpocketallowance) {
		this.destpocketallowance = destpocketallowance;
	}

	@Column(name = "DESTPOCKETTYPE", precision = 10, scale = 0)
	public Long getDestpockettype() {
		return this.destpockettype;
	}

	public void setDestpockettype(Long destpockettype) {
		this.destpockettype = destpockettype;
	}

	@Column(name = "DESTPOCKETID", scale = 0)
	public BigDecimal getDestpocketid() {
		return this.destpocketid;
	}

	public void setDestpocketid(BigDecimal destpocketid) {
		this.destpocketid = destpocketid;
	}

	@Column(name = "DESTPOCKETBALANCE", length = 1020)
	public String getDestpocketbalance() {
		return this.destpocketbalance;
	}

	public void setDestpocketbalance(String destpocketbalance) {
		this.destpocketbalance = destpocketbalance;
	}

	@Column(name = "DESTBANKACCOUNTNAME", length = 1020)
	public String getDestbankaccountname() {
		return this.destbankaccountname;
	}

	public void setDestbankaccountname(String destbankaccountname) {
		this.destbankaccountname = destbankaccountname;
	}

	@Column(name = "DESTCARDPAN", length = 1020)
	public String getDestcardpan() {
		return this.destcardpan;
	}

	public void setDestcardpan(String destcardpan) {
		this.destcardpan = destcardpan;
	}

	@Column(name = "BILLINGTYPE", precision = 10, scale = 0)
	public Long getBillingtype() {
		return this.billingtype;
	}

	public void setBillingtype(Long billingtype) {
		this.billingtype = billingtype;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "CHARGES", nullable = false, precision = 25, scale = 4)
	public BigDecimal getCharges() {
		return this.charges;
	}

	public void setCharges(BigDecimal charges) {
		this.charges = charges;
	}

	@Column(name = "TAXAMOUNT", precision = 25, scale = 4)
	public BigDecimal getTaxamount() {
		return this.taxamount;
	}

	public void setTaxamount(BigDecimal taxamount) {
		this.taxamount = taxamount;
	}

	@Column(name = "COMMODITY", nullable = false, precision = 10, scale = 0)
	public long getCommodity() {
		return this.commodity;
	}

	public void setCommodity(long commodity) {
		this.commodity = commodity;
	}

	@Column(name = "BUCKETTYPE", length = 1020)
	public String getBuckettype() {
		return this.buckettype;
	}

	public void setBuckettype(String buckettype) {
		this.buckettype = buckettype;
	}

	@Column(name = "SOURCEAPPLICATION", nullable = false, precision = 10, scale = 0)
	public long getSourceapplication() {
		return this.sourceapplication;
	}

	public void setSourceapplication(long sourceapplication) {
		this.sourceapplication = sourceapplication;
	}

	@Column(name = "SERVLETPATH", length = 1020)
	public String getServletpath() {
		return this.servletpath;
	}

	public void setServletpath(String servletpath) {
		this.servletpath = servletpath;
	}

	@Column(name = "CURRENCY", nullable = false, length = 1020)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "BANKCODE", precision = 10, scale = 0)
	public Long getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(Long bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "OPERATORCODE", precision = 10, scale = 0)
	public Long getOperatorcode() {
		return this.operatorcode;
	}

	public void setOperatorcode(Long operatorcode) {
		this.operatorcode = operatorcode;
	}

	@Column(name = "OPERATORRESPONSETIME")
	public Timestamp getOperatorresponsetime() {
		return this.operatorresponsetime;
	}

	public void setOperatorresponsetime(Timestamp operatorresponsetime) {
		this.operatorresponsetime = operatorresponsetime;
	}

	@Column(name = "OPERATORRESPONSECODE", precision = 10, scale = 0)
	public Long getOperatorresponsecode() {
		return this.operatorresponsecode;
	}

	public void setOperatorresponsecode(Long operatorresponsecode) {
		this.operatorresponsecode = operatorresponsecode;
	}

	@Column(name = "OPERATORREJECTREASON", length = 1020)
	public String getOperatorrejectreason() {
		return this.operatorrejectreason;
	}

	public void setOperatorrejectreason(String operatorrejectreason) {
		this.operatorrejectreason = operatorrejectreason;
	}

	@Column(name = "OPERATORERRORTEXT", length = 1020)
	public String getOperatorerrortext() {
		return this.operatorerrortext;
	}

	public void setOperatorerrortext(String operatorerrortext) {
		this.operatorerrortext = operatorerrortext;
	}

	@Column(name = "OPERATORAUTHORIZATIONCODE", length = 1020)
	public String getOperatorauthorizationcode() {
		return this.operatorauthorizationcode;
	}

	public void setOperatorauthorizationcode(String operatorauthorizationcode) {
		this.operatorauthorizationcode = operatorauthorizationcode;
	}

	@Column(name = "OPERATORREVERSALRESPONSETIME")
	public Timestamp getOperatorreversalresponsetime() {
		return this.operatorreversalresponsetime;
	}

	public void setOperatorreversalresponsetime(
			Timestamp operatorreversalresponsetime) {
		this.operatorreversalresponsetime = operatorreversalresponsetime;
	}

	@Column(name = "OPERATORREVERSALRESPONSECODE", precision = 10, scale = 0)
	public Long getOperatorreversalresponsecode() {
		return this.operatorreversalresponsecode;
	}

	public void setOperatorreversalresponsecode(
			Long operatorreversalresponsecode) {
		this.operatorreversalresponsecode = operatorreversalresponsecode;
	}

	@Column(name = "OPERATORREVERSALREJECTREASON", length = 1020)
	public String getOperatorreversalrejectreason() {
		return this.operatorreversalrejectreason;
	}

	public void setOperatorreversalrejectreason(
			String operatorreversalrejectreason) {
		this.operatorreversalrejectreason = operatorreversalrejectreason;
	}

	@Column(name = "OPERATORREVERSALERRORTEXT", length = 1020)
	public String getOperatorreversalerrortext() {
		return this.operatorreversalerrortext;
	}

	public void setOperatorreversalerrortext(String operatorreversalerrortext) {
		this.operatorreversalerrortext = operatorreversalerrortext;
	}

	@Column(name = "OPERATORREVERSALCOUNT", precision = 10, scale = 0)
	public Long getOperatorreversalcount() {
		return this.operatorreversalcount;
	}

	public void setOperatorreversalcount(Long operatorreversalcount) {
		this.operatorreversalcount = operatorreversalcount;
	}

	@Column(name = "OPERATORLASTREVERSALTIME")
	public Timestamp getOperatorlastreversaltime() {
		return this.operatorlastreversaltime;
	}

	public void setOperatorlastreversaltime(
			Timestamp operatorlastreversaltime) {
		this.operatorlastreversaltime = operatorlastreversaltime;
	}

	@Column(name = "TOPUPPERIOD", scale = 0)
	public BigDecimal getTopupperiod() {
		return this.topupperiod;
	}

	public void setTopupperiod(BigDecimal topupperiod) {
		this.topupperiod = topupperiod;
	}

	@Column(name = "BANKRETRIEVALREFERENCENUMBER", length = 1020)
	public String getBankretrievalreferencenumber() {
		return this.bankretrievalreferencenumber;
	}

	public void setBankretrievalreferencenumber(
			String bankretrievalreferencenumber) {
		this.bankretrievalreferencenumber = bankretrievalreferencenumber;
	}

	@Column(name = "BANKSYSTEMTRACEAUDITNUMBER", length = 1020)
	public String getBanksystemtraceauditnumber() {
		return this.banksystemtraceauditnumber;
	}

	public void setBanksystemtraceauditnumber(String banksystemtraceauditnumber) {
		this.banksystemtraceauditnumber = banksystemtraceauditnumber;
	}

	@Column(name = "BANKRESPONSETIME")
	public Timestamp getBankresponsetime() {
		return this.bankresponsetime;
	}

	public void setBankresponsetime(Timestamp bankresponsetime) {
		this.bankresponsetime = bankresponsetime;
	}

	@Column(name = "BANKRESPONSECODE", precision = 10, scale = 0)
	public Long getBankresponsecode() {
		return this.bankresponsecode;
	}

	public void setBankresponsecode(Long bankresponsecode) {
		this.bankresponsecode = bankresponsecode;
	}

	@Column(name = "BANKREJECTREASON", length = 1020)
	public String getBankrejectreason() {
		return this.bankrejectreason;
	}

	public void setBankrejectreason(String bankrejectreason) {
		this.bankrejectreason = bankrejectreason;
	}

	@Column(name = "BANKERRORTEXT", length = 1020)
	public String getBankerrortext() {
		return this.bankerrortext;
	}

	public void setBankerrortext(String bankerrortext) {
		this.bankerrortext = bankerrortext;
	}

	@Column(name = "BANKAUTHORIZATIONCODE", length = 1020)
	public String getBankauthorizationcode() {
		return this.bankauthorizationcode;
	}

	public void setBankauthorizationcode(String bankauthorizationcode) {
		this.bankauthorizationcode = bankauthorizationcode;
	}

	@Column(name = "BANKREVERSALRESPONSETIME")
	public Timestamp getBankreversalresponsetime() {
		return this.bankreversalresponsetime;
	}

	public void setBankreversalresponsetime(
			Timestamp bankreversalresponsetime) {
		this.bankreversalresponsetime = bankreversalresponsetime;
	}

	@Column(name = "BANKREVERSALRESPONSECODE", precision = 10, scale = 0)
	public Long getBankreversalresponsecode() {
		return this.bankreversalresponsecode;
	}

	public void setBankreversalresponsecode(Long bankreversalresponsecode) {
		this.bankreversalresponsecode = bankreversalresponsecode;
	}

	@Column(name = "BANKREVERSALREJECTREASON", length = 1020)
	public String getBankreversalrejectreason() {
		return this.bankreversalrejectreason;
	}

	public void setBankreversalrejectreason(String bankreversalrejectreason) {
		this.bankreversalrejectreason = bankreversalrejectreason;
	}

	@Column(name = "BANKREVERSALERRORTEXT", length = 1020)
	public String getBankreversalerrortext() {
		return this.bankreversalerrortext;
	}

	public void setBankreversalerrortext(String bankreversalerrortext) {
		this.bankreversalerrortext = bankreversalerrortext;
	}

	@Column(name = "BANKREVERSALAUTHORIZATIONCODE", length = 1020)
	public String getBankreversalauthorizationcode() {
		return this.bankreversalauthorizationcode;
	}

	public void setBankreversalauthorizationcode(
			String bankreversalauthorizationcode) {
		this.bankreversalauthorizationcode = bankreversalauthorizationcode;
	}

	@Column(name = "REVERSALCOUNT", precision = 10, scale = 0)
	public Long getReversalcount() {
		return this.reversalcount;
	}

	public void setReversalcount(Long reversalcount) {
		this.reversalcount = reversalcount;
	}

	@Column(name = "LASTREVERSALTIME")
	public Timestamp getLastreversaltime() {
		return this.lastreversaltime;
	}

	public void setLastreversaltime(Timestamp lastreversaltime) {
		this.lastreversaltime = lastreversaltime;
	}

	@Column(name = "CSRACTION", precision = 10, scale = 0)
	public Long getCsraction() {
		return this.csraction;
	}

	public void setCsraction(Long csraction) {
		this.csraction = csraction;
	}

	@Column(name = "CSRACTIONTIME")
	public Timestamp getCsractiontime() {
		return this.csractiontime;
	}

	public void setCsractiontime(Timestamp csractiontime) {
		this.csractiontime = csractiontime;
	}

	@Column(name = "CSRUSERID", scale = 0)
	public BigDecimal getCsruserid() {
		return this.csruserid;
	}

	public void setCsruserid(BigDecimal csruserid) {
		this.csruserid = csruserid;
	}

	@Column(name = "CSRUSERNAME", length = 1020)
	public String getCsrusername() {
		return this.csrusername;
	}

	public void setCsrusername(String csrusername) {
		this.csrusername = csrusername;
	}

	@Column(name = "CSRCOMMENT", length = 1020)
	public String getCsrcomment() {
		return this.csrcomment;
	}

	public void setCsrcomment(String csrcomment) {
		this.csrcomment = csrcomment;
	}

	@Column(name = "ISO8583_PROCESSINGCODE", length = 1020)
	public String getIso8583Processingcode() {
		return this.iso8583Processingcode;
	}

	public void setIso8583Processingcode(String iso8583Processingcode) {
		this.iso8583Processingcode = iso8583Processingcode;
	}

	@Column(name = "ISO8583_PRIMARYACCOUNTNUMBER", length = 1020)
	public String getIso8583Primaryaccountnumber() {
		return this.iso8583Primaryaccountnumber;
	}

	public void setIso8583Primaryaccountnumber(
			String iso8583Primaryaccountnumber) {
		this.iso8583Primaryaccountnumber = iso8583Primaryaccountnumber;
	}

	@Column(name = "ISO8583_SYSTEMTRACEAUDITNUMBER", length = 1020)
	public String getIso8583Systemtraceauditnumber() {
		return this.iso8583Systemtraceauditnumber;
	}

	public void setIso8583Systemtraceauditnumber(
			String iso8583Systemtraceauditnumber) {
		this.iso8583Systemtraceauditnumber = iso8583Systemtraceauditnumber;
	}

	@Column(name = "ISO8583_LOCALTXNTIMEHHMMSS", length = 1020)
	public String getIso8583Localtxntimehhmmss() {
		return this.iso8583Localtxntimehhmmss;
	}

	public void setIso8583Localtxntimehhmmss(String iso8583Localtxntimehhmmss) {
		this.iso8583Localtxntimehhmmss = iso8583Localtxntimehhmmss;
	}

	@Column(name = "ISO8583_MERCHANTTYPE", length = 1020)
	public String getIso8583Merchanttype() {
		return this.iso8583Merchanttype;
	}

	public void setIso8583Merchanttype(String iso8583Merchanttype) {
		this.iso8583Merchanttype = iso8583Merchanttype;
	}

	@Column(name = "ISO8583_ACQUIRINGINSTIDCODE", precision = 10, scale = 0)
	public Long getIso8583Acquiringinstidcode() {
		return this.iso8583Acquiringinstidcode;
	}

	public void setIso8583Acquiringinstidcode(Long iso8583Acquiringinstidcode) {
		this.iso8583Acquiringinstidcode = iso8583Acquiringinstidcode;
	}

	@Column(name = "ISO8583_RETRIEVALREFERENCENUM", length = 1020)
	public String getIso8583Retrievalreferencenum() {
		return this.iso8583Retrievalreferencenum;
	}

	public void setIso8583Retrievalreferencenum(
			String iso8583Retrievalreferencenum) {
		this.iso8583Retrievalreferencenum = iso8583Retrievalreferencenum;
	}

	@Column(name = "ISO8583_CARDACCEPTORIDCODE", length = 1020)
	public String getIso8583Cardacceptoridcode() {
		return this.iso8583Cardacceptoridcode;
	}

	public void setIso8583Cardacceptoridcode(String iso8583Cardacceptoridcode) {
		this.iso8583Cardacceptoridcode = iso8583Cardacceptoridcode;
	}

	@Column(name = "ISO8583_VARIANT", length = 1020)
	public String getIso8583Variant() {
		return this.iso8583Variant;
	}

	public void setIso8583Variant(String iso8583Variant) {
		this.iso8583Variant = iso8583Variant;
	}

	@Column(name = "ISO8583_RESPONSECODE", length = 1020)
	public String getIso8583Responsecode() {
		return this.iso8583Responsecode;
	}

	public void setIso8583Responsecode(String iso8583Responsecode) {
		this.iso8583Responsecode = iso8583Responsecode;
	}

	@Column(name = "BULKUPLOADID", scale = 0)
	public BigDecimal getBulkuploadid() {
		return this.bulkuploadid;
	}

	public void setBulkuploadid(BigDecimal bulkuploadid) {
		this.bulkuploadid = bulkuploadid;
	}

	@Column(name = "BULKUPLOADLINENUMBER", precision = 10, scale = 0)
	public Long getBulkuploadlinenumber() {
		return this.bulkuploadlinenumber;
	}

	public void setBulkuploadlinenumber(Long bulkuploadlinenumber) {
		this.bulkuploadlinenumber = bulkuploadlinenumber;
	}

	@Column(name = "COPYTOPERMANENTERROR", length = 1020)
	public String getCopytopermanenterror() {
		return this.copytopermanenterror;
	}

	public void setCopytopermanenterror(String copytopermanenterror) {
		this.copytopermanenterror = copytopermanenterror;
	}

	@Column(name = "WEBCLIENTIP", length = 1020)
	public String getWebclientip() {
		return this.webclientip;
	}

	public void setWebclientip(String webclientip) {
		this.webclientip = webclientip;
	}

	@Column(name = "OPERATORRRN", length = 1020)
	public String getOperatorrrn() {
		return this.operatorrrn;
	}

	public void setOperatorrrn(String operatorrrn) {
		this.operatorrrn = operatorrrn;
	}

	@Column(name = "OPERATORSTAN", length = 1020)
	public String getOperatorstan() {
		return this.operatorstan;
	}

	public void setOperatorstan(String operatorstan) {
		this.operatorstan = operatorstan;
	}

	@Column(name = "PRODUCTINDICATORCODE", length = 1020)
	public String getProductindicatorcode() {
		return this.productindicatorcode;
	}

	public void setProductindicatorcode(String productindicatorcode) {
		this.productindicatorcode = productindicatorcode;
	}

	@Column(name = "UNITS", scale = 0)
	public BigDecimal getUnits() {
		return this.units;
	}

	public void setUnits(BigDecimal units) {
		this.units = units;
	}

	@Column(name = "DENOMINATION", scale = 0)
	public BigDecimal getDenomination() {
		return this.denomination;
	}

	public void setDenomination(BigDecimal denomination) {
		this.denomination = denomination;
	}

	@Column(name = "TRANSACTIONCHARGEID", scale = 0)
	public BigDecimal getTransactionchargeid() {
		return this.transactionchargeid;
	}

	public void setTransactionchargeid(BigDecimal transactionchargeid) {
		this.transactionchargeid = transactionchargeid;
	}

	@Column(name = "ISPARTOFSHAREDUPCHAIN", precision = 3, scale = 0)
	public Short getIspartofsharedupchain() {
		return this.ispartofsharedupchain;
	}

	public void setIspartofsharedupchain(Short ispartofsharedupchain) {
		this.ispartofsharedupchain = ispartofsharedupchain;
	}

	
	@Column(name = "LOCALBALANCEREVERTREQUIRED", nullable = false, precision = 3, scale = 0)
	public short getLocalbalancerevertrequired() {
		return this.localbalancerevertrequired;
	}

	public void setLocalbalancerevertrequired(short localbalancerevertrequired) {
		this.localbalancerevertrequired = localbalancerevertrequired;
	}

	@Column(name = "LOCALREVERTREQUIRED", nullable = false, precision = 3, scale = 0)
	public short getLocalrevertrequired() {
		return this.localrevertrequired;
	}

	public void setLocalrevertrequired(short localrevertrequired) {
		this.localrevertrequired = localrevertrequired;
	}

	@Column(name = "BANKREVERSALREQUIRED", nullable = false, precision = 3, scale = 0)
	public short getBankreversalrequired() {
		return this.bankreversalrequired;
	}

	public void setBankreversalrequired(short bankreversalrequired) {
		this.bankreversalrequired = bankreversalrequired;
	}

	@Column(name = "OPERATORACTIONREQUIRED", nullable = false, precision = 3, scale = 0)
	public short getOperatoractionrequired() {
		return this.operatoractionrequired;
	}

	public void setOperatoractionrequired(short operatoractionrequired) {
		this.operatoractionrequired = operatoractionrequired;
	}

}
