package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Clob;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

import com.mfino.hibernate.Timestamp;

/**
 * PendingTxnsFile generated by hbm2java
 */
@Entity
@Table(name = "PENDING_TXNS_FILE")
public class PendingTxnsFile extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_Company = "company";
	public static final String FieldName_UploadFileStatus = "uploadfilestatus";
	private Company company;
	private String filename;
	private Clob filedata;
	private String description;
	private Long recordcount;
	private Long totallinecount;
	private Long errorlinecount;
	private long uploadfilestatus;
	private Clob uploadreport;
	private Long recordtype;
	private Timestamp fileprocesseddate;
	private Long resolveas;

	public PendingTxnsFile() {
	}

	

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "FILENAME", nullable = false, length = 1020)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "FILEDATA", nullable = false)
	public Clob getFiledata() {
		return this.filedata;
	}

	public void setFiledata(Clob filedata) {
		this.filedata = filedata;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RECORDCOUNT", precision = 10, scale = 0)
	public Long getRecordcount() {
		return this.recordcount;
	}

	public void setRecordcount(Long recordcount) {
		this.recordcount = recordcount;
	}

	@Column(name = "TOTALLINECOUNT", precision = 10, scale = 0)
	public Long getTotallinecount() {
		return this.totallinecount;
	}

	public void setTotallinecount(Long totallinecount) {
		this.totallinecount = totallinecount;
	}

	@Column(name = "ERRORLINECOUNT", precision = 10, scale = 0)
	public Long getErrorlinecount() {
		return this.errorlinecount;
	}

	public void setErrorlinecount(Long errorlinecount) {
		this.errorlinecount = errorlinecount;
	}

	@Column(name = "UPLOADFILESTATUS", nullable = false, precision = 10, scale = 0)
	public long getUploadfilestatus() {
		return this.uploadfilestatus;
	}

	public void setUploadfilestatus(long uploadfilestatus) {
		this.uploadfilestatus = uploadfilestatus;
	}

	@Column(name = "UPLOADREPORT")
	public Clob getUploadreport() {
		return this.uploadreport;
	}

	public void setUploadreport(Clob uploadreport) {
		this.uploadreport = uploadreport;
	}

	@Column(name = "RECORDTYPE", precision = 10, scale = 0)
	public Long getRecordtype() {
		return this.recordtype;
	}

	public void setRecordtype(Long recordtype) {
		this.recordtype = recordtype;
	}

	@Type(type = "userDefinedTimeStamp")
	@Column(name = "FILEPROCESSEDDATE")
	public Timestamp getFileprocesseddate() {
		return this.fileprocesseddate;
	}

	public void setFileprocesseddate(Timestamp fileprocesseddate) {
		this.fileprocesseddate = fileprocesseddate;
	}

	
	@Column(name = "RESOLVEAS", precision = 10, scale = 0)
	public Long getResolveas() {
		return this.resolveas;
	}

	public void setResolveas(Long resolveas) {
		this.resolveas = resolveas;
	}

}
