package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PendingTxnsEntry generated by hbm2java
 */
@Entity
@Table(name = "PENDING_TXNS_ENTRY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"TRANSACTIONSFILEID", "LINENUMBER" }))
public class PendingTxnsEntry extends Base implements java.io.Serializable {

	
	public static final String FieldName_PendingTransactionsFileID = "transactionsfileid";
	public static final String FieldName_PendingTransactionsLineNumber = "linenumber";
	private BigDecimal transactionsfileid;
	private long linenumber;
	private long status;
	private String resolvefailurereason;
	private Long notificationcode;
	private Long transferid;
	private BigDecimal amount;
	private String sourcemdn;
	private String destmdn;
	private Long id;

	public PendingTxnsEntry() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "id_Sequence")
	@SequenceGenerator(name = "id_Sequence", sequenceName = "pending_txns_entry_ID_SEQ")
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	@Column(name = "TRANSACTIONSFILEID", nullable = false, scale = 0)
	public BigDecimal getTransactionsfileid() {
		return this.transactionsfileid;
	}

	public void setTransactionsfileid(BigDecimal transactionsfileid) {
		this.transactionsfileid = transactionsfileid;
	}

	@Column(name = "LINENUMBER", nullable = false, precision = 10, scale = 0)
	public long getLinenumber() {
		return this.linenumber;
	}

	public void setLinenumber(long linenumber) {
		this.linenumber = linenumber;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "RESOLVEFAILUREREASON", length = 1020)
	public String getResolvefailurereason() {
		return this.resolvefailurereason;
	}

	public void setResolvefailurereason(String resolvefailurereason) {
		this.resolvefailurereason = resolvefailurereason;
	}

	@Column(name = "NOTIFICATIONCODE", precision = 10, scale = 0)
	public Long getNotificationcode() {
		return this.notificationcode;
	}

	public void setNotificationcode(Long notificationcode) {
		this.notificationcode = notificationcode;
	}

	@Column(name = "TRANSFERID", scale = 0)
	public Long getTransferid() {
		return this.transferid;
	}

	public void setTransferid(Long transferid) {
		this.transferid = transferid;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "SOURCEMDN", length = 1020)
	public String getSourcemdn() {
		return this.sourcemdn;
	}

	public void setSourcemdn(String sourcemdn) {
		this.sourcemdn = sourcemdn;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

}
