package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PendingTxnsEntry generated by hbm2java
 */
@Entity
@Table(name = "PENDING_TXNS_ENTRY", uniqueConstraints = @UniqueConstraint(columnNames = {
		"TRANSACTIONSFILEID", "LINENUMBER" }))
public class PendingTxnsEntry implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal transactionsfileid;
	private long linenumber;
	private long status;
	private String resolvefailurereason;
	private Long notificationcode;
	private BigDecimal transferid;
	private BigDecimal amount;
	private String sourcemdn;
	private String destmdn;

	public PendingTxnsEntry() {
	}

	public PendingTxnsEntry(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal transactionsfileid, long linenumber, long status,
			BigDecimal amount) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.transactionsfileid = transactionsfileid;
		this.linenumber = linenumber;
		this.status = status;
		this.amount = amount;
	}

	public PendingTxnsEntry(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal transactionsfileid, long linenumber, long status,
			String resolvefailurereason, Long notificationcode,
			BigDecimal transferid, BigDecimal amount, String sourcemdn,
			String destmdn) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.transactionsfileid = transactionsfileid;
		this.linenumber = linenumber;
		this.status = status;
		this.resolvefailurereason = resolvefailurereason;
		this.notificationcode = notificationcode;
		this.transferid = transferid;
		this.amount = amount;
		this.sourcemdn = sourcemdn;
		this.destmdn = destmdn;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "TRANSACTIONSFILEID", nullable = false, scale = 0)
	public BigDecimal getTransactionsfileid() {
		return this.transactionsfileid;
	}

	public void setTransactionsfileid(BigDecimal transactionsfileid) {
		this.transactionsfileid = transactionsfileid;
	}

	@Column(name = "LINENUMBER", nullable = false, precision = 10, scale = 0)
	public long getLinenumber() {
		return this.linenumber;
	}

	public void setLinenumber(long linenumber) {
		this.linenumber = linenumber;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "RESOLVEFAILUREREASON", length = 1020)
	public String getResolvefailurereason() {
		return this.resolvefailurereason;
	}

	public void setResolvefailurereason(String resolvefailurereason) {
		this.resolvefailurereason = resolvefailurereason;
	}

	@Column(name = "NOTIFICATIONCODE", precision = 10, scale = 0)
	public Long getNotificationcode() {
		return this.notificationcode;
	}

	public void setNotificationcode(Long notificationcode) {
		this.notificationcode = notificationcode;
	}

	@Column(name = "TRANSFERID", scale = 0)
	public BigDecimal getTransferid() {
		return this.transferid;
	}

	public void setTransferid(BigDecimal transferid) {
		this.transferid = transferid;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "SOURCEMDN", length = 1020)
	public String getSourcemdn() {
		return this.sourcemdn;
	}

	public void setSourcemdn(String sourcemdn) {
		this.sourcemdn = sourcemdn;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

}
