package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.mfino.hibernate.Timestamp;

/**
 * PermissionItem generated by hbm2java
 */
@Entity
@Table(name = "PERMISSION_ITEM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PERMISSION", "ITEMTYPE", "ITEMID", "FIELDID", "ACTION" }))
public class PermissionItem extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private PermissionGroup permissionGroup;
	private long permission;
	private long itemtype;
	private String itemid;
	private String fieldid;
	private String action;
	private String description;

	public PermissionItem() {
	}

	public PermissionItem(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long permission, long itemtype, String itemid, String fieldid,
			String action) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.permission = permission;
		this.itemtype = itemtype;
		this.itemid = itemid;
		this.fieldid = fieldid;
		this.action = action;
	}

	public PermissionItem(BigDecimal id, PermissionGroup permissionGroup,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, long permission,
			long itemtype, String itemid, String fieldid, String action,
			String description) {
		this.id = id;
		this.permissionGroup = permissionGroup;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.permission = permission;
		this.itemtype = itemtype;
		this.itemid = itemid;
		this.fieldid = fieldid;
		this.action = action;
		this.description = description;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSIONGROUPID")
	public PermissionGroup getPermissionGroup() {
		return this.permissionGroup;
	}

	public void setPermissionGroup(PermissionGroup permissionGroup) {
		this.permissionGroup = permissionGroup;
	}

	
	@Column(name = "PERMISSION", nullable = false, precision = 10, scale = 0)
	public long getPermission() {
		return this.permission;
	}

	public void setPermission(long permission) {
		this.permission = permission;
	}

	@Column(name = "ITEMTYPE", nullable = false, precision = 10, scale = 0)
	public long getItemtype() {
		return this.itemtype;
	}

	public void setItemtype(long itemtype) {
		this.itemtype = itemtype;
	}

	@Column(name = "ITEMID", nullable = false, length = 1020)
	public String getItemid() {
		return this.itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	@Column(name = "FIELDID", nullable = false, length = 1020)
	public String getFieldid() {
		return this.fieldid;
	}

	public void setFieldid(String fieldid) {
		this.fieldid = fieldid;
	}

	@Column(name = "ACTION", nullable = false, length = 1020)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	 @Override
	    public boolean equals(Object newObject)
	    {

	        if(!(newObject instanceof PermissionItem))
	            return false;

	        PermissionItem pNewObject = (PermissionItem) newObject;


	        if(((Long)this.getItemtype()).equals(pNewObject.getItemtype()) &&
	            this.getItemid().trim().equals(pNewObject.getItemid().trim()) &&
	            this.getFieldid().trim().equals(pNewObject.getFieldid().trim()) &&
	            this.getAction().trim().equals(pNewObject.getAction().trim()))
	        {
	            return true;
	        }
	        else
	            return false;
	        
	    }

	    public boolean matchesWithoutField(PermissionItem permissionItems){
	        return ((Long)this.getItemtype()).equals(permissionItems.getItemtype()) &&
	            this.getItemid().trim().equals(permissionItems.getItemid().trim()) &&
	            this.getAction().trim().equals(permissionItems.getAction().trim());
	    }
}
