package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * PermissionItem generated by hbm2java
 */
@Entity
@Table(name = "PERMISSION_ITEM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PERMISSION", "ITEMTYPE", "ITEMID", "FIELDID", "ACTION" }))
public class PermissionItem implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private PermissionGroup permissionGroup;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private long permission;
	private long itemtype;
	private String itemid;
	private String fieldid;
	private String action;
	private String description;

	public PermissionItem() {
	}

	public PermissionItem(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			long permission, long itemtype, String itemid, String fieldid,
			String action) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.permission = permission;
		this.itemtype = itemtype;
		this.itemid = itemid;
		this.fieldid = fieldid;
		this.action = action;
	}

	public PermissionItem(BigDecimal id, PermissionGroup permissionGroup,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, long permission,
			long itemtype, String itemid, String fieldid, String action,
			String description) {
		this.id = id;
		this.permissionGroup = permissionGroup;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.permission = permission;
		this.itemtype = itemtype;
		this.itemid = itemid;
		this.fieldid = fieldid;
		this.action = action;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSIONGROUPID")
	public PermissionGroup getPermissionGroup() {
		return this.permissionGroup;
	}

	public void setPermissionGroup(PermissionGroup permissionGroup) {
		this.permissionGroup = permissionGroup;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "PERMISSION", nullable = false, precision = 10, scale = 0)
	public long getPermission() {
		return this.permission;
	}

	public void setPermission(long permission) {
		this.permission = permission;
	}

	@Column(name = "ITEMTYPE", nullable = false, precision = 10, scale = 0)
	public long getItemtype() {
		return this.itemtype;
	}

	public void setItemtype(long itemtype) {
		this.itemtype = itemtype;
	}

	@Column(name = "ITEMID", nullable = false, length = 1020)
	public String getItemid() {
		return this.itemid;
	}

	public void setItemid(String itemid) {
		this.itemid = itemid;
	}

	@Column(name = "FIELDID", nullable = false, length = 1020)
	public String getFieldid() {
		return this.fieldid;
	}

	public void setFieldid(String fieldid) {
		this.fieldid = fieldid;
	}

	@Column(name = "ACTION", nullable = false, length = 1020)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
