package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
import com.mfino.hibernate.Timestamp;

/**
 * Person2Person generated by hbm2java
 */
@Entity
@Table(name = "PERSON_2_PERSON", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MSPID", "SUBSCRIBERID", "MDN" }))
public class Person2Person extends Base implements java.io.Serializable {

	
	private Subscriber subscriber;
	private mFinoServiceProvider mfinoServiceProvider;
	private String mdn;
	private String peername;
	private Timestamp activationtime;

	public Person2Person() {
	}

	public Person2Person(BigDecimal id, Subscriber subscriber,
			mFinoServiceProvider mfinoServiceProvider,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String mdn) {
		this.id = id;
		this.subscriber = subscriber;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mdn = mdn;
	}

	public Person2Person(BigDecimal id, Subscriber subscriber,
			mFinoServiceProvider mfinoServiceProvider,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String mdn,
			String peername, Timestamp activationtime) {
		this.id = id;
		this.subscriber = subscriber;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mdn = mdn;
		this.peername = peername;
		this.activationtime = activationtime;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERID", nullable = false)
	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public mFinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			mFinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	

	@Column(name = "MDN", nullable = false, length = 1020)
	public String getMdn() {
		return this.mdn;
	}

	public void setMdn(String mdn) {
		this.mdn = mdn;
	}

	@Column(name = "PEERNAME", length = 1020)
	public String getPeername() {
		return this.peername;
	}

	public void setPeername(String peername) {
		this.peername = peername;
	}

	@Column(name = "ACTIVATIONTIME")
	public Timestamp getActivationtime() {
		return this.activationtime;
	}

	public void setActivationtime(Timestamp activationtime) {
		this.activationtime = activationtime;
	}

}
