package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * PocketTemplateConfig generated by hbm2java
 */
@Entity
@Table(name = "POCKET_TEMPLATE_CONFIG")
public class PocketTemplateConfig implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private KycLevel kycLevel;
	private PocketTemplate pocketTemplate;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private long subscribertype;
	private Long businesspartnertype;
	private long commodity;
	private long pockettype;
	private Short issuspencepocket;
	private Short iscollectorpocket;
	private Short isdefault;
	private Set<PtcGroupMapping> ptcGroupMappings = new HashSet<PtcGroupMapping>(
			0);

	public PocketTemplateConfig() {
	}

	public PocketTemplateConfig(BigDecimal id, KycLevel kycLevel,
			PocketTemplate pocketTemplate, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			long subscribertype, long commodity, long pockettype) {
		this.id = id;
		this.kycLevel = kycLevel;
		this.pocketTemplate = pocketTemplate;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.subscribertype = subscribertype;
		this.commodity = commodity;
		this.pockettype = pockettype;
	}

	public PocketTemplateConfig(BigDecimal id, KycLevel kycLevel,
			PocketTemplate pocketTemplate, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			long subscribertype, Long businesspartnertype, long commodity,
			long pockettype, Short issuspencepocket, Short iscollectorpocket,
			Short isdefault, Set<PtcGroupMapping> ptcGroupMappings) {
		this.id = id;
		this.kycLevel = kycLevel;
		this.pocketTemplate = pocketTemplate;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.subscribertype = subscribertype;
		this.businesspartnertype = businesspartnertype;
		this.commodity = commodity;
		this.pockettype = pockettype;
		this.issuspencepocket = issuspencepocket;
		this.iscollectorpocket = iscollectorpocket;
		this.isdefault = isdefault;
		this.ptcGroupMappings = ptcGroupMappings;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KYCLEVEL", nullable = false)
	public KycLevel getKycLevel() {
		return this.kycLevel;
	}

	public void setKycLevel(KycLevel kycLevel) {
		this.kycLevel = kycLevel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETTEMPLATEID", nullable = false)
	public PocketTemplate getPocketTemplate() {
		return this.pocketTemplate;
	}

	public void setPocketTemplate(PocketTemplate pocketTemplate) {
		this.pocketTemplate = pocketTemplate;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SUBSCRIBERTYPE", nullable = false, precision = 10, scale = 0)
	public long getSubscribertype() {
		return this.subscribertype;
	}

	public void setSubscribertype(long subscribertype) {
		this.subscribertype = subscribertype;
	}

	@Column(name = "BUSINESSPARTNERTYPE", precision = 10, scale = 0)
	public Long getBusinesspartnertype() {
		return this.businesspartnertype;
	}

	public void setBusinesspartnertype(Long businesspartnertype) {
		this.businesspartnertype = businesspartnertype;
	}

	@Column(name = "COMMODITY", nullable = false, precision = 10, scale = 0)
	public long getCommodity() {
		return this.commodity;
	}

	public void setCommodity(long commodity) {
		this.commodity = commodity;
	}

	@Column(name = "POCKETTYPE", nullable = false, precision = 10, scale = 0)
	public long getPockettype() {
		return this.pockettype;
	}

	public void setPockettype(long pockettype) {
		this.pockettype = pockettype;
	}

	@Column(name = "ISSUSPENCEPOCKET", precision = 3, scale = 0)
	public Short getIssuspencepocket() {
		return this.issuspencepocket;
	}

	public void setIssuspencepocket(Short issuspencepocket) {
		this.issuspencepocket = issuspencepocket;
	}

	@Column(name = "ISCOLLECTORPOCKET", precision = 3, scale = 0)
	public Short getIscollectorpocket() {
		return this.iscollectorpocket;
	}

	public void setIscollectorpocket(Short iscollectorpocket) {
		this.iscollectorpocket = iscollectorpocket;
	}

	@Column(name = "ISDEFAULT", precision = 3, scale = 0)
	public Short getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Short isdefault) {
		this.isdefault = isdefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pocketTemplateConfig")
	public Set<PtcGroupMapping> getPtcGroupMappings() {
		return this.ptcGroupMappings;
	}

	public void setPtcGroupMappings(Set<PtcGroupMapping> ptcGroupMappings) {
		this.ptcGroupMappings = ptcGroupMappings;
	}

}
