package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * PocketTemplateConfig generated by hbm2java
 */
@Entity
@Table(name = "POCKET_TEMPLATE_CONFIG")
public class PocketTemplateConfig extends Base implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	public static final String FieldName_SubscriberType = "subscribertype";

	public static final String FieldName_BusinessPartnerType = "businesspartnertype";

	public static final String FieldName_KYCLevelByKYCLevel = "kycLevel";

	public static final String FieldName_PocketType = "pockettype";

	public static final String FieldName_Commodity = "commodity";

	public static final String FieldName_IsDefault = "isdefault";

	public static final String FieldName_IsSuspencePocket = "issuspencepocket";

	public static final String FieldName_IsCollectorPocket = "iscollectorpocket";

	public static final String FieldName_PTC_Group_MapFromPtcID = "ptcGroupMappings";
	
	private KycLevel kycLevel;
	private PocketTemplate pocketTemplate;
	private long subscribertype;
	private Long businesspartnertype;
	private long commodity;
	private long pockettype;
	private Short issuspencepocket;
	private Short iscollectorpocket;
	private Short isdefault;
	private Set<PtcGroupMapping> ptcGroupMappings = new HashSet<PtcGroupMapping>(
			0);

	public PocketTemplateConfig() {
	}

	public PocketTemplateConfig(BigDecimal id, KycLevel kycLevel,
			PocketTemplate pocketTemplate, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long subscribertype, long commodity, long pockettype) {
		this.id = id;
		this.kycLevel = kycLevel;
		this.pocketTemplate = pocketTemplate;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.subscribertype = subscribertype;
		this.commodity = commodity;
		this.pockettype = pockettype;
	}

	public PocketTemplateConfig(BigDecimal id, KycLevel kycLevel,
			PocketTemplate pocketTemplate, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long subscribertype, Long businesspartnertype, long commodity,
			long pockettype, Short issuspencepocket, Short iscollectorpocket,
			Short isdefault, Set<PtcGroupMapping> ptcGroupMappings) {
		this.id = id;
		this.kycLevel = kycLevel;
		this.pocketTemplate = pocketTemplate;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.subscribertype = subscribertype;
		this.businesspartnertype = businesspartnertype;
		this.commodity = commodity;
		this.pockettype = pockettype;
		this.issuspencepocket = issuspencepocket;
		this.iscollectorpocket = iscollectorpocket;
		this.isdefault = isdefault;
		this.ptcGroupMappings = ptcGroupMappings;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KYCLEVEL", nullable = false)
	public KycLevel getKycLevel() {
		return this.kycLevel;
	}

	public void setKycLevel(KycLevel kycLevel) {
		this.kycLevel = kycLevel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETTEMPLATEID", nullable = false)
	public PocketTemplate getPocketTemplate() {
		return this.pocketTemplate;
	}

	public void setPocketTemplate(PocketTemplate pocketTemplate) {
		this.pocketTemplate = pocketTemplate;
	}

	

	@Column(name = "SUBSCRIBERTYPE", nullable = false, precision = 10, scale = 0)
	public long getSubscribertype() {
		return this.subscribertype;
	}

	public void setSubscribertype(long subscribertype) {
		this.subscribertype = subscribertype;
	}

	@Column(name = "BUSINESSPARTNERTYPE", precision = 10, scale = 0)
	public Long getBusinesspartnertype() {
		return this.businesspartnertype;
	}

	public void setBusinesspartnertype(Long businesspartnertype) {
		this.businesspartnertype = businesspartnertype;
	}

	@Column(name = "COMMODITY", nullable = false, precision = 10, scale = 0)
	public long getCommodity() {
		return this.commodity;
	}

	public void setCommodity(long commodity) {
		this.commodity = commodity;
	}

	@Column(name = "POCKETTYPE", nullable = false, precision = 10, scale = 0)
	public long getPockettype() {
		return this.pockettype;
	}

	public void setPockettype(long pockettype) {
		this.pockettype = pockettype;
	}

	@Column(name = "ISSUSPENCEPOCKET", precision = 3, scale = 0)
	public Short getIssuspencepocket() {
		return this.issuspencepocket;
	}

	public void setIssuspencepocket(Short issuspencepocket) {
		this.issuspencepocket = issuspencepocket;
	}

	@Column(name = "ISCOLLECTORPOCKET", precision = 3, scale = 0)
	public Short getIscollectorpocket() {
		return this.iscollectorpocket;
	}

	public void setIscollectorpocket(Short iscollectorpocket) {
		this.iscollectorpocket = iscollectorpocket;
	}

	@Column(name = "ISDEFAULT", precision = 3, scale = 0)
	public Short getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Short isdefault) {
		this.isdefault = isdefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pocketTemplateConfig")
	public Set<PtcGroupMapping> getPtcGroupMappings() {
		return this.ptcGroupMappings;
	}

	public void setPtcGroupMappings(Set<PtcGroupMapping> ptcGroupMappings) {
		this.ptcGroupMappings = ptcGroupMappings;
	}

}
