package com.mfino.domain;
// Generated Jul 27, 2009 3:18:44 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

import com.mfino.fix.CmFinoFIX;
import com.mfino.hibernate.Timestamp;

/**
 * Pocket generated by hbm2java
 */
public class Pocket extends CmFinoFIX.CRPocket {

	@Override
	public void setLastTransactionTime(Timestamp NewVal) {
		if(!((this.getPocketTemplate().getIsCollectorPocket()) || (this.getPocketTemplate().getIsSuspencePocket()) || (this.getPocketTemplate().getIsSystemPocket()) )){
			super.setLastTransactionTime(NewVal);
		}
	}

	@Override
	public void setCurrentDailyExpenditure(BigDecimal NewVal) {
		if(!((this.getPocketTemplate().getIsCollectorPocket()) || (this.getPocketTemplate().getIsSuspencePocket()) || (this.getPocketTemplate().getIsSystemPocket()) )){
			super.setCurrentDailyExpenditure(NewVal);
		}
	}
	
	@Override
	public void setCurrentDailyTxnsCount(Integer NewVal) {
		if(!((this.getPocketTemplate().getIsCollectorPocket()) || (this.getPocketTemplate().getIsSuspencePocket()) || (this.getPocketTemplate().getIsSystemPocket()) )){
			super.setCurrentDailyTxnsCount(NewVal);
		}
	}

	@Override
	public void setCurrentMonthlyExpenditure(BigDecimal NewVal) {
		if(!((this.getPocketTemplate().getIsCollectorPocket()) || (this.getPocketTemplate().getIsSuspencePocket()) || (this.getPocketTemplate().getIsSystemPocket()) )){
			super.setCurrentMonthlyExpenditure(NewVal);
		}
	}
	
	@Override
	public void setCurrentMonthlyTxnsCount(Integer NewVal) {
		if(!((this.getPocketTemplate().getIsCollectorPocket()) || (this.getPocketTemplate().getIsSuspencePocket()) || (this.getPocketTemplate().getIsSystemPocket()) )){
			super.setCurrentMonthlyTxnsCount(NewVal);
		}
	}

	@Override
	public void setCurrentWeeklyExpenditure(BigDecimal NewVal) {
		if(!((this.getPocketTemplate().getIsCollectorPocket()) || (this.getPocketTemplate().getIsSuspencePocket()) || (this.getPocketTemplate().getIsSystemPocket()) )){
			super.setCurrentWeeklyExpenditure(NewVal);
		}
	}

	@Override
	public void setCurrentWeeklyTxnsCount(Integer NewVal) {
		if(!((this.getPocketTemplate().getIsCollectorPocket()) || (this.getPocketTemplate().getIsSuspencePocket()) || (this.getPocketTemplate().getIsSystemPocket()) )){
			super.setCurrentWeeklyTxnsCount(NewVal);
		}
	}
}



