package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * PocketTemplate generated by hbm2java
 */
@Entity
@Table(name = "POCKET_TEMPLATE")
public class PocketTemplate implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private MfinoServiceProvider mfinoServiceProvider;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private long type;
	private Long bankaccountcardtype;
	private String description;
	private long commodity;
	private Long cardpansuffixlength;
	private String units;
	private long allowance;
	private BigDecimal maximumstoredvalue;
	private BigDecimal minimumstoredvalue;
	private BigDecimal maxamountpertransaction;
	private BigDecimal minamountpertransaction;
	private BigDecimal maxamountperday;
	private BigDecimal maxamountperweek;
	private BigDecimal maxamountpermonth;
	private long maxtransactionsperday;
	private long maxtransactionsperweek;
	private long maxtransactionspermonth;
	private long mintimebetweentransactions;
	private Long bankcode;
	private Long operatorcode;
	private Long billingtype;
	private BigDecimal lowbalancentfcthresholdamt;
	private Short lowbalancenotificationenabled;
	private Long webtimeinterval;
	private Long webservicetimeinterval;
	private Long utktimeinterval;
	private Long bankchanneltimeinterval;
	private BigDecimal denomination;
	private BigDecimal maxunits;
	private String pocketcode;
	private long typeofcheck;
	private String regularexpression;
	private Short iscollectorpocket;
	private Long numberofpocketsallowedformdn;
	private Short issuspencepocket;
	private Short issystempocket;
	private BigDecimal interestrate;
	private Set<Pocket> pocketsForPockettemplateid = new HashSet<Pocket>(0);
	private Set<KycLevel> kycLevels = new HashSet<KycLevel>(0);
	private Set<Pocket> pocketsForOldpockettemplateid = new HashSet<Pocket>(0);
	private Set<PocketTemplateConfig> pocketTemplateConfigs = new HashSet<PocketTemplateConfig>(
			0);

	public PocketTemplate() {
	}

	public PocketTemplate(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, long type,
			long commodity, long allowance, BigDecimal maxamountpertransaction,
			BigDecimal minamountpertransaction, BigDecimal maxamountperday,
			BigDecimal maxamountperweek, BigDecimal maxamountpermonth,
			long maxtransactionsperday, long maxtransactionsperweek,
			long maxtransactionspermonth, long mintimebetweentransactions,
			long typeofcheck) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.type = type;
		this.commodity = commodity;
		this.allowance = allowance;
		this.maxamountpertransaction = maxamountpertransaction;
		this.minamountpertransaction = minamountpertransaction;
		this.maxamountperday = maxamountperday;
		this.maxamountperweek = maxamountperweek;
		this.maxamountpermonth = maxamountpermonth;
		this.maxtransactionsperday = maxtransactionsperday;
		this.maxtransactionsperweek = maxtransactionsperweek;
		this.maxtransactionspermonth = maxtransactionspermonth;
		this.mintimebetweentransactions = mintimebetweentransactions;
		this.typeofcheck = typeofcheck;
	}

	public PocketTemplate(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, long type,
			Long bankaccountcardtype, String description, long commodity,
			Long cardpansuffixlength, String units, long allowance,
			BigDecimal maximumstoredvalue, BigDecimal minimumstoredvalue,
			BigDecimal maxamountpertransaction,
			BigDecimal minamountpertransaction, BigDecimal maxamountperday,
			BigDecimal maxamountperweek, BigDecimal maxamountpermonth,
			long maxtransactionsperday, long maxtransactionsperweek,
			long maxtransactionspermonth, long mintimebetweentransactions,
			Long bankcode, Long operatorcode, Long billingtype,
			BigDecimal lowbalancentfcthresholdamt,
			Short lowbalancenotificationenabled, Long webtimeinterval,
			Long webservicetimeinterval, Long utktimeinterval,
			Long bankchanneltimeinterval, BigDecimal denomination,
			BigDecimal maxunits, String pocketcode, long typeofcheck,
			String regularexpression, Short iscollectorpocket,
			Long numberofpocketsallowedformdn, Short issuspencepocket,
			Short issystempocket, BigDecimal interestrate,
			Set<Pocket> pocketsForPockettemplateid, Set<KycLevel> kycLevels,
			Set<Pocket> pocketsForOldpockettemplateid,
			Set<PocketTemplateConfig> pocketTemplateConfigs) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.type = type;
		this.bankaccountcardtype = bankaccountcardtype;
		this.description = description;
		this.commodity = commodity;
		this.cardpansuffixlength = cardpansuffixlength;
		this.units = units;
		this.allowance = allowance;
		this.maximumstoredvalue = maximumstoredvalue;
		this.minimumstoredvalue = minimumstoredvalue;
		this.maxamountpertransaction = maxamountpertransaction;
		this.minamountpertransaction = minamountpertransaction;
		this.maxamountperday = maxamountperday;
		this.maxamountperweek = maxamountperweek;
		this.maxamountpermonth = maxamountpermonth;
		this.maxtransactionsperday = maxtransactionsperday;
		this.maxtransactionsperweek = maxtransactionsperweek;
		this.maxtransactionspermonth = maxtransactionspermonth;
		this.mintimebetweentransactions = mintimebetweentransactions;
		this.bankcode = bankcode;
		this.operatorcode = operatorcode;
		this.billingtype = billingtype;
		this.lowbalancentfcthresholdamt = lowbalancentfcthresholdamt;
		this.lowbalancenotificationenabled = lowbalancenotificationenabled;
		this.webtimeinterval = webtimeinterval;
		this.webservicetimeinterval = webservicetimeinterval;
		this.utktimeinterval = utktimeinterval;
		this.bankchanneltimeinterval = bankchanneltimeinterval;
		this.denomination = denomination;
		this.maxunits = maxunits;
		this.pocketcode = pocketcode;
		this.typeofcheck = typeofcheck;
		this.regularexpression = regularexpression;
		this.iscollectorpocket = iscollectorpocket;
		this.numberofpocketsallowedformdn = numberofpocketsallowedformdn;
		this.issuspencepocket = issuspencepocket;
		this.issystempocket = issystempocket;
		this.interestrate = interestrate;
		this.pocketsForPockettemplateid = pocketsForPockettemplateid;
		this.kycLevels = kycLevels;
		this.pocketsForOldpockettemplateid = pocketsForOldpockettemplateid;
		this.pocketTemplateConfigs = pocketTemplateConfigs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "TYPE", nullable = false, precision = 10, scale = 0)
	public long getType() {
		return this.type;
	}

	public void setType(long type) {
		this.type = type;
	}

	@Column(name = "BANKACCOUNTCARDTYPE", precision = 10, scale = 0)
	public Long getBankaccountcardtype() {
		return this.bankaccountcardtype;
	}

	public void setBankaccountcardtype(Long bankaccountcardtype) {
		this.bankaccountcardtype = bankaccountcardtype;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "COMMODITY", nullable = false, precision = 10, scale = 0)
	public long getCommodity() {
		return this.commodity;
	}

	public void setCommodity(long commodity) {
		this.commodity = commodity;
	}

	@Column(name = "CARDPANSUFFIXLENGTH", precision = 10, scale = 0)
	public Long getCardpansuffixlength() {
		return this.cardpansuffixlength;
	}

	public void setCardpansuffixlength(Long cardpansuffixlength) {
		this.cardpansuffixlength = cardpansuffixlength;
	}

	@Column(name = "UNITS", length = 1020)
	public String getUnits() {
		return this.units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

	@Column(name = "ALLOWANCE", nullable = false, precision = 10, scale = 0)
	public long getAllowance() {
		return this.allowance;
	}

	public void setAllowance(long allowance) {
		this.allowance = allowance;
	}

	@Column(name = "MAXIMUMSTOREDVALUE", precision = 25, scale = 4)
	public BigDecimal getMaximumstoredvalue() {
		return this.maximumstoredvalue;
	}

	public void setMaximumstoredvalue(BigDecimal maximumstoredvalue) {
		this.maximumstoredvalue = maximumstoredvalue;
	}

	@Column(name = "MINIMUMSTOREDVALUE", precision = 25, scale = 4)
	public BigDecimal getMinimumstoredvalue() {
		return this.minimumstoredvalue;
	}

	public void setMinimumstoredvalue(BigDecimal minimumstoredvalue) {
		this.minimumstoredvalue = minimumstoredvalue;
	}

	@Column(name = "MAXAMOUNTPERTRANSACTION", nullable = false, precision = 25, scale = 4)
	public BigDecimal getMaxamountpertransaction() {
		return this.maxamountpertransaction;
	}

	public void setMaxamountpertransaction(BigDecimal maxamountpertransaction) {
		this.maxamountpertransaction = maxamountpertransaction;
	}

	@Column(name = "MINAMOUNTPERTRANSACTION", nullable = false, precision = 25, scale = 4)
	public BigDecimal getMinamountpertransaction() {
		return this.minamountpertransaction;
	}

	public void setMinamountpertransaction(BigDecimal minamountpertransaction) {
		this.minamountpertransaction = minamountpertransaction;
	}

	@Column(name = "MAXAMOUNTPERDAY", nullable = false, precision = 25, scale = 4)
	public BigDecimal getMaxamountperday() {
		return this.maxamountperday;
	}

	public void setMaxamountperday(BigDecimal maxamountperday) {
		this.maxamountperday = maxamountperday;
	}

	@Column(name = "MAXAMOUNTPERWEEK", nullable = false, precision = 25, scale = 4)
	public BigDecimal getMaxamountperweek() {
		return this.maxamountperweek;
	}

	public void setMaxamountperweek(BigDecimal maxamountperweek) {
		this.maxamountperweek = maxamountperweek;
	}

	@Column(name = "MAXAMOUNTPERMONTH", nullable = false, precision = 25, scale = 4)
	public BigDecimal getMaxamountpermonth() {
		return this.maxamountpermonth;
	}

	public void setMaxamountpermonth(BigDecimal maxamountpermonth) {
		this.maxamountpermonth = maxamountpermonth;
	}

	@Column(name = "MAXTRANSACTIONSPERDAY", nullable = false, precision = 10, scale = 0)
	public long getMaxtransactionsperday() {
		return this.maxtransactionsperday;
	}

	public void setMaxtransactionsperday(long maxtransactionsperday) {
		this.maxtransactionsperday = maxtransactionsperday;
	}

	@Column(name = "MAXTRANSACTIONSPERWEEK", nullable = false, precision = 10, scale = 0)
	public long getMaxtransactionsperweek() {
		return this.maxtransactionsperweek;
	}

	public void setMaxtransactionsperweek(long maxtransactionsperweek) {
		this.maxtransactionsperweek = maxtransactionsperweek;
	}

	@Column(name = "MAXTRANSACTIONSPERMONTH", nullable = false, precision = 10, scale = 0)
	public long getMaxtransactionspermonth() {
		return this.maxtransactionspermonth;
	}

	public void setMaxtransactionspermonth(long maxtransactionspermonth) {
		this.maxtransactionspermonth = maxtransactionspermonth;
	}

	@Column(name = "MINTIMEBETWEENTRANSACTIONS", nullable = false, precision = 10, scale = 0)
	public long getMintimebetweentransactions() {
		return this.mintimebetweentransactions;
	}

	public void setMintimebetweentransactions(long mintimebetweentransactions) {
		this.mintimebetweentransactions = mintimebetweentransactions;
	}

	@Column(name = "BANKCODE", precision = 10, scale = 0)
	public Long getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(Long bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "OPERATORCODE", precision = 10, scale = 0)
	public Long getOperatorcode() {
		return this.operatorcode;
	}

	public void setOperatorcode(Long operatorcode) {
		this.operatorcode = operatorcode;
	}

	@Column(name = "BILLINGTYPE", precision = 10, scale = 0)
	public Long getBillingtype() {
		return this.billingtype;
	}

	public void setBillingtype(Long billingtype) {
		this.billingtype = billingtype;
	}

	@Column(name = "LOWBALANCENTFCTHRESHOLDAMT", precision = 25, scale = 4)
	public BigDecimal getLowbalancentfcthresholdamt() {
		return this.lowbalancentfcthresholdamt;
	}

	public void setLowbalancentfcthresholdamt(
			BigDecimal lowbalancentfcthresholdamt) {
		this.lowbalancentfcthresholdamt = lowbalancentfcthresholdamt;
	}

	@Column(name = "LOWBALANCENOTIFICATIONENABLED", precision = 3, scale = 0)
	public Short getLowbalancenotificationenabled() {
		return this.lowbalancenotificationenabled;
	}

	public void setLowbalancenotificationenabled(
			Short lowbalancenotificationenabled) {
		this.lowbalancenotificationenabled = lowbalancenotificationenabled;
	}

	@Column(name = "WEBTIMEINTERVAL", precision = 10, scale = 0)
	public Long getWebtimeinterval() {
		return this.webtimeinterval;
	}

	public void setWebtimeinterval(Long webtimeinterval) {
		this.webtimeinterval = webtimeinterval;
	}

	@Column(name = "WEBSERVICETIMEINTERVAL", precision = 10, scale = 0)
	public Long getWebservicetimeinterval() {
		return this.webservicetimeinterval;
	}

	public void setWebservicetimeinterval(Long webservicetimeinterval) {
		this.webservicetimeinterval = webservicetimeinterval;
	}

	@Column(name = "UTKTIMEINTERVAL", precision = 10, scale = 0)
	public Long getUtktimeinterval() {
		return this.utktimeinterval;
	}

	public void setUtktimeinterval(Long utktimeinterval) {
		this.utktimeinterval = utktimeinterval;
	}

	@Column(name = "BANKCHANNELTIMEINTERVAL", precision = 10, scale = 0)
	public Long getBankchanneltimeinterval() {
		return this.bankchanneltimeinterval;
	}

	public void setBankchanneltimeinterval(Long bankchanneltimeinterval) {
		this.bankchanneltimeinterval = bankchanneltimeinterval;
	}

	@Column(name = "DENOMINATION", scale = 0)
	public BigDecimal getDenomination() {
		return this.denomination;
	}

	public void setDenomination(BigDecimal denomination) {
		this.denomination = denomination;
	}

	@Column(name = "MAXUNITS", scale = 0)
	public BigDecimal getMaxunits() {
		return this.maxunits;
	}

	public void setMaxunits(BigDecimal maxunits) {
		this.maxunits = maxunits;
	}

	@Column(name = "POCKETCODE", length = 1020)
	public String getPocketcode() {
		return this.pocketcode;
	}

	public void setPocketcode(String pocketcode) {
		this.pocketcode = pocketcode;
	}

	@Column(name = "TYPEOFCHECK", nullable = false, precision = 10, scale = 0)
	public long getTypeofcheck() {
		return this.typeofcheck;
	}

	public void setTypeofcheck(long typeofcheck) {
		this.typeofcheck = typeofcheck;
	}

	@Column(name = "REGULAREXPRESSION", length = 1020)
	public String getRegularexpression() {
		return this.regularexpression;
	}

	public void setRegularexpression(String regularexpression) {
		this.regularexpression = regularexpression;
	}

	@Column(name = "ISCOLLECTORPOCKET", precision = 3, scale = 0)
	public Short getIscollectorpocket() {
		return this.iscollectorpocket;
	}

	public void setIscollectorpocket(Short iscollectorpocket) {
		this.iscollectorpocket = iscollectorpocket;
	}

	@Column(name = "NUMBEROFPOCKETSALLOWEDFORMDN", precision = 10, scale = 0)
	public Long getNumberofpocketsallowedformdn() {
		return this.numberofpocketsallowedformdn;
	}

	public void setNumberofpocketsallowedformdn(
			Long numberofpocketsallowedformdn) {
		this.numberofpocketsallowedformdn = numberofpocketsallowedformdn;
	}

	@Column(name = "ISSUSPENCEPOCKET", precision = 3, scale = 0)
	public Short getIssuspencepocket() {
		return this.issuspencepocket;
	}

	public void setIssuspencepocket(Short issuspencepocket) {
		this.issuspencepocket = issuspencepocket;
	}

	@Column(name = "ISSYSTEMPOCKET", precision = 3, scale = 0)
	public Short getIssystempocket() {
		return this.issystempocket;
	}

	public void setIssystempocket(Short issystempocket) {
		this.issystempocket = issystempocket;
	}

	@Column(name = "INTERESTRATE", precision = 25, scale = 4)
	public BigDecimal getInterestrate() {
		return this.interestrate;
	}

	public void setInterestrate(BigDecimal interestrate) {
		this.interestrate = interestrate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pocketTemplateByPockettemplateid")
	public Set<Pocket> getPocketsForPockettemplateid() {
		return this.pocketsForPockettemplateid;
	}

	public void setPocketsForPockettemplateid(
			Set<Pocket> pocketsForPockettemplateid) {
		this.pocketsForPockettemplateid = pocketsForPockettemplateid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pocketTemplate")
	public Set<KycLevel> getKycLevels() {
		return this.kycLevels;
	}

	public void setKycLevels(Set<KycLevel> kycLevels) {
		this.kycLevels = kycLevels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pocketTemplateByOldpockettemplateid")
	public Set<Pocket> getPocketsForOldpockettemplateid() {
		return this.pocketsForOldpockettemplateid;
	}

	public void setPocketsForOldpockettemplateid(
			Set<Pocket> pocketsForOldpockettemplateid) {
		this.pocketsForOldpockettemplateid = pocketsForOldpockettemplateid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pocketTemplate")
	public Set<PocketTemplateConfig> getPocketTemplateConfigs() {
		return this.pocketTemplateConfigs;
	}

	public void setPocketTemplateConfigs(
			Set<PocketTemplateConfig> pocketTemplateConfigs) {
		this.pocketTemplateConfigs = pocketTemplateConfigs;
	}

}
