package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 * ProductIndicator generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_INDICATOR")
public class ProductIndicator extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String FieldName_TransactionUICategory = "transactionuicategory";
	public static final String FieldName_Company = "company";
	public static final String FieldName_ProductIndicatorCode = "productindicatorcode";
	
	private Company company;
	private long transactionuicategory;
	private long channelsourceapplication;
	private String requestorid;
	private String productdescription;
	private String channeltext;
	private String productindicatorcode;

	public ProductIndicator() {
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	

	@Column(name = "TRANSACTIONUICATEGORY", nullable = false, precision = 10, scale = 0)
	public long getTransactionuicategory() {
		return this.transactionuicategory;
	}

	public void setTransactionuicategory(long transactionuicategory) {
		this.transactionuicategory = transactionuicategory;
	}

	@Column(name = "CHANNELSOURCEAPPLICATION", nullable = false, precision = 10, scale = 0)
	public long getChannelsourceapplication() {
		return this.channelsourceapplication;
	}

	public void setChannelsourceapplication(long channelsourceapplication) {
		this.channelsourceapplication = channelsourceapplication;
	}

	@Column(name = "REQUESTORID", length = 1020)
	public String getRequestorid() {
		return this.requestorid;
	}

	public void setRequestorid(String requestorid) {
		this.requestorid = requestorid;
	}

	@Column(name = "PRODUCTDESCRIPTION", length = 1020)
	public String getProductdescription() {
		return this.productdescription;
	}

	public void setProductdescription(String productdescription) {
		this.productdescription = productdescription;
	}

	@Column(name = "CHANNELTEXT", length = 1020)
	public String getChanneltext() {
		return this.channeltext;
	}

	public void setChanneltext(String channeltext) {
		this.channeltext = channeltext;
	}

	@Column(name = "PRODUCTINDICATORCODE", nullable = false, length = 1020)
	public String getProductindicatorcode() {
		return this.productindicatorcode;
	}

	public void setProductindicatorcode(String productindicatorcode) {
		this.productindicatorcode = productindicatorcode;
	}

}
