package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ProductIndicator generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_INDICATOR")
public class ProductIndicator implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Company company;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private long transactionuicategory;
	private long channelsourceapplication;
	private String requestorid;
	private String productdescription;
	private String channeltext;
	private String productindicatorcode;

	public ProductIndicator() {
	}

	public ProductIndicator(BigDecimal id, Company company,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby,
			long transactionuicategory, long channelsourceapplication,
			String productindicatorcode) {
		this.id = id;
		this.company = company;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.transactionuicategory = transactionuicategory;
		this.channelsourceapplication = channelsourceapplication;
		this.productindicatorcode = productindicatorcode;
	}

	public ProductIndicator(BigDecimal id, Company company,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby,
			long transactionuicategory, long channelsourceapplication,
			String requestorid, String productdescription, String channeltext,
			String productindicatorcode) {
		this.id = id;
		this.company = company;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.transactionuicategory = transactionuicategory;
		this.channelsourceapplication = channelsourceapplication;
		this.requestorid = requestorid;
		this.productdescription = productdescription;
		this.channeltext = channeltext;
		this.productindicatorcode = productindicatorcode;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "TRANSACTIONUICATEGORY", nullable = false, precision = 10, scale = 0)
	public long getTransactionuicategory() {
		return this.transactionuicategory;
	}

	public void setTransactionuicategory(long transactionuicategory) {
		this.transactionuicategory = transactionuicategory;
	}

	@Column(name = "CHANNELSOURCEAPPLICATION", nullable = false, precision = 10, scale = 0)
	public long getChannelsourceapplication() {
		return this.channelsourceapplication;
	}

	public void setChannelsourceapplication(long channelsourceapplication) {
		this.channelsourceapplication = channelsourceapplication;
	}

	@Column(name = "REQUESTORID", length = 1020)
	public String getRequestorid() {
		return this.requestorid;
	}

	public void setRequestorid(String requestorid) {
		this.requestorid = requestorid;
	}

	@Column(name = "PRODUCTDESCRIPTION", length = 1020)
	public String getProductdescription() {
		return this.productdescription;
	}

	public void setProductdescription(String productdescription) {
		this.productdescription = productdescription;
	}

	@Column(name = "CHANNELTEXT", length = 1020)
	public String getChanneltext() {
		return this.channeltext;
	}

	public void setChanneltext(String channeltext) {
		this.channeltext = channeltext;
	}

	@Column(name = "PRODUCTINDICATORCODE", nullable = false, length = 1020)
	public String getProductindicatorcode() {
		return this.productindicatorcode;
	}

	public void setProductindicatorcode(String productindicatorcode) {
		this.productindicatorcode = productindicatorcode;
	}

}
