package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "REGION", uniqueConstraints = @UniqueConstraint(columnNames = "REGIONCODE"))
public class Region extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	public static final String FieldName_RegionCode = "regioncode";

	public static final String FieldName_Company = "company";

	public static final String FieldName_RegionName = "regionname";
	
	private Company company;
	private String regionname;
	private String regioncode;
	private String description;
	private Set<Merchant> merchants = new HashSet<Merchant>(0);

	public Region() {
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	

	@Column(name = "REGIONNAME", nullable = false, length = 1020)
	public String getRegionname() {
		return this.regionname;
	}

	public void setRegionname(String regionname) {
		this.regionname = regionname;
	}

	@Column(name = "REGIONCODE", unique = true, nullable = false, length = 1020)
	public String getRegioncode() {
		return this.regioncode;
	}

	public void setRegioncode(String regioncode) {
		this.regioncode = regioncode;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Merchant> getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Set<Merchant> merchants) {
		this.merchants = merchants;
	}

}
