package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.mfino.hibernate.Timestamp;

/**
 * RolePermission generated by hbm2java
 */
@Entity
@Table(name = "ROLE_PERMISSION", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ROLE", "PERMISSION" }))
public class RolePermission extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_Role = "role";
	public static final String FieldName_Permission = "permission";
	private long role;
	private long permission;

	public RolePermission() {
	}

	public RolePermission(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			long role, long permission) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.role = role;
		this.permission = permission;
	}

	
	@Column(name = "ROLE", nullable = false, precision = 10, scale = 0)
	public long getRole() {
		return this.role;
	}

	public void setRole(long role) {
		this.role = role;
	}

	@Column(name = "PERMISSION", nullable = false, precision = 10, scale = 0)
	public long getPermission() {
		return this.permission;
	}

	public void setPermission(long permission) {
		this.permission = permission;
	}

}
