package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * RuleKey generated by hbm2java
 */
@Entity
@Table(name = "RULE_KEY")
public class RuleKey implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Service service;
	private TransactionType transactionType;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String txnrulekey;
	private String txnrulekeytype;
	private long txnrulekeypriority;
	private String txnrulekeycomparision;

	public RuleKey() {
	}

	public RuleKey(BigDecimal id, Service service,
			TransactionType transactionType, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			String txnrulekey, String txnrulekeytype, long txnrulekeypriority,
			String txnrulekeycomparision) {
		this.id = id;
		this.service = service;
		this.transactionType = transactionType;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.txnrulekey = txnrulekey;
		this.txnrulekeytype = txnrulekeytype;
		this.txnrulekeypriority = txnrulekeypriority;
		this.txnrulekeycomparision = txnrulekeycomparision;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONTYPEID", nullable = false)
	public TransactionType getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "TXNRULEKEY", nullable = false)
	public String getTxnrulekey() {
		return this.txnrulekey;
	}

	public void setTxnrulekey(String txnrulekey) {
		this.txnrulekey = txnrulekey;
	}

	@Column(name = "TXNRULEKEYTYPE", nullable = false)
	public String getTxnrulekeytype() {
		return this.txnrulekeytype;
	}

	public void setTxnrulekeytype(String txnrulekeytype) {
		this.txnrulekeytype = txnrulekeytype;
	}

	@Column(name = "TXNRULEKEYPRIORITY", nullable = false, precision = 10, scale = 0)
	public long getTxnrulekeypriority() {
		return this.txnrulekeypriority;
	}

	public void setTxnrulekeypriority(long txnrulekeypriority) {
		this.txnrulekeypriority = txnrulekeypriority;
	}

	@Column(name = "TXNRULEKEYCOMPARISION", nullable = false)
	public String getTxnrulekeycomparision() {
		return this.txnrulekeycomparision;
	}

	public void setTxnrulekeycomparision(String txnrulekeycomparision) {
		this.txnrulekeycomparision = txnrulekeycomparision;
	}

}
