package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * SctlSettlementMap generated by hbm2java
 */
@Entity
@Table(name = "SCTL_SETTLEMENT_MAP")
public class SctlSettlementMap implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Partner partner;
	private Service service;
	private SettlementTxnLog settlementTxnLog;
	private ServiceChargeTxnLog serviceChargeTxnLog;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal amount;
	private long status;
	private BigDecimal mspid;

	public SctlSettlementMap() {
	}

	public SctlSettlementMap(BigDecimal id, Service service,
			ServiceChargeTxnLog serviceChargeTxnLog,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal amount,
			long status, BigDecimal mspid) {
		this.id = id;
		this.service = service;
		this.serviceChargeTxnLog = serviceChargeTxnLog;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.amount = amount;
		this.status = status;
		this.mspid = mspid;
	}

	public SctlSettlementMap(BigDecimal id, Partner partner, Service service,
			SettlementTxnLog settlementTxnLog,
			ServiceChargeTxnLog serviceChargeTxnLog,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal amount,
			long status, BigDecimal mspid) {
		this.id = id;
		this.partner = partner;
		this.service = service;
		this.settlementTxnLog = settlementTxnLog;
		this.serviceChargeTxnLog = serviceChargeTxnLog;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.amount = amount;
		this.status = status;
		this.mspid = mspid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARTNERID")
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STLID")
	public SettlementTxnLog getSettlementTxnLog() {
		return this.settlementTxnLog;
	}

	public void setSettlementTxnLog(SettlementTxnLog settlementTxnLog) {
		this.settlementTxnLog = settlementTxnLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCTLID", nullable = false)
	public ServiceChargeTxnLog getServiceChargeTxnLog() {
		return this.serviceChargeTxnLog;
	}

	public void setServiceChargeTxnLog(ServiceChargeTxnLog serviceChargeTxnLog) {
		this.serviceChargeTxnLog = serviceChargeTxnLog;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "MSPID", nullable = false, scale = 0)
	public BigDecimal getMspid() {
		return this.mspid;
	}

	public void setMspid(BigDecimal mspid) {
		this.mspid = mspid;
	}

}
