package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ServiceSettlementCfg generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_SETTLEMENT_CFG")
public class ServiceSettlementCfg implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private MfinoServiceProvider mfinoServiceProvider;
	private PartnerServices partnerServices;
	private SettlementTemplate settlementTemplate;
	private Pocket pocket;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private Serializable startdate;
	private Serializable enddate;
	private Short isdefault;
	private Long schedulerstatus;
	private BigDecimal similarconfigid;

	public ServiceSettlementCfg() {
	}

	public ServiceSettlementCfg(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			PartnerServices partnerServices,
			SettlementTemplate settlementTemplate, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.partnerServices = partnerServices;
		this.settlementTemplate = settlementTemplate;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public ServiceSettlementCfg(BigDecimal id,
			MfinoServiceProvider mfinoServiceProvider,
			PartnerServices partnerServices,
			SettlementTemplate settlementTemplate, Pocket pocket,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, Serializable startdate,
			Serializable enddate, Short isdefault, Long schedulerstatus,
			BigDecimal similarconfigid) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.partnerServices = partnerServices;
		this.settlementTemplate = settlementTemplate;
		this.pocket = pocket;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.startdate = startdate;
		this.enddate = enddate;
		this.isdefault = isdefault;
		this.schedulerstatus = schedulerstatus;
		this.similarconfigid = similarconfigid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARTNERSERVICEID", nullable = false)
	public PartnerServices getPartnerServices() {
		return this.partnerServices;
	}

	public void setPartnerServices(PartnerServices partnerServices) {
		this.partnerServices = partnerServices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SETTLEMENTTEMPLATEID", nullable = false)
	public SettlementTemplate getSettlementTemplate() {
		return this.settlementTemplate;
	}

	public void setSettlementTemplate(SettlementTemplate settlementTemplate) {
		this.settlementTemplate = settlementTemplate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLLECTORPOCKET")
	public Pocket getPocket() {
		return this.pocket;
	}

	public void setPocket(Pocket pocket) {
		this.pocket = pocket;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "STARTDATE")
	public Serializable getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Serializable startdate) {
		this.startdate = startdate;
	}

	@Column(name = "ENDDATE")
	public Serializable getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Serializable enddate) {
		this.enddate = enddate;
	}

	@Column(name = "ISDEFAULT", precision = 3, scale = 0)
	public Short getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Short isdefault) {
		this.isdefault = isdefault;
	}

	@Column(name = "SCHEDULERSTATUS", precision = 10, scale = 0)
	public Long getSchedulerstatus() {
		return this.schedulerstatus;
	}

	public void setSchedulerstatus(Long schedulerstatus) {
		this.schedulerstatus = schedulerstatus;
	}

	@Column(name = "SIMILARCONFIGID", scale = 0)
	public BigDecimal getSimilarconfigid() {
		return this.similarconfigid;
	}

	public void setSimilarconfigid(BigDecimal similarconfigid) {
		this.similarconfigid = similarconfigid;
	}

}
