package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import com.mfino.hibernate.Timestamp;

/**
 * ServiceSettlementCfg generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_SETTLEMENT_CFG")
public class ServiceSettlementCfg extends Base implements java.io.Serializable {

	
	private mFinoServiceProvider mfinoServiceProvider;
	private PartnerServices partnerServices;
	private SettlementTemplate settlementTemplate;
	private Pocket pocket;
	private Timestamp startdate;
	private Timestamp enddate;
	private Short isdefault;
	private Long schedulerstatus;
	private BigDecimal similarconfigid;

	public ServiceSettlementCfg() {
	}

	public ServiceSettlementCfg(BigDecimal id,
			mFinoServiceProvider mfinoServiceProvider,
			PartnerServices partnerServices,
			SettlementTemplate settlementTemplate, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.partnerServices = partnerServices;
		this.settlementTemplate = settlementTemplate;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public ServiceSettlementCfg(BigDecimal id,
			mFinoServiceProvider mfinoServiceProvider,
			PartnerServices partnerServices,
			SettlementTemplate settlementTemplate, Pocket pocket,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, Timestamp startdate,
			Timestamp enddate, Short isdefault, Long schedulerstatus,
			BigDecimal similarconfigid) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.partnerServices = partnerServices;
		this.settlementTemplate = settlementTemplate;
		this.pocket = pocket;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.startdate = startdate;
		this.enddate = enddate;
		this.isdefault = isdefault;
		this.schedulerstatus = schedulerstatus;
		this.similarconfigid = similarconfigid;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public mFinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			mFinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARTNERSERVICEID", nullable = false)
	public PartnerServices getPartnerServices() {
		return this.partnerServices;
	}

	public void setPartnerServices(PartnerServices partnerServices) {
		this.partnerServices = partnerServices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SETTLEMENTTEMPLATEID", nullable = false)
	public SettlementTemplate getSettlementTemplate() {
		return this.settlementTemplate;
	}

	public void setSettlementTemplate(SettlementTemplate settlementTemplate) {
		this.settlementTemplate = settlementTemplate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COLLECTORPOCKET")
	public Pocket getPocket() {
		return this.pocket;
	}

	public void setPocket(Pocket pocket) {
		this.pocket = pocket;
	}

	

	@Column(name = "STARTDATE")
	public Timestamp getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Timestamp startdate) {
		this.startdate = startdate;
	}

	@Column(name = "ENDDATE")
	public Timestamp getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Timestamp enddate) {
		this.enddate = enddate;
	}

	@Column(name = "ISDEFAULT", precision = 3, scale = 0)
	public Short getIsdefault() {
		return this.isdefault;
	}

	public void setIsdefault(Short isdefault) {
		this.isdefault = isdefault;
	}

	@Column(name = "SCHEDULERSTATUS", precision = 10, scale = 0)
	public Long getSchedulerstatus() {
		return this.schedulerstatus;
	}

	public void setSchedulerstatus(Long schedulerstatus) {
		this.schedulerstatus = schedulerstatus;
	}

	@Column(name = "SIMILARCONFIGID", scale = 0)
	public BigDecimal getSimilarconfigid() {
		return this.similarconfigid;
	}

	public void setSimilarconfigid(BigDecimal similarconfigid) {
		this.similarconfigid = similarconfigid;
	}

}
