package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 * ServiceTransaction generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_TRANSACTION")
public class ServiceTransaction extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Service service;
	private MfinoServiceProvider mfinoServiceProvider;
	private TransactionType transactionType;
	private Short isreverseallowed;

	public ServiceTransaction() {
	}

	

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONTYPEID", nullable = false)
	public TransactionType getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	

	@Column(name = "ISREVERSEALLOWED", precision = 3, scale = 0)
	public Short getIsreverseallowed() {
		return this.isreverseallowed;
	}

	public void setIsreverseallowed(Short isreverseallowed) {
		this.isreverseallowed = isreverseallowed;
	}

}
