package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import com.mfino.hibernate.Timestamp;

/**
 * ServiceAudit generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_AUDIT")
public class ServiceAudit extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_ServiceProviderID = "serviceproviderid";
	public static final String FieldName_ServiceID = "serviceid";
	public static final String FieldName_SourceType = "sourcetype";
	public static final String FieldName_SourceID = "sourceid";
	public static final String FieldName_KYCLevelId = "kyclevelid";
	private BigDecimal serviceproviderid;
	private BigDecimal serviceid;
	private Long sourcetype;
	private BigDecimal sourceid;
	private BigDecimal kyclevelid;
	private Timestamp lasttransactiontime;
	private BigDecimal currentdailyexpenditure;
	private BigDecimal currentweeklyexpenditure;
	private BigDecimal currentmonthlyexpenditure;
	private long currentdailytxnscount;
	private long currentweeklytxnscount;
	private long currentmonthlytxnscount;
	private BigDecimal previousdailyexpenditure;
	private BigDecimal previousweeklyexpenditure;
	private BigDecimal previousmonthlyexpenditure;
	private long previousdailytxnscount;
	private long previousweeklytxnscount;
	private long previousmonthlytxnscount;

	public ServiceAudit() {
	}

	

	@Column(name = "SERVICEPROVIDERID", scale = 0)
	public BigDecimal getServiceproviderid() {
		return this.serviceproviderid;
	}

	public void setServiceproviderid(BigDecimal serviceproviderid) {
		this.serviceproviderid = serviceproviderid;
	}

	@Column(name = "SERVICEID", scale = 0)
	public BigDecimal getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(BigDecimal serviceid) {
		this.serviceid = serviceid;
	}

	@Column(name = "SOURCETYPE", precision = 10, scale = 0)
	public Long getSourcetype() {
		return this.sourcetype;
	}

	public void setSourcetype(Long sourcetype) {
		this.sourcetype = sourcetype;
	}

	@Column(name = "SOURCEID", scale = 0)
	public BigDecimal getSourceid() {
		return this.sourceid;
	}

	public void setSourceid(BigDecimal sourceid) {
		this.sourceid = sourceid;
	}

	@Column(name = "KYCLEVELID", scale = 0)
	public BigDecimal getKyclevelid() {
		return this.kyclevelid;
	}

	public void setKyclevelid(BigDecimal kyclevelid) {
		this.kyclevelid = kyclevelid;
	}

	@Column(name = "LASTTRANSACTIONTIME")
	public Timestamp getLasttransactiontime() {
		return this.lasttransactiontime;
	}

	public void setLasttransactiontime(Timestamp lasttransactiontime) {
		this.lasttransactiontime = lasttransactiontime;
	}

	@Column(name = "CURRENTDAILYEXPENDITURE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getCurrentdailyexpenditure() {
		return this.currentdailyexpenditure;
	}

	public void setCurrentdailyexpenditure(BigDecimal currentdailyexpenditure) {
		this.currentdailyexpenditure = currentdailyexpenditure;
	}

	@Column(name = "CURRENTWEEKLYEXPENDITURE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getCurrentweeklyexpenditure() {
		return this.currentweeklyexpenditure;
	}

	public void setCurrentweeklyexpenditure(BigDecimal currentweeklyexpenditure) {
		this.currentweeklyexpenditure = currentweeklyexpenditure;
	}

	@Column(name = "CURRENTMONTHLYEXPENDITURE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getCurrentmonthlyexpenditure() {
		return this.currentmonthlyexpenditure;
	}

	public void setCurrentmonthlyexpenditure(
			BigDecimal currentmonthlyexpenditure) {
		this.currentmonthlyexpenditure = currentmonthlyexpenditure;
	}

	@Column(name = "CURRENTDAILYTXNSCOUNT", nullable = false, precision = 10, scale = 0)
	public long getCurrentdailytxnscount() {
		return this.currentdailytxnscount;
	}

	public void setCurrentdailytxnscount(long currentdailytxnscount) {
		this.currentdailytxnscount = currentdailytxnscount;
	}

	@Column(name = "CURRENTWEEKLYTXNSCOUNT", nullable = false, precision = 10, scale = 0)
	public long getCurrentweeklytxnscount() {
		return this.currentweeklytxnscount;
	}

	public void setCurrentweeklytxnscount(long currentweeklytxnscount) {
		this.currentweeklytxnscount = currentweeklytxnscount;
	}

	@Column(name = "CURRENTMONTHLYTXNSCOUNT", nullable = false, precision = 10, scale = 0)
	public long getCurrentmonthlytxnscount() {
		return this.currentmonthlytxnscount;
	}

	public void setCurrentmonthlytxnscount(long currentmonthlytxnscount) {
		this.currentmonthlytxnscount = currentmonthlytxnscount;
	}

	@Column(name = "PREVIOUSDAILYEXPENDITURE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getPreviousdailyexpenditure() {
		return this.previousdailyexpenditure;
	}

	public void setPreviousdailyexpenditure(BigDecimal previousdailyexpenditure) {
		this.previousdailyexpenditure = previousdailyexpenditure;
	}

	@Column(name = "PREVIOUSWEEKLYEXPENDITURE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getPreviousweeklyexpenditure() {
		return this.previousweeklyexpenditure;
	}

	public void setPreviousweeklyexpenditure(
			BigDecimal previousweeklyexpenditure) {
		this.previousweeklyexpenditure = previousweeklyexpenditure;
	}

	@Column(name = "PREVIOUSMONTHLYEXPENDITURE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getPreviousmonthlyexpenditure() {
		return this.previousmonthlyexpenditure;
	}

	public void setPreviousmonthlyexpenditure(
			BigDecimal previousmonthlyexpenditure) {
		this.previousmonthlyexpenditure = previousmonthlyexpenditure;
	}

	@Column(name = "PREVIOUSDAILYTXNSCOUNT", nullable = false, precision = 10, scale = 0)
	public long getPreviousdailytxnscount() {
		return this.previousdailytxnscount;
	}

	public void setPreviousdailytxnscount(long previousdailytxnscount) {
		this.previousdailytxnscount = previousdailytxnscount;
	}

	@Column(name = "PREVIOUSWEEKLYTXNSCOUNT", nullable = false, precision = 10, scale = 0)
	public long getPreviousweeklytxnscount() {
		return this.previousweeklytxnscount;
	}

	public void setPreviousweeklytxnscount(long previousweeklytxnscount) {
		this.previousweeklytxnscount = previousweeklytxnscount;
	}

	@Column(name = "PREVIOUSMONTHLYTXNSCOUNT", nullable = false, precision = 10, scale = 0)
	public long getPreviousmonthlytxnscount() {
		return this.previousmonthlytxnscount;
	}

	public void setPreviousmonthlytxnscount(long previousmonthlytxnscount) {
		this.previousmonthlytxnscount = previousmonthlytxnscount;
	}

}
