package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * ServiceChargeTxnLog generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_CHARGE_TXN_LOG")
public class ServiceChargeTxnLog extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_TransactionID = "transactionid";
	public static final String FieldName_SCTLStatus = "status";
	public static final String FieldName_ChannelCodeID = "channelcodeid";
	public static final String FieldName_DestMDN = "destmdn";
	public static final String FieldName_SourceMDN = "sourcemdn";
	public static final String FieldName_SourcePartnerID = "sourcepartnerid";
	public static final String FieldName_DestPartnerID = "destpartnerid";
	public static final String FieldName_MFSBillerCode = "mfsbillercode";
	public static final String FieldName_CommodityTransferID = "commoditytransferid";
	public static final String FieldName_TransactionTypeID = "transactiontypeid";
	public static final String FieldName_ServiceID = "serviceid";
	public static final String FieldName_ParentSCTLID = "parentsctlid";
	public static final String FieldName_IntegrationTransactionID = "integrationtransactionid";
	public static final String FieldName_AdjustmentsFromSctlId = "adjustmentses";
	public static final String FieldName_Info1 = "info1";
	public static final String FieldName_ParentIntegrationTransID = "parentintegrationtransid";
	
	private MfinoServiceProvider mfinoServiceProvider;
	private BigDecimal transactionid;
	private String mfsbillercode;
	private BigDecimal sourcepartnerid;
	private BigDecimal destpartnerid;
	private String sourcemdn;
	private String destmdn;
	private String onbehalfofmdn;
	private BigDecimal serviceid;
	private BigDecimal transactiontypeid;
	private BigDecimal serviceproviderid;
	private BigDecimal channelcodeid;
	private BigDecimal transactionamount;
	private String transactionmode;
	private String invoiceno;
	private Long transactionruleid;
	private BigDecimal calculatedcharge;
	private BigDecimal commoditytransferid;
	private long status;
	private String failurereason;
	private Short ischargedistributed;
	private BigDecimal parentsctlid;
	private String reversalreason;
	private Short istransactionreversed;
	private Long amtrevstatus;
	private Long chrgrevstatus;
	private String integrationcode;
	private BigDecimal integrationtransactionid;
	private String info1;
	private Long chargemode;
	private String description;
	private BigDecimal parentintegrationtransid;
	private Set<SctlSettlementMap> sctlSettlementMaps = new HashSet<SctlSettlementMap>(
			0);
	private Set<BillPayments> billPaymentses = new HashSet<BillPayments>(0);
	private Set<MoneyClearanceGraved> moneyClearanceGravedsForRefundsctlid = new HashSet<MoneyClearanceGraved>(
			0);
	private Set<MoneyClearanceGraved> moneyClearanceGravedsForSctlid = new HashSet<MoneyClearanceGraved>(
			0);
	private Set<Adjustments> adjustmentses = new HashSet<Adjustments>(0);
	private Set<UnregisteredTxnInfo> unregisteredTxnInfos = new HashSet<UnregisteredTxnInfo>(
			0);
	private Set<SettlementTxnSctlMap> settlementTxnSctlMaps = new HashSet<SettlementTxnSctlMap>(
			0);

	public ServiceChargeTxnLog() {
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID")
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	
	@Column(name = "TRANSACTIONID", scale = 0)
	public BigDecimal getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(BigDecimal transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "MFSBILLERCODE", length = 1020)
	public String getMfsbillercode() {
		return this.mfsbillercode;
	}

	public void setMfsbillercode(String mfsbillercode) {
		this.mfsbillercode = mfsbillercode;
	}

	@Column(name = "SOURCEPARTNERID", scale = 0)
	public BigDecimal getSourcepartnerid() {
		return this.sourcepartnerid;
	}

	public void setSourcepartnerid(BigDecimal sourcepartnerid) {
		this.sourcepartnerid = sourcepartnerid;
	}

	@Column(name = "DESTPARTNERID", scale = 0)
	public BigDecimal getDestpartnerid() {
		return this.destpartnerid;
	}

	public void setDestpartnerid(BigDecimal destpartnerid) {
		this.destpartnerid = destpartnerid;
	}

	@Column(name = "SOURCEMDN", length = 1020)
	public String getSourcemdn() {
		return this.sourcemdn;
	}

	public void setSourcemdn(String sourcemdn) {
		this.sourcemdn = sourcemdn;
	}

	@Column(name = "DESTMDN", length = 1020)
	public String getDestmdn() {
		return this.destmdn;
	}

	public void setDestmdn(String destmdn) {
		this.destmdn = destmdn;
	}

	@Column(name = "ONBEHALFOFMDN", length = 1020)
	public String getOnbehalfofmdn() {
		return this.onbehalfofmdn;
	}

	public void setOnbehalfofmdn(String onbehalfofmdn) {
		this.onbehalfofmdn = onbehalfofmdn;
	}

	@Column(name = "SERVICEID", scale = 0)
	public BigDecimal getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(BigDecimal serviceid) {
		this.serviceid = serviceid;
	}

	@Column(name = "TRANSACTIONTYPEID", scale = 0)
	public BigDecimal getTransactiontypeid() {
		return this.transactiontypeid;
	}

	public void setTransactiontypeid(BigDecimal transactiontypeid) {
		this.transactiontypeid = transactiontypeid;
	}

	@Column(name = "SERVICEPROVIDERID", scale = 0)
	public BigDecimal getServiceproviderid() {
		return this.serviceproviderid;
	}

	public void setServiceproviderid(BigDecimal serviceproviderid) {
		this.serviceproviderid = serviceproviderid;
	}

	@Column(name = "CHANNELCODEID", scale = 0)
	public BigDecimal getChannelcodeid() {
		return this.channelcodeid;
	}

	public void setChannelcodeid(BigDecimal channelcodeid) {
		this.channelcodeid = channelcodeid;
	}

	@Column(name = "TRANSACTIONAMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getTransactionamount() {
		return this.transactionamount;
	}

	public void setTransactionamount(BigDecimal transactionamount) {
		this.transactionamount = transactionamount;
	}

	@Column(name = "TRANSACTIONMODE", length = 1020)
	public String getTransactionmode() {
		return this.transactionmode;
	}

	public void setTransactionmode(String transactionmode) {
		this.transactionmode = transactionmode;
	}

	@Column(name = "INVOICENO", length = 1020)
	public String getInvoiceno() {
		return this.invoiceno;
	}

	public void setInvoiceno(String invoiceno) {
		this.invoiceno = invoiceno;
	}

	@Column(name = "TRANSACTIONRULEID", scale = 0)
	public Long getTransactionruleid() {
		return this.transactionruleid;
	}

	public void setTransactionruleid(Long transactionruleid) {
		this.transactionruleid = transactionruleid;
	}

	@Column(name = "CALCULATEDCHARGE", precision = 25, scale = 4)
	public BigDecimal getCalculatedcharge() {
		return this.calculatedcharge;
	}

	public void setCalculatedcharge(BigDecimal calculatedcharge) {
		this.calculatedcharge = calculatedcharge;
	}

	@Column(name = "COMMODITYTRANSFERID", scale = 0)
	public BigDecimal getCommoditytransferid() {
		return this.commoditytransferid;
	}

	public void setCommoditytransferid(BigDecimal commoditytransferid) {
		this.commoditytransferid = commoditytransferid;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "FAILUREREASON", length = 1020)
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

	@Column(name = "ISCHARGEDISTRIBUTED", precision = 3, scale = 0)
	public Short getIschargedistributed() {
		return this.ischargedistributed;
	}

	public void setIschargedistributed(Short ischargedistributed) {
		this.ischargedistributed = ischargedistributed;
	}

	@Column(name = "PARENTSCTLID", scale = 0)
	public BigDecimal getParentsctlid() {
		return this.parentsctlid;
	}

	public void setParentsctlid(BigDecimal parentsctlid) {
		this.parentsctlid = parentsctlid;
	}

	@Column(name = "REVERSALREASON", length = 1020)
	public String getReversalreason() {
		return this.reversalreason;
	}

	public void setReversalreason(String reversalreason) {
		this.reversalreason = reversalreason;
	}

	@Column(name = "ISTRANSACTIONREVERSED", precision = 3, scale = 0)
	public Short getIstransactionreversed() {
		return this.istransactionreversed;
	}

	public void setIstransactionreversed(Short istransactionreversed) {
		this.istransactionreversed = istransactionreversed;
	}

	@Column(name = "AMTREVSTATUS", precision = 10, scale = 0)
	public Long getAmtrevstatus() {
		return this.amtrevstatus;
	}

	public void setAmtrevstatus(Long amtrevstatus) {
		this.amtrevstatus = amtrevstatus;
	}

	@Column(name = "CHRGREVSTATUS", precision = 10, scale = 0)
	public Long getChrgrevstatus() {
		return this.chrgrevstatus;
	}

	public void setChrgrevstatus(Long chrgrevstatus) {
		this.chrgrevstatus = chrgrevstatus;
	}

	@Column(name = "INTEGRATIONCODE")
	public String getIntegrationcode() {
		return this.integrationcode;
	}

	public void setIntegrationcode(String integrationcode) {
		this.integrationcode = integrationcode;
	}

	@Column(name = "INTEGRATIONTRANSACTIONID", scale = 0)
	public BigDecimal getIntegrationtransactionid() {
		return this.integrationtransactionid;
	}

	public void setIntegrationtransactionid(BigDecimal integrationtransactionid) {
		this.integrationtransactionid = integrationtransactionid;
	}

	@Column(name = "INFO1")
	public String getInfo1() {
		return this.info1;
	}

	public void setInfo1(String info1) {
		this.info1 = info1;
	}

	@Column(name = "CHARGEMODE", precision = 10, scale = 0)
	public Long getChargemode() {
		return this.chargemode;
	}

	public void setChargemode(Long chargemode) {
		this.chargemode = chargemode;
	}

	@Column(name = "DESCRIPTION", length = 1020)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PARENTINTEGRATIONTRANSID", scale = 0)
	public BigDecimal getParentintegrationtransid() {
		return this.parentintegrationtransid;
	}

	public void setParentintegrationtransid(BigDecimal parentintegrationtransid) {
		this.parentintegrationtransid = parentintegrationtransid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceChargeTxnLog")
	public Set<SctlSettlementMap> getSctlSettlementMaps() {
		return this.sctlSettlementMaps;
	}

	public void setSctlSettlementMaps(Set<SctlSettlementMap> sctlSettlementMaps) {
		this.sctlSettlementMaps = sctlSettlementMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceChargeTxnLog")
	public Set<BillPayments> getBillPaymentses() {
		return this.billPaymentses;
	}

	public void setBillPaymentses(Set<BillPayments> billPaymentses) {
		this.billPaymentses = billPaymentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceChargeTxnLogByRefundsctlid")
	public Set<MoneyClearanceGraved> getMoneyClearanceGravedsForRefundsctlid() {
		return this.moneyClearanceGravedsForRefundsctlid;
	}

	public void setMoneyClearanceGravedsForRefundsctlid(
			Set<MoneyClearanceGraved> moneyClearanceGravedsForRefundsctlid) {
		this.moneyClearanceGravedsForRefundsctlid = moneyClearanceGravedsForRefundsctlid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceChargeTxnLogBySctlid")
	public Set<MoneyClearanceGraved> getMoneyClearanceGravedsForSctlid() {
		return this.moneyClearanceGravedsForSctlid;
	}

	public void setMoneyClearanceGravedsForSctlid(
			Set<MoneyClearanceGraved> moneyClearanceGravedsForSctlid) {
		this.moneyClearanceGravedsForSctlid = moneyClearanceGravedsForSctlid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceChargeTxnLog")
	public Set<Adjustments> getAdjustmentses() {
		return this.adjustmentses;
	}

	public void setAdjustmentses(Set<Adjustments> adjustmentses) {
		this.adjustmentses = adjustmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceChargeTxnLog")
	public Set<UnregisteredTxnInfo> getUnregisteredTxnInfos() {
		return this.unregisteredTxnInfos;
	}

	public void setUnregisteredTxnInfos(
			Set<UnregisteredTxnInfo> unregisteredTxnInfos) {
		this.unregisteredTxnInfos = unregisteredTxnInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceChargeTxnLog")
	public Set<SettlementTxnSctlMap> getSettlementTxnSctlMaps() {
		return this.settlementTxnSctlMaps;
	}

	public void setSettlementTxnSctlMaps(
			Set<SettlementTxnSctlMap> settlementTxnSctlMaps) {
		this.settlementTxnSctlMaps = settlementTxnSctlMaps;
	}

}
