package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;
/**
 * ServiceDefualtConfig generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_DEFUALT_CONFIG")
public class ServiceDefualtConfig extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Service service;
	private Partner partner;
	private Long sourcepockettype;
	private Long destpockettype;
	private Set<PartnerDefaultServices> partnerDefaultServiceses = new HashSet<PartnerDefaultServices>(
			0);

	public ServiceDefualtConfig() {
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEPROVIDERID", nullable = false)
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	
	@Column(name = "SOURCEPOCKETTYPE", precision = 10, scale = 0)
	public Long getSourcepockettype() {
		return this.sourcepockettype;
	}

	public void setSourcepockettype(Long sourcepockettype) {
		this.sourcepockettype = sourcepockettype;
	}

	@Column(name = "DESTPOCKETTYPE", precision = 10, scale = 0)
	public Long getDestpockettype() {
		return this.destpockettype;
	}

	public void setDestpockettype(Long destpockettype) {
		this.destpockettype = destpockettype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceDefualtConfig")
	public Set<PartnerDefaultServices> getPartnerDefaultServiceses() {
		return this.partnerDefaultServiceses;
	}

	public void setPartnerDefaultServiceses(
			Set<PartnerDefaultServices> partnerDefaultServiceses) {
		this.partnerDefaultServiceses = partnerDefaultServiceses;
	}

}
