package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "SERVICE")
public class Service extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	public static final String FieldName_ServiceName = "servicename";
	
	private MfinoServiceProvider mfinoServiceProvider;
	private String servicename;
	private String displayname;
	private Set<TransactionRule> transactionRules = new HashSet<TransactionRule>(
			0);
	private Set<ActorChannelMapping> actorChannelMappings = new HashSet<ActorChannelMapping>(
			0);
	private Set<MfaTransactionsInfo> mfaTransactionsInfos = new HashSet<MfaTransactionsInfo>(
			0);
	private Set<ServiceDefualtConfig> serviceDefualtConfigs = new HashSet<ServiceDefualtConfig>(
			0);
	private Set<PartnerServices> partnerServiceses = new HashSet<PartnerServices>(
			0);
	private Set<ServiceTransaction> serviceTransactions = new HashSet<ServiceTransaction>(
			0);
	private Set<RuleKey> ruleKeys = new HashSet<RuleKey>(0);
	private Set<SctlSettlementMap> sctlSettlementMaps = new HashSet<SctlSettlementMap>(
			0);

	public Service() {
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	
	@Column(name = "SERVICENAME", length = 1020)
	public String getServicename() {
		return this.servicename;
	}

	public void setServicename(String servicename) {
		this.servicename = servicename;
	}

	@Column(name = "DISPLAYNAME", length = 1020)
	public String getDisplayname() {
		return this.displayname;
	}

	public void setDisplayname(String displayname) {
		this.displayname = displayname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<TransactionRule> getTransactionRules() {
		return this.transactionRules;
	}

	public void setTransactionRules(Set<TransactionRule> transactionRules) {
		this.transactionRules = transactionRules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<ActorChannelMapping> getActorChannelMappings() {
		return this.actorChannelMappings;
	}

	public void setActorChannelMappings(
			Set<ActorChannelMapping> actorChannelMappings) {
		this.actorChannelMappings = actorChannelMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<MfaTransactionsInfo> getMfaTransactionsInfos() {
		return this.mfaTransactionsInfos;
	}

	public void setMfaTransactionsInfos(
			Set<MfaTransactionsInfo> mfaTransactionsInfos) {
		this.mfaTransactionsInfos = mfaTransactionsInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<ServiceDefualtConfig> getServiceDefualtConfigs() {
		return this.serviceDefualtConfigs;
	}

	public void setServiceDefualtConfigs(
			Set<ServiceDefualtConfig> serviceDefualtConfigs) {
		this.serviceDefualtConfigs = serviceDefualtConfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<PartnerServices> getPartnerServiceses() {
		return this.partnerServiceses;
	}

	public void setPartnerServiceses(Set<PartnerServices> partnerServiceses) {
		this.partnerServiceses = partnerServiceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<ServiceTransaction> getServiceTransactions() {
		return this.serviceTransactions;
	}

	public void setServiceTransactions(
			Set<ServiceTransaction> serviceTransactions) {
		this.serviceTransactions = serviceTransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<RuleKey> getRuleKeys() {
		return this.ruleKeys;
	}

	public void setRuleKeys(Set<RuleKey> ruleKeys) {
		this.ruleKeys = ruleKeys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<SctlSettlementMap> getSctlSettlementMaps() {
		return this.sctlSettlementMaps;
	}

	public void setSctlSettlementMaps(Set<SctlSettlementMap> sctlSettlementMaps) {
		this.sctlSettlementMaps = sctlSettlementMaps;
	}

}
