package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * ServiceDefualtConfig generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_DEFUALT_CONFIG")
public class ServiceDefualtConfig implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Service service;
	private Partner partner;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private Long sourcepockettype;
	private Long destpockettype;
	private Set<PartnerDefaultServices> partnerDefaultServiceses = new HashSet<PartnerDefaultServices>(
			0);

	public ServiceDefualtConfig() {
	}

	public ServiceDefualtConfig(BigDecimal id, Service service,
			Partner partner, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby) {
		this.id = id;
		this.service = service;
		this.partner = partner;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public ServiceDefualtConfig(BigDecimal id, Service service,
			Partner partner, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, Long sourcepockettype,
			Long destpockettype,
			Set<PartnerDefaultServices> partnerDefaultServiceses) {
		this.id = id;
		this.service = service;
		this.partner = partner;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sourcepockettype = sourcepockettype;
		this.destpockettype = destpockettype;
		this.partnerDefaultServiceses = partnerDefaultServiceses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEID", nullable = false)
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICEPROVIDERID", nullable = false)
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SOURCEPOCKETTYPE", precision = 10, scale = 0)
	public Long getSourcepockettype() {
		return this.sourcepockettype;
	}

	public void setSourcepockettype(Long sourcepockettype) {
		this.sourcepockettype = sourcepockettype;
	}

	@Column(name = "DESTPOCKETTYPE", precision = 10, scale = 0)
	public Long getDestpockettype() {
		return this.destpockettype;
	}

	public void setDestpockettype(Long destpockettype) {
		this.destpockettype = destpockettype;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceDefualtConfig")
	public Set<PartnerDefaultServices> getPartnerDefaultServiceses() {
		return this.partnerDefaultServiceses;
	}

	public void setPartnerDefaultServiceses(
			Set<PartnerDefaultServices> partnerDefaultServiceses) {
		this.partnerDefaultServiceses = partnerDefaultServiceses;
	}

}
