package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import com.mfino.hibernate.Timestamp;

/**
 * SettlementTxnSctlMap generated by hbm2java
 */
@Entity
@Table(name = "SETTLEMENT_TXN_SCTL_MAP")
public class SettlementTxnSctlMap extends Base implements java.io.Serializable {

	
	private SettlementTxnLog settlementTxnLog;
	private ServiceChargeTxnLog serviceChargeTxnLog;
	private long status;
	private BigDecimal mspid;

	public SettlementTxnSctlMap() {
	}

	public SettlementTxnSctlMap(BigDecimal id,
			SettlementTxnLog settlementTxnLog,
			ServiceChargeTxnLog serviceChargeTxnLog,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, long status,
			BigDecimal mspid) {
		this.id = id;
		this.settlementTxnLog = settlementTxnLog;
		this.serviceChargeTxnLog = serviceChargeTxnLog;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.status = status;
		this.mspid = mspid;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STLID", nullable = false)
	public SettlementTxnLog getSettlementTxnLog() {
		return this.settlementTxnLog;
	}

	public void setSettlementTxnLog(SettlementTxnLog settlementTxnLog) {
		this.settlementTxnLog = settlementTxnLog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCTLID", nullable = false)
	public ServiceChargeTxnLog getServiceChargeTxnLog() {
		return this.serviceChargeTxnLog;
	}

	public void setServiceChargeTxnLog(ServiceChargeTxnLog serviceChargeTxnLog) {
		this.serviceChargeTxnLog = serviceChargeTxnLog;
	}

	

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "MSPID", nullable = false, scale = 0)
	public BigDecimal getMspid() {
		return this.mspid;
	}

	public void setMspid(BigDecimal mspid) {
		this.mspid = mspid;
	}

}
