package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * SettlementScheduleLog generated by hbm2java
 */
@Entity
@Table(name = "SETTLEMENT_SCHEDULE_LOG")
public class SettlementScheduleLog implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal mspid;
	private BigDecimal partnerservicesid;
	private BigDecimal servicesettlementconfigid;
	private String qrtzjobid;
	private Short isscheduled;
	private String reasontext;
	private Serializable lastsettled;
	private Serializable nextsettle;

	public SettlementScheduleLog() {
	}

	public SettlementScheduleLog(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal mspid, BigDecimal partnerservicesid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mspid = mspid;
		this.partnerservicesid = partnerservicesid;
	}

	public SettlementScheduleLog(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal mspid, BigDecimal partnerservicesid,
			BigDecimal servicesettlementconfigid, String qrtzjobid,
			Short isscheduled, String reasontext, Serializable lastsettled,
			Serializable nextsettle) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mspid = mspid;
		this.partnerservicesid = partnerservicesid;
		this.servicesettlementconfigid = servicesettlementconfigid;
		this.qrtzjobid = qrtzjobid;
		this.isscheduled = isscheduled;
		this.reasontext = reasontext;
		this.lastsettled = lastsettled;
		this.nextsettle = nextsettle;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MSPID", nullable = false, scale = 0)
	public BigDecimal getMspid() {
		return this.mspid;
	}

	public void setMspid(BigDecimal mspid) {
		this.mspid = mspid;
	}

	@Column(name = "PARTNERSERVICESID", nullable = false, scale = 0)
	public BigDecimal getPartnerservicesid() {
		return this.partnerservicesid;
	}

	public void setPartnerservicesid(BigDecimal partnerservicesid) {
		this.partnerservicesid = partnerservicesid;
	}

	@Column(name = "SERVICESETTLEMENTCONFIGID", scale = 0)
	public BigDecimal getServicesettlementconfigid() {
		return this.servicesettlementconfigid;
	}

	public void setServicesettlementconfigid(
			BigDecimal servicesettlementconfigid) {
		this.servicesettlementconfigid = servicesettlementconfigid;
	}

	@Column(name = "QRTZJOBID", length = 1020)
	public String getQrtzjobid() {
		return this.qrtzjobid;
	}

	public void setQrtzjobid(String qrtzjobid) {
		this.qrtzjobid = qrtzjobid;
	}

	@Column(name = "ISSCHEDULED", precision = 3, scale = 0)
	public Short getIsscheduled() {
		return this.isscheduled;
	}

	public void setIsscheduled(Short isscheduled) {
		this.isscheduled = isscheduled;
	}

	@Column(name = "REASONTEXT", length = 1020)
	public String getReasontext() {
		return this.reasontext;
	}

	public void setReasontext(String reasontext) {
		this.reasontext = reasontext;
	}

	@Column(name = "LASTSETTLED")
	public Serializable getLastsettled() {
		return this.lastsettled;
	}

	public void setLastsettled(Serializable lastsettled) {
		this.lastsettled = lastsettled;
	}

	@Column(name = "NEXTSETTLE")
	public Serializable getNextsettle() {
		return this.nextsettle;
	}

	public void setNextsettle(Serializable nextsettle) {
		this.nextsettle = nextsettle;
	}

}
