package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * SmscConfiguration generated by hbm2java
 */
@Entity
@Table(name = "SMSC_CONFIGURATION", uniqueConstraints = @UniqueConstraint(columnNames = "SHORTCODE"))
public class SmscConfiguration implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private SmsPartner smsPartner;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String shortcode;
	private String longnumber;
	private String smartfrensmscid;
	private String otherlocaloperatorsmscid;
	private BigDecimal charging;
	private String header;
	private String footer;

	public SmscConfiguration() {
	}

	public SmscConfiguration(BigDecimal id, SmsPartner smsPartner,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby) {
		this.id = id;
		this.smsPartner = smsPartner;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public SmscConfiguration(BigDecimal id, SmsPartner smsPartner,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String shortcode,
			String longnumber, String smartfrensmscid,
			String otherlocaloperatorsmscid, BigDecimal charging,
			String header, String footer) {
		this.id = id;
		this.smsPartner = smsPartner;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.shortcode = shortcode;
		this.longnumber = longnumber;
		this.smartfrensmscid = smartfrensmscid;
		this.otherlocaloperatorsmscid = otherlocaloperatorsmscid;
		this.charging = charging;
		this.header = header;
		this.footer = footer;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARTNERID", nullable = false)
	public SmsPartner getSmsPartner() {
		return this.smsPartner;
	}

	public void setSmsPartner(SmsPartner smsPartner) {
		this.smsPartner = smsPartner;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SHORTCODE", unique = true, length = 1020)
	public String getShortcode() {
		return this.shortcode;
	}

	public void setShortcode(String shortcode) {
		this.shortcode = shortcode;
	}

	@Column(name = "LONGNUMBER", length = 1020)
	public String getLongnumber() {
		return this.longnumber;
	}

	public void setLongnumber(String longnumber) {
		this.longnumber = longnumber;
	}

	@Column(name = "SMARTFRENSMSCID", length = 1020)
	public String getSmartfrensmscid() {
		return this.smartfrensmscid;
	}

	public void setSmartfrensmscid(String smartfrensmscid) {
		this.smartfrensmscid = smartfrensmscid;
	}

	@Column(name = "OTHERLOCALOPERATORSMSCID", length = 1020)
	public String getOtherlocaloperatorsmscid() {
		return this.otherlocaloperatorsmscid;
	}

	public void setOtherlocaloperatorsmscid(String otherlocaloperatorsmscid) {
		this.otherlocaloperatorsmscid = otherlocaloperatorsmscid;
	}

	@Column(name = "CHARGING", precision = 25, scale = 4)
	public BigDecimal getCharging() {
		return this.charging;
	}

	public void setCharging(BigDecimal charging) {
		this.charging = charging;
	}

	@Column(name = "HEADER", length = 1020)
	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	@Column(name = "FOOTER", length = 1020)
	public String getFooter() {
		return this.footer;
	}

	public void setFooter(String footer) {
		this.footer = footer;
	}

}
