package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SmsPartner generated by hbm2java
 */
@Entity
@Table(name = "SMS_PARTNER")
public class SmsPartner extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_PartnerName = "partnername";
	private MfinoUser mfinoUser;
	private String partnername;
	private String contactname;
	private String contactphone;
	private String contactemail;
	private String serverip;
	private String apikey;
	private Short sendreport;
	private Set<SmscConfiguration> smscConfigurations = new HashSet<SmscConfiguration>(
			0);
	private Set<SmsTransactionLog> smsTransactionLogs = new HashSet<SmsTransactionLog>(
			0);

	public SmsPartner() {
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID", nullable = false)
	public MfinoUser getMfinoUser() {
		return this.mfinoUser;
	}

	public void setMfinoUser(MfinoUser mfinoUser) {
		this.mfinoUser = mfinoUser;
	}

	

	@Column(name = "PARTNERNAME", nullable = false, length = 1020)
	public String getPartnername() {
		return this.partnername;
	}

	public void setPartnername(String partnername) {
		this.partnername = partnername;
	}

	@Column(name = "CONTACTNAME", nullable = false, length = 1020)
	public String getContactname() {
		return this.contactname;
	}

	public void setContactname(String contactname) {
		this.contactname = contactname;
	}

	@Column(name = "CONTACTPHONE", nullable = false, length = 1020)
	public String getContactphone() {
		return this.contactphone;
	}

	public void setContactphone(String contactphone) {
		this.contactphone = contactphone;
	}

	@Column(name = "CONTACTEMAIL", nullable = false, length = 1020)
	public String getContactemail() {
		return this.contactemail;
	}

	public void setContactemail(String contactemail) {
		this.contactemail = contactemail;
	}

	@Column(name = "SERVERIP", nullable = false, length = 1020)
	public String getServerip() {
		return this.serverip;
	}

	public void setServerip(String serverip) {
		this.serverip = serverip;
	}

	@Column(name = "APIKEY", nullable = false, length = 1020)
	public String getApikey() {
		return this.apikey;
	}

	public void setApikey(String apikey) {
		this.apikey = apikey;
	}

	@Column(name = "SENDREPORT", precision = 3, scale = 0)
	public Short getSendreport() {
		return this.sendreport;
	}

	public void setSendreport(Short sendreport) {
		this.sendreport = sendreport;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "smsPartner")
	public Set<SmscConfiguration> getSmscConfigurations() {
		return this.smscConfigurations;
	}

	public void setSmscConfigurations(Set<SmscConfiguration> smscConfigurations) {
		this.smscConfigurations = smscConfigurations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "smsPartner")
	public Set<SmsTransactionLog> getSmsTransactionLogs() {
		return this.smsTransactionLogs;
	}

	public void setSmsTransactionLogs(Set<SmsTransactionLog> smsTransactionLogs) {
		this.smsTransactionLogs = smsTransactionLogs;
	}

}
