package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * SubscriberGroups generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIBER_GROUPS")
public class SubscriberGroup extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_Subscriber = "subscriberid";
	private Long subscriberid;
	private Long groupid;

	public SubscriberGroup() {
	}

	public SubscriberGroup(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public SubscriberGroup(BigDecimal id, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			Long subscriberid, Long groupid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.subscriberid = subscriberid;
		this.groupid = groupid;
	}

	

	@Column(name = "SUBSCRIBERID", precision = 10, scale = 0)
	public Long getSubscriberid() {
		return this.subscriberid;
	}

	public void setSubscriberid(Long subscriberid) {
		this.subscriberid = subscriberid;
	}

	@Column(name = "GROUPID", precision = 10, scale = 0)
	public Long getGroupid() {
		return this.groupid;
	}

	public void setGroupid(Long groupid) {
		this.groupid = groupid;
	}

}
