package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * SubscriberMdn generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIBER_MDN", uniqueConstraints = @UniqueConstraint(columnNames = "MDN"))
public class SubscriberMdn implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Subscriber subscriber;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String mdn;
	private String imsi;
	private String marketingcategory;
	private String idtype;
	private String idnumber;
	private String authenticationphonenumber;
	private long status;
	private String authenticationphrase;
	private long restrictions;
	private long wrongpincount;
	private String digestedpin;
	private String merchantdigestedpin;
	private String mdnbrand;
	private Serializable statustime;
	private Serializable activationtime;
	private Serializable lasttransactiontime;
	private BigDecimal lasttransactionid;
	private String h2hallowedip;
	private Short ismdnrecycled;
	private String scramblecode;
	private String otp;
	private Serializable otpexpirationtime;
	private String applicationid;
	private Short isforcecloserequested;
	private String authorizationtoken;
	private String userapikey;
	private String othermdn;
	private Long otpretrycount;
	private BigDecimal cashinfirsttimeid;
	private String isidlifetime;
	private String domaddridentity;
	private String ktpdocumentpath;
	private String subscriberformpath;
	private String supportingdocumentpath;
	private String closecomments;
	private BigDecimal upgradeacctstatus;
	private String upgradeacctapprovedby;
	private Serializable upgradeaccttime;
	private String upgradeacctcomments;
	private BigDecimal closeagent;
	private String closeuser;
	private String ktpid;
	private Set<MoneyClearanceGraved> moneyClearanceGravedsForRefundmdnid = new HashSet<MoneyClearanceGraved>(
			0);
	private Set<MoneyClearanceGraved> moneyClearanceGravedsForMdnid = new HashSet<MoneyClearanceGraved>(
			0);
	private Set<BulkLop> bulkLops = new HashSet<BulkLop>(0);
	private Set<PendingCommodityTransfer> pendingCommodityTransfers = new HashSet<PendingCommodityTransfer>(
			0);
	private Set<CloseAcctSetlMdn> closeAcctSetlMdns = new HashSet<CloseAcctSetlMdn>(
			0);
	private Set<Pocket> pockets = new HashSet<Pocket>(0);
	private Set<CommodityTransfer> commodityTransfers = new HashSet<CommodityTransfer>(
			0);
	private Set<ExcludeSubscriberLc> excludeSubscriberLcs = new HashSet<ExcludeSubscriberLc>(
			0);
	private Set<LetterOfPurchase> letterOfPurchases = new HashSet<LetterOfPurchase>(
			0);
	private Set<UnregisteredTxnInfo> unregisteredTxnInfos = new HashSet<UnregisteredTxnInfo>(
			0);
	private Set<ChannelSessionMgmt> channelSessionMgmts = new HashSet<ChannelSessionMgmt>(
			0);

	public SubscriberMdn() {
	}

	public SubscriberMdn(BigDecimal id, Subscriber subscriber,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String mdn, long status,
			long restrictions, long wrongpincount, Serializable statustime) {
		this.id = id;
		this.subscriber = subscriber;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mdn = mdn;
		this.status = status;
		this.restrictions = restrictions;
		this.wrongpincount = wrongpincount;
		this.statustime = statustime;
	}

	public SubscriberMdn(BigDecimal id, Subscriber subscriber,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String mdn, String imsi,
			String marketingcategory, String idtype, String idnumber,
			String authenticationphonenumber, long status,
			String authenticationphrase, long restrictions, long wrongpincount,
			String digestedpin, String merchantdigestedpin, String mdnbrand,
			Serializable statustime, Serializable activationtime,
			Serializable lasttransactiontime, BigDecimal lasttransactionid,
			String h2hallowedip, Short ismdnrecycled, String scramblecode,
			String otp, Serializable otpexpirationtime, String applicationid,
			Short isforcecloserequested, String authorizationtoken,
			String userapikey, String othermdn, Long otpretrycount,
			BigDecimal cashinfirsttimeid, String isidlifetime,
			String domaddridentity, String ktpdocumentpath,
			String subscriberformpath, String supportingdocumentpath,
			String closecomments, BigDecimal upgradeacctstatus,
			String upgradeacctapprovedby, Serializable upgradeaccttime,
			String upgradeacctcomments, BigDecimal closeagent,
			String closeuser, String ktpid,
			Set<MoneyClearanceGraved> moneyClearanceGravedsForRefundmdnid,
			Set<MoneyClearanceGraved> moneyClearanceGravedsForMdnid,
			Set<BulkLop> bulkLops,
			Set<PendingCommodityTransfer> pendingCommodityTransfers,
			Set<CloseAcctSetlMdn> closeAcctSetlMdns, Set<Pocket> pockets,
			Set<CommodityTransfer> commodityTransfers,
			Set<ExcludeSubscriberLc> excludeSubscriberLcs,
			Set<LetterOfPurchase> letterOfPurchases,
			Set<UnregisteredTxnInfo> unregisteredTxnInfos,
			Set<ChannelSessionMgmt> channelSessionMgmts) {
		this.id = id;
		this.subscriber = subscriber;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.mdn = mdn;
		this.imsi = imsi;
		this.marketingcategory = marketingcategory;
		this.idtype = idtype;
		this.idnumber = idnumber;
		this.authenticationphonenumber = authenticationphonenumber;
		this.status = status;
		this.authenticationphrase = authenticationphrase;
		this.restrictions = restrictions;
		this.wrongpincount = wrongpincount;
		this.digestedpin = digestedpin;
		this.merchantdigestedpin = merchantdigestedpin;
		this.mdnbrand = mdnbrand;
		this.statustime = statustime;
		this.activationtime = activationtime;
		this.lasttransactiontime = lasttransactiontime;
		this.lasttransactionid = lasttransactionid;
		this.h2hallowedip = h2hallowedip;
		this.ismdnrecycled = ismdnrecycled;
		this.scramblecode = scramblecode;
		this.otp = otp;
		this.otpexpirationtime = otpexpirationtime;
		this.applicationid = applicationid;
		this.isforcecloserequested = isforcecloserequested;
		this.authorizationtoken = authorizationtoken;
		this.userapikey = userapikey;
		this.othermdn = othermdn;
		this.otpretrycount = otpretrycount;
		this.cashinfirsttimeid = cashinfirsttimeid;
		this.isidlifetime = isidlifetime;
		this.domaddridentity = domaddridentity;
		this.ktpdocumentpath = ktpdocumentpath;
		this.subscriberformpath = subscriberformpath;
		this.supportingdocumentpath = supportingdocumentpath;
		this.closecomments = closecomments;
		this.upgradeacctstatus = upgradeacctstatus;
		this.upgradeacctapprovedby = upgradeacctapprovedby;
		this.upgradeaccttime = upgradeaccttime;
		this.upgradeacctcomments = upgradeacctcomments;
		this.closeagent = closeagent;
		this.closeuser = closeuser;
		this.ktpid = ktpid;
		this.moneyClearanceGravedsForRefundmdnid = moneyClearanceGravedsForRefundmdnid;
		this.moneyClearanceGravedsForMdnid = moneyClearanceGravedsForMdnid;
		this.bulkLops = bulkLops;
		this.pendingCommodityTransfers = pendingCommodityTransfers;
		this.closeAcctSetlMdns = closeAcctSetlMdns;
		this.pockets = pockets;
		this.commodityTransfers = commodityTransfers;
		this.excludeSubscriberLcs = excludeSubscriberLcs;
		this.letterOfPurchases = letterOfPurchases;
		this.unregisteredTxnInfos = unregisteredTxnInfos;
		this.channelSessionMgmts = channelSessionMgmts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERID", nullable = false)
	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "MDN", unique = true, nullable = false, length = 1020)
	public String getMdn() {
		return this.mdn;
	}

	public void setMdn(String mdn) {
		this.mdn = mdn;
	}

	@Column(name = "IMSI", length = 1020)
	public String getImsi() {
		return this.imsi;
	}

	public void setImsi(String imsi) {
		this.imsi = imsi;
	}

	@Column(name = "MARKETINGCATEGORY", length = 1020)
	public String getMarketingcategory() {
		return this.marketingcategory;
	}

	public void setMarketingcategory(String marketingcategory) {
		this.marketingcategory = marketingcategory;
	}

	@Column(name = "IDTYPE", length = 1020)
	public String getIdtype() {
		return this.idtype;
	}

	public void setIdtype(String idtype) {
		this.idtype = idtype;
	}

	@Column(name = "IDNUMBER", length = 1020)
	public String getIdnumber() {
		return this.idnumber;
	}

	public void setIdnumber(String idnumber) {
		this.idnumber = idnumber;
	}

	@Column(name = "AUTHENTICATIONPHONENUMBER", length = 1020)
	public String getAuthenticationphonenumber() {
		return this.authenticationphonenumber;
	}

	public void setAuthenticationphonenumber(String authenticationphonenumber) {
		this.authenticationphonenumber = authenticationphonenumber;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "AUTHENTICATIONPHRASE", length = 1020)
	public String getAuthenticationphrase() {
		return this.authenticationphrase;
	}

	public void setAuthenticationphrase(String authenticationphrase) {
		this.authenticationphrase = authenticationphrase;
	}

	@Column(name = "RESTRICTIONS", nullable = false, precision = 10, scale = 0)
	public long getRestrictions() {
		return this.restrictions;
	}

	public void setRestrictions(long restrictions) {
		this.restrictions = restrictions;
	}

	@Column(name = "WRONGPINCOUNT", nullable = false, precision = 10, scale = 0)
	public long getWrongpincount() {
		return this.wrongpincount;
	}

	public void setWrongpincount(long wrongpincount) {
		this.wrongpincount = wrongpincount;
	}

	@Column(name = "DIGESTEDPIN", length = 1020)
	public String getDigestedpin() {
		return this.digestedpin;
	}

	public void setDigestedpin(String digestedpin) {
		this.digestedpin = digestedpin;
	}

	@Column(name = "MERCHANTDIGESTEDPIN", length = 1020)
	public String getMerchantdigestedpin() {
		return this.merchantdigestedpin;
	}

	public void setMerchantdigestedpin(String merchantdigestedpin) {
		this.merchantdigestedpin = merchantdigestedpin;
	}

	@Column(name = "MDNBRAND", length = 1020)
	public String getMdnbrand() {
		return this.mdnbrand;
	}

	public void setMdnbrand(String mdnbrand) {
		this.mdnbrand = mdnbrand;
	}

	@Column(name = "STATUSTIME", nullable = false)
	public Serializable getStatustime() {
		return this.statustime;
	}

	public void setStatustime(Serializable statustime) {
		this.statustime = statustime;
	}

	@Column(name = "ACTIVATIONTIME")
	public Serializable getActivationtime() {
		return this.activationtime;
	}

	public void setActivationtime(Serializable activationtime) {
		this.activationtime = activationtime;
	}

	@Column(name = "LASTTRANSACTIONTIME")
	public Serializable getLasttransactiontime() {
		return this.lasttransactiontime;
	}

	public void setLasttransactiontime(Serializable lasttransactiontime) {
		this.lasttransactiontime = lasttransactiontime;
	}

	@Column(name = "LASTTRANSACTIONID", scale = 0)
	public BigDecimal getLasttransactionid() {
		return this.lasttransactionid;
	}

	public void setLasttransactionid(BigDecimal lasttransactionid) {
		this.lasttransactionid = lasttransactionid;
	}

	@Column(name = "H2HALLOWEDIP", length = 1020)
	public String getH2hallowedip() {
		return this.h2hallowedip;
	}

	public void setH2hallowedip(String h2hallowedip) {
		this.h2hallowedip = h2hallowedip;
	}

	@Column(name = "ISMDNRECYCLED", precision = 3, scale = 0)
	public Short getIsmdnrecycled() {
		return this.ismdnrecycled;
	}

	public void setIsmdnrecycled(Short ismdnrecycled) {
		this.ismdnrecycled = ismdnrecycled;
	}

	@Column(name = "SCRAMBLECODE", length = 1020)
	public String getScramblecode() {
		return this.scramblecode;
	}

	public void setScramblecode(String scramblecode) {
		this.scramblecode = scramblecode;
	}

	@Column(name = "OTP", length = 1020)
	public String getOtp() {
		return this.otp;
	}

	public void setOtp(String otp) {
		this.otp = otp;
	}

	@Column(name = "OTPEXPIRATIONTIME")
	public Serializable getOtpexpirationtime() {
		return this.otpexpirationtime;
	}

	public void setOtpexpirationtime(Serializable otpexpirationtime) {
		this.otpexpirationtime = otpexpirationtime;
	}

	@Column(name = "APPLICATIONID", length = 1020)
	public String getApplicationid() {
		return this.applicationid;
	}

	public void setApplicationid(String applicationid) {
		this.applicationid = applicationid;
	}

	@Column(name = "ISFORCECLOSEREQUESTED", precision = 3, scale = 0)
	public Short getIsforcecloserequested() {
		return this.isforcecloserequested;
	}

	public void setIsforcecloserequested(Short isforcecloserequested) {
		this.isforcecloserequested = isforcecloserequested;
	}

	@Column(name = "AUTHORIZATIONTOKEN")
	public String getAuthorizationtoken() {
		return this.authorizationtoken;
	}

	public void setAuthorizationtoken(String authorizationtoken) {
		this.authorizationtoken = authorizationtoken;
	}

	@Column(name = "USERAPIKEY")
	public String getUserapikey() {
		return this.userapikey;
	}

	public void setUserapikey(String userapikey) {
		this.userapikey = userapikey;
	}

	@Column(name = "OTHERMDN", length = 1020)
	public String getOthermdn() {
		return this.othermdn;
	}

	public void setOthermdn(String othermdn) {
		this.othermdn = othermdn;
	}

	@Column(name = "OTPRETRYCOUNT", precision = 10, scale = 0)
	public Long getOtpretrycount() {
		return this.otpretrycount;
	}

	public void setOtpretrycount(Long otpretrycount) {
		this.otpretrycount = otpretrycount;
	}

	@Column(name = "CASHINFIRSTTIMEID", scale = 0)
	public BigDecimal getCashinfirsttimeid() {
		return this.cashinfirsttimeid;
	}

	public void setCashinfirsttimeid(BigDecimal cashinfirsttimeid) {
		this.cashinfirsttimeid = cashinfirsttimeid;
	}

	@Column(name = "ISIDLIFETIME", length = 2)
	public String getIsidlifetime() {
		return this.isidlifetime;
	}

	public void setIsidlifetime(String isidlifetime) {
		this.isidlifetime = isidlifetime;
	}

	@Column(name = "DOMADDRIDENTITY", length = 2)
	public String getDomaddridentity() {
		return this.domaddridentity;
	}

	public void setDomaddridentity(String domaddridentity) {
		this.domaddridentity = domaddridentity;
	}

	@Column(name = "KTPDOCUMENTPATH")
	public String getKtpdocumentpath() {
		return this.ktpdocumentpath;
	}

	public void setKtpdocumentpath(String ktpdocumentpath) {
		this.ktpdocumentpath = ktpdocumentpath;
	}

	@Column(name = "SUBSCRIBERFORMPATH")
	public String getSubscriberformpath() {
		return this.subscriberformpath;
	}

	public void setSubscriberformpath(String subscriberformpath) {
		this.subscriberformpath = subscriberformpath;
	}

	@Column(name = "SUPPORTINGDOCUMENTPATH")
	public String getSupportingdocumentpath() {
		return this.supportingdocumentpath;
	}

	public void setSupportingdocumentpath(String supportingdocumentpath) {
		this.supportingdocumentpath = supportingdocumentpath;
	}

	@Column(name = "CLOSECOMMENTS", length = 512)
	public String getClosecomments() {
		return this.closecomments;
	}

	public void setClosecomments(String closecomments) {
		this.closecomments = closecomments;
	}

	@Column(name = "UPGRADEACCTSTATUS", precision = 22, scale = 0)
	public BigDecimal getUpgradeacctstatus() {
		return this.upgradeacctstatus;
	}

	public void setUpgradeacctstatus(BigDecimal upgradeacctstatus) {
		this.upgradeacctstatus = upgradeacctstatus;
	}

	@Column(name = "UPGRADEACCTAPPROVEDBY")
	public String getUpgradeacctapprovedby() {
		return this.upgradeacctapprovedby;
	}

	public void setUpgradeacctapprovedby(String upgradeacctapprovedby) {
		this.upgradeacctapprovedby = upgradeacctapprovedby;
	}

	@Column(name = "UPGRADEACCTTIME")
	public Serializable getUpgradeaccttime() {
		return this.upgradeaccttime;
	}

	public void setUpgradeaccttime(Serializable upgradeaccttime) {
		this.upgradeaccttime = upgradeaccttime;
	}

	@Column(name = "UPGRADEACCTCOMMENTS")
	public String getUpgradeacctcomments() {
		return this.upgradeacctcomments;
	}

	public void setUpgradeacctcomments(String upgradeacctcomments) {
		this.upgradeacctcomments = upgradeacctcomments;
	}

	@Column(name = "CLOSEAGENT", scale = 0)
	public BigDecimal getCloseagent() {
		return this.closeagent;
	}

	public void setCloseagent(BigDecimal closeagent) {
		this.closeagent = closeagent;
	}

	@Column(name = "CLOSEUSER")
	public String getCloseuser() {
		return this.closeuser;
	}

	public void setCloseuser(String closeuser) {
		this.closeuser = closeuser;
	}

	@Column(name = "KTPID", length = 50)
	public String getKtpid() {
		return this.ktpid;
	}

	public void setKtpid(String ktpid) {
		this.ktpid = ktpid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdnByRefundmdnid")
	public Set<MoneyClearanceGraved> getMoneyClearanceGravedsForRefundmdnid() {
		return this.moneyClearanceGravedsForRefundmdnid;
	}

	public void setMoneyClearanceGravedsForRefundmdnid(
			Set<MoneyClearanceGraved> moneyClearanceGravedsForRefundmdnid) {
		this.moneyClearanceGravedsForRefundmdnid = moneyClearanceGravedsForRefundmdnid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdnByMdnid")
	public Set<MoneyClearanceGraved> getMoneyClearanceGravedsForMdnid() {
		return this.moneyClearanceGravedsForMdnid;
	}

	public void setMoneyClearanceGravedsForMdnid(
			Set<MoneyClearanceGraved> moneyClearanceGravedsForMdnid) {
		this.moneyClearanceGravedsForMdnid = moneyClearanceGravedsForMdnid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<BulkLop> getBulkLops() {
		return this.bulkLops;
	}

	public void setBulkLops(Set<BulkLop> bulkLops) {
		this.bulkLops = bulkLops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<PendingCommodityTransfer> getPendingCommodityTransfers() {
		return this.pendingCommodityTransfers;
	}

	public void setPendingCommodityTransfers(
			Set<PendingCommodityTransfer> pendingCommodityTransfers) {
		this.pendingCommodityTransfers = pendingCommodityTransfers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<CloseAcctSetlMdn> getCloseAcctSetlMdns() {
		return this.closeAcctSetlMdns;
	}

	public void setCloseAcctSetlMdns(Set<CloseAcctSetlMdn> closeAcctSetlMdns) {
		this.closeAcctSetlMdns = closeAcctSetlMdns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<Pocket> getPockets() {
		return this.pockets;
	}

	public void setPockets(Set<Pocket> pockets) {
		this.pockets = pockets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<CommodityTransfer> getCommodityTransfers() {
		return this.commodityTransfers;
	}

	public void setCommodityTransfers(Set<CommodityTransfer> commodityTransfers) {
		this.commodityTransfers = commodityTransfers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<ExcludeSubscriberLc> getExcludeSubscriberLcs() {
		return this.excludeSubscriberLcs;
	}

	public void setExcludeSubscriberLcs(
			Set<ExcludeSubscriberLc> excludeSubscriberLcs) {
		this.excludeSubscriberLcs = excludeSubscriberLcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<LetterOfPurchase> getLetterOfPurchases() {
		return this.letterOfPurchases;
	}

	public void setLetterOfPurchases(Set<LetterOfPurchase> letterOfPurchases) {
		this.letterOfPurchases = letterOfPurchases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<UnregisteredTxnInfo> getUnregisteredTxnInfos() {
		return this.unregisteredTxnInfos;
	}

	public void setUnregisteredTxnInfos(
			Set<UnregisteredTxnInfo> unregisteredTxnInfos) {
		this.unregisteredTxnInfos = unregisteredTxnInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriberMdn")
	public Set<ChannelSessionMgmt> getChannelSessionMgmts() {
		return this.channelSessionMgmts;
	}

	public void setChannelSessionMgmts(
			Set<ChannelSessionMgmt> channelSessionMgmts) {
		this.channelSessionMgmts = channelSessionMgmts;
	}

}
