package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * SubscriberStatusEvent generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIBER_STATUS_EVENT")
public class SubscriberStatusEvent implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal subscriberid;
	private Serializable pickupdatetime;
	private Short processingstatus;
	private long statusonpickup;
	private long subscribertype;

	public SubscriberStatusEvent() {
	}

	public SubscriberStatusEvent(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal subscriberid, Serializable pickupdatetime,
			long statusonpickup, long subscribertype) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.subscriberid = subscriberid;
		this.pickupdatetime = pickupdatetime;
		this.statusonpickup = statusonpickup;
		this.subscribertype = subscribertype;
	}

	public SubscriberStatusEvent(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal subscriberid, Serializable pickupdatetime,
			Short processingstatus, long statusonpickup, long subscribertype) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.subscriberid = subscriberid;
		this.pickupdatetime = pickupdatetime;
		this.processingstatus = processingstatus;
		this.statusonpickup = statusonpickup;
		this.subscribertype = subscribertype;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SUBSCRIBERID", nullable = false, scale = 0)
	public BigDecimal getSubscriberid() {
		return this.subscriberid;
	}

	public void setSubscriberid(BigDecimal subscriberid) {
		this.subscriberid = subscriberid;
	}

	@Column(name = "PICKUPDATETIME", nullable = false)
	public Serializable getPickupdatetime() {
		return this.pickupdatetime;
	}

	public void setPickupdatetime(Serializable pickupdatetime) {
		this.pickupdatetime = pickupdatetime;
	}

	@Column(name = "PROCESSINGSTATUS", precision = 3, scale = 0)
	public Short getProcessingstatus() {
		return this.processingstatus;
	}

	public void setProcessingstatus(Short processingstatus) {
		this.processingstatus = processingstatus;
	}

	@Column(name = "STATUSONPICKUP", nullable = false, precision = 10, scale = 0)
	public long getStatusonpickup() {
		return this.statusonpickup;
	}

	public void setStatusonpickup(long statusonpickup) {
		this.statusonpickup = statusonpickup;
	}

	@Column(name = "SUBSCRIBERTYPE", nullable = false, precision = 10, scale = 0)
	public long getSubscribertype() {
		return this.subscribertype;
	}

	public void setSubscribertype(long subscribertype) {
		this.subscribertype = subscribertype;
	}

}
