package com.mfino.domain;

// Generated Sep 27, 2016 2:09:23 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Subscriber generated by hbm2java
 */
@Entity
@Table(name = "SUBSCRIBER")
public class Subscriber implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Address addressBySubscriberaddressid;
	private Address addressBySubscriberaddressktpid;
	private MfinoUser mfinoUserBySubscriberuserid;
	private MfinoUser mfinoUserByUserid;
	private MfinoServiceProvider mfinoServiceProvider;
	private KycLevel kycLevel;
	private Company company;
	private AuthPersonDetails authPersonDetails;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal parentid;
	private String firstname;
	private String lastname;
	private String gender;
	private String birthplace;
	private Serializable dateofbirth;
	private String mdnbrand;
	private String email;
	private Long notificationmethod;
	private long language;
	private String currency;
	private String timezone;
	private long restrictions;
	private long type;
	private long status;
	private Serializable statustime;
	private Serializable activationtime;
	private Serializable approveorrejecttime;
	private String approvedorrejectedby;
	private String approveorrejectcomment;
	private String appliedby;
	private Serializable appliedtime;
	private short dompetmerchant;
	private String securityquestion;
	private String securityanswer;
	private Long partnertype;
	private BigDecimal upgradablekyclevel;
	private Long upgradestate;
	private Serializable idexiparetiontime;
	private BigDecimal referenceaccount;
	private String aliasname;
	private Short detailsrequired;
	private Long registrationmedium;
	private BigDecimal registeringpartnerid;
	private Long approvalidnumber;
	private Serializable lastnotificationtime;
	private String nickname;
	private Short isemailverified;
	private String mothersmaidenname;
	private Set<SubscriberMdn> subscriberMdns = new HashSet<SubscriberMdn>(0);
	private Set<BillPaymentTxn> billPaymentTxns = new HashSet<BillPaymentTxn>(0);
	private Set<SubscriberAddiInfo> subscriberAddiInfos = new HashSet<SubscriberAddiInfo>(
			0);
	private Set<SubscriberFavorite> subscriberFavorites = new HashSet<SubscriberFavorite>(
			0);
	private Merchant merchant;
	private Set<Person2Person> person2Persons = new HashSet<Person2Person>(0);
	private Set<PendingCommodityTransfer> pendingCommodityTransfers = new HashSet<PendingCommodityTransfer>(
			0);
	private Set<BulkUpload> bulkUploads = new HashSet<BulkUpload>(0);
	private Set<CardInfo> cardInfos = new HashSet<CardInfo>(0);
	private Set<TxnAmountDstrbLog> txnAmountDstrbLogs = new HashSet<TxnAmountDstrbLog>(
			0);
	private Set<CommodityTransfer> commodityTransfers = new HashSet<CommodityTransfer>(
			0);
	private Set<CreditcardDestinations> creditcardDestinationses = new HashSet<CreditcardDestinations>(
			0);
	private Set<CreditCardTransaction> creditCardTransactions = new HashSet<CreditCardTransaction>(
			0);
	private Set<Partner> partners = new HashSet<Partner>(0);

	public Subscriber() {
	}

	public Subscriber(BigDecimal id, MfinoServiceProvider mfinoServiceProvider,
			Company company, Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal parentid,
			long language, String currency, long restrictions, long type,
			long status, Serializable statustime, short dompetmerchant) {
		this.id = id;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.company = company;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.parentid = parentid;
		this.language = language;
		this.currency = currency;
		this.restrictions = restrictions;
		this.type = type;
		this.status = status;
		this.statustime = statustime;
		this.dompetmerchant = dompetmerchant;
	}

	public Subscriber(BigDecimal id, Address addressBySubscriberaddressid,
			Address addressBySubscriberaddressktpid,
			MfinoUser mfinoUserBySubscriberuserid, MfinoUser mfinoUserByUserid,
			MfinoServiceProvider mfinoServiceProvider, KycLevel kycLevel,
			Company company, AuthPersonDetails authPersonDetails,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, BigDecimal parentid,
			String firstname, String lastname, String gender,
			String birthplace, Serializable dateofbirth, String mdnbrand,
			String email, Long notificationmethod, long language,
			String currency, String timezone, long restrictions, long type,
			long status, Serializable statustime, Serializable activationtime,
			Serializable approveorrejecttime, String approvedorrejectedby,
			String approveorrejectcomment, String appliedby,
			Serializable appliedtime, short dompetmerchant,
			String securityquestion, String securityanswer, Long partnertype,
			BigDecimal upgradablekyclevel, Long upgradestate,
			Serializable idexiparetiontime, BigDecimal referenceaccount,
			String aliasname, Short detailsrequired, Long registrationmedium,
			BigDecimal registeringpartnerid, Long approvalidnumber,
			Serializable lastnotificationtime, String nickname,
			Short isemailverified, String mothersmaidenname,
			Set<SubscriberMdn> subscriberMdns,
			Set<BillPaymentTxn> billPaymentTxns,
			Set<SubscriberAddiInfo> subscriberAddiInfos,
			Set<SubscriberFavorite> subscriberFavorites, Merchant merchant,
			Set<Person2Person> person2Persons,
			Set<PendingCommodityTransfer> pendingCommodityTransfers,
			Set<BulkUpload> bulkUploads, Set<CardInfo> cardInfos,
			Set<TxnAmountDstrbLog> txnAmountDstrbLogs,
			Set<CommodityTransfer> commodityTransfers,
			Set<CreditcardDestinations> creditcardDestinationses,
			Set<CreditCardTransaction> creditCardTransactions,
			Set<Partner> partners) {
		this.id = id;
		this.addressBySubscriberaddressid = addressBySubscriberaddressid;
		this.addressBySubscriberaddressktpid = addressBySubscriberaddressktpid;
		this.mfinoUserBySubscriberuserid = mfinoUserBySubscriberuserid;
		this.mfinoUserByUserid = mfinoUserByUserid;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.kycLevel = kycLevel;
		this.company = company;
		this.authPersonDetails = authPersonDetails;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.parentid = parentid;
		this.firstname = firstname;
		this.lastname = lastname;
		this.gender = gender;
		this.birthplace = birthplace;
		this.dateofbirth = dateofbirth;
		this.mdnbrand = mdnbrand;
		this.email = email;
		this.notificationmethod = notificationmethod;
		this.language = language;
		this.currency = currency;
		this.timezone = timezone;
		this.restrictions = restrictions;
		this.type = type;
		this.status = status;
		this.statustime = statustime;
		this.activationtime = activationtime;
		this.approveorrejecttime = approveorrejecttime;
		this.approvedorrejectedby = approvedorrejectedby;
		this.approveorrejectcomment = approveorrejectcomment;
		this.appliedby = appliedby;
		this.appliedtime = appliedtime;
		this.dompetmerchant = dompetmerchant;
		this.securityquestion = securityquestion;
		this.securityanswer = securityanswer;
		this.partnertype = partnertype;
		this.upgradablekyclevel = upgradablekyclevel;
		this.upgradestate = upgradestate;
		this.idexiparetiontime = idexiparetiontime;
		this.referenceaccount = referenceaccount;
		this.aliasname = aliasname;
		this.detailsrequired = detailsrequired;
		this.registrationmedium = registrationmedium;
		this.registeringpartnerid = registeringpartnerid;
		this.approvalidnumber = approvalidnumber;
		this.lastnotificationtime = lastnotificationtime;
		this.nickname = nickname;
		this.isemailverified = isemailverified;
		this.mothersmaidenname = mothersmaidenname;
		this.subscriberMdns = subscriberMdns;
		this.billPaymentTxns = billPaymentTxns;
		this.subscriberAddiInfos = subscriberAddiInfos;
		this.subscriberFavorites = subscriberFavorites;
		this.merchant = merchant;
		this.person2Persons = person2Persons;
		this.pendingCommodityTransfers = pendingCommodityTransfers;
		this.bulkUploads = bulkUploads;
		this.cardInfos = cardInfos;
		this.txnAmountDstrbLogs = txnAmountDstrbLogs;
		this.commodityTransfers = commodityTransfers;
		this.creditcardDestinationses = creditcardDestinationses;
		this.creditCardTransactions = creditCardTransactions;
		this.partners = partners;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERADDRESSID")
	public Address getAddressBySubscriberaddressid() {
		return this.addressBySubscriberaddressid;
	}

	public void setAddressBySubscriberaddressid(
			Address addressBySubscriberaddressid) {
		this.addressBySubscriberaddressid = addressBySubscriberaddressid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERADDRESSKTPID")
	public Address getAddressBySubscriberaddressktpid() {
		return this.addressBySubscriberaddressktpid;
	}

	public void setAddressBySubscriberaddressktpid(
			Address addressBySubscriberaddressktpid) {
		this.addressBySubscriberaddressktpid = addressBySubscriberaddressktpid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERUSERID")
	public MfinoUser getMfinoUserBySubscriberuserid() {
		return this.mfinoUserBySubscriberuserid;
	}

	public void setMfinoUserBySubscriberuserid(
			MfinoUser mfinoUserBySubscriberuserid) {
		this.mfinoUserBySubscriberuserid = mfinoUserBySubscriberuserid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USERID")
	public MfinoUser getMfinoUserByUserid() {
		return this.mfinoUserByUserid;
	}

	public void setMfinoUserByUserid(MfinoUser mfinoUserByUserid) {
		this.mfinoUserByUserid = mfinoUserByUserid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KYCLEVEL")
	public KycLevel getKycLevel() {
		return this.kycLevel;
	}

	public void setKycLevel(KycLevel kycLevel) {
		this.kycLevel = kycLevel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMPANYID", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AUTHORIZINGPERSONID")
	public AuthPersonDetails getAuthPersonDetails() {
		return this.authPersonDetails;
	}

	public void setAuthPersonDetails(AuthPersonDetails authPersonDetails) {
		this.authPersonDetails = authPersonDetails;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "PARENTID", nullable = false, scale = 0)
	public BigDecimal getParentid() {
		return this.parentid;
	}

	public void setParentid(BigDecimal parentid) {
		this.parentid = parentid;
	}

	@Column(name = "FIRSTNAME", length = 1020)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "LASTNAME", length = 1020)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "GENDER", length = 1020)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "BIRTHPLACE", length = 1020)
	public String getBirthplace() {
		return this.birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	@Column(name = "DATEOFBIRTH")
	public Serializable getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Serializable dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	@Column(name = "MDNBRAND", length = 1020)
	public String getMdnbrand() {
		return this.mdnbrand;
	}

	public void setMdnbrand(String mdnbrand) {
		this.mdnbrand = mdnbrand;
	}

	@Column(name = "EMAIL", length = 1020)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "NOTIFICATIONMETHOD", precision = 10, scale = 0)
	public Long getNotificationmethod() {
		return this.notificationmethod;
	}

	public void setNotificationmethod(Long notificationmethod) {
		this.notificationmethod = notificationmethod;
	}

	@Column(name = "LANGUAGE", nullable = false, precision = 10, scale = 0)
	public long getLanguage() {
		return this.language;
	}

	public void setLanguage(long language) {
		this.language = language;
	}

	@Column(name = "CURRENCY", nullable = false, length = 1020)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "TIMEZONE", length = 1020)
	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	@Column(name = "RESTRICTIONS", nullable = false, precision = 10, scale = 0)
	public long getRestrictions() {
		return this.restrictions;
	}

	public void setRestrictions(long restrictions) {
		this.restrictions = restrictions;
	}

	@Column(name = "TYPE", nullable = false, precision = 10, scale = 0)
	public long getType() {
		return this.type;
	}

	public void setType(long type) {
		this.type = type;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "STATUSTIME", nullable = false)
	public Serializable getStatustime() {
		return this.statustime;
	}

	public void setStatustime(Serializable statustime) {
		this.statustime = statustime;
	}

	@Column(name = "ACTIVATIONTIME")
	public Serializable getActivationtime() {
		return this.activationtime;
	}

	public void setActivationtime(Serializable activationtime) {
		this.activationtime = activationtime;
	}

	@Column(name = "APPROVEORREJECTTIME")
	public Serializable getApproveorrejecttime() {
		return this.approveorrejecttime;
	}

	public void setApproveorrejecttime(Serializable approveorrejecttime) {
		this.approveorrejecttime = approveorrejecttime;
	}

	@Column(name = "APPROVEDORREJECTEDBY", length = 1020)
	public String getApprovedorrejectedby() {
		return this.approvedorrejectedby;
	}

	public void setApprovedorrejectedby(String approvedorrejectedby) {
		this.approvedorrejectedby = approvedorrejectedby;
	}

	@Column(name = "APPROVEORREJECTCOMMENT", length = 1020)
	public String getApproveorrejectcomment() {
		return this.approveorrejectcomment;
	}

	public void setApproveorrejectcomment(String approveorrejectcomment) {
		this.approveorrejectcomment = approveorrejectcomment;
	}

	@Column(name = "APPLIEDBY", length = 1020)
	public String getAppliedby() {
		return this.appliedby;
	}

	public void setAppliedby(String appliedby) {
		this.appliedby = appliedby;
	}

	@Column(name = "APPLIEDTIME")
	public Serializable getAppliedtime() {
		return this.appliedtime;
	}

	public void setAppliedtime(Serializable appliedtime) {
		this.appliedtime = appliedtime;
	}

	@Column(name = "DOMPETMERCHANT", nullable = false, precision = 3, scale = 0)
	public short getDompetmerchant() {
		return this.dompetmerchant;
	}

	public void setDompetmerchant(short dompetmerchant) {
		this.dompetmerchant = dompetmerchant;
	}

	@Column(name = "SECURITYQUESTION", length = 1020)
	public String getSecurityquestion() {
		return this.securityquestion;
	}

	public void setSecurityquestion(String securityquestion) {
		this.securityquestion = securityquestion;
	}

	@Column(name = "SECURITYANSWER", length = 1020)
	public String getSecurityanswer() {
		return this.securityanswer;
	}

	public void setSecurityanswer(String securityanswer) {
		this.securityanswer = securityanswer;
	}

	@Column(name = "PARTNERTYPE", precision = 10, scale = 0)
	public Long getPartnertype() {
		return this.partnertype;
	}

	public void setPartnertype(Long partnertype) {
		this.partnertype = partnertype;
	}

	@Column(name = "UPGRADABLEKYCLEVEL", scale = 0)
	public BigDecimal getUpgradablekyclevel() {
		return this.upgradablekyclevel;
	}

	public void setUpgradablekyclevel(BigDecimal upgradablekyclevel) {
		this.upgradablekyclevel = upgradablekyclevel;
	}

	@Column(name = "UPGRADESTATE", precision = 10, scale = 0)
	public Long getUpgradestate() {
		return this.upgradestate;
	}

	public void setUpgradestate(Long upgradestate) {
		this.upgradestate = upgradestate;
	}

	@Column(name = "IDEXIPARETIONTIME")
	public Serializable getIdexiparetiontime() {
		return this.idexiparetiontime;
	}

	public void setIdexiparetiontime(Serializable idexiparetiontime) {
		this.idexiparetiontime = idexiparetiontime;
	}

	@Column(name = "REFERENCEACCOUNT", scale = 0)
	public BigDecimal getReferenceaccount() {
		return this.referenceaccount;
	}

	public void setReferenceaccount(BigDecimal referenceaccount) {
		this.referenceaccount = referenceaccount;
	}

	@Column(name = "ALIASNAME", length = 1020)
	public String getAliasname() {
		return this.aliasname;
	}

	public void setAliasname(String aliasname) {
		this.aliasname = aliasname;
	}

	@Column(name = "DETAILSREQUIRED", precision = 3, scale = 0)
	public Short getDetailsrequired() {
		return this.detailsrequired;
	}

	public void setDetailsrequired(Short detailsrequired) {
		this.detailsrequired = detailsrequired;
	}

	@Column(name = "REGISTRATIONMEDIUM", precision = 10, scale = 0)
	public Long getRegistrationmedium() {
		return this.registrationmedium;
	}

	public void setRegistrationmedium(Long registrationmedium) {
		this.registrationmedium = registrationmedium;
	}

	@Column(name = "REGISTERINGPARTNERID", scale = 0)
	public BigDecimal getRegisteringpartnerid() {
		return this.registeringpartnerid;
	}

	public void setRegisteringpartnerid(BigDecimal registeringpartnerid) {
		this.registeringpartnerid = registeringpartnerid;
	}

	@Column(name = "APPROVALIDNUMBER", precision = 10, scale = 0)
	public Long getApprovalidnumber() {
		return this.approvalidnumber;
	}

	public void setApprovalidnumber(Long approvalidnumber) {
		this.approvalidnumber = approvalidnumber;
	}

	@Column(name = "LASTNOTIFICATIONTIME")
	public Serializable getLastnotificationtime() {
		return this.lastnotificationtime;
	}

	public void setLastnotificationtime(Serializable lastnotificationtime) {
		this.lastnotificationtime = lastnotificationtime;
	}

	@Column(name = "NICKNAME")
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "ISEMAILVERIFIED", precision = 3, scale = 0)
	public Short getIsemailverified() {
		return this.isemailverified;
	}

	public void setIsemailverified(Short isemailverified) {
		this.isemailverified = isemailverified;
	}

	@Column(name = "MOTHERSMAIDENNAME", length = 1020)
	public String getMothersmaidenname() {
		return this.mothersmaidenname;
	}

	public void setMothersmaidenname(String mothersmaidenname) {
		this.mothersmaidenname = mothersmaidenname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<SubscriberMdn> getSubscriberMdns() {
		return this.subscriberMdns;
	}

	public void setSubscriberMdns(Set<SubscriberMdn> subscriberMdns) {
		this.subscriberMdns = subscriberMdns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<BillPaymentTxn> getBillPaymentTxns() {
		return this.billPaymentTxns;
	}

	public void setBillPaymentTxns(Set<BillPaymentTxn> billPaymentTxns) {
		this.billPaymentTxns = billPaymentTxns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<SubscriberAddiInfo> getSubscriberAddiInfos() {
		return this.subscriberAddiInfos;
	}

	public void setSubscriberAddiInfos(
			Set<SubscriberAddiInfo> subscriberAddiInfos) {
		this.subscriberAddiInfos = subscriberAddiInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<SubscriberFavorite> getSubscriberFavorites() {
		return this.subscriberFavorites;
	}

	public void setSubscriberFavorites(
			Set<SubscriberFavorite> subscriberFavorites) {
		this.subscriberFavorites = subscriberFavorites;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<Person2Person> getPerson2Persons() {
		return this.person2Persons;
	}

	public void setPerson2Persons(Set<Person2Person> person2Persons) {
		this.person2Persons = person2Persons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<PendingCommodityTransfer> getPendingCommodityTransfers() {
		return this.pendingCommodityTransfers;
	}

	public void setPendingCommodityTransfers(
			Set<PendingCommodityTransfer> pendingCommodityTransfers) {
		this.pendingCommodityTransfers = pendingCommodityTransfers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<BulkUpload> getBulkUploads() {
		return this.bulkUploads;
	}

	public void setBulkUploads(Set<BulkUpload> bulkUploads) {
		this.bulkUploads = bulkUploads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<CardInfo> getCardInfos() {
		return this.cardInfos;
	}

	public void setCardInfos(Set<CardInfo> cardInfos) {
		this.cardInfos = cardInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<TxnAmountDstrbLog> getTxnAmountDstrbLogs() {
		return this.txnAmountDstrbLogs;
	}

	public void setTxnAmountDstrbLogs(Set<TxnAmountDstrbLog> txnAmountDstrbLogs) {
		this.txnAmountDstrbLogs = txnAmountDstrbLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<CommodityTransfer> getCommodityTransfers() {
		return this.commodityTransfers;
	}

	public void setCommodityTransfers(Set<CommodityTransfer> commodityTransfers) {
		this.commodityTransfers = commodityTransfers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<CreditcardDestinations> getCreditcardDestinationses() {
		return this.creditcardDestinationses;
	}

	public void setCreditcardDestinationses(
			Set<CreditcardDestinations> creditcardDestinationses) {
		this.creditcardDestinationses = creditcardDestinationses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<CreditCardTransaction> getCreditCardTransactions() {
		return this.creditCardTransactions;
	}

	public void setCreditCardTransactions(
			Set<CreditCardTransaction> creditCardTransactions) {
		this.creditCardTransactions = creditCardTransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriber")
	public Set<Partner> getPartners() {
		return this.partners;
	}

	public void setPartners(Set<Partner> partners) {
		this.partners = partners;
	}

}
