package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TransactionChargeLog generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION_CHARGE_LOG")
public class TransactionChargeLog implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private TransactionCharge transactionCharge;
	private MfinoServiceProvider mfinoServiceProvider;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal servicechargetransactionlogid;
	private BigDecimal calculatedcharge;

	public TransactionChargeLog() {
	}

	public TransactionChargeLog(BigDecimal id,
			TransactionCharge transactionCharge, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal servicechargetransactionlogid,
			BigDecimal calculatedcharge) {
		this.id = id;
		this.transactionCharge = transactionCharge;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.servicechargetransactionlogid = servicechargetransactionlogid;
		this.calculatedcharge = calculatedcharge;
	}

	public TransactionChargeLog(BigDecimal id,
			TransactionCharge transactionCharge,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby,
			BigDecimal servicechargetransactionlogid,
			BigDecimal calculatedcharge) {
		this.id = id;
		this.transactionCharge = transactionCharge;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.servicechargetransactionlogid = servicechargetransactionlogid;
		this.calculatedcharge = calculatedcharge;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONCHARGEID", nullable = false)
	public TransactionCharge getTransactionCharge() {
		return this.transactionCharge;
	}

	public void setTransactionCharge(TransactionCharge transactionCharge) {
		this.transactionCharge = transactionCharge;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID")
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SERVICECHARGETRANSACTIONLOGID", nullable = false, scale = 0)
	public BigDecimal getServicechargetransactionlogid() {
		return this.servicechargetransactionlogid;
	}

	public void setServicechargetransactionlogid(
			BigDecimal servicechargetransactionlogid) {
		this.servicechargetransactionlogid = servicechargetransactionlogid;
	}

	@Column(name = "CALCULATEDCHARGE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getCalculatedcharge() {
		return this.calculatedcharge;
	}

	public void setCalculatedcharge(BigDecimal calculatedcharge) {
		this.calculatedcharge = calculatedcharge;
	}

}
