package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TransactionCharge generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION_CHARGE")
public class TransactionCharge implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private TransactionRule transactionRule;
	private ChargeType chargeType;
	private MfinoServiceProvider mfinoServiceProvider;
	private ChargeDefinition chargeDefinition;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private Short isactive;
	private Short ischrgdstrbapplicabletosrcsub;
	private Short ischrgdstrbapplicabletodestsub;
	private Set<SharePartner> sharePartners = new HashSet<SharePartner>(0);
	private Set<TransactionChargeLog> transactionChargeLogs = new HashSet<TransactionChargeLog>(
			0);
	private Set<TxnAmountDstrbLog> txnAmountDstrbLogs = new HashSet<TxnAmountDstrbLog>(
			0);

	public TransactionCharge() {
	}

	public TransactionCharge(BigDecimal id, TransactionRule transactionRule,
			ChargeType chargeType, MfinoServiceProvider mfinoServiceProvider,
			ChargeDefinition chargeDefinition, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby) {
		this.id = id;
		this.transactionRule = transactionRule;
		this.chargeType = chargeType;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.chargeDefinition = chargeDefinition;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public TransactionCharge(BigDecimal id, TransactionRule transactionRule,
			ChargeType chargeType, MfinoServiceProvider mfinoServiceProvider,
			ChargeDefinition chargeDefinition, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			Short isactive, Short ischrgdstrbapplicabletosrcsub,
			Short ischrgdstrbapplicabletodestsub,
			Set<SharePartner> sharePartners,
			Set<TransactionChargeLog> transactionChargeLogs,
			Set<TxnAmountDstrbLog> txnAmountDstrbLogs) {
		this.id = id;
		this.transactionRule = transactionRule;
		this.chargeType = chargeType;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.chargeDefinition = chargeDefinition;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.isactive = isactive;
		this.ischrgdstrbapplicabletosrcsub = ischrgdstrbapplicabletosrcsub;
		this.ischrgdstrbapplicabletodestsub = ischrgdstrbapplicabletodestsub;
		this.sharePartners = sharePartners;
		this.transactionChargeLogs = transactionChargeLogs;
		this.txnAmountDstrbLogs = txnAmountDstrbLogs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONRULEID", nullable = false)
	public TransactionRule getTransactionRule() {
		return this.transactionRule;
	}

	public void setTransactionRule(TransactionRule transactionRule) {
		this.transactionRule = transactionRule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGETYPEID", nullable = false)
	public ChargeType getChargeType() {
		return this.chargeType;
	}

	public void setChargeType(ChargeType chargeType) {
		this.chargeType = chargeType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGEDEFINITIONID", nullable = false)
	public ChargeDefinition getChargeDefinition() {
		return this.chargeDefinition;
	}

	public void setChargeDefinition(ChargeDefinition chargeDefinition) {
		this.chargeDefinition = chargeDefinition;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "ISACTIVE", precision = 3, scale = 0)
	public Short getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Short isactive) {
		this.isactive = isactive;
	}

	@Column(name = "ISCHRGDSTRBAPPLICABLETOSRCSUB", precision = 3, scale = 0)
	public Short getIschrgdstrbapplicabletosrcsub() {
		return this.ischrgdstrbapplicabletosrcsub;
	}

	public void setIschrgdstrbapplicabletosrcsub(
			Short ischrgdstrbapplicabletosrcsub) {
		this.ischrgdstrbapplicabletosrcsub = ischrgdstrbapplicabletosrcsub;
	}

	@Column(name = "ISCHRGDSTRBAPPLICABLETODESTSUB", precision = 3, scale = 0)
	public Short getIschrgdstrbapplicabletodestsub() {
		return this.ischrgdstrbapplicabletodestsub;
	}

	public void setIschrgdstrbapplicabletodestsub(
			Short ischrgdstrbapplicabletodestsub) {
		this.ischrgdstrbapplicabletodestsub = ischrgdstrbapplicabletodestsub;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionCharge")
	public Set<SharePartner> getSharePartners() {
		return this.sharePartners;
	}

	public void setSharePartners(Set<SharePartner> sharePartners) {
		this.sharePartners = sharePartners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionCharge")
	public Set<TransactionChargeLog> getTransactionChargeLogs() {
		return this.transactionChargeLogs;
	}

	public void setTransactionChargeLogs(
			Set<TransactionChargeLog> transactionChargeLogs) {
		this.transactionChargeLogs = transactionChargeLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionCharge")
	public Set<TxnAmountDstrbLog> getTxnAmountDstrbLogs() {
		return this.txnAmountDstrbLogs;
	}

	public void setTxnAmountDstrbLogs(Set<TxnAmountDstrbLog> txnAmountDstrbLogs) {
		this.txnAmountDstrbLogs = txnAmountDstrbLogs;
	}

}
