package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionCharge generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION_CHARGE")
public class TransactionCharge  extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_TransactionRule = "transactionRule";
	public static final String FieldName_ChargeType = "chargeType";
	public static final String FieldName_ChargeDefinition = "chargeDefinition";
	private TransactionRule transactionRule;
	private ChargeType chargeType;
	private MfinoServiceProvider mfinoServiceProvider;
	private ChargeDefinition chargeDefinition;
	private Short isactive;
	private Short ischrgdstrbapplicabletosrcsub;
	private Short ischrgdstrbapplicabletodestsub;
	private Set<SharePartner> sharePartners = new HashSet<SharePartner>(0);
	private Set<TransactionChargeLog> transactionChargeLogs = new HashSet<TransactionChargeLog>(
			0);
	private Set<TxnAmountDstrbLog> txnAmountDstrbLogs = new HashSet<TxnAmountDstrbLog>(
			0);

	public TransactionCharge() {
	}

	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONRULEID", nullable = false)
	public TransactionRule getTransactionRule() {
		return this.transactionRule;
	}

	public void setTransactionRule(TransactionRule transactionRule) {
		this.transactionRule = transactionRule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGETYPEID", nullable = false)
	public ChargeType getChargeType() {
		return this.chargeType;
	}

	public void setChargeType(ChargeType chargeType) {
		this.chargeType = chargeType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID", nullable = false)
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGEDEFINITIONID", nullable = false)
	public ChargeDefinition getChargeDefinition() {
		return this.chargeDefinition;
	}

	public void setChargeDefinition(ChargeDefinition chargeDefinition) {
		this.chargeDefinition = chargeDefinition;
	}

	
	@Column(name = "ISACTIVE", precision = 3, scale = 0)
	public Short getIsactive() {
		return this.isactive;
	}

	public void setIsactive(Short isactive) {
		this.isactive = isactive;
	}

	@Column(name = "ISCHRGDSTRBAPPLICABLETOSRCSUB", precision = 3, scale = 0)
	public Short getIschrgdstrbapplicabletosrcsub() {
		return this.ischrgdstrbapplicabletosrcsub;
	}

	public void setIschrgdstrbapplicabletosrcsub(
			Short ischrgdstrbapplicabletosrcsub) {
		this.ischrgdstrbapplicabletosrcsub = ischrgdstrbapplicabletosrcsub;
	}

	@Column(name = "ISCHRGDSTRBAPPLICABLETODESTSUB", precision = 3, scale = 0)
	public Short getIschrgdstrbapplicabletodestsub() {
		return this.ischrgdstrbapplicabletodestsub;
	}

	public void setIschrgdstrbapplicabletodestsub(
			Short ischrgdstrbapplicabletodestsub) {
		this.ischrgdstrbapplicabletodestsub = ischrgdstrbapplicabletodestsub;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionCharge")
	public Set<SharePartner> getSharePartners() {
		return this.sharePartners;
	}

	public void setSharePartners(Set<SharePartner> sharePartners) {
		this.sharePartners = sharePartners;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionCharge")
	public Set<TransactionChargeLog> getTransactionChargeLogs() {
		return this.transactionChargeLogs;
	}

	public void setTransactionChargeLogs(
			Set<TransactionChargeLog> transactionChargeLogs) {
		this.transactionChargeLogs = transactionChargeLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionCharge")
	public Set<TxnAmountDstrbLog> getTxnAmountDstrbLogs() {
		return this.txnAmountDstrbLogs;
	}

	public void setTxnAmountDstrbLogs(Set<TxnAmountDstrbLog> txnAmountDstrbLogs) {
		this.txnAmountDstrbLogs = txnAmountDstrbLogs;
	}

}
