package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * TransactionChargeLog generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION_CHARGE_LOG")
public class TransactionChargeLog extends Base implements java.io.Serializable {

	
	private TransactionCharge transactionCharge;
	private mFinoServiceProvider mfinoServiceProvider;
	private BigDecimal servicechargetransactionlogid;
	private BigDecimal calculatedcharge;

	public TransactionChargeLog() {
	}

	public TransactionChargeLog(BigDecimal id,
			TransactionCharge transactionCharge, Timestamp lastupdatetime,
			String updatedby, Timestamp createtime, String createdby,
			BigDecimal servicechargetransactionlogid,
			BigDecimal calculatedcharge) {
		this.id = id;
		this.transactionCharge = transactionCharge;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.servicechargetransactionlogid = servicechargetransactionlogid;
		this.calculatedcharge = calculatedcharge;
	}

	public TransactionChargeLog(BigDecimal id,
			TransactionCharge transactionCharge,
			mFinoServiceProvider mfinoServiceProvider,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby,
			BigDecimal servicechargetransactionlogid,
			BigDecimal calculatedcharge) {
		this.id = id;
		this.transactionCharge = transactionCharge;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.servicechargetransactionlogid = servicechargetransactionlogid;
		this.calculatedcharge = calculatedcharge;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONCHARGEID", nullable = false)
	public TransactionCharge getTransactionCharge() {
		return this.transactionCharge;
	}

	public void setTransactionCharge(TransactionCharge transactionCharge) {
		this.transactionCharge = transactionCharge;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID")
	public mFinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			mFinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	

	@Column(name = "SERVICECHARGETRANSACTIONLOGID", nullable = false, scale = 0)
	public BigDecimal getServicechargetransactionlogid() {
		return this.servicechargetransactionlogid;
	}

	public void setServicechargetransactionlogid(
			BigDecimal servicechargetransactionlogid) {
		this.servicechargetransactionlogid = servicechargetransactionlogid;
	}

	@Column(name = "CALCULATEDCHARGE", nullable = false, precision = 25, scale = 4)
	public BigDecimal getCalculatedcharge() {
		return this.calculatedcharge;
	}

	public void setCalculatedcharge(BigDecimal calculatedcharge) {
		this.calculatedcharge = calculatedcharge;
	}

}
