package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TxnAmountDstrbLog generated by hbm2java
 */
@Entity
@Table(name = "TXN_AMOUNT_DSTRB_LOG")
public class TxnAmountDstrbLog implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Pocket pocket;
	private Partner partner;
	private Subscriber subscriber;
	private TransactionCharge transactionCharge;
	private MfinoServiceProvider mfinoServiceProvider;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal servicechargetransactionlogid;
	private BigDecimal transactionid;
	private BigDecimal shareamount;
	private BigDecimal taxamount;
	private Short ispartofcharge;
	private Short isactualamount;
	private Short ispartofsharedupchain;
	private long status;
	private String failurereason;

	public TxnAmountDstrbLog() {
	}

	public TxnAmountDstrbLog(BigDecimal id, Pocket pocket,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby,
			BigDecimal servicechargetransactionlogid, BigDecimal transactionid,
			BigDecimal shareamount, long status) {
		this.id = id;
		this.pocket = pocket;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.servicechargetransactionlogid = servicechargetransactionlogid;
		this.transactionid = transactionid;
		this.shareamount = shareamount;
		this.status = status;
	}

	public TxnAmountDstrbLog(BigDecimal id, Pocket pocket, Partner partner,
			Subscriber subscriber, TransactionCharge transactionCharge,
			MfinoServiceProvider mfinoServiceProvider,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby,
			BigDecimal servicechargetransactionlogid, BigDecimal transactionid,
			BigDecimal shareamount, BigDecimal taxamount, Short ispartofcharge,
			Short isactualamount, Short ispartofsharedupchain, long status,
			String failurereason) {
		this.id = id;
		this.pocket = pocket;
		this.partner = partner;
		this.subscriber = subscriber;
		this.transactionCharge = transactionCharge;
		this.mfinoServiceProvider = mfinoServiceProvider;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.servicechargetransactionlogid = servicechargetransactionlogid;
		this.transactionid = transactionid;
		this.shareamount = shareamount;
		this.taxamount = taxamount;
		this.ispartofcharge = ispartofcharge;
		this.isactualamount = isactualamount;
		this.ispartofsharedupchain = ispartofsharedupchain;
		this.status = status;
		this.failurereason = failurereason;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POCKETID", nullable = false)
	public Pocket getPocket() {
		return this.pocket;
	}

	public void setPocket(Pocket pocket) {
		this.pocket = pocket;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARTNERID")
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBSCRIBERID")
	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONCHARGEID")
	public TransactionCharge getTransactionCharge() {
		return this.transactionCharge;
	}

	public void setTransactionCharge(TransactionCharge transactionCharge) {
		this.transactionCharge = transactionCharge;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MSPID")
	public MfinoServiceProvider getMfinoServiceProvider() {
		return this.mfinoServiceProvider;
	}

	public void setMfinoServiceProvider(
			MfinoServiceProvider mfinoServiceProvider) {
		this.mfinoServiceProvider = mfinoServiceProvider;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SERVICECHARGETRANSACTIONLOGID", nullable = false, scale = 0)
	public BigDecimal getServicechargetransactionlogid() {
		return this.servicechargetransactionlogid;
	}

	public void setServicechargetransactionlogid(
			BigDecimal servicechargetransactionlogid) {
		this.servicechargetransactionlogid = servicechargetransactionlogid;
	}

	@Column(name = "TRANSACTIONID", nullable = false, scale = 0)
	public BigDecimal getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(BigDecimal transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "SHAREAMOUNT", nullable = false, precision = 25, scale = 4)
	public BigDecimal getShareamount() {
		return this.shareamount;
	}

	public void setShareamount(BigDecimal shareamount) {
		this.shareamount = shareamount;
	}

	@Column(name = "TAXAMOUNT", precision = 25, scale = 4)
	public BigDecimal getTaxamount() {
		return this.taxamount;
	}

	public void setTaxamount(BigDecimal taxamount) {
		this.taxamount = taxamount;
	}

	@Column(name = "ISPARTOFCHARGE", precision = 3, scale = 0)
	public Short getIspartofcharge() {
		return this.ispartofcharge;
	}

	public void setIspartofcharge(Short ispartofcharge) {
		this.ispartofcharge = ispartofcharge;
	}

	@Column(name = "ISACTUALAMOUNT", precision = 3, scale = 0)
	public Short getIsactualamount() {
		return this.isactualamount;
	}

	public void setIsactualamount(Short isactualamount) {
		this.isactualamount = isactualamount;
	}

	@Column(name = "ISPARTOFSHAREDUPCHAIN", precision = 3, scale = 0)
	public Short getIspartofsharedupchain() {
		return this.ispartofsharedupchain;
	}

	public void setIspartofsharedupchain(Short ispartofsharedupchain) {
		this.ispartofsharedupchain = ispartofsharedupchain;
	}

	@Column(name = "STATUS", nullable = false, precision = 10, scale = 0)
	public long getStatus() {
		return this.status;
	}

	public void setStatus(long status) {
		this.status = status;
	}

	@Column(name = "FAILUREREASON", length = 1020)
	public String getFailurereason() {
		return this.failurereason;
	}

	public void setFailurereason(String failurereason) {
		this.failurereason = failurereason;
	}

}
