package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TxnPendingSummary generated by hbm2java
 */
@Entity
@Table(name = "TXN_PENDING_SUMMARY")
public class TxnPendingSummary implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private BigDecimal sctlid;
	private Long csraction;
	private Serializable csractiontime;
	private BigDecimal csruserid;
	private String csrusername;
	private String csrcomment;

	public TxnPendingSummary() {
	}

	public TxnPendingSummary(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
	}

	public TxnPendingSummary(BigDecimal id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			BigDecimal sctlid, Long csraction, Serializable csractiontime,
			BigDecimal csruserid, String csrusername, String csrcomment) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.sctlid = sctlid;
		this.csraction = csraction;
		this.csractiontime = csractiontime;
		this.csruserid = csruserid;
		this.csrusername = csrusername;
		this.csrcomment = csrcomment;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "SCTLID", nullable = false, scale = 0)
	public BigDecimal getSctlid() {
		return this.sctlid;
	}

	public void setSctlid(BigDecimal sctlid) {
		this.sctlid = sctlid;
	}

	@Column(name = "CSRACTION", precision = 10, scale = 0)
	public Long getCsraction() {
		return this.csraction;
	}

	public void setCsraction(Long csraction) {
		this.csraction = csraction;
	}

	@Column(name = "CSRACTIONTIME")
	public Serializable getCsractiontime() {
		return this.csractiontime;
	}

	public void setCsractiontime(Serializable csractiontime) {
		this.csractiontime = csractiontime;
	}

	@Column(name = "CSRUSERID", scale = 0)
	public BigDecimal getCsruserid() {
		return this.csruserid;
	}

	public void setCsruserid(BigDecimal csruserid) {
		this.csruserid = csruserid;
	}

	@Column(name = "CSRUSERNAME", length = 1020)
	public String getCsrusername() {
		return this.csrusername;
	}

	public void setCsrusername(String csrusername) {
		this.csrusername = csrusername;
	}

	@Column(name = "CSRCOMMENT", length = 1020)
	public String getCsrcomment() {
		return this.csrcomment;
	}

	public void setCsrcomment(String csrcomment) {
		this.csrcomment = csrcomment;
	}

}
