package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TxnRuleAddnInfo generated by hbm2java
 */
@Entity
@Table(name = "TXN_RULE_ADDN_INFO")
public class TxnRuleAddnInfo implements java.io.Serializable {

	private BigDecimal id;
	private long version;
	private TransactionRule transactionRule;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private String txnrulekey;
	private String txnrulevalue;
	private String txnrulecomparator;

	public TxnRuleAddnInfo() {
	}

	public TxnRuleAddnInfo(BigDecimal id, TransactionRule transactionRule,
			Serializable lastupdatetime, String updatedby,
			Serializable createtime, String createdby, String txnrulekey,
			String txnrulevalue, String txnrulecomparator) {
		this.id = id;
		this.transactionRule = transactionRule;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.txnrulekey = txnrulekey;
		this.txnrulevalue = txnrulevalue;
		this.txnrulecomparator = txnrulecomparator;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONRULEID", nullable = false)
	public TransactionRule getTransactionRule() {
		return this.transactionRule;
	}

	public void setTransactionRule(TransactionRule transactionRule) {
		this.transactionRule = transactionRule;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "TXNRULEKEY", nullable = false)
	public String getTxnrulekey() {
		return this.txnrulekey;
	}

	public void setTxnrulekey(String txnrulekey) {
		this.txnrulekey = txnrulekey;
	}

	@Column(name = "TXNRULEVALUE", nullable = false)
	public String getTxnrulevalue() {
		return this.txnrulevalue;
	}

	public void setTxnrulevalue(String txnrulevalue) {
		this.txnrulevalue = txnrulevalue;
	}

	@Column(name = "TXNRULECOMPARATOR", nullable = false)
	public String getTxnrulecomparator() {
		return this.txnrulecomparator;
	}

	public void setTxnrulecomparator(String txnrulecomparator) {
		this.txnrulecomparator = txnrulecomparator;
	}

}
