package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.mfino.hibernate.Timestamp;

/**
 * TxnRuleAddnInfo generated by hbm2java
 */
@Entity
@Table(name = "TXN_RULE_ADDN_INFO")
public class TxnRuleAddnInfo extends Base implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String FieldName_TransactionRule = "transactionRule";
	public static final String FieldName_TxnRuleKey = "txnrulekey";
	public static final String FieldName_TxnRuleValue = "txnrulevalue";
	public static final String FieldName_TxnRuleComparator = "txnrulecomparator";
	private TransactionRule transactionRule;
	private String txnrulekey;
	private String txnrulevalue;
	private String txnrulecomparator;

	public TxnRuleAddnInfo() {
	}

	public TxnRuleAddnInfo(BigDecimal id, TransactionRule transactionRule,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String txnrulekey,
			String txnrulevalue, String txnrulecomparator) {
		this.id = id;
		this.transactionRule = transactionRule;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.txnrulekey = txnrulekey;
		this.txnrulevalue = txnrulevalue;
		this.txnrulecomparator = txnrulecomparator;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONRULEID", nullable = false)
	public TransactionRule getTransactionRule() {
		return this.transactionRule;
	}

	public void setTransactionRule(TransactionRule transactionRule) {
		this.transactionRule = transactionRule;
	}

	
	@Column(name = "TXNRULEKEY", nullable = false)
	public String getTxnrulekey() {
		return this.txnrulekey;
	}

	public void setTxnrulekey(String txnrulekey) {
		this.txnrulekey = txnrulekey;
	}

	@Column(name = "TXNRULEVALUE", nullable = false)
	public String getTxnrulevalue() {
		return this.txnrulevalue;
	}

	public void setTxnrulevalue(String txnrulevalue) {
		this.txnrulevalue = txnrulevalue;
	}

	@Column(name = "TXNRULECOMPARATOR", nullable = false)
	public String getTxnrulecomparator() {
		return this.txnrulecomparator;
	}

	public void setTxnrulecomparator(String txnrulecomparator) {
		this.txnrulecomparator = txnrulecomparator;
	}

}
