package com.mfino.domain;
// Generated Jul 28, 2009 7:33:34 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.commons.lang.StringUtils;

import com.mfino.dao.DAOFactory;
import com.mfino.dao.EnumTextDAO;
import com.mfino.dao.query.EnumTextQuery;
import com.mfino.fix.CmFinoFIX;

/**
 * User generated by hbm2java
 * Modified by Sid
 */
public class User extends CmFinoFIX.CRUser {

    private Set<Integer> permissions;
    private String languageCode;

    public Set<Integer> getPermissions() {
        return permissions;
    }

    public void setPermissions(Set<Integer> permissions) {
        this.permissions = permissions;
    }

    public User() {
        super();
        this.setFailedLoginCount(0);
        this.setFirstTimeLogin(Boolean.TRUE);
        this.permissions = new HashSet<Integer>();
    }

    /**
     * @return the languageCode
     */
    public String getLanguageCode() {
        if (languageCode == null && getLanguage() != null) {
            EnumTextQuery query = new EnumTextQuery();
            query.setLanguage(CmFinoFIX.Language_English);
            query.setTagId(CmFinoFIX.TagID_Language);
            query.setEnumCode(getLanguage().toString());
            EnumTextDAO dao = DAOFactory.getInstance().getEnumTextDAO();
            List<EnumText> results = dao.get(query);
            if (results.size() > 0) {
                languageCode = results.get(0).getEnumValue();
            } else {
                languageCode = StringUtils.EMPTY;
            }
        }
        return languageCode;
    }

    /**
     * @param languageCode the languageCode to set
     */
    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }
}
