package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import com.mfino.hibernate.Timestamp;
/**
 * Village generated by hbm2java
 */
@Entity
@Table(name = "VILLAGE")
public class Village extends Base implements java.io.Serializable {

	
	private District district;
	private String villageid;
	private String displaytext;

	public Village() {
	}

	public Village(BigDecimal id, District district,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String villageid) {
		this.id = id;
		this.district = district;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.villageid = villageid;
	}

	public Village(BigDecimal id, District district,
			Timestamp lastupdatetime, String updatedby,
			Timestamp createtime, String createdby, String villageid,
			String displaytext) {
		this.id = id;
		this.district = district;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.villageid = villageid;
		this.displaytext = displaytext;
	}

	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDDISTRICT", nullable = false)
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}


	@Column(name = "VILLAGEID", nullable = false, length = 80)
	public String getVillageid() {
		return this.villageid;
	}

	public void setVillageid(String villageid) {
		this.villageid = villageid;
	}

	@Column(name = "DISPLAYTEXT", length = 800)
	public String getDisplaytext() {
		return this.displaytext;
	}

	public void setDisplaytext(String displaytext) {
		this.displaytext = displaytext;
	}

}
