package com.mfino.domain;

// Generated Sep 27, 2016 5:23:21 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * VisafoneTxnGenerator generated by hbm2java
 */
@Entity
@Table(name = "VISAFONE_TXN_GENERATOR")
public class VisafoneTxnGenerator implements java.io.Serializable {

	private long id;
	private long version;
	private Serializable lastupdatetime;
	private String updatedby;
	private Serializable createtime;
	private String createdby;
	private Serializable txntimestamp;
	private Long txncount;

	public VisafoneTxnGenerator() {
	}

	public VisafoneTxnGenerator(long id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
	}

	public VisafoneTxnGenerator(long id, Serializable lastupdatetime,
			String updatedby, Serializable createtime, String createdby,
			Serializable txntimestamp, Long txncount) {
		this.id = id;
		this.lastupdatetime = lastupdatetime;
		this.updatedby = updatedby;
		this.createtime = createtime;
		this.createdby = createdby;
		this.txntimestamp = txntimestamp;
		this.txncount = txncount;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "VERSION", nullable = false, precision = 10, scale = 0)
	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	@Column(name = "LASTUPDATETIME", nullable = false)
	public Serializable getLastupdatetime() {
		return this.lastupdatetime;
	}

	public void setLastupdatetime(Serializable lastupdatetime) {
		this.lastupdatetime = lastupdatetime;
	}

	@Column(name = "UPDATEDBY", nullable = false, length = 1020)
	public String getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(String updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "CREATETIME", nullable = false)
	public Serializable getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Serializable createtime) {
		this.createtime = createtime;
	}

	@Column(name = "CREATEDBY", nullable = false, length = 1020)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "TXNTIMESTAMP")
	public Serializable getTxntimestamp() {
		return this.txntimestamp;
	}

	public void setTxntimestamp(Serializable txntimestamp) {
		this.txntimestamp = txntimestamp;
	}

	@Column(name = "TXNCOUNT", precision = 10, scale = 0)
	public Long getTxncount() {
		return this.txncount;
	}

	public void setTxncount(Long txncount) {
		this.txncount = txncount;
	}

}
