//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.21 at 12:49:04 PM IST 
//


package com.mfino.iframework.inquiry.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TrxID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TrxTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TerminalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ChannelID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="BillerCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Payload">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TrxAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "payload"
})
@XmlRootElement(name = "Inquiry")
public class Inquiry {

    @XmlElement(name = "Header", required = true)
    protected Inquiry.Header header;
    @XmlElement(name = "Payload", required = true)
    protected Inquiry.Payload payload;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Inquiry.Header }
     *     
     */
    public Inquiry.Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inquiry.Header }
     *     
     */
    public void setHeader(Inquiry.Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link Inquiry.Payload }
     *     
     */
    public Inquiry.Payload getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inquiry.Payload }
     *     
     */
    public void setPayload(Inquiry.Payload value) {
        this.payload = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TrxID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TrxTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TerminalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ChannelID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BillerCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageID",
        "trxID",
        "trxTime",
        "terminalID",
        "channelID",
        "billerID",
        "billerCategory"
    })
    public static class Header {

        @XmlElement(name = "MessageID", required = true)
        protected String messageID;
        @XmlElement(name = "TrxID", required = true)
        protected String trxID;
        @XmlElement(name = "TrxTime", required = true)
        protected String trxTime;
        @XmlElement(name = "TerminalID", required = true)
        protected String terminalID;
        @XmlElement(name = "ChannelID", required = true)
        protected String channelID;
        @XmlElement(name = "BillerID", required = true)
        protected String billerID;
        @XmlElement(name = "BillerCategory", required = true)
        protected String billerCategory;

        /**
         * Gets the value of the messageID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageID() {
            return messageID;
        }

        /**
         * Sets the value of the messageID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageID(String value) {
            this.messageID = value;
        }

        /**
         * Gets the value of the trxID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrxID() {
            return trxID;
        }

        /**
         * Sets the value of the trxID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrxID(String value) {
            this.trxID = value;
        }

        /**
         * Gets the value of the trxTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrxTime() {
            return trxTime;
        }

        /**
         * Sets the value of the trxTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrxTime(String value) {
            this.trxTime = value;
        }

        /**
         * Gets the value of the terminalID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTerminalID() {
            return terminalID;
        }

        /**
         * Sets the value of the terminalID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTerminalID(String value) {
            this.terminalID = value;
        }

        /**
         * Gets the value of the channelID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChannelID() {
            return channelID;
        }

        /**
         * Sets the value of the channelID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChannelID(String value) {
            this.channelID = value;
        }

        /**
         * Gets the value of the billerID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillerID() {
            return billerID;
        }

        /**
         * Sets the value of the billerID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillerID(String value) {
            this.billerID = value;
        }

        /**
         * Gets the value of the billerCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBillerCategory() {
            return billerCategory;
        }

        /**
         * Sets the value of the billerCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBillerCategory(String value) {
            this.billerCategory = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TrxAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customerID",
        "trxAmount"
    })
    public static class Payload {

        @XmlElement(name = "CustomerID", required = true)
        protected String customerID;
        @XmlElement(name = "TrxAmount", required = true)
        protected String trxAmount;

        /**
         * Gets the value of the customerID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerID() {
            return customerID;
        }

        /**
         * Sets the value of the customerID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerID(String value) {
            this.customerID = value;
        }

        /**
         * Gets the value of the trxAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTrxAmount() {
            return trxAmount;
        }

        /**
         * Sets the value of the trxAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTrxAmount(String value) {
            this.trxAmount = value;
        }

    }

}
