
/*
 * 
 */

package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Jun 28 15:52:48 IST 2013
 * Generated source version: 2.2.10
 * 
 */


@WebServiceClient(name = "IBSServices", 
                  wsdlLocation = "file:/D:/MFinoWorkspace/main/Sterling/SterlingBankIntegration/src/main/resources/wsdl/sterling.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class IBSServices extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://tempuri.org/", "IBSServices");
    public final static QName IBSServicesSoap12 = new QName("http://tempuri.org/", "IBSServicesSoap12");
    public final static QName IBSServicesSoap = new QName("http://tempuri.org/", "IBSServicesSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/MFinoWorkspace/main/Sterling/SterlingBankIntegration/src/main/resources/wsdl/sterling.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/MFinoWorkspace/main/Sterling/SterlingBankIntegration/src/main/resources/wsdl/sterling.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public IBSServices(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IBSServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IBSServices() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns IBSServicesSoap
     */
    @WebEndpoint(name = "IBSServicesSoap12")
    public IBSServicesSoap getIBSServicesSoap12() {
        return super.getPort(IBSServicesSoap12, IBSServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBSServicesSoap
     */
    @WebEndpoint(name = "IBSServicesSoap12")
    public IBSServicesSoap getIBSServicesSoap12(WebServiceFeature... features) {
        return super.getPort(IBSServicesSoap12, IBSServicesSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns IBSServicesSoap
     */
    @WebEndpoint(name = "IBSServicesSoap")
    public IBSServicesSoap getIBSServicesSoap() {
        return super.getPort(IBSServicesSoap, IBSServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBSServicesSoap
     */
    @WebEndpoint(name = "IBSServicesSoap")
    public IBSServicesSoap getIBSServicesSoap(WebServiceFeature... features) {
        return super.getPort(IBSServicesSoap, IBSServicesSoap.class, features);
    }

}
