package com.mfino.dbcopytool.reportdb.domain;

// Generated 05-Apr-2012 00:05:38 by Hibernate Tools 3.1.0.beta4

import java.text.SimpleDateFormat;
import java.util.Date;

import org.hibernate.Session;

import com.mfino.dbcopytool.persistence.ReportDbHibernateUtil;

/**
 * SubscriberClassification generated by hbm2java
 */

public class Ledger extends TableRow implements
		java.io.Serializable {

	// Fields

	private String ID;
	private String commodityTransferID;
	private String sourceMDN;
	private String sourcePocketID;
	private String sourcePocketBalance;
	private String destMDN;
	private String destPocketID;
	private String destPocketBalance;
	private String amount;	
	private Date createTime;
	private String year;
	private String monthName;
	private String dayofMonth;
	private String weekDay;
	private Date updateTime;


	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	public String getCommodityTransferID() {
		return commodityTransferID;
	}

	public void setCommodityTransferID(String commodityTransferID) {
		this.commodityTransferID = commodityTransferID;
	}

	public String getSourceMDN() {
		return sourceMDN;
	}

	public void setSourceMDN(String sourceMDN) {
		this.sourceMDN = sourceMDN;
	}

	public String getSourcePocketID() {
		return sourcePocketID;
	}

	public void setSourcePocketID(String sourcePocketID) {
		this.sourcePocketID = sourcePocketID;
	}

	public String getSourcePocketBalance() {
		return sourcePocketBalance;
	}

	public void setSourcePocketBalance(String sourcePocketBalance) {
		this.sourcePocketBalance = sourcePocketBalance;
	}

	public String getDestMDN() {
		return destMDN;
	}

	public void setDestMDN(String destMDN) {
		this.destMDN = destMDN;
	}

	public String getDestPocketID() {
		return destPocketID;
	}

	public void setDestPocketID(String destPocketID) {
		this.destPocketID = destPocketID;
	}

	public String getDestPocketBalance() {
		return destPocketBalance;
	}

	public void setDestPocketBalance(String destPocketBalance) {
		this.destPocketBalance = destPocketBalance;
	}

	public String getAmount() {
		return amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	@Override
	public void initialiseRow(Object[] m) {
		int i = -1;
		this.ID = m[++i].toString();
		this.commodityTransferID = m[++i].toString();
		this.sourceMDN = m[++i].toString();
		this.sourcePocketID = m[++i].toString();
		this.sourcePocketBalance = m[++i].toString();
		this.destMDN = m[++i].toString();
		this.destPocketID = m[++i].toString();
		this.destPocketBalance = m[++i].toString();
		this.amount =  m[++i].toString();
		this.createTime = (Date) m[++i];
		this.updateTime = (Date) m[++i];
		transfromRow();

	}

	@Override
	public void transfromRow() {
		Date d = this.createTime;
		this.year = new SimpleDateFormat("yyyy").format(d);
		this.monthName = new SimpleDateFormat("MMMM").format(d);
		this.dayofMonth = new SimpleDateFormat("dd").format(d);
		this.weekDay = new SimpleDateFormat("EEEE").format(d);
	}

	@Override
	public void insertRow() {
		Session session = ReportDbHibernateUtil.getSessionFactory().openSession();
		session.beginTransaction();
		session.saveOrUpdate(this);
		session.getTransaction().commit();
		session.close();
	}

	@Override
	public void printRow() {
	
	}

	// Property accessors

	

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMonthName() {
		return this.monthName;
	}

	public void setMonthName(String monthName) {
		this.monthName = monthName;
	}

	public String getDayofMonth() {
		return this.dayofMonth;
	}

	public void setDayofMonth(String dayofMonth) {
		this.dayofMonth = dayofMonth;
	}

	public String getWeekDay() {
		return this.weekDay;
	}

	public void setWeekDay(String weekDay) {
		this.weekDay = weekDay;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	

	
}
