package com.mfino.dbcopytool.reportdb.domain;

// Generated 05-Apr-2012 00:05:37 by Hibernate Tools 3.1.0.beta4

import java.text.SimpleDateFormat;
import java.util.Date;

import org.hibernate.Session;

import com.mfino.dbcopytool.persistence.ReportDbHibernateUtil;

/**
 * AgentClassification generated by hbm2java
 */

public class Partner extends TableRow implements
		java.io.Serializable {

	// Fields

	private String subscriberId;
	private String firstName;
	private String agentId;
	private String agentCode;
	private String agentType;
	private String city;
	private String state;
	private Date createTime;
	private String createYear;
	private String createMonthName;
	private String createDayofMonth;
	private String createWeekDay;
	private Date updateTime;
	private String updateYear;
	private String updateMonthName;
	private String updateDayofMonth;
	private String updateWeekDay;

	// Constructors

	/** default constructor */
	public Partner() {
	}

	/** minimal constructor */
	public Partner(String subscriberId) {
		this.subscriberId = subscriberId;
	}

	/** full constructor */
	public Partner(String subscriberId, String firstName,
			String partnerId, String agentCode, String agentType, String city,
			String state, Date createTime, String year, String monthName,
			String dayofMonth, String weekDay) {
		this.subscriberId = subscriberId;
		this.firstName = firstName;
		this.agentId = partnerId;
		this.agentCode = agentCode;
		this.agentType = agentType;
		this.city = city;
		this.state = state;
		this.createTime = createTime;
		this.createYear = year;
		this.createMonthName = monthName;
		this.createDayofMonth = dayofMonth;
		this.createWeekDay = weekDay;
	}

	@Override
	public void initialiseRow(Object[] m) {
		int i = -1;
		this.subscriberId = m[++i].toString();
		this.firstName = (m[++i] != null) ? m[i].toString() : "";
		this.agentId = m[++i].toString();
		this.agentCode = m[++i].toString();
		this.agentType = m[++i].toString();
		this.city = m[++i].toString();
		this.state = m[++i].toString();
		this.createTime = (Date) m[++i];
		this.updateTime = (Date)m[++i];
		transfromRow();
	}

	@Override
	public void transfromRow() {
		Date d = this.createTime;
		this.createYear = new SimpleDateFormat("yyyy").format(d);
		this.createMonthName = new SimpleDateFormat("MMMM").format(d);
		this.createDayofMonth = new SimpleDateFormat("dd").format(d);
		this.createWeekDay = new SimpleDateFormat("EEEE").format(d);
		d = this.updateTime;
		this.updateYear = new SimpleDateFormat("yyyy").format(d);
		this.updateMonthName = new SimpleDateFormat("MMMM").format(d);
		this.updateDayofMonth = new SimpleDateFormat("dd").format(d);
		this.updateWeekDay = new SimpleDateFormat("EEEE").format(d);
	}

	@Override
	public void insertRow() {
		Session session = ReportDbHibernateUtil.getSessionFactory().openSession();
		session.beginTransaction();
		session.saveOrUpdate(this);
		session.getTransaction().commit();
		session.close();
	}

	@Override
	public void printRow() {
		System.out.println(this.subscriberId + "," + this.firstName + ","
				+ this.agentId + "," + this.agentCode + "," + this.agentType
				+ "," + this.city + "," + this.state + "," + this.createTime
				+ "," + this.createYear + "," + this.createMonthName + ","
				+ this.createDayofMonth + "," + this.createWeekDay);
	}

	// Property accessors

	public String getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	public String getAgentType() {
		return this.agentType;
	}

	public void setAgentType(String agentType) {
		this.agentType = agentType;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	public String getCreateMonthName() {
		return createMonthName;
	}

	public void setCreateMonthName(String createMonthName) {
		this.createMonthName = createMonthName;
	}

	public String getCreateDayofMonth() {
		return createDayofMonth;
	}

	public void setCreateDayofMonth(String createDayofMonth) {
		this.createDayofMonth = createDayofMonth;
	}

	public String getCreateWeekDay() {
		return createWeekDay;
	}

	public void setCreateWeekDay(String createWeekDay) {
		this.createWeekDay = createWeekDay;
	}

	public String getUpdateYear() {
		return updateYear;
	}

	public void setUpdateYear(String updateYear) {
		this.updateYear = updateYear;
	}

	public String getUpdateMonthName() {
		return updateMonthName;
	}

	public void setUpdateMonthName(String updateMonthName) {
		this.updateMonthName = updateMonthName;
	}

	public String getUpdateDayofMonth() {
		return updateDayofMonth;
	}

	public void setUpdateDayofMonth(String updateDayofMonth) {
		this.updateDayofMonth = updateDayofMonth;
	}

	public String getUpdateWeekDay() {
		return updateWeekDay;
	}

	public void setUpdateWeekDay(String updateWeekDay) {
		this.updateWeekDay = updateWeekDay;
	}
	
	public String getCreateYear() {
		return createYear;
	}

	public void setCreateYear(String createYear) {
		this.createYear = createYear;
	}
}
