package com.mfino.dbcopytool.reportdb.domain;

// Generated 05-Apr-2012 00:05:38 by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.hibernate.Session;

import com.mfino.dbcopytool.persistence.ReportDbHibernateUtil;

/**
 * PendingCommodityTransfer generated by hbm2java
 */

public class PendingCommodityTransfer extends TableRow implements
		java.io.Serializable {

	// Fields

	private String commodityTransferId;
	private String transactionId;
	private String uicategory;
	private Date pendingCommodityTransferStartTime;
	private String createYear;
	private String createMonthName;
	private String createDayofMonth;
	private String createWeekDay;
	private String uicategoryName;
	private String transferStatus;
	private String sourcePocketId;
	private String destPocketId;
	private BigDecimal amount;
	private BigDecimal charges;
	private BigDecimal taxAmount;
	private String transactionChargeId;
	private Boolean isPartOfSharedUpChain;
	private String sourceSubscriberId;
	private String sourcePocketType;
	private String sourceMessage;
	private String destSubscriberId;
	private String destPocketType;
	private String sourceMdn;
	private String destMdn;
	private String sourceApplication;
	private String sctlID;
	private Date pendingCommodityTransferUpdateTime;
	private String updateYear;
	private String updateMonthName;
	private String updateDayofMonth;
	private String updateWeekDay;
	private String bankRRN;
	private String bankSTAN;
	
	

	// Constructors

	/** default constructor */
	public PendingCommodityTransfer() {
	}

	/** minimal constructor */
	public PendingCommodityTransfer(String commodityTransferId, String createMonthName) {
		this.commodityTransferId = commodityTransferId;
		this.createMonthName = createMonthName;
	}

	/** full constructor */
	public PendingCommodityTransfer(String commodityTransferId,
			String transactionId, String uicategory,
			Date pendingCommodityTransferStartTime, String year,
			String monthName, String dayofMonth, String weekDay,
			String uicategoryName, String transferStatus,
			String sourcePocketId, String destPocketId, BigDecimal amount,
			BigDecimal charges, BigDecimal taxAmount,
			String transactionChargeId, Boolean isPartOfSharedUpChain,
			String sourceSubscriberId, String sourcePocketType,
			String sourceMessage, String destSubscriberId,
			String destPocketType, String sourceMdn, String sourcePocketId1,
			String destMdn, String destPocketId1, String sourceApplication) {
		this.commodityTransferId = commodityTransferId;
		this.transactionId = transactionId;
		this.uicategory = uicategory;
		this.pendingCommodityTransferStartTime = pendingCommodityTransferStartTime;
		this.createYear = year;
		this.createMonthName = monthName;
		this.createDayofMonth = dayofMonth;
		this.createWeekDay = weekDay;
		this.uicategoryName = uicategoryName;
		this.transferStatus = transferStatus;
		this.sourcePocketId = sourcePocketId;
		this.destPocketId = destPocketId;
		this.amount = amount;
		this.charges = charges;
		this.taxAmount = taxAmount;
		this.transactionChargeId = transactionChargeId;
		this.isPartOfSharedUpChain = isPartOfSharedUpChain;
		this.sourceSubscriberId = sourceSubscriberId;
		this.sourcePocketType = sourcePocketType;
		this.sourceMessage = sourceMessage;
		this.destSubscriberId = destSubscriberId;
		this.destPocketType = destPocketType;
		this.sourceMdn = sourceMdn;
		this.destMdn = destMdn;
		this.sourceApplication = sourceApplication;
	}

	String hqlQuery = "select pct.ID, pct.TransactionsLogByTransactionID.ID, pct.StartTime, pct.UICategory, "
			+ "et1.DisplayText, pct.TransferStatus, "
			+ "pct.PocketBySourcePocketID.ID, pct.DestPocketID, pct.Amount, pct.Charges,"
			+ "pct.TaxAmount, pct.TransactionChargeID, pct.IsPartOfSharedUpChain, "
			+ "pct.SubscriberBySourceSubscriberID.ID, pct.SourcePocketType, pct.SourceMessage, "
			+ "pct.DestSubscriberID, pct.DestPocketType, pct.SourceMDN, "
			+ "pct.DestMDN, pct.SourceApplication "
			+ "from PendingCommodityTransfer as pct, EnumText et1 "
			+ "where et1.TagID=5636 and et1.EnumCode=pct.UICategory ";

	@Override
	public void initialiseRow(Object[] m) {
		int i = -1;
		this.commodityTransferId = m[++i].toString();
		this.transactionId = m[++i].toString();
		this.pendingCommodityTransferStartTime = (Date) m[++i];
		this.uicategory = m[++i].toString();
		this.uicategoryName = m[++i].toString();
		this.transferStatus = m[++i].toString();
		this.sourcePocketId = m[++i].toString();
		this.destPocketId = m[++i].toString();
		this.amount = (BigDecimal) m[++i];
		this.charges = (BigDecimal) m[++i];
		this.taxAmount = (BigDecimal) m[++i];
		this.transactionChargeId = m[++i] != null ? m[i].toString() : "null";
		this.isPartOfSharedUpChain = (Boolean) m[++i];
		this.sourceSubscriberId = m[++i].toString();
		this.sourcePocketType = m[++i].toString();
		this.sourceMessage = m[++i].toString();
		this.destSubscriberId = m[++i].toString();
		this.destPocketType = m[++i].toString();
		this.sourceMdn = m[++i].toString();
		this.destMdn = m[++i].toString();
		this.sourceApplication = m[++i].toString();
		this.sctlID = m[++i] != null ? m[i].toString() : "";
		this.pendingCommodityTransferUpdateTime = (Date) m[++i];
		this.bankRRN = m[++i] != null ? m[i].toString() : "";
		this.bankSTAN = m[++i] != null ? m[i].toString() : "";
		transfromRow();
	}

	@Override
	public void printRow() {
		System.out.println(this.commodityTransferId + "," + this.transactionId
				+ "," + this.pendingCommodityTransferStartTime + ","
				+ this.createYear + "," + this.createMonthName + "," + this.createDayofMonth
				+ "," + this.createWeekDay + "," + this.uicategory + ","
				+ this.uicategoryName + "," + this.transferStatus + ","
				+ this.sourcePocketId + "," + this.destPocketId + ","
				+ this.amount + "," + this.charges + "," + this.taxAmount + ","
				+ this.transactionChargeId + "," + this.isPartOfSharedUpChain
				+ "," + this.sourceSubscriberId + "," + this.sourcePocketType
				+ "," + this.sourceMessage + "," + this.destSubscriberId + ","
				+ this.destPocketType + "," + this.sourceMdn + ","
				+ this.destMdn + "," + this.sourceApplication);
	}

	@Override
	public void transfromRow() {
		Date d = this.pendingCommodityTransferStartTime;
		this.createYear = new SimpleDateFormat("yyyy").format(d);
		this.createMonthName = new SimpleDateFormat("MMMM").format(d);
		this.createDayofMonth = new SimpleDateFormat("dd").format(d);
		this.createWeekDay = new SimpleDateFormat("EEEE").format(d);
		d = this.pendingCommodityTransferUpdateTime;
		this.updateYear = new SimpleDateFormat("yyyy").format(d);
		this.updateMonthName = new SimpleDateFormat("MMMM").format(d);
		this.updateDayofMonth = new SimpleDateFormat("dd").format(d);
		this.updateWeekDay = new SimpleDateFormat("EEEE").format(d);
	}

	@Override
	public void insertRow() {
		Session session = ReportDbHibernateUtil.getSessionFactory().openSession();
		session.beginTransaction();
		session.saveOrUpdate(this);
		session.getTransaction().commit();
		session.close();
	}

	// Property accessors

	public String getCommodityTransferId() {
		return this.commodityTransferId;
	}

	public void setCommodityTransferId(String commodityTransferId) {
		this.commodityTransferId = commodityTransferId;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getUicategory() {
		return this.uicategory;
	}

	public void setUicategory(String uicategory) {
		this.uicategory = uicategory;
	}

	public Date getPendingCommodityTransferStartTime() {
		return this.pendingCommodityTransferStartTime;
	}

	public void setPendingCommodityTransferStartTime(
			Date pendingCommodityTransferStartTime) {
		this.pendingCommodityTransferStartTime = pendingCommodityTransferStartTime;
	}

	public String getUicategoryName() {
		return this.uicategoryName;
	}

	public void setUicategoryName(String uicategoryName) {
		this.uicategoryName = uicategoryName;
	}

	public String getTransferStatus() {
		return this.transferStatus;
	}

	public void setTransferStatus(String transferStatus) {
		this.transferStatus = transferStatus;
	}

	public String getSourcePocketId() {
		return this.sourcePocketId;
	}

	public void setSourcePocketId(String sourcePocketId) {
		this.sourcePocketId = sourcePocketId;
	}

	public String getDestPocketId() {
		return this.destPocketId;
	}

	public void setDestPocketId(String destPocketId) {
		this.destPocketId = destPocketId;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getCharges() {
		return this.charges;
	}

	public void setCharges(BigDecimal charges) {
		this.charges = charges;
	}

	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	public String getTransactionChargeId() {
		return this.transactionChargeId;
	}

	public void setTransactionChargeId(String transactionChargeId) {
		this.transactionChargeId = transactionChargeId;
	}

	public Boolean getIsPartOfSharedUpChain() {
		return this.isPartOfSharedUpChain;
	}

	public void setIsPartOfSharedUpChain(Boolean isPartOfSharedUpChain) {
		this.isPartOfSharedUpChain = isPartOfSharedUpChain;
	}

	public String getSourceSubscriberId() {
		return this.sourceSubscriberId;
	}

	public void setSourceSubscriberId(String sourceSubscriberId) {
		this.sourceSubscriberId = sourceSubscriberId;
	}

	public String getSourcePocketType() {
		return this.sourcePocketType;
	}

	public void setSourcePocketType(String sourcePocketType) {
		this.sourcePocketType = sourcePocketType;
	}

	public String getSourceMessage() {
		return this.sourceMessage;
	}

	public void setSourceMessage(String sourceMessage) {
		this.sourceMessage = sourceMessage;
	}

	public String getDestSubscriberId() {
		return this.destSubscriberId;
	}

	public void setDestSubscriberId(String destSubscriberId) {
		this.destSubscriberId = destSubscriberId;
	}

	public String getDestPocketType() {
		return this.destPocketType;
	}

	public void setDestPocketType(String destPocketType) {
		this.destPocketType = destPocketType;
	}

	public String getSourceMdn() {
		return this.sourceMdn;
	}

	public void setSourceMdn(String sourceMdn) {
		this.sourceMdn = sourceMdn;
	}

	public String getDestMdn() {
		return this.destMdn;
	}

	public void setDestMdn(String destMdn) {
		this.destMdn = destMdn;
	}

	public String getSourceApplication() {
		return this.sourceApplication;
	}

	public void setSourceApplication(String sourceApplication) {
		this.sourceApplication = sourceApplication;
	}

	public String getSctlID() {
		return sctlID;
	}

	public void setSctlID(String sctlID) {
		this.sctlID = sctlID;
	}
	
	
	public Date getPendingCommodityTransferUpdateTime() {
		return this.pendingCommodityTransferUpdateTime ;
	}

	public void setPendingCommodityTransferUpdateTime(Date pendingCommodityTransferUpdateTime) {
		this.pendingCommodityTransferUpdateTime = pendingCommodityTransferUpdateTime ;
	}
	
	public String getCreateMonthName() {
		return createMonthName;
	}

	public void setCreateMonthName(String createMonthName) {
		this.createMonthName = createMonthName;
	}

	public String getCreateDayofMonth() {
		return createDayofMonth;
	}

	public void setCreateDayofMonth(String createDayofMonth) {
		this.createDayofMonth = createDayofMonth;
	}

	public String getCreateWeekDay() {
		return createWeekDay;
	}

	public void setCreateWeekDay(String createWeekDay) {
		this.createWeekDay = createWeekDay;
	}

	public String getUpdateYear() {
		return updateYear;
	}

	public void setUpdateYear(String updateYear) {
		this.updateYear = updateYear;
	}

	public String getUpdateMonthName() {
		return updateMonthName;
	}

	public void setUpdateMonthName(String updateMonthName) {
		this.updateMonthName = updateMonthName;
	}

	public String getUpdateDayofMonth() {
		return updateDayofMonth;
	}

	public void setUpdateDayofMonth(String updateDayofMonth) {
		this.updateDayofMonth = updateDayofMonth;
	}

	public String getUpdateWeekDay() {
		return updateWeekDay;
	}

	public void setUpdateWeekDay(String updateWeekDay) {
		this.updateWeekDay = updateWeekDay;
	}
	
	public String getCreateYear() {
		return createYear;
	}

	public void setCreateYear(String createYear) {
		this.createYear = createYear;
	}
	
	public String getBankRRN() {
		return bankRRN;
	}

	public void setBankRRN(String bankRRN) {
		this.bankRRN = bankRRN;
	}

	public String getBankSTAN() {
		return bankSTAN;
	}

	public void setBankSTAN(String bankSTAN) {
		this.bankSTAN = bankSTAN;
	}


}
