package com.mfino.dbcopytool.reportdb.domain;

// Generated 05-Apr-2012 00:05:38 by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.Session;

import com.mfino.dbcopytool.persistence.ReportDbHibernateUtil;
import com.mfino.fix.CmFinoFIX;

/**
 * SubscriberPocket generated by hbm2java
 */

public class Pocket extends TableRow implements java.io.Serializable {

	// Fields

	private String pocketId;
	private String subscriberMdn;
	private String subscriberID;
	private BigDecimal currentBalance;
	private String pocketType;
	private Date createTime;
	private Date updateTime;
	private BigDecimal currentDailyExpenditure;
	private BigDecimal currentWeeklyExpenditure;
	private BigDecimal currentMonthlyExpenditure;
	private String currentDailyTxnsCount;
	private String currentWeeklyTxnsCount;
	private String currentMonthlyTxnsCount;
	private String pkDescription;
	private BigDecimal pkMaxAmountPerTransaction;
	private BigDecimal pkMinAmountPerTransaction;
	private BigDecimal pkMaxAmountPerDay;
	private BigDecimal pkMaxAmountPerWeek;
	private BigDecimal pkMaxAmountPerMonth;
	private String pkMaxTransactionsPerDay;
	private String pkMaxTransactionsPerWeek;
	private String pkMaxTransactionsPerMonth;
	private String pocketStatus;
	private String cardPan;
	
	

	// Constructors

	/** default constructor */
	public Pocket() {
	}

	/** minimal constructor */
	public Pocket(String pocketId) {
		this.pocketId = pocketId;
	}

	/** full constructor */
	public Pocket(String subscriberMdn, String pocketId,
			BigDecimal currentBalance, String pocketType) {
		this.pocketId = pocketId;
		this.subscriberMdn = subscriberMdn;
		this.pocketType = pocketType;
		this.currentBalance = currentBalance;

	}
	
	@Override
	public void initialiseRow(Object[] m) {
		int i = -1;
		this.pocketId = m[++i].toString();
		this.subscriberMdn = m[++i].toString();
		this.subscriberID = m[++i].toString();
		this.currentBalance = (BigDecimal) m[++i];
		this.cardPan =  m[++i] != null ? ((String)m[i]).toString() : "";
		this.createTime = (Date) m[++i];
		this.updateTime = (Date) m[++i];
		this.currentDailyExpenditure = (BigDecimal) m[++i];
		this.currentWeeklyExpenditure = (BigDecimal) m[++i];
		this.currentMonthlyExpenditure = (BigDecimal) m[++i];
		this.currentDailyTxnsCount = m[++i].toString();
		this.currentWeeklyTxnsCount = m[++i].toString();
		this.currentMonthlyTxnsCount = m[++i].toString();
		this.pkDescription = m[++i].toString();
		this.pkMaxAmountPerTransaction = (BigDecimal) m[++i];
		this.pkMinAmountPerTransaction = (BigDecimal) m[++i];
		this.pkMaxAmountPerDay = (BigDecimal) m[++i];
		this.pkMaxAmountPerWeek = (BigDecimal) m[++i];
		this.pkMaxAmountPerMonth = (BigDecimal) m[++i];
		this.pkMaxTransactionsPerDay = m[++i].toString();
		this.pkMaxTransactionsPerWeek = m[++i].toString();
		this.pkMaxTransactionsPerMonth = m[++i].toString();
		this.pocketType =  m[++i].toString();
		this.pocketStatus =  m[++i].toString();
		transfromRow();
	}

	@Override
	public void transfromRow() {
		
	}

	@Override
	public void insertRow() {
		Session session = ReportDbHibernateUtil.getSessionFactory().openSession();
		session.beginTransaction();
		session.saveOrUpdate(this);
		session.getTransaction().commit();
		session.close();
	}

	@Override
	public void printRow() {
		System.out.println(this.subscriberMdn + "," + this.pocketId + ","
				+ this.pocketType + "," + this.currentBalance);
	}

	// Property accessors

	public String getSubscriberMdn() {
		return this.subscriberMdn;
	}

	public void setSubscriberMdn(String subscriberMdn) {
		this.subscriberMdn = subscriberMdn;
	}

	public String getPocketId() {
		return this.pocketId;
	}

	public void setPocketId(String pocketId) {
		this.pocketId = pocketId;
	}

	public BigDecimal getCurrentBalance() {
		return this.currentBalance;
	}

	public void setCurrentBalance(BigDecimal currentBalance) {
		this.currentBalance = currentBalance;
	}
	
	public String getSubscriberID() {
		return subscriberID;
	}

	public void setSubscriberID(String subscriberID) {
		this.subscriberID = subscriberID;
	}
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	public BigDecimal getCurrentDailyExpenditure() {
		return this.currentDailyExpenditure;
	}

	public void setCurrentDailyExpenditure(BigDecimal currentDailyExpenditure) {
		this.currentDailyExpenditure = currentDailyExpenditure;
	}

	public BigDecimal getCurrentWeeklyExpenditure() {
		return this.currentWeeklyExpenditure;
	}

	public void setCurrentWeeklyExpenditure(BigDecimal currentWeeklyExpenditure) {
		this.currentWeeklyExpenditure = currentWeeklyExpenditure;
	}

	public BigDecimal getCurrentMonthlyExpenditure() {
		return this.currentMonthlyExpenditure;
	}

	public void setCurrentMonthlyExpenditure(BigDecimal currentMonthlyExpenditure) {
		this.currentMonthlyExpenditure = currentMonthlyExpenditure;
	}

	public String getCurrentDailyTxnsCount() {
		return this.currentDailyTxnsCount;
	}

	public void setCurrentDailyTxnsCount(String currentDailyTxnsCount) {
		this.currentDailyTxnsCount = currentDailyTxnsCount;
	}

	public String getCurrentWeeklyTxnsCount() {
		return this.currentWeeklyTxnsCount;
	}

	public void setCurrentWeeklyTxnsCount(String currentWeeklyTxnsCount) {
		this.currentWeeklyTxnsCount = currentWeeklyTxnsCount;
	}

	public String getCurrentMonthlyTxnsCount() {
		return this.currentMonthlyTxnsCount;
	}

	public void setCurrentMonthlyTxnsCount(String currentMonthlyTxnsCount) {
		this.currentMonthlyTxnsCount = currentMonthlyTxnsCount;
	}

	public String getPkDescription() {
		return this.pkDescription;
	}

	public void setPkDescription(String pkDescription) {
		this.pkDescription = pkDescription;
	}

	public BigDecimal getPkMaxAmountPerTransaction() {
		return pkMaxAmountPerTransaction;
	}

	public void setPkMaxAmountPerTransaction(BigDecimal pkMaxAmountPerTransaction) {
		this.pkMaxAmountPerTransaction = pkMaxAmountPerTransaction;
	}

	public BigDecimal getPkMinAmountPerTransaction() {
		return pkMinAmountPerTransaction;
	}

	public void setPkMinAmountPerTransaction(BigDecimal pkMinAmountPerTransaction) {
		this.pkMinAmountPerTransaction = pkMinAmountPerTransaction;
	}

	public BigDecimal getPkMaxAmountPerDay() {
		return pkMaxAmountPerDay;
	}

	public void setPkMaxAmountPerDay(BigDecimal pkMaxAmountPerDay) {
		this.pkMaxAmountPerDay = pkMaxAmountPerDay;
	}

	public BigDecimal getPkMaxAmountPerWeek() {
		return pkMaxAmountPerWeek;
	}

	public void setPkMaxAmountPerWeek(BigDecimal pkMaxAmountPerWeek) {
		this.pkMaxAmountPerWeek = pkMaxAmountPerWeek;
	}

	public BigDecimal getPkMaxAmountPerMonth() {
		return pkMaxAmountPerMonth;
	}

	public void setPkMaxAmountPerMonth(BigDecimal pkMaxAmountPerMonth) {
		this.pkMaxAmountPerMonth = pkMaxAmountPerMonth;
	}

	public String getPkMaxTransactionsPerDay() {
		return pkMaxTransactionsPerDay;
	}

	public void setPkMaxTransactionsPerDay(String pkMaxTransactionsPerDay) {
		this.pkMaxTransactionsPerDay = pkMaxTransactionsPerDay;
	}

	public String getPkMaxTransactionsPerWeek() {
		return pkMaxTransactionsPerWeek;
	}

	public void setPkMaxTransactionsPerWeek(String pkMaxTransactionsPerWeek) {
		this.pkMaxTransactionsPerWeek = pkMaxTransactionsPerWeek;
	}

	public String getPkMaxTransactionsPerMonth() {
		return pkMaxTransactionsPerMonth;
	}

	public void setPkMaxTransactionsPerMonth(String pkMaxTransactionsPerMonth) {
		this.pkMaxTransactionsPerMonth = pkMaxTransactionsPerMonth;
	}
	
	public String getPocketType() {
		return pocketType;
	}

	public void setPocketType(String pocketType) {
		this.pocketType = pocketType;
	}

	public String getPocketStatus() {
		return pocketStatus;
	}

	public void setPocketStatus(String pocketStatus) {
		this.pocketStatus = pocketStatus;
	}
	
	public String getCardPan() {
		return cardPan;
	}

	public void setCardPan(String cardPan) {
		this.cardPan = cardPan;
	}
}
