package com.mfino.dbcopytool.reportdb.domain;

// Generated 05-Apr-2012 00:05:38 by Hibernate Tools 3.1.0.beta4

import java.text.SimpleDateFormat;
import java.util.Date;

import org.hibernate.Session;

import com.mfino.dbcopytool.persistence.ReportDbHibernateUtil;
import com.mfino.fix.CmFinoFIX;

/**
 * SubscriberClassification generated by hbm2java
 */

public class Subscriber extends TableRow implements
		java.io.Serializable {

	// Fields

	private String subscriberId;
	private String firstName;
	private String subscriberMdn;
	private String kyclevel;
	private String city;
	private String state;
	private String addressLine1;
	private String addressLine2;
	private String zipCode;
	private Date createTime;
	private String createYear;
	private String createMonthName;
	private String createDayofMonth;
	private String createWeekDay;
	private String lastName;
	private String type;
	private Date updateTime;
	private String updateYear;
	private String updateMonthName;
	private String updateDayofMonth;
	private String updateWeekDay;
	private String createdBy = "";
	private String updatedBy = ""; 
	
	private String language;
	private String timeZone;
	private String status;
	private String restrictions;
	private String DOB;
	private String email;
	private String currency;
	private String IdType;
	private String IdNumber;
	
	
	private String partnerCode = "";
	private String partnerType = "";
	private String userName = "";
	private String tradeName = "";
	private String lineOfBusiness = "";
	private String contactPerson = "";
	private String contactPersonDesignation = "";
	private String phoneNumber = "";
	private String faxNumber = "";
	private String partnerClass = "";
	

	@Override
	public void initialiseRow(Object[] m) {
		int i = -1;
		this.subscriberId = m[++i] != null ? m[i].toString() : "";
		this.firstName = m[++i] != null ? m[i].toString() : "";
		this.lastName = m[++i] != null ? m[i].toString() : "";
		this.subscriberMdn =m[++i] != null ? m[i].toString() : "";
		this.kyclevel = m[++i] != null ? m[i].toString() : "";
		this.type = m[++i] != null ? m[i].toString() : "";
		this.IdType = m[++i] != null ? m[i].toString() : "";
		this.IdNumber = m[++i] != null ? m[i].toString() : "";
		this.city = m[++i] != null ? m[i].toString() : "";
		this.state = m[++i] != null ? m[i].toString() : "";
		this.addressLine1 = m[++i] != null ? m[i].toString() : "";
		this.addressLine2 = m[++i] != null ? m[i].toString() : "";
		this.zipCode = m[++i] != null ? m[i].toString() : "";
		this.createTime = (Date) m[++i];
		this.updateTime = (Date) m[++i];
		this.createdBy =  m[++i] != null ? m[i].toString() : "";
		this.updatedBy =  m[++i] != null ? m[i].toString() : "";
		this.language = m[++i] != null ? m[i].toString() : "";
		this.timeZone = m[++i] != null ? m[i].toString() : ""; 
		this.status = m[++i] != null ? m[i].toString() : "";
		this.restrictions = m[++i] != null ? m[i].toString() : ""; 
		this.DOB = m[++i] != null ? m[i].toString() : "";
		this.email = m[++i] != null ? m[i].toString() : "";
		this.currency = m[++i] != null ? m[i].toString() : "";
		
		if(this.type.equalsIgnoreCase("2")){
			this.partnerCode = m[++i] != null ? m[i].toString() : "";
			this.partnerType = m[++i] != null ? m[i].toString() : ""; 
			this.userName = m[++i] != null ? m[i].toString() : "";
			this.tradeName = m[++i] != null ? m[i].toString() : ""; 
			this.lineOfBusiness = m[++i] != null ? m[i].toString() : "";
			this.contactPerson = m[++i] != null ? m[i].toString() : "";
			this.contactPersonDesignation = m[++i] != null ? m[i].toString() : "";
			this.phoneNumber = m[++i] != null ? m[i].toString() : ""; 
			this.faxNumber = m[++i] != null ? m[i].toString() : "";
			this.partnerClass = m[++i] != null ? m[i].toString() : "";
		}
		
		transfromRow();
	}

	@Override
	public void transfromRow() {
		Date d = this.createTime;
		this.createYear = new SimpleDateFormat("yyyy").format(d);
		this.createMonthName = new SimpleDateFormat("MMMM").format(d);
		this.createDayofMonth = new SimpleDateFormat("dd").format(d);
		this.createWeekDay = new SimpleDateFormat("EEEE").format(d);
		d = this.updateTime;
		this.updateYear = new SimpleDateFormat("yyyy").format(d);
		this.updateMonthName = new SimpleDateFormat("MMMM").format(d);
		this.updateDayofMonth = new SimpleDateFormat("dd").format(d);
		this.updateWeekDay = new SimpleDateFormat("EEEE").format(d);
		
		if(this.type.equalsIgnoreCase("0")){
			this.type = "Subscriber";
		}else{
			this.type = "Partner";
		}
		
		int res = Integer.parseInt(this.restrictions.trim());
		this.restrictions = "";
		if((res & CmFinoFIX.SubscriberRestrictions_AbsoluteLocked) != 0){
			this.restrictions += "| AbsoluteLocked";
		}
		if((res & CmFinoFIX.SubscriberRestrictions_NoFundMovement) != 0){
			this.restrictions += "| NoFundMovement";
		}
		if((res & CmFinoFIX.SubscriberRestrictions_SecurityLocked) != 0){
			this.restrictions += "| SecurityLocked";
		}
		if((res & CmFinoFIX.SubscriberRestrictions_SelfSuspended) != 0){
			this.restrictions += "| SelfSuspended";
		}
		if((res & CmFinoFIX.SubscriberRestrictions_Suspended) != 0){
			this.restrictions += "| Suspended";
		}
		if(res  == 0){
			this.restrictions += "| None";
		}
	}

	@Override
	public void insertRow() {
		Session session = ReportDbHibernateUtil.getSessionFactory().openSession();
		session.beginTransaction();
		session.saveOrUpdate(this);
		session.getTransaction().commit();
		session.close();
	}

	@Override
	public void printRow() {
		System.out.println(this.subscriberId + "," + this.firstName + ","
				+ this.subscriberMdn + "," + this.kyclevel + "," + this.city
				+ "," + this.state + "," + this.createTime + "," + this.createYear
				+ "," + this.createMonthName + "," + this.createDayofMonth + ","
				+ this.createWeekDay);
	}

	// Property accessors

	public String getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(String subscriberId) {
		this.subscriberId = subscriberId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSubscriberMdn() {
		return this.subscriberMdn;
	}

	public void setSubscriberMdn(String subscriberMdn) {
		this.subscriberMdn = subscriberMdn;
	}

	public String getKyclevel() {
		return this.kyclevel;
	}

	public void setKyclevel(String kyclevel) {
		this.kyclevel = kyclevel;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	

	public void printData() {
		System.out.println(this.subscriberId + "," + this.subscriberMdn + ","
				+ this.kyclevel + "," + this.city + "," + this.state + ","
				+ this.createTime + "," + this.createYear + "," + this.createMonthName
				+ "," + this.createDayofMonth + "," + this.createWeekDay);
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	public String getCreateMonthName() {
		return createMonthName;
	}

	public void setCreateMonthName(String createMonthName) {
		this.createMonthName = createMonthName;
	}

	public String getCreateDayofMonth() {
		return createDayofMonth;
	}

	public void setCreateDayofMonth(String createDayofMonth) {
		this.createDayofMonth = createDayofMonth;
	}

	public String getCreateWeekDay() {
		return createWeekDay;
	}

	public void setCreateWeekDay(String createWeekDay) {
		this.createWeekDay = createWeekDay;
	}

	public String getUpdateYear() {
		return updateYear;
	}

	public void setUpdateYear(String updateYear) {
		this.updateYear = updateYear;
	}

	public String getUpdateMonthName() {
		return updateMonthName;
	}

	public void setUpdateMonthName(String updateMonthName) {
		this.updateMonthName = updateMonthName;
	}

	public String getUpdateDayofMonth() {
		return updateDayofMonth;
	}

	public void setUpdateDayofMonth(String updateDayofMonth) {
		this.updateDayofMonth = updateDayofMonth;
	}

	public String getUpdateWeekDay() {
		return updateWeekDay;
	}

	public void setUpdateWeekDay(String updateWeekDay) {
		this.updateWeekDay = updateWeekDay;
	}
	
	public String getCreateYear() {
		return createYear;
	}

	public void setCreateYear(String createYear) {
		this.createYear = createYear;
	}
	
	
	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getTimeZone() {
		return timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRestrictions() {
		return restrictions;
	}

	public void setRestrictions(String restrictions) {
		this.restrictions = restrictions;
	}

	public String getDOB() {
		return DOB;
	}

	public void setDOB(String dOB) {
		DOB = dOB;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getPartnerCode() {
		return partnerCode;
	}

	public void setPartnerCode(String partnerCode) {
		this.partnerCode = partnerCode;
	}

	public String getPartnerType() {
		return partnerType;
	}

	public void setPartnerType(String partnerType) {
		this.partnerType = partnerType;
	}

	
	public String getTradeName() {
		return tradeName;
	}

	public void setTradeName(String tradeName) {
		this.tradeName = tradeName;
	}

	public String getLineOfBusiness() {
		return lineOfBusiness;
	}

	public void setLineOfBusiness(String lineOfBusiness) {
		this.lineOfBusiness = lineOfBusiness;
	}

	public String getContactPerson() {
		return contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getFaxNumber() {
		return faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	public String getPartnerClass() {
		return partnerClass;
	}

	public void setPartnerClass(String partnerClass) {
		this.partnerClass = partnerClass;
	}
	
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getAddressLine1() {
		return addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}
	
	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}
	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	public String getIdType() {
		return IdType;
	}

	public void setIdType(String idType) {
		IdType = idType;
	}

	public String getIdNumber() {
		return IdNumber;
	}

	public void setIdNumber(String idNumber) {
		IdNumber = idNumber;
	}
	
	public String getContactPersonDesignation() {
		return contactPersonDesignation;
	}

	public void setContactPersonDesignation(String contactPersonDesignation) {
		this.contactPersonDesignation = contactPersonDesignation;
	}

		
}
