package com.mfino.dbcopytool.reportdb.domain;

// Generated 05-Apr-2012 00:05:37 by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import org.hibernate.Query;
import org.hibernate.Session;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.mfino.dbcopytool.persistence.MfinoDbHibernateUtil;
import com.mfino.dbcopytool.persistence.ReportDbHibernateUtil;

/**
 * Sctl generated by hbm2java
 */

public class SubscriberBasedSctlTxn extends TableRow implements java.io.Serializable {

	// Fields
		private Logger log = LoggerFactory.getLogger(this.getClass());
		
		private String sctlIdSubscriberMDN;
		private String sctlid;
		private String transactionId;
		
		private Date createTime;
		private String createYear;
		private String createMonthName;
		private String createDayofMonth;
		private String createWeekDay;
		private String createHour;

		private Date updateTime;
		private String updateYear;
		private String updateMonthName;
		private String updateDayofMonth;
		private String updateWeekDay;
		private String updateHour;

		private String sourceMdn;
		private String destMdn;
		private String subscriberMdn;
		
		

		private String sourceSubscriberId;
		private String destSubscriberId;

		private String serviceId;
		private String service;

		private String transactionTypeId;
		private String transactionType;

		private String channelCodeId;
		private String channel;

		private BigDecimal transactionAmount;
		private BigDecimal calculatedCharge;

		private String commodityTransferId;

		private String statusId;
		private String status;
		private String mfsBillerCode;
		private String info1;
		private String invoiceNo;

		private Boolean ischargeDistributed;
		
		private BigDecimal paidAmount;

		// Constructors

		/** default constructor */
		public SubscriberBasedSctlTxn() {
		}

		/** minimal constructor */
		public SubscriberBasedSctlTxn(String sctlid) {
			this.sctlid = sctlid;
		}

		/** full constructor */
		public SubscriberBasedSctlTxn(String sctlid, String transactionId, Date updateTime,
				String year, String month, String dayofMonth, String weekDay,
				String hour, String sourceMdn, String destMdn, String serviceId,
				String service, String transactionTypeId, String transactionType,
				String channelCodeId, String channel, BigDecimal transactionAmount,
				BigDecimal calculatedCharge, String commodityTransferId,
				String statusId, String status, Boolean ischargeDistributed) {
			this.sctlid = sctlid;
			this.transactionId = transactionId;

			this.updateTime = updateTime;
			this.updateYear = year;
			this.updateMonthName = month;
			this.updateDayofMonth = dayofMonth;
			this.updateWeekDay = weekDay;
			this.updateHour = hour;

			this.sourceMdn = sourceMdn;
			this.destMdn = destMdn;

			this.serviceId = serviceId;
			this.service = service;

			this.transactionTypeId = transactionTypeId;
			this.transactionType = transactionType;

			this.channelCodeId = channelCodeId;
			this.channel = channel;

			this.statusId = statusId;
			this.status = status;

			this.transactionAmount = transactionAmount;
			this.calculatedCharge = calculatedCharge;

			this.commodityTransferId = commodityTransferId;

			this.ischargeDistributed = ischargeDistributed;
		}

		String hqlQuery = "select sctl.ID, sctl.TransactionID, "
				+ "sctl.SourceMDN, sctl.DestMDN, "
				+ "sctl.ServiceID,ss.ServiceName, "
				+ "sctl.TransactionTypeID, tt.TransactionName, "
				+ "sctl.ChannelCodeID,cc.ChannelName, "
				+ "sctl.TransactionAmount, sctl.CalculatedCharge, "
				+ "sctl.CommodityTransferID,  "
				+ "sctl.Status,et.DisplayText, "
				+ "sctl.IsChargeDistributed, sctl.LastUpdateTime "
				+ "from ServiceChargeTransactionLog as sctl,TransactionType tt,Service ss,ChannelCode cc,EnumText et "
				+ "where sctl.TransactionTypeID = tt.ID "
				+ "and sctl.ChannelCodeID = cc.ID "
				+ "and et.TagID = 6089 and sctl.Status = et.EnumCode "
				+ "and sctl.ServiceID = ss.ID";

		@Override
		public void initialiseRow(Object[] m) {
			int i = -1;
			this.sctlid = m[++i].toString();
			this.transactionId = m[++i].toString();

			this.sourceMdn = m[++i] != null ? m[i].toString() : "";
			this.destMdn = m[++i] != null ? m[i].toString() : "";
			this.subscriberMdn = m[++i] != null ? m[i].toString() : "";

			this.serviceId = m[++i] != null ? m[i].toString() : "";
			this.service = m[++i] != null ? m[i].toString() : "";

			this.transactionTypeId = m[++i] != null ? m[i].toString() : "";
			this.transactionType = m[++i] != null ? m[i].toString() : "";

			this.channelCodeId = m[++i] != null ? m[i].toString() : "";
			this.channel = m[++i] != null ? m[i].toString() : "";

			this.transactionAmount = (BigDecimal) m[++i];
			this.calculatedCharge = (BigDecimal) m[++i];

			this.commodityTransferId = m[++i] != null ? m[i].toString() : "";

			this.statusId = m[++i] != null ? m[i].toString() : "";
			this.status = m[++i] != null ? m[i].toString() : "";
			this.mfsBillerCode =  m[++i] != null ? m[i].toString() : "";
			this.info1 =  m[++i] != null ? m[i].toString() : "";
			this.setInvoiceNo(m[++i] != null ? m[i].toString() : "");
			this.ischargeDistributed = (Boolean) m[++i];
			
			this.createTime = (Date)m[++i];
			this.updateTime = (Date) m[++i];

			transfromRow();
		}

		@Override
		public void transfromRow() {
			Date d = this.createTime;
			this.createYear = new SimpleDateFormat("yyyy").format(d);
			this.createMonthName = new SimpleDateFormat("MMMM").format(d);
			this.createDayofMonth = new SimpleDateFormat("dd").format(d);
			this.createWeekDay = new SimpleDateFormat("EEEE").format(d);
			this.createHour = new SimpleDateFormat("HH").format(d);
			d = this.updateTime;
			this.updateYear = new SimpleDateFormat("yyyy").format(d);
			this.updateMonthName = new SimpleDateFormat("MMMM").format(d);
			this.updateDayofMonth = new SimpleDateFormat("dd").format(d);
			this.updateWeekDay = new SimpleDateFormat("EEEE").format(d);
			this.updateHour = new SimpleDateFormat("HH").format(d);
			this.paidAmount = this.transactionAmount.subtract(this.calculatedCharge);
			this.sctlIdSubscriberMDN = this.commodityTransferId+this.subscriberMdn;
			setSourceAndDestSubscriberId();
		}
		
		private void setSourceAndDestSubscriberId(){
			if(this.sourceMdn.equalsIgnoreCase("")){
				this.sourceSubscriberId = "";
			}else{
				this.sourceSubscriberId = getSubscriberId(this.sourceMdn);
			}
			if(this.destMdn.equalsIgnoreCase("")){
				this.destSubscriberId = "";
			}else{
				this.destSubscriberId = getSubscriberId(this.destMdn);
			}
		}
		
		public String getSubscriberId(String MDN){
			String retiredMDN = MDN+"R0";
			hqlQuery = "select subMdn.Subscriber.id,subMdn.MDN from SubscriberMDN as subMdn where subMdn.MDN='"+MDN+"' OR subMdn.MDN='"+retiredMDN+"'";
			Session session =MfinoDbHibernateUtil.getSessionFactory().openSession();
			Query query = session.createQuery(hqlQuery);
			List subList = query.list();
			session.close();
			if(subList.size() != 0){
				Object[] m = ((Object[]) subList.get(0));
				int i = -1;
				return m[++i] != null ? m[i].toString() : "";
			}
			return "";
		}
		

		@Override
		public void insertRow() {
			Session session = ReportDbHibernateUtil.getSessionFactory().openSession();
			session.beginTransaction();
			session.saveOrUpdate(this);
			session.getTransaction().commit();
			session.close();		
		}
		

		@Override
		public void printRow() {
			System.out.println(this.sctlid + "," + this.transactionId + ","
					+ this.updateTime + "," + this.updateYear + "," + this.updateMonthName + ","
					+ this.updateDayofMonth + "," + this.updateWeekDay + "," + this.updateHour + ","
					+ this.sourceMdn + "," + this.destMdn + "," + this.serviceId
					+ "," + this.service + "," + this.transactionTypeId + ","
					+ this.transactionType + "," + this.channelCodeId + ","
					+ this.channel + "," + this.transactionAmount + ","
					+ this.calculatedCharge + "," + this.commodityTransferId + ","
					+ this.statusId + "," + this.status + ","
					+ this.ischargeDistributed);
		}

		// Property accessors

		public String getSctlid() {
			return this.sctlid;
		}

		public void setSctlid(String sctlid) {
			this.sctlid = sctlid;
		}

		public String getTransactionId() {
			return this.transactionId;
		}

		public void setTransactionId(String transactionId) {
			this.transactionId = transactionId;
		}

		
		public String getSourceMdn() {
			return this.sourceMdn;
		}

		public void setSourceMdn(String sourceMdn) {
			this.sourceMdn = sourceMdn;
		}

		public String getDestMdn() {
			return this.destMdn;
		}

		public void setDestMdn(String destMdn) {
			this.destMdn = destMdn;
		}

		public String getServiceId() {
			return this.serviceId;
		}

		public void setServiceId(String serviceId) {
			this.serviceId = serviceId;
		}

		public String getservice() {
			return this.service;
		}

		public void setservice(String service) {
			this.service = service;
		}

		public String getTransactionTypeId() {
			return this.transactionTypeId;
		}

		public void setTransactionTypeId(String transactionTypeId) {
			this.transactionTypeId = transactionTypeId;
		}

		public String gettransactionType() {
			return this.transactionType;
		}

		public void settransactionType(String transactionType) {
			this.transactionType = transactionType;
		}

		public String getChannelCodeId() {
			return this.channelCodeId;
		}

		public void setChannelCodeId(String channelCodeId) {
			this.channelCodeId = channelCodeId;
		}

		public BigDecimal getTransactionAmount() {
			return this.transactionAmount;
		}

		public void setTransactionAmount(BigDecimal transactionAmount) {
			this.transactionAmount = transactionAmount;
		}

		public BigDecimal getCalculatedCharge() {
			return this.calculatedCharge;
		}

		public void setCalculatedCharge(BigDecimal calculatedCharge) {
			this.calculatedCharge = calculatedCharge;
		}

		public String getCommodityTransferId() {
			return this.commodityTransferId;
		}

		public void setCommodityTransferId(String commodityTransferId) {
			this.commodityTransferId = commodityTransferId;
		}

		public Boolean getIschargeDistributed() {
			return this.ischargeDistributed;
		}

		public void setIschargeDistributed(Boolean ischargeDistributed) {
			this.ischargeDistributed = ischargeDistributed;
		}

		public String getService() {
			return this.service;
		}

		public void setService(String service) {
			this.service = service;
		}

		public String getTransactionType() {
			return this.transactionType;
		}

		public void setTransactionType(String transactionType) {
			this.transactionType = transactionType;
		}

		public String getChannel() {
			return this.channel;
		}

		public void setChannel(String channel) {
			this.channel = channel;
		}

		public String getStatusId() {
			return this.statusId;
		}

		public void setStatusId(String statusId) {
			this.statusId = statusId;
		}

		public String getStatus() {
			return this.status;
		}

		public void setStatus(String status) {
			this.status = status;
		}
		
		public Date getUpdateTime() {
			return updateTime;
		}

		public void setUpdateTime(Date updateTime) {
			this.updateTime = updateTime;
		}
		
		public String getCreateMonthName() {
			return createMonthName;
		}

		public void setCreateMonthName(String createMonthName) {
			this.createMonthName = createMonthName;
		}

		public String getCreateDayofMonth() {
			return createDayofMonth;
		}

		public void setCreateDayofMonth(String createDayofMonth) {
			this.createDayofMonth = createDayofMonth;
		}

		public String getCreateWeekDay() {
			return createWeekDay;
		}

		public void setCreateWeekDay(String createWeekDay) {
			this.createWeekDay = createWeekDay;
		}

		public String getUpdateYear() {
			return updateYear;
		}

		public void setUpdateYear(String updateYear) {
			this.updateYear = updateYear;
		}

		public String getUpdateMonthName() {
			return updateMonthName;
		}

		public void setUpdateMonthName(String updateMonthName) {
			this.updateMonthName = updateMonthName;
		}

		public String getUpdateDayofMonth() {
			return updateDayofMonth;
		}

		public void setUpdateDayofMonth(String updateDayofMonth) {
			this.updateDayofMonth = updateDayofMonth;
		}

		public String getUpdateWeekDay() {
			return updateWeekDay;
		}

		public void setUpdateWeekDay(String updateWeekDay) {
			this.updateWeekDay = updateWeekDay;
		}
		
		public String getUpdateHour() {
			return updateHour;
		}

		public void setUpdateHour(String updateHour) {
			this.updateHour = updateHour;
		}
		
		public String getCreateYear() {
			return createYear;
		}

		public void setCreateYear(String createYear) {
			this.createYear = createYear;
		}
		
		public String getCreateHour() {
			return createHour;
		}

		public void setCreateHour(String createHour) {
			this.createHour = createHour;
		}
		
		public Date getCreateTime() {
			return createTime;
		}

		public void setCreateTime(Date createTime) {
			this.createTime = createTime;
		}
		
		public BigDecimal getPaidAmount() {
			return paidAmount;
		}

		public void setPaidAmount(BigDecimal paidAmount) {
			this.paidAmount = paidAmount;
		}
		
		public String getSourceSubscriberId() {
			return sourceSubscriberId;
		}

		public void setSourceSubscriberId(String sourceSubscriberId) {
			this.sourceSubscriberId = sourceSubscriberId;
		}

		public String getDestSubscriberId() {
			return destSubscriberId;
		}

		public void setDestSubscriberId(String destSubscribertId) {
			this.destSubscriberId = destSubscribertId;
		}
		
		public String getSubscriberMdn() {
			return subscriberMdn;
		}

		public void setSubscriberMdn(String subscriberMdn) {
			this.subscriberMdn = subscriberMdn;
		}
		
		public String getSctlIdSubscriberMDN() {
			return sctlIdSubscriberMDN;
		}

		public void setSctlIdSubscriberMDN(String sctlIdSubscriberMDN) {
			this.sctlIdSubscriberMDN = sctlIdSubscriberMDN;
		}
		
		public String getMfsBillerCode() {
			return mfsBillerCode;
		}

		public void setMfsBillerCode(String mfsBillerCode) {
			this.mfsBillerCode = mfsBillerCode;
		}

		public String getInfo1() {
			return info1;
		}

		public void setInfo1(String info1) {
			this.info1 = info1;
		}

		public String getInvoiceNo() {
			return invoiceNo;
		}

		public void setInvoiceNo(String invoiceNo) {
			this.invoiceNo = invoiceNo;
		}

		
		

}
